/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * AnalysisController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code AnalysisController}，共 4 个端点。
 * <p>路径规范: /api/v1/nextwiki/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py nextwiki} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { FileNodeVO } from './models';

/**
 * getOverview: GET /api/v1/nextwiki/analysis/overview
 */
export function getOverview(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/nextwiki/analysis/overview`);
}

/**
 * statsByType: GET /api/v1/nextwiki/analysis/by-type
 */
export function statsByType(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/nextwiki/analysis/by-type`);
}

/**
 * topLargeFiles: GET /api/v1/nextwiki/analysis/top-large-files
 */
export function topLargeFiles(params: {
    limit?: number;
  }): Promise<FileNodeVO[]> {
  return requestClient.get<FileNodeVO[]>(`/api/v1/nextwiki/analysis/top-large-files`, { params });
}

/**
 * analyze: POST /api/v1/nextwiki/analysis/summary
 */
export function analyze(data: string): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/nextwiki/analysis/summary`, data);
}
