/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * DownloadController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code DownloadController}，共 4 个端点。
 * <p>路径规范: /api/v1/nextwiki/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py nextwiki} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { Record<string, never> } from './models';

/**
 * downloadFolder: POST /api/v1/nextwiki/download/folder/{folderId}
 */
export function downloadFolder(path: {
    folderId: string;
  }, params: {
    response?: Record<string, unknown>;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/nextwiki/download/folder/${folderId}`, { params });
}

/**
 * download: POST /api/v1/nextwiki/download/{nodeId}
 */
export function download(path: {
    nodeId: string;
  }, params: {
    request?: Record<string, unknown>;
    response?: Record<string, unknown>;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/nextwiki/download/${nodeId}`, { params });
}

/**
 * generateSignedUrl: POST /api/v1/nextwiki/download/{nodeId}/signed-url
 */
export function generateSignedUrl(path: {
    nodeId: string;
  }, params: {
    request?: Record<string, unknown>;
  }): Promise<string> {
  return requestClient.post<string>(`/api/v1/nextwiki/download/${nodeId}/signed-url`, { params });
}

/**
 * downloadBySignedUrl: GET /api/v1/nextwiki/download/signed/{sign}
 */
export function downloadBySignedUrl(path: {
    sign: string;
  }, params: {
    expires?: number;
    request?: Record<string, unknown>;
    response?: Record<string, unknown>;
  }): Promise<void> {
  return requestClient.get<void>(`/api/v1/nextwiki/download/signed/${sign}`, { params });
}
