/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * FileCommentController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code FileCommentController}，共 4 个端点。
 * <p>路径规范: /api/v1/nextwiki/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py nextwiki} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { FileCommentVO } from './models';

/**
 * listComments: GET /nextwiki/comments/file/{fileNodeId}
 */
export function listComments({ fileNodeId }: {
    fileNodeId: string;
  }): Promise<FileCommentVO[]> {
  return requestClient.get<FileCommentVO[]>(`/nextwiki/comments/file/${fileNodeId}`);
}

/**
 * addComment: POST /nextwiki/comments
 */
export function addComment(data: Record<string, unknown>): Promise<FileCommentVO> {
  return requestClient.post<FileCommentVO>(`/nextwiki/comments`, data);
}

/**
 * deleteComment: DELETE /nextwiki/comments/{commentId}
 */
export function deleteComment({ commentId }: {
    commentId: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/nextwiki/comments/${commentId}`);
}

/**
 * resolveComment: POST /nextwiki/comments/{commentId}/resolve
 */
export function resolveComment({ commentId }: {
    commentId: string;
  }): Promise<void> {
  return requestClient.post<void>(`/nextwiki/comments/${commentId}/resolve`);
}
