/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * 后端统一响应结构（对齐 {@code YdszResponse<T>}）
 * <p>注意: requestClient 拦截器已按 successCode='A00000' 解包 data，
 * 业务调用处泛型直接写 data 类型；此处类型仅供契约说明使用。
 */
export interface YdszResponse<T = unknown> {
  /** 业务成功码（A00000 表示成功） */
  code: string;
  /** 提示信息 */
  msg: string;
  /** 业务数据 */
  data: T;
  /** 链路追踪 ID */
  traceId?: string;
  requestId?: string;
  spanId?: string;
  timestamp?: number;
  extensions?: Record<string, unknown>;
}

/** 分页响应（对齐后端 {@code PageResponse<T>}：total/pageNum/pageSize 平铺 + data 分页数据） */
export interface PageResponse<T = unknown> {
  /** 总记录数 */
  total?: number;
  /** 当前页码（从 1 开始） */
  pageNum?: number;
  /** 每页记录数 */
  pageSize?: number;
  /** 分页数据（由后端工厂方法填充） */
  data: T;
}

/** 分页查询参数（前端通用约定） */
export interface PageQuery {
  pageNum?: number;
  pageSize?: number;
}

export interface SearchRequest {

  serialVersionUID?: number;

  keyword?: string;

  types?: string[];

  page?: number;

  pageSize?: number;

  sortBy?: string;

  ascending?: boolean;

  highlight?: boolean;

  highlightPreTag?: string;

  highlightPostTag?: string;

  highlightFragmentSize?: number;

  fuzzy?: boolean;

  fuzzyMinSimilarity?: number;

  filters?: '/** 等于 */
    EQ' | '/** 不等于 */
    NE' | '/** 在...范围内 */
    IN' | '/** 不在...范围内 */
    NOT_IN' | '/** 大于 */
    GT' | '/** 小于 */
    LT' | '/** 大于等于 */
    GTE' | '/** 小于等于 */
    LTE' | '/** 介于两者之间 */
    BETWEEN'[];

  aggregations?: string[];

  tenantId?: string;

  userId?: string;

  roles?: string[];

  deptId?: string;

  admin?: boolean;

  titleOnly?: boolean;

  cursor?: string;

  offset?: string;
}