/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型定义生成件（interface 占位不计入行数规则）
/**
 * 后端统一响应结构（对齐 {@code YdszResponse<T>}）
 * <p>注意: requestClient 拦截器已按 successCode='A00000' 解包 data，
 * 业务调用处泛型直接写 data 类型；此处类型仅供契约说明使用。
 */
export interface YdszResponse<T = unknown> {
  /** 业务成功码（A00000 表示成功） */
  code: string;
  /** 提示信息 */
  msg: string;
  /** 业务数据 */
  data: T;
  /** 链路追踪 ID */
  traceId?: string;
  requestId?: string;
  spanId?: string;
  timestamp?: number;
  extensions?: Record<string, unknown>;
}

/** 分页响应（对齐后端 {@code PageResponse<T>}：total/pageNum/pageSize 平铺 + data 分页数据） */
export interface PageResponse<T = unknown> {
  /** 总记录数 */
  total?: number;
  /** 当前页码（从 1 开始） */
  pageNum?: number;
  /** 每页记录数 */
  pageSize?: number;
  /** 分页数据（由后端工厂方法填充） */
  data: T;
}

/** 分页查询参数（前端通用约定） */
export interface PageQuery {
  pageNum?: number;
  pageSize?: number;
}

/**
 * 统一搜索请求
 *
 * 封装所有搜索引擎通用的搜索参数，包括关键词、分页、排序、过滤、高亮等。 各业务模块通过 `SearchProvider` 补充特定于实体的搜索逻辑。
 */
export interface SearchRequest {
  serialVersionUID?: number;
  /** 搜索关键词 */
  keyword?: string;
  /** 搜索范围（实体类型列表），为空表示搜索全部 */
  types?: string[];
  /** 页码（从 1 开始） */
  page?: number;
  /** 每页大小 */
  pageSize?: number;
  /** 排序字段 */
  sortBy?: string;
  /** 是否升序 */
  ascending?: boolean;
  /** 是否启用高亮 */
  highlight?: boolean;
  /** 高亮前置标签 */
  highlightPreTag?: string;
  /** 高亮后置标签 */
  highlightPostTag?: string;
  /** 高亮片段最大长度 */
  highlightFragmentSize?: number;
  /** 是否启用模糊匹配 */
  fuzzy?: boolean;
  /** 模糊匹配最小相似度（0~1） */
  fuzzyMinSimilarity?: number;
  /** 过滤条件（字段名 → 值列表） */
  filters?: 'EQ' | 'NE' | 'IN' | 'NOT_IN' | 'GT' | 'LT' | 'GTE' | 'LTE' | 'BETWEEN'[];
  /** 聚合字段列表（用于分面统计） */
  aggregations?: string[];
  /** 租户 ID（权限隔离） */
  tenantId?: string;
  /** 操作人 ID（权限过滤） */
  userId?: string;
  /** 操作人角色列表（权限过滤） */
  roles?: string[];
  /** 操作人部门 ID（权限过滤） */
  deptId?: string;
  /** 是否管理员（跳过权限过滤） */
  admin?: boolean;
  /** 是否仅搜索标题字段（不含内容） */
  titleOnly?: boolean;
  /** P3-21: 游标分页 cursor（base64 编码，为空表示从头开始） */
  cursor?: string;
  offset?: string;
}

/**
 * 文件节点聚合根 VO
 *
 * S2-P1-2 改进：引入领域行为方法
 * 文件节点是知识库系统的核心聚合根，包含完整的业务字段和领域行为：
 * 基础属性：节点 ID、父节点 ID、名称、类型、路径、层级
 * 存储属性：存储键、存储桶、存储类型、文件哈希、大小
 * 状态属性：版本号、排序号、星标、分享状态、锁定状态
 * 关系属性：子节点列表、标签列表
 * 领域行为：
 * #isFolder() / #isFile() — 类型判断
 * #isRoot() — 根节点判断（父节点为 null 或 "0"）
 * #isDescendantOf(FileNodeVO) — 后代关系判断（基于路径前缀）
 * #canMoveTo(FileNodeVO) — 移动合法性校验（防循环）
 * #calculatePath(String, String) — 静态路径计算工具
 * 设计说明：
 * 本 VO 兼具领域聚合根与展示视图职责，适用于当前单体架构
 * 未来微服务拆分时，可将展示字段抽取为 `FileNodeView`
 * 数据持久化通过 `FileNodeDTO` → `FileNode` 转换实现
 */
export interface FileNodeVO {
  serialVersionUID?: number;
  id?: string;
  parentId?: string;
  name?: string;
  nodeType?: string;
  suffix?: string;
  size?: number;
  mimeType?: string;
  storageKey?: string;
  bucketName?: string;
  storageClass?: string;
  fileHash?: string;
  path?: string;
  level?: number;
  sort?: number;
  currentVersion?: number;
  thumbnailKey?: string;
  previewReady?: boolean;
  starred?: boolean;
  status?: string;
  shareStatus?: string;
  tenantId?: string;
  createdBy?: string;
  updatedBy?: string;
  createdAt?: string;
  updatedAt?: string;
  children?: FileNodeVO[];
  tags?: string[];
}

/**
 * 批量操作结果（P2-F4）。
 *
 * 提供比简单 count 更详细的批量操作结果，包含每个条目的处理状态与失败原因， 前端可据此展示"部分成功"详情弹窗，而非仅显示"成功 N 条"。
 * <h3>典型返回结构</h3>
 * <pre>{@code
 * {
 * "total": 5,
 * "successCount": 3,
 * "failureCount": 2,
 * "details": [
 * {"item": "job-001", "success": true,  "error": null},
 * {"item": "job-002", "success": false, "error": "任务不存在"},
 * ...
 * ]
 * }
 * }</pre>
 * @param <T> 批量操作项的类型（通常为 String，表示 jobId）
 */
export interface BatchResultDTO {
  /** 总处理条数 */
  total?: number;
  /** 成功条数 */
  successCount?: number;
  /** 失败条数 */
  failureCount?: number;
  /** 明细列表 */
  details?: Record<string, unknown>[];
  /** 操作项标识 */
  item?: Record<string, unknown>;
  /** 是否成功 */
  success?: boolean;
  /** 失败原因（成功时为 null） */
  error?: string;
}

/**
 * 文件版本 VO
 */
export interface FileVersionVO {
  serialVersionUID?: number;
  id?: string;
  fileNodeId?: string;
  versionNumber?: number;
  storageKey?: string;
  size?: number;
  fileHash?: string;
  mimeType?: string;
  remark?: string;
  changeType?: string;
  active?: boolean;
  createdBy?: string;
  createdAt?: string;
}

/**
 * 文件评论 VO
 */
export interface FileCommentVO {
  serialVersionUID?: number;
  id?: string;
  fileNodeId?: string;
  content?: string;
  parentCommentId?: string;
  resolved?: boolean;
  position?: string;
  edited?: boolean;
  createdBy?: string;
  createdAt?: string;
}

/**
 * 存储配额 VO
 */
export interface StorageQuotaVO {
  serialVersionUID?: number;
  id?: string;
  scopeType?: string;
  scopeId?: string;
  quotaLimit?: number;
  quotaUsed?: number;
  fileCountLimit?: number;
  fileCountUsed?: number;
  createdBy?: string;
  createdAt?: string;
  updatedBy?: string;
  updatedAt?: string;
  revision?: number;
  deleted?: number;
}

/**
 * 全文搜索结果 VO
 */
export interface SearchResultVO {
  serialVersionUID?: number;
  hits?: Record<string, unknown>[];
  total?: number;
  page?: number;
  pageSize?: number;
  tookMs?: number;
  fileNodeId?: string;
  name?: string;
  path?: string;
  nodeType?: string;
  suffix?: string;
  size?: number;
  highlight?: string;
  score?: number;
  tags?: string[];
  createdBy?: string;
  updatedAt?: string;
}

/**
 * 分享链接 VO
 */
export interface ShareLinkVO {
  serialVersionUID?: number;
  id?: string;
  fileNodeId?: string;
  shareCode?: string;
  extractCode?: string;
  fileName?: string;
  shareType?: string;
  expireTime?: string;
  maxAccessCount?: number;
  accessCount?: number;
  status?: string;
  shareTargetType?: string;
  password?: string;
  reminderSent?: boolean;
  title?: string;
  hasPassword?: boolean;
  shareUrl?: string;
  createdBy?: string;
  updatedBy?: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * 分享访问日志 VO
 */
export interface ShareAccessLogVO {
  serialVersionUID?: number;
  id?: string;
  shareId?: string;
  shareCode?: string;
  fileNodeId?: string;
  visitorId?: string;
  visitorName?: string;
  visitorIp?: string;
  userAgent?: string;
  accessType?: string;
  accessStatus?: string;
  failReason?: string;
  accessTime?: string;
  createdAt?: string;
  updatedBy?: string;
  updatedAt?: string;
  revision?: number;
  deleted?: number;
}

/**
 * 分享目标用户 VO
 */
export interface ShareRecipientVO {
  serialVersionUID?: number;
  id?: string;
  shareId?: string;
  recipientType?: string;
  recipientId?: string;
  recipientName?: string;
  status?: string;
  viewedAt?: string;
  createdBy?: string;
  createdAt?: string;
}

/**
 * 知识库空间视图对象
 *
 * 返回给前端的空间信息。
 */
export interface SpaceVO {
  serialVersionUID?: number;
  id?: string;
  name?: string;
  description?: string;
  iconUrl?: string;
  coverUrl?: string;
  ownerId?: string;
  status?: string;
  visibility?: string;
  sortOrder?: number;
  memberCount?: number;
  nodeCount?: number;
  quotaLimit?: number;
  quotaUsed?: number;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * 空间成员 DTO
 */
export interface SpaceMemberDTO {
  serialVersionUID?: number;
  id?: string;
  spaceId?: string;
  userId?: string;
  role?: string;
  tenantId?: string;
  joinedAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
}

/**
 * 空间模板 DTO
 */
export interface SpaceTemplateDTO {
  serialVersionUID?: number;
  id?: string;
  name?: string;
  description?: string;
  category?: string;
  iconUrl?: string;
  tenantId?: string;
  systemFlag?: boolean;
  publicAccess?: boolean;
  structureJson?: string;
  sortOrder?: number;
  usageCount?: number;
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
}

/**
 * 标签 DTO
 *
 * 用于标签的创建和更新操作，作为 Repository 接口 CUD 方法的入参。
 */
export interface TagDTO {
  serialVersionUID?: number;
  id?: string;
  name?: string;
  color?: string;
  type?: string;
  usageCount?: number;
  createdBy?: string;
  updatedBy?: string;
  createdAt?: string;
  updatedAt?: string;
  tenantId?: string;
}

/**
 * 标签 VO
 */
export interface TagVO {
  serialVersionUID?: number;
  id?: string;
  name?: string;
  color?: string;
  type?: string;
  usageCount?: number;
  createdBy?: string;
  createdAt?: string;
}

/**
 * 回收站条目 VO
 */
export interface TrashItemVO {
  serialVersionUID?: number;
  id?: string;
  fileNodeId?: string;
  originalName?: string;
  originalPath?: string;
  originalParentId?: string;
  nodeType?: string;
  size?: number;
  deletedTime?: string;
  purgeTime?: string;
  status?: string;
  createdBy?: string;
  createdAt?: string;
}

/**
 * 用户收藏夹视图对象
 *
 * 返回给前端的收藏节点信息（含节点元数据 + 收藏排序号）。
 */
export interface UserFavoriteVO {
  serialVersionUID?: number;
  favoriteId?: string;
  nodeId?: string;
  name?: string;
  nodeType?: string;
  suffix?: string;
  size?: number;
  path?: string;
  thumbnailKey?: string;
  sortOrder?: number;
  starred?: boolean;
  updatedAt?: string;
  favoritedAt?: string;
}

/**
 * 用户最近访问视图对象
 *
 * 返回给前端的最近访问节点信息（含节点元数据 + 访问信息）。
 */
export interface UserRecentVO {
  serialVersionUID?: number;
  nodeId?: string;
  name?: string;
  nodeType?: string;
  suffix?: string;
  size?: number;
  path?: string;
  thumbnailKey?: string;
  accessType?: string;
  accessedAt?: string;
  updatedBy?: string;
  updatedAt?: string;
}
