/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * UserFavoriteController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code UserFavoriteController}，共 6 个端点。
 * <p>路径规范: /api/v1/nextwiki/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py nextwiki} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { UserFavoriteVO } from './models';

/**
 * listFavorites: GET /api/nextwiki/favorites
 */
export function listFavorites(params: {
    limit?: number;
  }): Promise<UserFavoriteVO[]> {
  return requestClient.get<UserFavoriteVO[]>(`/api/nextwiki/favorites`, { params });
}

/**
 * addFavorite: POST /api/nextwiki/favorites/{nodeId}
 */
export function addFavorite({ nodeId }: {
    nodeId: string;
  }): Promise<string> {
  return requestClient.post<string>(`/api/nextwiki/favorites/${nodeId}`);
}

/**
 * removeFavorite: DELETE /api/nextwiki/favorites/{nodeId}
 */
export function removeFavorite({ nodeId }: {
    nodeId: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/nextwiki/favorites/${nodeId}`);
}

/**
 * isFavorited: GET /api/nextwiki/favorites/{nodeId}/is-favorited
 */
export function isFavorited({ nodeId }: {
    nodeId: string;
  }): Promise<boolean> {
  return requestClient.get<boolean>(`/api/nextwiki/favorites/${nodeId}/is-favorited`);
}

/**
 * updatesort: POST /api/nextwiki/favorites/{nodeId}/sort
 */
export function updatesort({ nodeId }: {
    nodeId: string;
  }, params: {
    sort?: number;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/api/nextwiki/favorites/${nodeId}/sort`, { params });
}

/**
 * updateSortOrder: POST /api/nextwiki/favorites/{nodeId}/sort
 * <p>{@link updatesort} 的别名，供视图层使用驼峰命名。
 */
export function updateSortOrder({ nodeId }: {
    nodeId: string;
  }, params: {
    sort?: number;
  }): Promise<boolean> {
  return updatesort({ nodeId }, params);
}

/**
 * getFavoriteCount: GET /api/nextwiki/favorites/count
 */
export function getFavoriteCount(): Promise<number> {
  return requestClient.get<number>(`/api/nextwiki/favorites/count`);
}
