<!--
 * 任务 DAG（列表页）
 *
 * @path apps\cronjob-web\src\views\jobDag\index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 任务 DAG（列表页）
 * <p>消费后端契约 JobDagController（src/api/jobDag.ts，auto-generated by bash/gen-contract.py）：
 * 数据源 listEnabledDags()，支持启用 enableDag / 停用 disableDag（按 dagStatus 显示其一）、
 * 触发 triggerDag、删除 deleteDag、编辑/新增（jobDag-form.vue），
 * 以及版本管理：listDagVersions 抽屉展示版本记录 + rollbackDag 回滚。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import type { VxeGridProps } from '@ydsz/plugins/vxe-table';

import { Page, useVbenModal } from '@ydsz/common-ui';

import { ElButton, ElDrawer, ElEmpty, ElMessage, ElMessageBox, ElTable, ElTableColumn, ElTag, h } from 'element-plus';
import { ref } from 'vue';

import { useYDSZVxeGrid } from '#/adapter/vxe-table';
import {
  deleteDag,
  disableDag,
  enableDag,
  listDagVersions,
  listEnabledDags,
  rollbackDag,
  triggerDag,
} from '#/api/jobDag';
import type { JobDagVO, JobDagVersionVO } from '#/api/models';

import JobDagForm from './jobDag-form.vue';

defineOptions({ name: 'JobDagManagement' });

/** 判断 DAG 是否为启用状态（兼容字符串/数字取值，未知值按启用处理） */
function isDagEnabled(dag: JobDagVO): boolean {
  const status = dag.dagStatus;
  return status === undefined || !(status === 'DISABLED' || status === 'PAUSED' || status === '0');
}

const gridOptions: VxeGridProps<JobDagVO> = {
  columns: [
    { type: 'seq', width: 50, title: '序号' },
    { field: 'dagName', title: 'DAG名称', width: 180 },
    { field: 'dagKey', title: 'DAG标识', width: 150 },
    {
      field: 'dagStatus',
      title: '状态',
      width: 90,
      slots: {
        default: ({ row }) => {
          const dag = row as JobDagVO;
          return h(
            ElTag,
            { type: isDagEnabled(dag) ? 'success' : 'info' },
            () => (isDagEnabled(dag) ? '启用' : '停用'),
          );
        },
      },
    },
    { field: 'triggerType', title: '触发类型', width: 110 },
    { field: 'cronExpression', title: 'Cron', width: 150 },
    { field: 'version', title: '版本', width: 80 },
    { field: 'description', title: '描述', width: 160 },
    { field: 'createdAt', title: '创建时间', width: 160 },
    {
      field: 'action',
      title: '操作',
      width: 300,
      fixed: 'right',
      slots: {
        default: ({ row }) => {
          const dag = row as JobDagVO;
          return h('div', { class: 'flex gap-1' }, [
            h(ElButton, { size: 'small', link: true, type: 'primary', onClick: () => handleEdit(dag) }, () => '编辑'),
            isDagEnabled(dag)
              ? h(ElButton, { size: 'small', link: true, type: 'warning', onClick: () => handleDisable(dag) }, () => '停用')
              : h(ElButton, { size: 'small', link: true, type: 'success', onClick: () => handleEnable(dag) }, () => '启用'),
            h(ElButton, { size: 'small', link: true, type: 'primary', onClick: () => handleTrigger(dag) }, () => '触发'),
            h(ElButton, { size: 'small', link: true, type: 'primary', onClick: () => handleVersions(dag) }, () => '版本'),
            h(ElButton, { size: 'small', link: true, type: 'danger', onClick: () => handleDelete(dag) }, () => '删除'),
          ]);
        },
      },
    },
  ],
  height: 'auto',
  proxyConfig: {
    ajax: {
      query: async () => {
        const items = await listEnabledDags();
        return { items, total: items.length };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, zoom: true },
};

const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });

const [JobDagFormModal, jobDagFormApi] = useVbenModal({ connectedComponent: JobDagForm });

function handleAdd() {
  jobDagFormApi.open();
}

function handleEdit(row: JobDagVO) {
  jobDagFormApi.setData({ record: row });
  jobDagFormApi.open();
}

async function handleEnable(row: JobDagVO) {
  if (!row.id) return;
  try {
    await enableDag({ dagId: row.id });
    ElMessage.success('已启用');
    gridApi.query();
  } catch {
    // 错误提示由请求拦截器统一处理
  }
}

async function handleDisable(row: JobDagVO) {
  if (!row.id) return;
  try {
    await disableDag({ dagId: row.id });
    ElMessage.success('已停用');
    gridApi.query();
  } catch {
    // 错误提示由请求拦截器统一处理
  }
}

async function handleTrigger(row: JobDagVO) {
  if (!row.dagKey) return;
  try {
    await ElMessageBox.confirm(`确定立即触发DAG「${row.dagName}」吗？`, '触发确认', { type: 'warning' });
    await triggerDag({ dagKey: row.dagKey, triggerBy: 'console' });
    ElMessage.success('触发成功');
  } catch {
    // 用户取消或请求失败
  }
}

async function handleDelete(row: JobDagVO) {
  try {
    await ElMessageBox.confirm(`确定删除DAG「${row.dagName}」吗？`, '删除确认', { type: 'warning' });
    if (row.id) await deleteDag({ dagId: row.id });
    ElMessage.success('删除成功');
    gridApi.query();
  } catch {
    // 用户取消或请求失败
  }
}

/** 版本记录抽屉状态 */
const versionsDrawerVisible = ref(false);
const versions = ref<JobDagVersionVO[]>([]);
const currentDagId = ref('');

async function handleVersions(row: JobDagVO) {
  if (!row.id) return;
  currentDagId.value = row.id;
  versionsDrawerVisible.value = true;
  try {
    versions.value = await listDagVersions({ dagId: row.id });
  } catch {
    versions.value = [];
    // 错误提示由请求拦截器统一处理
  }
}

async function handleRollback(versionRow: JobDagVersionVO) {
  try {
    await ElMessageBox.confirm(
      `确定将DAG回滚到版本 v${versionRow.version ?? ''} 吗？`,
      '回滚确认',
      { type: 'warning' },
    );
    await rollbackDag({ dagId: currentDagId.value }, { version: versionRow.version });
    ElMessage.success('回滚成功');
    versionsDrawerVisible.value = false;
    gridApi.query();
  } catch {
    // 用户取消或请求失败
  }
}
</script>

<template>
  <Page auto-content-height>
    <Grid table-title="DAG管理">
      <template #toolbar-tools>
        <ElButton type="primary" @click="handleAdd">新增</ElButton>
      </template>
    </Grid>
    <JobDagFormModal @success="gridApi.query()" />
    <ElDrawer v-model="versionsDrawerVisible" title="DAG 版本记录" size="60%">
      <ElTable :data="versions" border>
        <ElTableColumn prop="version" label="版本" width="80" />
        <ElTableColumn prop="dagName" label="名称" width="160" />
        <ElTableColumn prop="dagKey" label="标识" width="160" />
        <ElTableColumn prop="triggerType" label="触发类型" width="120" />
        <ElTableColumn prop="cronExpression" label="Cron" width="140" />
        <ElTableColumn prop="remark" label="备注" min-width="120" />
        <ElTableColumn prop="createdAt" label="创建时间" width="170" />
        <ElTableColumn label="操作" width="100" fixed="right">
          <template #default="{ row }">
            <ElButton size="small" link type="primary" @click="handleRollback(row as JobDagVersionVO)">
              回滚
            </ElButton>
          </template>
        </ElTableColumn>
      </ElTable>
      <ElEmpty v-if="versions.length === 0" description="暂无版本记录" />
    </ElDrawer>
  </Page>
</template>