<!--
 * 图标选择器组件
 *
 * <p>提供可视化的图标选择功能，支持搜索过滤、网格展示、点击选择。
 *
 * @path apps\userinfo-web\src\views\system\menu\components\IconPicker.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 图标选择器
 * <p>基于 lucide 图标库，提供可视化图标选择能力。
 *
 * @author ydsz-team
 * @since 1.0.0
*/
import { ElDialog, ElInput, ElMessage, ElScrollbar } from 'element-plus';
import { computed, ref } from 'vue';

defineOptions({ name: 'IconPicker' });

const emit = defineEmits<{
  select: [icon: string];
  close: [];
}>();

/** 弹窗可见性 */
const visible = ref(false);

/** 搜索关键词 */
const searchKeyword = ref('');

/** 当前选中图标 */
const selectedIcon = ref('');

/** 常用 lucide 图标列表 */
const ICON_LIST: { name: string; label: string }[] = [
  { name: 'lucide:home', label: '首页' },
  { name: 'lucide:users', label: '用户' },
  { name: 'lucide:user', label: '个人' },
  { name: 'lucide:settings', label: '设置' },
  { name: 'lucide:settings-2', label: '配置' },
  { name: 'lucide:shield-check', label: '权限' },
  { name: 'lucide:shield-alert', label: '安全' },
  { name: 'lucide:menu', label: '菜单' },
  { name: 'lucide:folder', label: '文件夹' },
  { name: 'lucide:file-text', label: '文档' },
  { name: 'lucide:database', label: '数据库' },
  { name: 'lucide:server', label: '服务器' },
  { name: 'lucide:monitor', label: '监控' },
  { name: 'lucide:bar-chart', label: '图表' },
  { name: 'lucide:pie-chart', label: '饼图' },
  { name: 'lucide:activity', label: '活动' },
  { name: 'lucide:mail', label: '邮件' },
  { name: 'lucide:message-square', label: '消息' },
  { name: 'lucide:bell', label: '通知' },
  { name: 'lucide:calendar', label: '日历' },
  { name: 'lucide:clock', label: '时钟' },
  { name: 'lucide:history', label: '历史' },
  { name: 'lucide:search', label: '搜索' },
  { name: 'lucide:filter', label: '过滤' },
  { name: 'lucide:edit', label: '编辑' },
  { name: 'lucide:trash', label: '删除' },
  { name: 'lucide:plus', label: '添加' },
  { name: 'lucide:minus', label: '减少' },
  { name: 'lucide:check', label: '确认' },
  { name: 'lucide:x', label: '关闭' },
  { name: 'lucide:chevron-down', label: '展开' },
  { name: 'lucide:chevron-right', label: '折叠' },
  { name: 'lucide:arrow-up', label: '上升' },
  { name: 'lucide:arrow-down', label: '下降' },
  { name: 'lucide:refresh-cw', label: '刷新' },
  { name: 'lucide:download', label: '下载' },
  { name: 'lucide:upload', label: '上传' },
  { name: 'lucide:share', label: '分享' },
  { name: 'lucide:link', label: '链接' },
  { name: 'lucide:globe', label: '全球' },
  { name: 'lucide:map', label: '地图' },
  { name: 'lucide:map-pin', label: '定位' },
  { name: 'lucide:phone', label: '电话' },
  { name: 'lucide:video', label: '视频' },
  { name: 'lucide:image', label: '图片' },
  { name: 'lucide:music', label: '音乐' },
  { name: 'lucide:camera', label: '相机' },
  { name: 'lucide:printer', label: '打印' },
  { name: 'lucide:cloud', label: '云' },
  { name: 'lucide:hard-drive', label: '硬盘' },
  { name: 'lucide:cpu', label: '处理器' },
  { name: 'lucide:wifi', label: '网络' },
  { name: 'lucide:bluetooth', label: '蓝牙' },
  { name: 'lucide:battery', label: '电池' },
  { name: 'lucide:lock', label: '锁定' },
  { name: 'lucide:unlock', label: '解锁' },
  { name: 'lucide:key', label: '密钥' },
  { name: 'lucide:key-round', label: '钥匙' },
  { name: 'lucide:log-in', label: '登录' },
  { name: 'lucide:log-out', label: '登出' },
  { name: 'lucide:user-plus', label: '添加用户' },
  { name: 'lucide:user-minus', label: '移除用户' },
  { name: 'lucide:user-check', label: '用户确认' },
  { name: 'lucide:building', label: '建筑' },
  { name: 'lucide:building-2', label: '公司' },
  { name: 'lucide:factory', label: '工厂' },
  { name: 'lucide:store', label: '商店' },
  { name: 'lucide:shopping-cart', label: '购物车' },
  { name: 'lucide:credit-card', label: '信用卡' },
  { name: 'lucide:wallet', label: '钱包' },
  { name: 'lucide:receipt', label: '收据' },
  { name: 'lucide:package', label: '包裹' },
  { name: 'lucide:truck', label: '运输' },
  { name: 'lucide:plane', label: '飞机' },
  { name: 'lucide:ship', label: '轮船' },
  { name: 'lucide:train', label: '火车' },
  { name: 'lucide:car', label: '汽车' },
  { name: 'lucide:bike', label: '自行车' },
  { name: 'lucide:footprints', label: '足迹' },
  { name: 'lucide:compass', label: '指南针' },
  { name: 'lucide:navigation', label: '导航' },
  { name: 'lucide:anchor', label: '锚点' },
  { name: 'lucide:flag', label: '旗帜' },
  { name: 'lucide:award', label: '奖励' },
  { name: 'lucide:trophy', label: '奖杯' },
  { name: 'lucide:medal', label: '奖牌' },
  { name: 'lucide:star', label: '星标' },
  { name: 'lucide:heart', label: '收藏' },
  { name: 'lucide:thumbs-up', label: '点赞' },
  { name: 'lucide:thumbs-down', label: '踩' },
  { name: 'lucide:eye', label: '查看' },
  { name: 'lucide:eye-off', label: '隐藏' },
  { name: 'lucide:bookmark', label: '书签' },
  { name: 'lucide:tag', label: '标签' },
  { name: 'lucide:tags', label: '标签组' },
  { name: 'lucide:folder-open', label: '打开文件夹' },
  { name: 'lucide:folder-plus', label: '新建文件夹' },
  { name: 'lucide:file-plus', label: '新建文件' },
  { name: 'lucide:file-minus', label: '删除文件' },
  { name: 'lucide:clipboard', label: '剪贴板' },
  { name: 'lucide:copy', label: '复制' },
  { name: 'lucide:clipboard-check', label: '已复制' },
  { name: 'lucide:scissors', label: '剪切' },
  { name: 'lucide:rotate-cw', label: '旋转' },
  { name: 'lucide:maximize', label: '最大化' },
  { name: 'lucide:minimize', label: '最小化' },
  { name: 'lucide:expand', label: '展开' },
  { name: 'lucide:shrink', label: '收缩' },
  { name: 'lucide:move', label: '移动' },
  { name: 'lucide:cursor', label: '光标' },
  { name: 'lucide:mouse-pointer', label: '鼠标' },
  { name: 'lucide:table', label: '表格' },
  { name: 'lucide:layout', label: '布局' },
  { name: 'lucide:layout-grid', label: '网格布局' },
  { name: 'lucide:layout-list', label: '列表布局' },
  { name: 'lucide:sidebar', label: '侧边栏' },
  { name: 'lucide:panel-left', label: '左侧面板' },
  { name: 'lucide:panel-right', label: '右侧面板' },
  { name: 'lucide:panel-top', label: '顶部面板' },
  { name: 'lucide:panel-bottom', label: '底部面板' },
  { name: 'lucide:more-horizontal', label: '更多' },
  { name: 'lucide:more-vertical', label: '更多' },
  { name: 'lucide:grid', label: '网格' },
  { name: 'lucide:grid-3x3', label: '九宫格' },
  { name: 'lucide:list', label: '列表' },
  { name: 'lucide:check-square', label: '勾选' },
  { name: 'lucide:square', label: '方形' },
  { name: 'lucide:circle', label: '圆形' },
  { name: 'lucide:triangle', label: '三角形' },
  { name: 'lucide:hexagon', label: '六边形' },
  { name: 'lucide:pentagon', label: '五边形' },
  { name: 'lucide:octagon', label: '八边形' },
  { name: 'lucide:alarm-clock', label: '闹钟' },
  { name: 'lucide:stopwatch', label: '秒表' },
  { name: 'lucide:timer', label: '计时器' },
  { name: 'lucide:hourglass', label: '沙漏' },
  { name: 'lucide:sun', label: '太阳' },
  { name: 'lucide:moon', label: '月亮' },
  { name: 'lucide:cloud-sun', label: '多云' },
  { name: 'lucide:cloud-moon', label: '月夜' },
  { name: 'lucide:cloud-rain', label: '雨天' },
  { name: 'lucide:cloud-snow', label: '雪天' },
  { name: 'lucide:cloud-lightning', label: '雷电' },
  { name: 'lucide:wind', label: '风' },
  { name: 'lucide:thermometer', label: '温度' },
  { name: 'lucide:droplets', label: '水滴' },
  { name: 'lucide:flame', label: '火焰' },
  { name: 'lucide:zap', label: '闪电' },
  { name: 'lucide:atom', label: '原子' },
  { name: 'lucide:dna', label: 'DNA' },
  { name: 'lucide:microscope', label: '显微镜' },
  { name: 'lucide:telescope', label: '望远镜' },
  { name: 'lucide:rocket', label: '火箭' },
  { name: 'lucide:satellite', label: '卫星' },
  { name: 'lucide:radar', label: '雷达' },
  { name: 'lucide:radio', label: '广播' },
  { name: 'lucide:antenna', label: '天线' },
  { name: 'lucide:signal', label: '信号' },
  { name: 'lucide:tower-control', label: '控制塔' },
  { name: 'lucide:briefcase', label: '公文包' },
  { name: 'lucide:graduation-cap', label: '毕业' },
  { name: 'lucide:book', label: '书籍' },
  { name: 'lucide:book-open', label: '打开的书' },
  { name: 'lucide:library', label: '图书馆' },
  { name: 'lucide:newspaper', label: '报纸' },
  { name: 'lucide:scroll', label: '卷轴' },
  { name: 'lucide:scroll-text', label: '文本卷轴' },
  { name: 'lucide:pen', label: '钢笔' },
  { name: 'lucide:pen-tool', label: '画笔' },
  { name: 'lucide:pencil', label: '铅笔' },
  { name: 'lucide:highlighter', label: '高亮' },
  { name: 'lucide:marker', label: '标记' },
  { name: 'lucide:palette', label: '调色板' },
  { name: 'lucide:brush', label: '刷子' },
  { name: 'lucide:eraser', label: '橡皮' },
  { name: 'lucide:ruler', label: '尺子' },
  { name: 'lucide:calculator', label: '计算器' },
  { name: 'lucide:abacus', label: '算盘' },
  { name: 'lucide:brain', label: '大脑' },
  { name: 'lucide:lightbulb', label: '灯泡' },
  { name: 'lucide:target', label: '目标' },
  { name: 'lucide:bulb', label: '灯泡' },
  { name: 'lucide:plug', label: '插头' },
  { name: 'lucide:power', label: '电源' },
  { name: 'lucide:toggle-left', label: '开关' },
  { name: 'lucide:webhook', label: 'Webhook' },
  { name: 'lucide:workflow', label: '工作流' },
  { name: 'lucide:git-branch', label: '分支' },
  { name: 'lucide:git-commit', label: '提交' },
  { name: 'lucide:git-merge', label: '合并' },
  { name: 'lucide:git-pull-request', label: 'PR' },
  { name: 'lucide:code', label: '代码' },
  { name: 'lucide:code-2', label: '代码' },
  { name: 'lucide:terminal', label: '终端' },
  { name: 'lucide:bug', label: 'Bug' },
  { name: 'lucide:blocks', label: '积木' },
  { name: 'lucide:puzzle', label: '拼图' },
  { name: 'lucide:container', label: '容器' },
  { name: 'lucide:layers', label: '层级' },
  { name: 'lucide:layer', label: '层' },
  { name: 'lucide:component', label: '组件' },
  { name: 'lucide:shapes', label: '形状' },
  { name: 'lucide:box', label: '盒子' },
  { name: 'lucide:cube', label: '立方体' },
  { name: 'lucide:briefcase-business', label: '商务' },
  { name: 'lucide:receipt-text', label: '发票' },
  { name: 'lucide:wallet-cards', label: '卡包' },
  { name: 'lucide:coins', label: '硬币' },
  { name: 'lucide:banknote', label: '钞票' },
  { name: 'lucide:landmark', label: '地标' },
  { name: 'lucide:scale', label: '天平' },
  { name: 'lucide:gavel', label: '法槌' },
  { name: 'lucide:hammer', label: '锤子' },
  { name: 'lucide:wrench', label: '扳手' },
  { name: 'lucide:shovel', label: '铲子' },
  { name: 'lucide:pickaxe', label: '镐' },
  { name: 'lucide:construction', label: '施工' },
  { name: 'lucide:traffic-cone', label: '路障' },
  { name: 'lucide:barrier-block', label: '屏障' },
  { name: 'lucide:fence', label: '围栏' },
  { name: 'lucide:door-open', label: '开门' },
  { name: 'lucide:door-closed', label: '关门' },
  { name: 'lucide:archive', label: '归档' },
  { name: 'lucide:inbox', label: '收件箱' },
  { name: 'lucide:send', label: '发送' },
  { name: 'lucide:reply', label: '回复' },
  { name: 'lucide:reply-all', label: '回复全部' },
  { name: 'lucide:forward', label: '转发' },
  { name: 'lucide:paperclip', label: '附件' },
  { name: 'lucide:archive-restore', label: '恢复归档' },
  { name: 'lucide:archive-x', label: '删除归档' },
  { name: 'lucide:file-check', label: '文件确认' },
  { name: 'lucide:file-x', label: '文件错误' },
  { name: 'lucide:file-warning', label: '文件警告' },
  { name: 'lucide:file-question', label: '文件疑问' },
  { name: 'lucide:file-search', label: '文件搜索' },
  { name: 'lucide:file-code', label: '代码文件' },
  { name: 'lucide:file-json', label: 'JSON文件' },
  { name: 'lucide:file-cog', label: '配置文件' },
  { name: 'lucide:file-spreadsheet', label: '表格文件' },
  { name: 'lucide:file-type', label: '文件类型' },
  { name: 'lucide:presentation', label: '演示' },
  { name: 'lucide:projector', label: '投影仪' },
  { name: 'lucide:projector', label: '投影仪' },
  { name: 'lucide:calendar-check', label: '日程确认' },
  { name: 'lucide:calendar-clock', label: '日程时间' },
  { name: 'lucide:calendar-days', label: '日程天数' },
  { name: 'lucide:calendar-heart', label: '日程收藏' },
  { name: 'lucide:calendar-off', label: '日程关闭' },
  { name: 'lucide:calendar-plus', label: '添加日程' },
  { name: 'lucide:calendar-search', label: '搜索日程' },
  { name: 'lucide:calendar-x', label: '删除日程' },
  { name: 'lucide:clock-1', label: '时钟' },
  { name: 'lucide:clock-12', label: '时钟' },
  { name: 'lucide:alarm-check', label: '闹钟确认' },
  { name: 'lucide:alarm-minus', label: '闹钟减少' },
  { name: 'lucide:alarm-plus', label: '闹钟增加' },
  { name: 'lucide:alarm-off', label: '闹钟关闭' },
  { name: 'lucide:bed', label: '床' },
  { name: 'lucide:bed-double', label: '双人床' },
  { name: 'lucide:bed-single', label: '单人床' },
  { name: 'lucide:bath', label: '浴缸' },
  { name: 'lucide:shower-head', label: '淋浴' },
  { name: 'lucide:toilet', label: '马桶' },
  { name: 'lucide:scissors-line-dashed', label: '虚线剪刀' },
  { name: 'lucide:bone', label: '骨头' },
  { name: 'lucide:apple', label: '苹果' },
  { name: 'lucide:beef', label: '牛肉' },
  { name: 'lucide:coffee', label: '咖啡' },
  { name: 'lucide:utensils', label: '餐具' },
  { name: 'lucide:wine', label: '酒' },
  { name: 'lucide:beer', label: '啤酒' },
  { name: 'lucide:cake', label: '蛋糕' },
  { name: 'lucide:cookie', label: '饼干' },
  { name: 'lucide:ice-cream', label: '冰淇淋' },
  { name: 'lucide:pizza', label: '披萨' },
  { name: 'lucide:salad', label: '沙拉' },
  { name: 'lucide:sandwich', label: '三明治' },
  { name: 'lucide:soup', label: '汤' },
  { name: 'lucide:egg', label: '鸡蛋' },
  { name: 'lucide:milk', label: '牛奶' },
  { name: 'lucide:wheat', label: '小麦' },
  { name: 'lucide:bean', label: '豆子' },
  { name: 'lucide:plant', label: '植物' },
  { name: 'lucide:tree-pine', label: '松树' },
  { name: 'lucide:flower', label: '花' },
  { name: 'lucide:leaf', label: '叶子' },
  { name: 'lucide:mountain', label: '山' },
  { name: 'lucide:mountain-snow', label: '雪山' },
  { name: 'lucide:snowflake', label: '雪花' },
  { name: 'lucide:umbrella', label: '雨伞' },
  { name: 'lucide:rainbow', label: '彩虹' },
  { name: 'lucide:tornado', label: '龙卷风' },
  { name: 'lucide:volcano', label: '火山' },
  { name: 'lucide:waves', label: '波浪' },
  { name: 'lucide:fish', label: '鱼' },
  { name: 'lucide:shrimp', label: '虾' },
  { name: 'lucide:whale', label: '鲸鱼' },
  { name: 'lucide:dolphin', label: '海豚' },
  { name: 'lucide:snail', label: '蜗牛' },
  { name: 'lucide:bug', label: '虫子' },
  { name: 'lucide:cat', label: '猫' },
  { name: 'lucide:dog', label: '狗' },
  { name: 'lucide:rabbit', label: '兔子' },
  { name: 'lucide:mouse', label: '老鼠' },
  { name: 'lucide:spider', label: '蜘蛛' },
  { name: 'lucide:ladybug', label: '瓢虫' },
  { name: 'lucide:bird', label: '鸟' },
  { name: 'lucide:squirrel', label: '松鼠' },
  { name: 'lucide:turtle', label: '乌龟' },
  { name: 'lucide:unicorn', label: '独角兽' },
  { name: 'lucide:dragon', label: '龙' },
  { name: 'lucide:dinosaur', label: '恐龙' },
  { name: 'lucide:ghost', label: '幽灵' },
  { name: 'lucide:alien', label: '外星人' },
  { name: 'lucide:robot', label: '机器人' },
  { name: 'lucide:gamepad', label: '手柄' },
  { name: 'lucide:gamepad-2', label: '手柄' },
  { name: 'lucide:dice-1', label: '骰子' },
  { name: 'lucide:club', label: '梅花' },
  { name: 'lucide:diamond', label: '方块' },
  { name: 'lucide:heart', label: '红心' },
  { name: 'lucide:spade', label: '黑桃' },
  { name: 'lucide:chess', label: '国际象棋' },
  { name: 'lucide:medal', label: '奖牌' },
  { name: 'lucide:crown', label: '皇冠' },
  { name: 'lucide:gem', label: '宝石' },
  { name: 'lucide:ring', label: '戒指' },
  { name: 'lucide:shield', label: '盾牌' },
  { name: 'lucide:sword', label: '剑' },
  { name: 'lucide:swords', label: '双剑' },
  { name: 'lucide:axe', label: '斧头' },
  { name: 'lucide:bow-arrow', label: '弓箭' },
  { name: 'lucide:shuriken', label: '手里剑' },
  { name: 'lucide:fire-extinguisher', label: '灭火器' },
  { name: 'lucide:first-aid-kit', label: '急救包' },
  { name: 'lucide:hard-hat', label: '安全帽' },
  { name: 'lucide:life-buoy', label: '救生圈' },
  { name: 'lucide:siren', label: '警报器' },
  { name: 'lucide:ambulance', label: '救护车' },
  { name: 'lucide:hospital', label: '医院' },
  { name: 'lucide:stethoscope', label: '听诊器' },
  { name: 'lucide:syringe', label: '注射器' },
  { name: 'lucide:pill', label: '药丸' },
  { name: 'lucide:tablets', label: '药片' },
  { name: 'lucide:thermometer', label: '温度计' },
  { name: 'lucide:bandage', label: '绷带' },
  { name: 'lucide:brain', label: '大脑' },
  { name: 'lucide:ear', label: '耳朵' },
  { name: 'lucide:eye', label: '眼睛' },
  { name: 'lucide:foot', label: '脚' },
  { name: 'lucide:hand', label: '手' },
  { name: 'lucide:heart-pulse', label: '心率' },
  { name: 'lucide:lungs', label: '肺' },
  { name: 'lucide:skull', label: '头骨' },
  { name: 'lucide:tooth', label: '牙齿' },
  { name: 'lucide:baby', label: '婴儿' },
  { name: 'lucide:person-standing', label: '站立' },
  { name: 'lucide:accessibility', label: '无障碍' },
  { name: 'lucide:wheelchair', label: '轮椅' },
  { name: 'lucide:cane', label: '拐杖' },
  { name: 'lucide:crutch', label: '拐杖' },
  { name: 'lucide:monitor-speaker', label: '显示器音响' },
  { name: 'lucide:speaker', label: '音响' },
  { name: 'lucide:headphones', label: '耳机' },
  { name: 'lucide:headphone', label: '耳机' },
  { name: 'lucide:mic', label: '麦克风' },
  { name: 'lucide:mic-off', label: '关闭麦克风' },
  { name: 'lucide:volume', label: '音量' },
  { name: 'lucide:volume-1', label: '音量低' },
  { name: 'lucide:volume-2', label: '音量高' },
  { name: 'lucide:volume-x', label: '静音' },
  { name: 'lucide:play', label: '播放' },
  { name: 'lucide:pause', label: '暂停' },
  { name: 'lucide:skip-back', label: '上一曲' },
  { name: 'lucide:skip-forward', label: '下一曲' },
  { name: 'lucide:repeat', label: '循环' },
  { name: 'lucide:repeat-1', label: '单曲循环' },
  { name: 'lucide:shuffle', label: '随机' },
  { name: 'lucide:disc', label: '唱片' },
  { name: 'lucide:disc-2', label: '唱片' },
  { name: 'lucide:disc-3', label: '唱片' },
  { name: 'lucide:album', label: '专辑' },
  { name: 'lucide:radio', label: '收音机' },
  { name: 'lucide:ticket', label: '票' },
  { name: 'lucide:ticket-check', label: '票确认' },
  { name: 'lucide:ticket-minus', label: '票减少' },
  { name: 'lucide:ticket-percent', label: '票百分比' },
  { name: 'lucide:ticket-plus', label: '票增加' },
  { name: 'lucide:ticket-x', label: '票删除' },
  { name: 'lucide:trophy', label: '奖杯' },
  { name: 'lucide:medal', label: '奖牌' },
  { name: 'lucide:ribbon', label: '丝带' },
  { name: 'lucide:rosette', label: '玫瑰' },
  { name: 'lucide:rosette-number', label: '玫瑰编号' },
  { name: 'lucide:sparkle', label: '闪光' },
  { name: 'lucide:sparkles', label: '闪光' },
  { name: 'lucide:party-popper', label: '派对' },
  { name: 'lucide:popcorn', label: '爆米花' },
  { name: 'lucide:cake-slice', label: '蛋糕' },
  { name: 'lucide:cup-soda', label: '苏打水' },
  { name: 'lucide:martini', label: '马提尼' },
  { name: 'lucide:clover', label: '三叶草' },
  { name: 'lucide:shamrock', label: '三叶草' },
  { name: 'lucide:cactus', label: '仙人掌' },
  { name: 'lucide:palmtree', label: '棕榈树' },
  { name: 'lucide:evergreen', label: '常青树' },
  { name: 'lucide:deciduous-tree', label: '落叶树' },
  { name: 'lucide:seedling', label: '幼苗' },
  { name: 'lucide:herb', label: '草药' },
  { name: 'lucide:sprout', label: '芽' },
  { name: 'lucide:vine', label: '藤蔓' },
  { name: 'lucide:watermelon', label: '西瓜' },
  { name: 'lucide:melon', label: '甜瓜' },
  { name: 'lucide:cherry', label: '樱桃' },
  { name: 'lucide:lemon', label: '柠檬' },
  { name: 'lucide:banana', label: '香蕉' },
  { name: 'lucide:pineapple', label: '菠萝' },
  { name: 'lucide:mango', label: '芒果' },
  { name: 'lucide:peach', label: '桃子' },
  { name: 'lucide:pear', label: '梨' },
  { name: 'lucide:strawberry', label: '草莓' },
  { name: 'lucide:blueberry', label: '蓝莓' },
  { name: 'lucide:grapes', label: '葡萄' },
  { name: 'lucide:kiwi', label: '猕猴桃' },
  { name: 'lucide:avocado', label: '牛油果' },
  { name: 'lucide:broccoli', label: '西兰花' },
  { name: 'lucide:carrot', label: '胡萝卜' },
  { name: 'lucide:corn', label: '玉米' },
  { name: 'lucide:hot-pepper', label: '辣椒' },
  { name: 'lucide:potato', label: '土豆' },
  { name: 'lucide:sweet-potato', label: '红薯' },
  { name: 'lucide:onion', label: '洋葱' },
  { name: 'lucide:garlic', label: '大蒜' },
  { name: 'lucide:mushroom', label: '蘑菇' },
  { name: 'lucide:peanut', label: '花生' },
  { name: 'lucide:walnut', label: '核桃' },
  { name: 'lucide:hazelnut', label: '榛子' },
  { name: 'lucide:cashew', label: '腰果' },
  { name: 'lucide:almond', label: '杏仁' },
  { name: 'lucide:pistachio', label: '开心果' },
  { name: 'lucide:chestnut', label: '栗子' },
  { name: 'lucide:bean', label: '豆子' },
  { name: 'lucide:soybean', label: '大豆' },
  { name: 'lucide:lentil', label: '扁豆' },
  { name: 'lucide:pea', label: '豌豆' },
  { name: 'lucide:chickpea', label: '鹰嘴豆' },
  { name: 'lucide:rice', label: '米饭' },
  { name: 'lucide:wheat', label: '小麦' },
  { name: 'lucide:oat', label: '燕麦' },
  { name: 'lucide:barley', label: '大麦' },
  { name: 'lucide:rye', label: '黑麦' },
  { name: 'lucide:quinoa', label: '藜麦' },
  { name: 'lucide:flax', label: '亚麻' },
  { name: 'lucide:hemp', label: '大麻' },
  { name: 'lucide:cotton', label: '棉花' },
  { name: 'lucide:silk', label: '丝绸' },
  { name: 'lucide:wool', label: '羊毛' },
  { name: 'lucide:leather', label: '皮革' },
  { name: 'lucide:rubber', label: '橡胶' },
  { name: 'lucide:plastic', label: '塑料' },
  { name: 'lucide:glass', label: '玻璃' },
  { name: 'lucide:metal', label: '金属' },
  { name: 'lucide:wood', label: '木材' },
  { name: 'lucide:stone', label: '石头' },
  { name: 'lucide:brick', label: '砖块' },
  { name: 'lucide:concrete', label: '混凝土' },
  { name: 'lucide:marble', label: '大理石' },
  { name: 'lucite:granite', label: '花岗岩' },
  { name: 'lucite:slate', label: '石板' },
  { name: 'lucite:sand', label: '沙子' },
  { name: 'lucite:clay', label: '粘土' },
  { name: 'lucite:soil', label: '土壤' },
  { name: 'lucite:mud', label: '泥' },
  { name: 'lucite:dust', label: '灰尘' },
  { name: 'lucite:ash', label: '灰' },
  { name: 'lucite:smoke', label: '烟' },
  { name: 'lucite:steam', label: '蒸汽' },
  { name: 'lucite:cloud', label: '云' },
  { name: 'lucite:fog', label: '雾' },
  { name: 'lucite:mist', label: '薄雾' },
  { name: 'lucite:dew', label: '露水' },
  { name: 'lucite:frost', label: '霜' },
  { name: 'lucite:ice', label: '冰' },
  { name: 'lucite:snow', label: '雪' },
  { name: 'lucite:hail', label: '冰雹' },
  { name: 'lucite:sleet', label: '雨夹雪' },
  { name: 'lucite:rain', label: '雨' },
  { name: 'lucite:storm', label: '暴风雨' },
  { name: 'lucite:thunder', label: '雷' },
  { name: 'lucite:lightning', label: '闪电' },
  { name: 'lucite:rainbow', label: '彩虹' },
  { name: 'lucite:sunrise', label: '日出' },
  { name: 'lucite:sunset', label: '日落' },
  { name: 'lucite:twilight', label: '暮光' },
  { name: 'lucite:night', label: '夜晚' },
  { name: 'lucite:moon', label: '月亮' },
  { name: 'lucite:star', label: '星星' },
  { name: 'lucite:galaxy', label: '银河' },
  { name: 'lucite:universe', label: '宇宙' },
  { name: 'lucite:planet', label: '行星' },
  { name: 'lucite:satellite', label: '卫星' },
  { name: 'lucite:astronaut', label: '宇航员' },
  { name: 'lucite:telescope', label: '望远镜' },
  { name: 'lucite:microscope', label: '显微镜' },
  { name: 'lucite:magnet', label: '磁铁' },
  { name: 'lucite:battery', label: '电池' },
  { name: 'lucite:battery-charging', label: '充电' },
  { name: 'lucite:battery-full', label: '满电' },
  { name: 'lucite:battery-low', label: '低电' },
  { name: 'lucite:battery-medium', label: '中电' },
  { name: 'lucite:battery-warning', label: '电量警告' },
  { name: 'lucite:cable', label: '电缆' },
  { name: 'lucite:plug', label: '插头' },
  { name: 'lucite:outlet', label: '插座' },
  { name: 'lucite:light-switch', label: '灯开关' },
  { name: 'lucite:fan', label: '风扇' },
  { name: 'lucite:air-conditioner', label: '空调' },
  { name: 'lucite:heater', label: '暖气' },
  { name: 'lucite:thermostat', label: '温控器' },
  { name: 'lucite:fireplace', label: '壁炉' },
  { name: 'lucite:chimney', label: '烟囱' },
  { name: 'lucite:roof', label: '屋顶' },
  { name: 'lucite:wall', label: '墙' },
  { name: 'lucite:floor', label: '地板' },
  { name: 'lucite:ceiling', label: '天花板' },
  { name: 'lucite:door', label: '门' },
  { name: 'lucite:window', label: '窗户' },
  { name: 'lucite:stairs', label: '楼梯' },
  { name: 'lucite:elevator', label: '电梯' },
  { name: 'lucite:escalator', label: '扶梯' },
  { name: 'lucite:ramp', label: '坡道' },
  { name: 'lucite:bridge', label: '桥' },
  { name: 'lucite:tunnel', label: '隧道' },
  { name: 'lucite:road', label: '道路' },
  { name: 'lucite:highway', label: '高速公路' },
  { name: 'lucite:railroad', label: '铁路' },
  { name: 'lucite:subway', label: '地铁' },
  { name: 'lucite:tram', label: '电车' },
  { name: 'lucite:bus', label: '公交车' },
  { name: 'lucite:taxi', label: '出租车' },
  { name: 'lucite:ambulance', label: '救护车' },
  { name: 'lucite:fire-truck', label: '消防车' },
  { name: 'lucite:police-car', label: '警车' },
  { name: 'lucite:helicopter', label: '直升机' },
  { name: 'lucite:airplane', label: '飞机' },
  { name: 'lucite:jet', label: '喷气机' },
  { name: 'lucite:rocket', label: '火箭' },
  { name: 'lucite:ufo', label: 'UFO' },
  { name: 'lucite:satellite', label: '卫星' },
  { name: 'lucite:space-station', label: '空间站' },
  { name: 'lucite:moon-rover', label: '月球车' },
  { name: 'lucite:mars-rover', label: '火星车' },
  { name: 'lucite:telescope', label: '望远镜' },
  { name: 'lucite:observatory', label: '天文台' },
  { name: 'lucite:planetarium', label: '天文馆' },
  { name: 'lucite:museum', label: '博物馆' },
  { name: 'lucite:gallery', label: '画廊' },
  { name: 'lucite:theater', label: '剧院' },
  { name: 'lucite:cinema', label: '电影院' },
  { name: 'lucite:stadium', label: '体育场' },
  { name: 'lucite:arena', label: '竞技场' },
  { name: 'lucite:pool', label: '游泳池' },
  { name: 'lucite:beach', label: '海滩' },
  { name: 'lucite:island', label: '岛屿' },
  { name: 'lucite:volcano', label: '火山' },
  { name: 'lucite:mountain', label: '山' },
  { name: 'lucite:hill', label: '小山' },
  { name: 'lucite:valley', label: '山谷' },
  { name: 'lucite:canyon', label: '峡谷' },
  { name: 'lucite:cave', label: '洞穴' },
  { name: 'lucite:desert', label: '沙漠' },
  { name: 'lucite:forest', label: '森林' },
  { name: 'lucite:jungle', label: '丛林' },
  { name: 'lucite:savanna', label: '草原' },
  { name: 'lucite:tundra', label: '冻原' },
  { name: 'lucite:glacier', label: '冰川' },
  { name: 'lucite:iceberg', label: '冰山' },
  { name: 'lucite:ocean', label: '海洋' },
  { name: 'lucite:sea', label: '海' },
  { name: 'lucite:lake', label: '湖' },
  { name: 'lucite:river', label: '河流' },
  { name: 'lucite:stream', label: '小溪' },
  { name: 'lucite:waterfall', label: '瀑布' },
  { name: 'lucite:spring', label: '泉水' },
  { name: 'lucite:well', label: '井' },
  { name: 'lucite:fountain', label: '喷泉' },
  { name: 'lucite:pond', label: '池塘' },
  { name: 'lucite:swamp', label: '沼泽' },
  { name: 'lucite:marsh', label: '湿地' },
  { name: 'lucite:bog', label: '泥炭地' },
  { name: 'lucite:fen', label: '沼泽' },
  { name: 'lucite:mangrove', label: '红树林' },
  { name: 'lucite:coral', label: '珊瑚' },
  { name: 'lucite:reef', label: '礁石' },
  { name: 'lucite:kelp', label: '海藻' },
  { name: 'lucite:seaweed', label: '海草' },
  { name: 'lucite:algae', label: '藻类' },
  { name: 'lucite:plankton', label: '浮游生物' },
  { name: 'lucite:fish', label: '鱼' },
  { name: 'lucite:shark', label: '鲨鱼' },
  { name: 'lucite:whale', label: '鲸鱼' },
  { name: 'lucite:dolphin', label: '海豚' },
  { name: 'lucite:seal', label: '海豹' },
  { name: 'lucite:sea-lion', label: '海狮' },
  { name: 'lucite:walrus', label: '海象' },
  { name: 'lucite:otter', label: '水獭' },
  { name: 'lucite:beaver', label: '海狸' },
  { name: 'lucite:platypus', label: '鸭嘴兽' },
  { name: 'lucite:echidna', label: '针鼹' },
  { name: 'lucite:kangaroo', label: '袋鼠' },
  { name: 'lucite:koala', label: '考拉' },
  { name: 'lucite:wombat', label: '袋熊' },
  { name: 'lucite:possum', label: '负鼠' },
  { name: 'lucite:opossum', label: '负鼠' },
  { name: 'lucite:armadillo', label: '犰狳' },
  { name: 'lucite:sloth', label: '树懒' },
  { name: 'lucite:anteater', label: '食蚁兽' },
  { name: 'lucite:pangolin', label: '穿山甲' },
  { name: 'lucite:elephant', label: '大象' },
  { name: 'lucite:mammoth', label: '猛犸' },
  { name: 'lucite:rhinoceros', label: '犀牛' },
  { name: 'lucite:hippopotamus', label: '河马' },
  { name: 'lucite:giraffe', label: '长颈鹿' },
  { name: 'lucite:camel', label: '骆驼' },
  { name: 'lucite:llama', label: '羊驼' },
  { name: 'lucite:alpaca', label: '羊驼' },
  { name: 'lucite:vicuna', label: '骆马' },
  { name: 'lucite:deer', label: '鹿' },
  { name: 'lucite:elk', label: '麋鹿' },
  { name: 'lucite:moose', label: '驼鹿' },
  { name: 'lucite:reindeer', label: '驯鹿' },
  { name: 'lucite:caribou', label: '驯鹿' },
  { name: 'lucite:antelope', label: '羚羊' },
  { name: 'lucite:gazelle', label: '瞪羚' },
  { name: 'lucite:impala', label: '黑斑羚' },
  { name: 'lucite:wildebeest', label: '角马' },
  { name: 'lucite:buffalo', label: '水牛' },
  { name: 'lucite:bison', label: '野牛' },
  { name: 'lucite:cow', label: '牛' },
  { name: 'lucite:bull', label: '公牛' },
  { name: 'lucite:ox', label: '公牛' },
  { name: 'lucite:calf', label: '小牛' },
  { name: 'lucite:goat', label: '山羊' },
  { name: 'lucite:sheep', label: '绵羊' },
  { name: 'lucite:lamb', label: '羔羊' },
  { name: 'lucite:ram', label: '公羊' },
  { name: 'lucite:ewe', label: '母羊' },
  { name: 'lucite:pig', label: '猪' },
  { name: 'lucite:boar', label: '野猪' },
  { name: 'lucite:hog', label: '猪' },
  { name: 'lucite:warthog', label: '疣猪' },
  { name: 'lucite:peccary', label: '西貒' },
  { name: 'lucite:horse', label: '马' },
  { name: 'lucite:stallion', label: '种马' },
  { name: 'lucite:mare', label: '母马' },
  { name: 'lucite:foal', label: '马驹' },
  { name: 'lucite:colt', label: '小公马' },
  { name: 'lucite:filly', label: '小母马' },
  { name: 'lucite:pony', label: '小马' },
  { name: 'lucite:donkey', label: '驴' },
  { name: 'lucite:mule', label: '骡子' },
  { name: 'lucite:zebra', label: '斑马' },
  { name: 'lucite:unicorn', label: '独角兽' },
];

/** 过滤后的图标列表 */
const filteredIcons = computed(() => {
  const keyword = searchKeyword.value.toLowerCase().trim();
  if (!keyword) return ICON_LIST;
  return ICON_LIST.filter(
    (icon) => icon.name.toLowerCase().includes(keyword) || icon.label.toLowerCase().includes(keyword),
  );
});

/** 打开弹窗 */
function open(): void {
  visible.value = true;
  searchKeyword.value = '';
  selectedIcon.value = '';
}

/** 关闭弹窗 */
function close(): void {
  visible.value = false;
  emit('close');
}

/** 选择图标 */
function selectIcon(icon: { name: string; label: string }): void {
  selectedIcon.value = icon.name;
  emit('select', icon.name);
  ElMessage.success(`已选择图标：${icon.label}`);
  close();
}

/** 清除选择 */
function clearSelection(): void {
  selectedIcon.value = '';
  emit('select', '');
  close();
}

defineExpose({ open, close });
</script>

<template>
  <ElDialog
    v-model="visible"
    title="选择图标"
    width="700px"
    :close-on-click-modal="true"
    @close="close"
  >
    <div class="icon-picker">
      <!-- 搜索框 -->
      <div class="mb-4">
        <ElInput
          v-model="searchKeyword"
          placeholder="搜索图标名称..."
          clearable
          prefix-icon="lucide:search"
        />
      </div>

      <!-- 图标网格 -->
      <ElScrollbar max-height="400px">
        <div class="grid grid-cols-8 gap-2 p-1">
          <div
            v-for="icon in filteredIcons"
            :key="icon.name"
            class="icon-item flex cursor-pointer flex-col items-center justify-center rounded border p-2 hover:border-blue-500 hover:bg-blue-50"
            :class="{ 'border-blue-500 bg-blue-50': selectedIcon === icon.name }"
            :title="icon.label"
            @click="selectIcon(icon)"
          >
            <span class="text-lg">{{ icon.name }}</span>
            <span class="mt-1 truncate text-xs text-gray-500">{{ icon.label }}</span>
          </div>
        </div>
        <div v-if="filteredIcons.length === 0" class="py-8 text-center text-gray-400">
          未找到匹配的图标
        </div>
      </ElScrollbar>

      <!-- 底部操作 -->
      <div class="mt-4 flex justify-between border-t pt-3">
        <span class="text-sm text-gray-500">
          共 {{ filteredIcons.length }} 个图标
        </span>
        <div class="flex gap-2">
          <ElButton size="small" @click="clearSelection">清除选择</ElButton>
          <ElButton size="small" @click="close">取消</ElButton>
        </div>
      </div>
    </div>
  </ElDialog>
</template>

<style scoped>
.icon-picker {
  min-height: 300px;
}

.icon-item {
  transition: all 0.2s ease;
}

.icon-item:hover {
  transform: scale(1.05);
}
</style>
