<!--
 * 运维缓存管理页面
 *
 * <p>管理消息模板缓存和 BloomFilter，展示缓存命中率、填充率等运维指标，
 * 支持清理单个缓存和全量清理等操作。
 *
 * @path apps/message-web/src/views/ops/index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 运维缓存管理（指标展示 + 缓存操作）
 * <p>消费后端契约 OpsController（src/api/ops.ts，auto-generated by bash/gen-contract.py）：
 * getTemplateCacheStats() 查询模板缓存统计，evictTemplateCache() 清理单个缓存条目，
 * clearTemplateCache() 全量清理模板缓存，getBloomFilterStats() 查询 BloomFilter 统计。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import { Page } from '@ydsz/common-ui';

import { createLogger } from '@YDSZ-core/shared/utils';
import {
  ElButton,
  ElCard,
  ElDialog,
  ElForm,
  ElFormItem,
  ElInput,
  ElMessage,
  ElMessageBox,
} from 'element-plus';
import { onMounted, ref } from 'vue';

import {
  clearTemplateCache,
  evictTemplateCache,
  getBloomFilterStats,
  getTemplateCacheStats,
} from '#/api/ops';
import type { BloomFilterStatsVO, CacheStatsVO } from '#/api/models';

defineOptions({ name: 'OpsCacheManagement' });

const logger = createLogger('ops-cache');

/** 加载状态 */
const loading = ref(false);

/** 模板缓存统计 */
const cacheStats = ref<CacheStatsVO>({});

/** BloomFilter 统计 */
const bloomStats = ref<BloomFilterStatsVO>({});

/** 清理弹窗可见性 */
const evictDialogVisible = ref(false);

/** 清理表单 */
const evictForm = ref({ template: '});

/** 缓存命中率百分比 */
const hitRatePercent = ref(0);

/** 加载模板缓存统计 */
async function loadCacheStats(): Promise<void> {
  try {
    const stats = await getTemplateCacheStats();
    cacheStats.value = stats ?? {};
    hitRatePercent.value = Math.round((stats?.hitRate ?? 0) * 100);
  } catch (error) {
    logger.warn('查询模板缓存统计失败: {}', error);
  }
}

/** 加载 BloomFilter 统计 */
async function loadBloomStats(): Promise<void> {
  try {
    const stats = await getBloomFilterStats();
    bloomStats.value = stats ?? {};
  } catch (error) {
    logger.warn('查询 BloomFilter 统计失败: {}', error);
  }
}

/** 加载所有统计数据 */
async function loadAllStats(): Promise<void> {
  loading.value = true;
  try {
    await Promise.all([loadCacheStats(), loadBloomStats()]);
  } finally {
    loading.value = false;
  }
}

/** 确认清理单个缓存 */
async function handleEvictCache(): Promise<void> {
  if (!evictForm.value.template.trim()) {
    ElMessage.warning('请输入要清理的模板编码');
    return;
  }
  try {
    await ElMessageBox.confirm(
      `确定清理模板「${evictForm.value.template}」的缓存吗？`,
      '清理确认',
      { type: 'warning' },
    );
  } catch {
    logger.debug('用户取消清理缓存操作');
    return;
  }
  try {
    await evictTemplateCache({ template: evictForm.value.template.trim() });
    ElMessage.success('缓存清理成功');
    evictDialogVisible.value = false;
    evictForm.value.template = '';
    loadCacheStats();
  } catch (error) {
    logger.warn('清理缓存失败: {}', error);
  }
}

/** 确认全量清理缓存 */
async function handleClearAllCache(): Promise<void> {
  try {
    await ElMessageBox.confirm(
      '确定全量清理模板缓存吗？清理后所有模板将被重新加载，操作不可恢复。',
      '全量清理确认',
      { type: 'warning', confirmButtonText: '确认清理', cancelButtonText: '取消' },
    );
  } catch {
    logger.debug('用户取消全量清理缓存操作');
    return;
  }
  try {
    await clearTemplateCache();
    ElMessage.success('全量缓存清理成功');
    loadCacheStats();
  } catch (error) {
    logger.warn('全量清理缓存失败: {}', error);
  }
}

onMounted(() => {
  loadAllStats();
});
</script>

<template>
  <Page auto-content-height>
    <div class="ops-container p-4">
      <!-- 顶部指标卡片区 -->
      <div class="mb-4 grid grid-cols-1 gap-4 md:grid-cols-4">
        <ElCard shadow="hover">
          <div class="flex flex-col items-center">
            <span class="text-sm text-gray-500">缓存命中率</span>
            <span class="mt-2 text-2xl font-bold text-green-600">{{ hitRatePercent }}%</span>
          </div>
        </ElCard>
        <ElCard shadow="hover">
          <div class="flex flex-col items-center">
            <span class="text-sm text-gray-500">缓存条目数</span>
            <span class="mt-2 text-2xl font-bold text-blue-600">{{ cacheStats.size ?? 0 }}</span>
          </div>
        </ElCard>
        <ElCard shadow="hover">
          <div class="flex flex-col items-center">
            <span class="text-sm text-gray-500">BF 填充率</span>
            <span class="mt-2 text-2xl font-bold text-purple-600">
              {{ bloomStats.expectedInsertions ?? 0 }}
            </span>
          </div>
        </ElCard>
        <ElCard shadow="hover">
          <div class="flex flex-col items-center">
            <span class="text-sm text-gray-500">BF 误判率</span>
            <span class="mt-2 text-2xl font-bold text-red-500">
              {{ ((bloomStats.fpp ?? 0) * 100).toFixed(4) }}%
            </span>
          </div>
        </ElCard>
      </div>

      <div class="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <!-- 模板缓存区 -->
        <ElCard shadow="never">
          <div class="mb-4 flex items-center justify-between">
            <h3 class="text-base font-medium">模板缓存统计</h3>
            <div class="flex gap-2">
              <ElButton size="small" @click="loadCacheStats">刷新</ElButton>
              <ElButton size="small" type="primary" @click="evictDialogVisible = true">
                清理单条
              </ElButton>
              <ElButton size="small" type="danger" @click="handleClearAllCache">
                全量清理
              </ElButton>
            </div>
          </div>

          <div v-loading="loading" class="space-y-4">
            <div class="grid grid-cols-2 gap-4">
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">命中次数</span>
                <p class="mt-1 text-lg font-mono font-bold">{{ cacheStats.hitCount ?? 0 }}</p>
              </div>
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">未命中次数</span>
                <p class="mt-1 text-lg font-mono font-bold">{{ cacheStats.missCount ?? 0 }}</p>
              </div>
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">淘汰次数</span>
                <p class="mt-1 text-lg font-mono font-bold">{{ cacheStats.evictionCount ?? 0 }}</p>
              </div>
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">缓存大小</span>
                <p class="mt-1 text-lg font-mono font-bold">{{ cacheStats.size ?? 0 }} 条</p>
              </div>
            </div>
          </div>
        </ElCard>

        <!-- BloomFilter 区 -->
        <ElCard shadow="never">
          <div class="mb-4 flex items-center justify-between">
            <h3 class="text-base font-medium">BloomFilter 统计</h3>
            <ElButton size="small" @click="loadBloomStats">刷新</ElButton>
          </div>

          <div v-loading="loading" class="space-y-4">
            <div class="grid grid-cols-2 gap-4">
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">预期插入数</span>
                <p class="mt-1 text-lg font-mono font-bold">
                  {{ bloomStats.expectedInsertions ?? 0 }}
                </p>
              </div>
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">当前误判率 (FPP)</span>
                <p class="mt-1 text-lg font-mono font-bold">
                  {{ ((bloomStats.fpp ?? 0) * 100).toFixed(4) }}%
                </p>
              </div>
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">是否主窗口</span>
                <p class="mt-1 text-lg font-mono font-bold">
                  {{ bloomStats.primary ? '是' : '否' }}
                </p>
              </div>
              <div class="rounded bg-gray-50 p-3">
                <span class="text-xs text-gray-500">窗口存活秒数</span>
                <p class="mt-1 text-lg font-mono font-bold">
                  {{ bloomStats.windowAgeSeconds ?? 0 }}s
                </p>
              </div>
            </div>
          </div>
        </ElCard>
      </div>

      <!-- 清理单条缓存弹窗 -->
      <ElDialog v-model="evictDialogVisible" title="清理单条模板缓存" width="480px">
        <ElForm :model="evictForm" label-width="100px">
          <ElFormItem label="模板编码" required>
            <ElInput
              v-model="evictForm.template"
              placeholder="请输入要清理的模板编码"
              clearable
            />
          </ElFormItem>
        </ElForm>
        <template #footer>
          <ElButton @click="evictDialogVisible = false">取消</ElButton>
          <ElButton type="primary" @click="handleEvictCache">确认清理</ElButton>
        </template>
      </ElDialog>
    </div>
  </Page>
</template>
