/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * DagWorkflowController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code DagWorkflowController}，共 4 个端点。
 * <p>路径规范: /api/v1/agent/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py agent} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { DagWorkflow, DagWorkflowDTO } from './models';

/**
 * save: POST /agent/dag-workflow/save
 */
export function save(data: DagWorkflowDTO): Promise<string> {
  return requestClient.post<string>(`/agent/dag-workflow/save`, data);
}

/**
 * getByCode: GET /agent/dag-workflow/{code}
 */
export function getByCode({ code }: {
    code: string;
  }): Promise<DagWorkflow> {
  return requestClient.get<DagWorkflow>(`/agent/dag-workflow/${code}`);
}

/**
 * list: GET /agent/dag-workflow/list
 */
export function list(params: {
    category?: string;
  }): Promise<DagWorkflow[]> {
  return requestClient.get<DagWorkflow[]>(`/agent/dag-workflow/list`, { params });
}

/**
 * delete: DELETE /agent/dag-workflow/{code}
 */
export function deleteApi({ code }: {
    code: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/agent/dag-workflow/${code}`);
}
