/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * RagController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RagController}，共 4 个端点。
 * <p>路径规范: /api/v1/agent/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @path apps\agent-web\src\api\rag.ts
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py agent} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { DocumentIngestDTO, RagQueryDTO } from './models';

/**
 * ingest: POST /api/v1/agent/rag/ingest
 */
export function ingest(data: DocumentIngestDTO): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.post<Record<string, Record<string, unknown>>>(`/api/v1/agent/rag/ingest`, data);
}

/**
 * search: POST /api/v1/agent/rag/search
 */
export function search(data: RagQueryDTO): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.post<Record<string, Record<string, unknown>>>(`/api/v1/agent/rag/search`, data);
}

/**
 * deleteDocument: DELETE /api/v1/agent/rag/documents/{documentId}
 */
export function deleteDocument({ documentId }: {
    documentId: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/agent/rag/documents/${documentId}`);
}

/**
 * stats: GET /api/v1/agent/rag/stats
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function stats(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/agent/rag/stats`);
}
