/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * RagController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RagController}，共 4 个端点。
 * <p>路径规范: /api/v1/agent/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py agent} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { DocumentIngestDTO, RagQueryDTO } from './models';

/**
 * ingest: POST /api/v1/agent/rag/ingest
 */
export function ingest(data: DocumentIngestDTO): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/agent/rag/ingest`, data);
}

/**
 * search: POST /api/v1/agent/rag/search
 */
export function search(data: RagQueryDTO): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/agent/rag/search`, data);
}

/**
 * deleteDocument: DELETE /api/v1/agent/rag/documents/{documentId}
 */
export function deleteDocument(path: {
    documentId: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/agent/rag/documents/${documentId}`);
}

/**
 * stats: GET /api/v1/agent/rag/stats
 */
export function stats(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/agent/rag/stats`);
}
