/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * TriggerController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code TriggerController}，共 7 个端点。
 * <p>路径规范: /api/v1/agent/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py agent} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { AgentTrigger } from './models';

/**
 * createTrigger: POST /api/agent/triggers
 */
export function createTrigger(data: Record<string, unknown>): Promise<AgentTrigger> {
  return requestClient.post<AgentTrigger>(`/api/agent/triggers`, data);
}

/**
 * updateTrigger: PUT /api/agent/triggers/{triggerId}
 */
export function updateTrigger({ triggerId }: {
    triggerId: string;
  }, data: Record<string, unknown>): Promise<AgentTrigger> {
  return requestClient.put<AgentTrigger>(`/api/agent/triggers/${triggerId}`, data);
}

/**
 * enableTrigger: POST /api/agent/triggers/{triggerId}/enable
 */
export function enableTrigger({ triggerId }: {
    triggerId: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/agent/triggers/${triggerId}/enable`);
}

/**
 * disableTrigger: POST /api/agent/triggers/{triggerId}/disable
 */
export function disableTrigger({ triggerId }: {
    triggerId: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/agent/triggers/${triggerId}/disable`);
}

/**
 * deleteTrigger: DELETE /api/agent/triggers/{triggerId}
 */
export function deleteTrigger({ triggerId }: {
    triggerId: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/agent/triggers/${triggerId}`);
}

/**
 * getTrigger: GET /api/agent/triggers/{triggerId}
 */
export function getTrigger({ triggerId }: {
    triggerId: string;
  }): Promise<AgentTrigger> {
  return requestClient.get<AgentTrigger>(`/api/agent/triggers/${triggerId}`);
}

/**
 * listTriggers: GET /api/agent/triggers
 */
export function listTriggers(): Promise<AgentTrigger[]> {
  return requestClient.get<AgentTrigger[]>(`/api/agent/triggers`);
}
