#!/usr/bin/env python3
"""Generate i18n files for 78 locales. Reads comm data; fills gaps from embedded tables."""
import json, os, sys

BC=r"D:\Code\open\ydsz-micro\comm\locales\src\langs"
BM=r"D:\Code\open\ydsz-micro\main\src\locales\langs"

L=["af-ZA","am-ET","ar-EG","ar-SA","az-AZ","bg-BG","bn-BD","bs-BA","ca-ES","cs-CZ","cy-GB","da-DK","de-AT","de-CH","de-DE","el-GR","en-GB","es-AR","es-ES","es-MX","et-EE","eu-ES","fa-IR","fi-FI","fil-PH","fr-CA","fr-FR","gl-ES","gu-IN","he-IL","hi-IN","hr-HR","hu-HU","hy-AM","id-ID","is-IS","it-IT","ja-JP","ka-GE","kk-KZ","km-KH","kn-IN","ko-KR","lo-LA","lt-LT","lv-LV","mk-MK","ml-IN","mn-MN","mr-IN","ms-MY","my-MM","nb-NO","ne-NP","nl-BE","nl-NL","pl-PL","pt-BR","pt-PT","ro-RO","ru-RU","si-LK","sk-SK","sl-SI","sq-AL","sr-RS","sv-SE","sw-KE","ta-IN","te-IN","th-TH","tr-TR","uk-UA","ur-PK","uz-UZ","vi-VN","zh-HK","zh-TW","zu-ZA"]

def rj(p):
    try:
        with open(p,'r',encoding='utf-8') as f:return json.load(f)
    except:return {}

def sg(d,k,fb):
    v=d.get(k)
    if not v or not isinstance(v,str) or "MYMEMORY WARNING" in v:return fb
    return v

# Transaction data: key -> locale -> text
# Loaded from separate JSON file generated by write_data.py
def load_data():
    dp=os.path.join(os.path.dirname(os.path.abspath(__file__)),"i18n_data.json")
    return rj(dp)

def main():
    T=load_data()
    cnt=0
    for loc in L:
        cc=rj(os.path.join(BC,loc,"common.json"))
        ca=rj(os.path.join(BC,loc,"authentication.json"))
        login=sg(cc,"login",T.get("login",{}).get(loc,"Login"))
        qr=sg(ca,"qrcodeLogin",T.get("qrcodeLogin",{}).get(loc,"QR Code Login"))
        fp=sg(ca,"forgetPassword",T.get("forgetPassword",{}).get(loc,"Forget Password"))
        g=lambda k,d="":T.get(k,{}).get(loc,d)
        page={"auth":{"login":login,"register":g("register"),"codeLogin":g("codeLogin"),"qrcodeLogin":qr,"forgetPassword":fp},
        "dashboard":{"title":g("dash_title"),"analytics":g("dash_analytics"),"workspace":g("dash_workspace")},
        "microKernel":{"containerLabel":g("container"),
        "phase":{"loading":g("ph_loading"),"loaded":g("ph_loaded"),"mounting":g("ph_mounting"),"mounted":g("ph_loaded"),"unmounting":g("ph_unmounting"),"error":g("ph_error")},
        "announcements":{"loading":g("ann_loading"),"loaded":g("ann_loaded"),"mounting":g("ann_mounting"),"mounted":g("ann_mounted"),"unmounting":g("ann_unmounting"),"error":g("ann_error")},
        "errorMask":{"title":g("err_title"),"hint":g("err_hint")}}}
        demos={"title":g("demos_title")}
        od=os.path.join(BM,loc)
        os.makedirs(od,exist_ok=True)
        with open(os.path.join(od,"page.json"),'w',encoding='utf-8') as f:
            json.dump(page,f,ensure_ascii=False,indent=2);f.write("\n")
        with open(os.path.join(od,"demos.json"),'w',encoding='utf-8') as f:
            json.dump(demos,f,ensure_ascii=False,indent=2);f.write("\n")
        cnt+=1
    print(f"Generated {cnt} locale file pairs")

if __name__=="__main__":
    main()
