/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * NotificationController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code NotificationController}，共 10 个端点。
 * <p>路径规范: /api/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { BroadcastRequestDTO, MessageResult, NotificationQueryDTO, NotificationSendDTO, PageResponse, PushRealtimeRequestDTO } from './models';

/**
 * send: POST /api/message/notifications/send
 */
export function send(data: NotificationSendDTO): Promise<number> {
  return requestClient.post<number>(`/api/message/notifications/send`, data);
}

/**
 * inbox: GET /api/message/notifications/inbox
 */
export function inbox(params: {
    query?: NotificationQueryDTO;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/message/notifications/inbox`, { params });
}

/**
 * countUnread: GET /api/message/notifications/unreadCount
 */
export function countUnread(): Promise<number> {
  return requestClient.get<number>(`/api/message/notifications/unreadCount`);
}

/**
 * markRead: POST /api/message/notifications/{id}/read
 */
export function markRead(path: {
    id: string;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/api/message/notifications/${id}/read`);
}

/**
 * markAllRead: POST /api/message/notifications/readAll
 */
export function markAllRead(): Promise<number> {
  return requestClient.post<number>(`/api/message/notifications/readAll`);
}

/**
 * delete: DELETE /api/message/notifications
 */
export function delete(data: string[]): Promise<void> {
  return requestClient.delete<void>(`/api/message/notifications`, data);
}

/**
 * recall: POST /api/message/notifications/{id}/recall
 */
export function recall(path: {
    id: string;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/api/message/notifications/${id}/recall`);
}

/**
 * push: POST /api/message/notifications/push
 */
export function push(params: {
    userId?: string;
    type?: string;
  }, data: PushRealtimeRequestDTO): Promise<unknown> {
  return requestClient.post<unknown>(`/api/message/notifications/push`, data, { params });
}

/**
 * broadcast: POST /api/message/notifications/broadcast
 */
export function broadcast(data: BroadcastRequestDTO): Promise<MessageResult> {
  return requestClient.post<MessageResult>(`/api/message/notifications/broadcast`, data);
}

/**
 * pushRealtime: POST /api/message/notifications/push-realtime
 */
export function pushRealtime(data: PushRealtimeRequestDTO): Promise<MessageResult> {
  return requestClient.post<MessageResult>(`/api/message/notifications/push-realtime`, data);
}
