// zh-TW, zu-ZA, hy-AM, az-AZ, bg-BG, cs-CZ, sk-SK, sl-SI, sr-RS, sq-AL
module.exports = {
'zh-TW': {
  biz: {
    fileName:"檔案名稱",fileSize:"檔案大小",fileType:"檔案類型",filePath:"檔案路徑",uploadTime:"上傳時間",owner:"擁有者",shareLink:"分享連結",sharePassword:"提取密碼",expireTime:"過期時間",tagName:"標籤名稱",tagColor:"標籤顏色",commentContent:"評論內容",commentAuthor:"評論人",commentTime:"評論時間",totalQuota:"總配額",usedQuota:"已用配額",create:"新增",edit:"編輯",delete:"刪除",confirmDelete:"確定刪除嗎？",operationSuccess:"操作成功",seq:"序號",name:"名稱",type:"類型",operation:"操作",action:"操作",path:"路徑",createdBy:"建立人",createdAt:"建立時間",status:"狀態",visibility:"可見性",description:"描述",
    fileManagement:"檔案管理",uploadFile:"上傳檔案",newFolder:"新增資料夾",folderName:"資料夾名稱",folderNamePlaceholder:"請輸入資料夾名稱",parentId:"父目錄ID",parentIdPlaceholder:"請輸入父目錄ID（留空表示根目錄）",preview:"預覽",download:"下載",onlineEdit:"編輯",version:"版本",rename:"重新命名",move:"移動",copy:"複製",nameColumn:"名稱",nodeType:"類型",fileSizeColumn:"大小",pathColumn:"路徑",createdByColumn:"建立人",createdAtColumn:"建立時間",nodeTypeDirectory:"目錄",nodeTypeFile:"檔案",searchNamePlaceholder:"請輸入名稱",confirmCopy:"確定複製「{name}」嗎？",confirmDeleteFile:"確定刪除「{name}」嗎？刪除後不可恢復。",deleteSuccess:"刪除成功",copySuccess:"複製成功",renameTitle:"重新命名",renamePlaceholder:"請輸入新名稱",renameNameRequired:"請輸入新名稱",renameSuccess:"重新命名成功",moveTitle:"移動檔案",movePlaceholder:"請輸入目標父目錄ID（留空表示根目錄）",moveSuccess:"移動成功",uploadSuccess:"上傳成功",downloadStarted:"下載已開始",newFolderTitle:"新增資料夾",confirm:"確定",cancel:"取消",
    versionRemark:"版本備註",versionRemarkPlaceholder:"請輸入版本備註（選填）",versionRemarkMax:"版本備註不超過200字元",selectFileLabel:"選擇檔案",selectFilePrompt:"請選擇要上傳的檔案",fileInfo:"檔案資訊",fileInfoName:"名稱：",fileInfoSize:"大小：",fileInfoType:"類型：",fileInfoChunked:"將使用分段上傳",uploadProgress:"上傳進度",uploadFileTitle:"上傳檔案",dragUploadHint:"點擊或拖曳檔案到此處上傳",chunkUploadHint:"檔案大小 ≥ 100MB 時自動使用分段上傳（支援中斷續傳）",singleFileLimit:"一次只能上傳一個檔案",
    filePreviewTitle:"檔案預覽",selectFilePreview:"請選擇要預覽的檔案",formatLabel:"格式",previewSupported:"支援預覽",previewUnsupported:"不支援預覽",generatePreview:"產生預覽",previewGenerated:"預覽已產生，請重新整理檢視",close:"關閉",unsupportedFormat:"該檔案格式暫不支援線上預覽",downloadPrompt:"請下載後使用本機應用程式開啟",downloadNow:"立即下載",textLoadFailed:"載入文字內容失敗",
    spaceManagement:"空間管理",spaceName:"空間名稱",spaceNamePlaceholder:"請輸入空間名稱",spaceDescription:"空間描述",spaceDescriptionPlaceholder:"請輸入空間描述（選填）",visibilityLabel:"可見性",visibilityPlaceholder:"請選擇可見性",visibilityPrivate:"私人",visibilityPublic:"公開",memberCount:"成員數",nodeCount:"檔案數",usedStorage:"已用儲存空間",editSpace:"編輯空間",newSpace:"新增空間",members:"成員",archive:"歸檔",memberHeader:"空間成員",userId:"使用者ID",userIdPlaceholder:"請輸入使用者ID",role:"角色",rolePlaceholder:"角色",addMember:"新增",addMemberSuccess:"新增成員成功",userIdRequired:"請輸入使用者ID",removeMember:"移除",removeMemberConfirm:"確定移除該成員嗎？",removeSuccess:"移除成功",noMembers:"無成員",memberJoinTime:"加入時間",archiveConfirm:"確定歸檔空間「{name}」嗎？歸檔後空間將變為唯讀。",archiveConf:"歸檔確認",archiveSuccess:"歸檔成功",deleteSpaceConfirm:"確定刪除空間「{name}」嗎？刪除後不可恢復。",deleteConf:"刪除確認",updateSuccess:"更新成功",confirmToggleVisibility:"可見性：",
    commentManagement:"檔案評論",commentId:"評論ID",fileNodeId:"檔案節點ID",resolved:"已解決",unresolved:"未解決",commenter:"評論人",resolveAction:"解決",resolvedSuccess:"已標記為解決",commentDeleteConf:"確定刪除該評論嗎？",queryComments:"查詢評論",newComment:"新增評論",fileNodeIdInputPlaceholder:"請輸入檔案節點ID",fileNodeIdRequired:"請先輸入檔案節點ID",commentFormTitle:"新增評論",fileNodeIdLabel:"檔案節點ID",commentContentLabel:"評論內容",commentContentPlaceholder:"請輸入評論內容",mentionUsers:"提及使用者",mentionPlaceholder:"輸入關鍵字搜尋使用者，選中即為 @提及（可為空）",
    quotaManagement:"儲存配額",scopeType:"儲存範圍類型",scopeTypePlaceholder:"儲存範圍類型（如 USER / SPACE，可選）",scopeId:"儲存範圍ID",scopeIdPlaceholder:"儲存範圍ID（可選）",queryQuota:"查詢配額",adjustQuota:"調整配額",querySuccess:"查詢成功",capacityUsage:"容量使用",fileCountUsage:"檔案數使用",byteUnit:"位元組",quotaLimit:"配額上限（位元組）",usedCapacity:"已用容量（位元組）",fileCountLimit:"檔案數上限",usedFileCount:"已用檔案數",updatedAt:"更新時間",updatedBy:"更新人",
    shareManagement:"我的分享",shareId:"分享ID",title:"標題",fileNameShare:"檔案名稱",accessCount:"存取次數",accessLog:"存取紀錄",recipients:"接收人",revoke:"撤銷",receivedShares:"收到的分享",receiveRecordId:"接收紀錄ID",sharer:"分享人",viewTime:"查看時間",receiveTime:"接收時間",newShare:"新增分享",revokeConfirm:"確定撤銷分享「{name}」嗎？",revokeConf:"撤銷確認",revokeSuccess:"撤銷成功",refresh:"重新整理",visitor:"訪客",accessType:"存取類型",accessStatus:"狀態",accessTime:"存取時間",failReason:"失敗原因",recipientName:"接收人",recipientType:"接收類型",viewedAt:"查看時間",shareCreatedAt:"建立時間",
    tagManagement:"標籤管理",tagId:"標籤ID",usageCount:"使用次數",bind:"綁定",fileTags:"檔案標籤",bindToFile:"綁定標籤到檔案",bindPlaceholder:"請輸入檔案節點ID",tagIdPlaceholder:"請輸入標籤ID",bindRequired:"請填寫檔案節點ID與標籤ID",bindSuccess:"綁定成功",fileTagsQuery:"檔案標籤查詢 / 推薦",query:"查詢",recommendTags:"推薦標籤",tagIdRequired:"請先輸入檔案節點ID",noFileTags:"該檔案沒有標籤",newTag:"新增標籤",tagNameLabel:"標籤名稱",tagColorLabel:"標籤顏色",tagColorPlaceholder:"如 #409eff（可選）",tagNameRequired:"請輸入標籤名稱",createSuccess:"建立成功",
    searchTitle:"全文搜尋",searchInputPlaceholder:"搜尋檔案...",searchButton:"搜尋",searchType:"類型",advancedSearch:"進階搜尋",searchAll:"全部",searchDocument:"文件",searchImage:"圖片",searchVideo:"影片",searchAudio:"音訊",searchOther:"其他",didYouMean:"您是不是要搜：",searchResultCount:"找到 {total} 個結果（用時 {ms}ms）",noResults:"未找到匹配的結果",searchHistory:"搜尋歷史記錄",hotSearches:"熱門搜尋",clearHistory:"清空",searchClearHistoryConfirm:"確定清空全部搜尋歷史嗎？此操作不可恢復。",searchRebuildIndices:"重建索引",searchRebuildIndicesConfirm:"重建搜尋索引將觸發背景全量重新建構，可能耗時較長。確定繼續嗎？",searchAdvancedTitle:"進階搜尋",searchAdvancedKeyword:"搜尋關鍵字",searchAdvancedKeywordPlaceholder:"請輸入搜尋關鍵字",searchAdvancedKeywordRequired:"請輸入搜尋關鍵字",searchAdvancedType:"檔案類型",searchAdvancedTypePlaceholder:"請選擇檔案類型",searchAdvancedTimeRange:"開始時間",searchAdvancedStartDatePlaceholder:"請選擇開始時間",searchAdvancedEndDate:"結束時間",searchAdvancedEndDatePlaceholder:"請選擇結束時間",searchAdvancedTags:"標籤",searchAdvancedTagsPlaceholder:"請選擇標籤（可多選）",searchAdvancedSuccess:"進階搜尋完成",
    trashAutoPurgeHint:"提示：回收桶中的檔案在清除到期後將自動永久刪除，請及時還原重要資料。",trashOriginalName:"原始名稱",trashOriginalPath:"原始路徑",trashNodeType:"節點類型",trashSize:"檔案大小",trashDeletedTime:"刪除時間",trashPurgeTime:"清除時間",trashStatusPending:"待清除",trashStatusPurged:"已清除",trashStatusRestored:"已還原",trashRestore:"還原",trashPurge:"永久刪除",trashRestoreConfirm:"確定還原該檔案嗎？",trashRestoreSuccess:"還原成功",trashPurgeConfirm:"永久刪除後將無法恢復，確定繼續嗎？",trashPurgeSuccess:"永久刪除成功",trashBatchSelectTip:"請先選擇要還原的檔案",trashBatchNoValid:"已選的檔案中沒有可還原的項目",trashBatchRestore:"批次還原",trashBatchRestoreConfirm:"確定還原選中的檔案嗎？",trashBatchRestoreSuccess:"批次還原成功",trashEmpty:"清空回收桶",trashEmptyConfirm:"清空回收桶將永久刪除所有已清除的檔案，此操作不可恢復，確定繼續嗎？",trashEmptySuccess:"清空回收桶成功",
    favoritesSuffix:"副檔名",favoritesFavoritedAt:"收藏時間",favoritesSortOrder:"排序權重",favoritesTotalLabel:"收藏",favoritesRemove:"移除收藏",favoritesRemoveConfirm:"確定從收藏中移除「{name}」嗎？",favoritesRemoveSuccess:"移除成功",favoritesSortSuccess:"排序更新成功",
    recentSuffix:"副檔名",recentAccessedAt:"訪問時間",recentTotalLabel:"最近存取",recentRemove:"移除紀錄",recentRemoveConfirm:"確定從最近存取中移除該紀錄嗎？",recentRemoveSuccess:"移除成功",recentClearAll:"清空全部",recentClearAllConfirm:"確定清空全部最近存取紀錄嗎？",recentClearAllSuccess:"清空成功",
    accessCount:"",accessLog:"",accessStatus:"",accessTime:"",accessType:"",action:"",addMember:"",addMemberSuccess:"",adjustQuota:"",advancedSearch:"",archive:"",archiveConf:"",archiveConfirm:"",archiveSuccess:"",bind:"",bindPlaceholder:"",bindRequired:"",bindSuccess:"",bindToFile:"",byteUnit:"",capacityUsage:"",clearHistory:"",close:"",commentContent:"",commentContentLabel:"",commentContentPlaceholder:"",commentDeleteConf:"",commentFormTitle:"",commentId:"",commentManagement:"",commentTime:"",commenter:"",confirmCopy:"",confirmDelete:"",confirmDeleteFile:"",confirmToggleVisibility:"",copy:"",copySuccess:"",createSuccess:"",createdAt:"",createdAtColumn:"",createdBy:"",createdByColumn:"",deleteConf:"",deleteSpaceConfirm:"",deleteSuccess:"",didYouMean:"",download:"",downloadNow:"",downloadPrompt:"",downloadStarted:"",dragUploadHint:"",editSpace:"",expireTime:"",failReason:"",
    chunkUploadHint:"",seq:"#"
  },
  page: {file:"檔案管理",fileList:"檔案列表",fileComment:"檔案評論",share:"分享管理",shareList:"分享列表",tag:"標籤管理",tagList:"標籤列表",storage:"儲存管理",quota:"儲存配額",analysis:"儲存分析",aiAssist:"AI 助手",search:"全文搜尋"}
}
};