/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * DebugController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code DebugController}，共 3 个端点。
 * <p>路径规范: /api/v1/agent/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py agent} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { AgentTraceDetailDTO, AgentTraceListDTO } from './models';

/**
 * listTraces: GET /api/v1/agent/debug/traces
 */
export function listTraces(params: {
    limit?: number;
  }): Promise<AgentTraceListDTO[]> {
  return requestClient.get<AgentTraceListDTO[]>(`/api/v1/agent/debug/traces`, { params });
}

/**
 * getTrace: GET /api/v1/agent/debug/trace/{traceId}
 */
export function getTrace(path: {
    traceId: string;
  }): Promise<AgentTraceDetailDTO> {
  return requestClient.get<AgentTraceDetailDTO>(`/api/v1/agent/debug/trace/${traceId}`);
}

/**
 * replayTrace: POST /api/v1/agent/debug/trace/{traceId}/replay
 */
export function replayTrace(path: {
    traceId: string;
  }): Promise<string> {
  return requestClient.post<string>(`/api/v1/agent/debug/trace/${traceId}/replay`);
}
