/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * PromptController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code PromptController}，共 2 个端点。
 * <p>路径规范: /api/v1/agent/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py agent} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { Record<string, never> } from './models';

/**
 * evaluate: POST /api/v1/agent/prompt/evaluate
 */
export function evaluate(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/agent/prompt/evaluate`, data);
}

/**
 * compare: POST /api/v1/agent/prompt/compare
 */
export function compare(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/agent/prompt/compare`, data);
}
