const fs=require('fs'),path=require('path');
const TD=__dirname+'/_translations';
fs.mkdirSync(TD,{recursive:true});
const LOC=__dirname+'/langs';
const EN=JSON.parse(fs.readFileSync(path.join(LOC,'en-US','business.json'),'utf8'));
const ENP=JSON.parse(fs.readFileSync(path.join(LOC,'en-US','page.json'),'utf8'));

// Helper: build business.json content by starting from EN values, applying overrides
function makeBiz(overrides){
  const out={...EN};
  for(const k in overrides){out[k]=overrides[k];}
  return out;
}
function makePage(overrides){
  const out={...ENP};
  for(const k in overrides){out[k]=overrides[k];}
  return out;
}
// Write JSON translation data file for a locale
function write(loc,bizOverrides,pageOverrides){
  const data={business:makeBiz(bizOverrides),page:makePage(pageOverrides||{})};
  fs.writeFileSync(path.join(TD,loc+'.json'),JSON.stringify(data),null,2);
  process.stdout.write('.');
}

// ============ BATCH 1: Major Latin-script European & others ============
write('bg-BG',{rule:'Правила',ruleName:'Име на правило',ruleCode:'Код на правило',variable:'Променлива на правило',decisionTable:'Таблица за решения',hitPolicy:'Политика за съвпадение',cepPattern:'CEP модел',dslContent:'DSL съдържание',dslVersion:'DSL версия',cepName:'CEP име',cepWindow:'CEP прозорец',breakpointName:'Име на преквател',breakpointCondition:'Условие на преквател',auditTime:'Време',auditUser:'Потребител',auditAction:'Действие',auditResult:'Резултат',category:'Категория',description:'Описание',createdAt:'Създадено',sampleValue:'Примерна стойност',totalRules:'Общо правила'},{});

write('bn-BD',{rule:'নিয়ম',ruleName:'নিয়মের নাম',ruleCode:'নিয়ম কোড',variable:'নিয়ম ভেরিয়েবল',decisionTable:'সিদ্ধান্ত টেবিল',hitPolicy:'হিট নীতি',cepPattern:'CEP প্যাটার্ন',dslContent:'DSL কন্টেন্ট',dslVersion:'DSL সংস্করণ',cepName:'CEP নাম',cepWindow:'CEP উইন্ডো',breakpointName:'ব্রেকপয়েন্ট নাম',breakpointCondition:'ব্রেকপয়েন্ট শর্ত',auditTime:'সময়',auditUser:'ব্যবহারকারী',auditAction:'অ্যাকশন',auditResult:'ফলাফল',category:'বিভাগ',description:'বিবরণ',createdAt:'তৈরি',sampleValue:'নমুনা মান',totalRules:'মোট নিয়ম'},{});

write('nb-NO',{rule:'Regler',ruleName:'Regelnavn',ruleCode:'Regelkode',variable:'Regelvariabel',decisionTable:'Beslutningstabell',hitPolicy:'Treffpolitikk',cepPattern:'CEP-mønster',dslContent:'DSL-innhold',dslVersion:'DSL-versjon',cepName:'CEP-navn',cepWindow:'CEP-vindu',breakpointName:'Brytpunktnavn',breakpointCondition:'Brytpunktbetning',auditTime:'Tid',auditUser:'Bruker',auditAction:'Handling',auditResult:'Resultat',category:'Kategori',description:'Beskrivelse',createdAt:'Opprettet',sampleValue:'Eksempelverdi',totalRules:'Totalt regler'},{});

write('nl-BE',{rule:'Regels',ruleName:'Regelnaam',ruleCode:'Regelcode',variable:'Regelvariabele',decisionTable:'Beslissingstabel',hitPolicy:'Hitbeleid',cepPattern:'CEP-patroon',dslContent:'DSL-inhoud',dslVersion:'DSL-versie',cepName:'CEP-naam',cepWindow:'CEP-venster',breakpointName:'Breekpuntnaam',breakpointCondition:'Breekpuntvoorwaarde',auditTime:'Tijd',auditUser:'Gebruiker',auditAction:'Actie',auditResult:'Resultaat',category:'Categorie',description:'Beschrijving',createdAt:'Aangemaakt',sampleValue:'Voorbeeldwaarde',totalRules:'Totaal regels'},{});

write('nl-NL',{rule:'Regels',ruleName:'Regelnaam',ruleCode:'Regelcode',variable:'Regelvariabele',decisionTable:'Beslissingstabel',hitPolicy:'Hitbeleid',cepPattern:'CEP-patroon',dslContent:'DSL-inhoud',dslVersion:'DSL-versie',cepName:'CEP-naam',cepWindow:'CEP-venster',breakpointName:'Breekpuntnaam',breakpointCondition:'Breekpuntvoorwaarde',auditTime:'Tijd',auditUser:'Gebruiker',auditAction:'Actie',auditResult:'Resultaat',category:'Categorie',description:'Beschrijving',createdAt:'Aangemaakt',sampleValue:'Voorbeeldwaarde',totalRules:'Totaal regels'},{});

write('pt-PT',{rule:'Regras',ruleName:'Nome da regra',ruleCode:'Código da regra',variable:'Variável de regra',decisionTable:'Tabela de decisão',hitPolicy:'Política de acerto',cepPattern:'Padrão CEP',dslContent:'Conteúdo DSL',dslVersion:'Versão DSL',cepName:'Nome CEP',cepWindow:'Janela CEP',breakpointName:'Nome do ponto de interrupção',breakpointCondition:'Condição do ponto de interrupção',auditTime:'Tempo',auditUser:'Utilizador',auditAction:'Ação',auditResult:'Resultado',category:'Categoria',description:'Descrição',createdAt:'Criado',sampleValue:'Valor de amostra',totalRules:'Total regras'});

write('ro-RO',{rule:'Reguli',ruleName:'Nume regulă',ruleCode:'Cod regulă',variable:'Variabilă regulă',decisionTable:'Tabel decizii',hitPolicy:'Politica de lovire',cepPattern:'Model CEP',dslContent:'Conținut DSL',dslVersion:'Versiune DSL',cepName:'Nume CEP',cepWindow:'Fereastră CEP',breakpointName:'Nume punct de întrerupere',breakpointCondition:'Condiție punct de întrerupere',auditTime:'Timp',auditUser:'Utilizator',auditAction:'Acțiune',auditResult:'Rezultat',category:'Categorie',description:'Descriere',createdAt:'Creat',sampleVal:'Valoare eșantion',totalRules:'Total reguli'},{});

write('sk-SK',{rule:'Pravidlá',ruleName:'Názov pravidla',ruleCode:'Kód pravidla',variable:'Premenná pravidla',decisionTable:'Rozhodovacia tabuľka',hitPolicy:'Politika zásahu',cepPattern:'CEP vzor',dslContent:'DSL obsah',dslVersion:'DSL verzia',cepName:'CEP názov',cepWindow:'CEP okno',breakpointName:'Názov zarážky',breakpointCondition:'Podmienka zarážky',auditTime:'Čas',auditUser:'Používateľ',auditAction:'Akcia',auditResult:'Výsledok',category:'Kategória',description:'Popis',createdAt:'Vytvorené',sampleValue:'Vzorková hodnota',totalRules:'Celkom pravidiel'},{});

write('sl-SI',{rule:'Pravila',ruleName:'Ime pravila',ruleCode:'Koda pravila',variable:'Spremenljivka pravila',decisionTable:'Tablica odločitev',hitPolicy:'Politika zadetkov',cepPattern:'CEP vzorec',dslContent:'DSL vsebina',dslVersion:'DSL različica',cepName:'CEP ime',cepWindow:'CEP okno',breakpointName:'Ime prekinitvene točke',breakpointCondition:'Pogoj prekinitvene točke',auditTime:'Čas',auditUser:'Uporabnik',auditAction:'Dejanje',auditResult:'Rezultat',category:'Kategorija',description:'Opis',createdAt:'Ustvarjeno',sampleValue:'Vrednost vzorca',totalRules:'Skupaj pravil'},{});

write('sq-AL',{rule:'Rregullat',ruleName:'Emri i rregullit',ruleCode:'Kodi i rregullit',variable:'Ndryshorja e rregullit',decisionTable:'Tabela e vendimeve',hitPolicy:'Politika e goditjes',cepPattern:'Model CEP',dslContent:'Përmbajtja DSL',dslVersion:'Versioni DSL',cepName:'Emri CEP',cepWindow:'Dritarja CEP',breakpointName:'Emri i pikës ndërprerëse',breakpointCondition:'Kushti i pikës ndërprerëse',auditTime:'Koha',auditUser:'Përdoruesi',auditAction:'Veprimi',auditRezultati:'Rezultati',category:'Kategoria',description:'Përshkrimi',createdAt:'Krijuar',sampleValue:'Vlera e mostrës',totalRules:'Total rregullat'},{});

write('sr-RS',{rule:'Правила',ruleName:'Назив правила',ruleCode:'Код правила',variable:'Променљива правила',decisionTable:'Таблица одлука',hitPolicy:'Правила поготка',cepPattern:'CEP образац',dslContent:'DSL садржај',dslVersion:'DSL верзија',cepName:'CEP назив',cepWindow:'CEP прозор',breakpointName:'Назив прекида',breakpointCondition:'Услов прекида',auditTime:'Време',auditUser:'Корисник',auditAction:'Акција',auditResult:'Резултат',category:'Категорија',description:'Опис',createdAt:'Креирано',sampleValue:'Узорак вредности',totalRules:'Укупно правила'},{});

write('sv-SE',{rule:'Regler',ruleName:'Regelnamn',ruleCode:'Regelkod',variable:'Regelvariabel',decisionTable:'Beslutstabell',hitPolicy:'Träffpolicy',cepPattern:'CEP-mönster',dslContent:'DSL-innehåll',dslVersion:'DSL-version',cepName:'CEP-namn',cepWindow:'CEP-fönster',breakpointName:'Brytpunktsnamn',breakpointCondition:'Brytpunktsvillkor',auditTime:'Tid',auditUser:'Användare',auditAction:'Åtgärd',auditResult:'Resultat',category:'Kategori',description:'Beskrivning',createdAt:'Skapad',sampleValue:'Provvärde',totalRules:'Totalt regler'},{});

write('uk-UA',{rule:'Правила',ruleName:'Назва правила',ruleCode:'Код правила',variable:'Змінна правила',decisionTable:'Таблиця рішень',hitPolicy:'Політика збігів',cepPattern:'CEP шаблон',dslContent:'Вміст DSL',dslVersion:'Версія DSL',cepName:'Назва CEP',cepWindow:'Вікно CEP',breakpointName:'Назва точки розриву',breakpointCondition:'Умова точки розриву',auditTime:'Час',auditUser:'Користувач',auditAction:'Дія',auditResult:'Результат',category:'Категорія',description:'Опис',createdAt:'Створено',sampleValue:'Вибіркове значення',totalRules:'Усього правил'},{});

write('vi-VN',{rule:'Quản lý quy tắc',ruleName:'Tên quy tắc',ruleCode:'Mã quy tắc',variable:'Biến số',decisionTable:'Bảng quyết định',hitPolicy:'Chính sách trúng',cepPattern:'Mẫu CEP',dslContent:'Nội dung DSL',dslVersion:'Phiên bản DSL',cepName:'Tên CEP',cepWindow:'Cửa sổ CEP',breakpointName:'Tên điểm ngắt',breakpointCondition:'Điều kiện điểm ngắt',auditTime:'Thời gian',auditUser:'Người dùng',auditAction:'Hành động',auditResult:'Kết quả',category:'Danh mục',description:'Mô tả',createdAt:'Được tạo',sampleValue:'Giá trị mẫu',totalRules:'Tổng quy tắc'});

write('az-AZ',{rule:'Qaydalar',ruleName:'Qayda adı',ruleCode:'Qayda kodu',variable:'Qayda dəyişəni',decisionTable:'Qərar cədvəli',hitPolicy:'Zərbə siyasəti',cepPattern:'CEP nümunəsi',dslContent:'DSL məzmunu',dslVersion:'DSL versiyası',cepName:'CEP adı',cepWindow:'CEP pəncərəsi',breakpointName:'Kəsilma nöqtəsi adı',breakpointCondition:'Kəsilma nöqtəsi şərti',auditTime:'Vaxt',auditUser:'İstifadəçi',auditAction:'Fəaliyyət',auditResult:'Nəticə',category:'Kateqoriya',description:'Təsvir',createdAt:'Yaradılıb',sampleValue:'Nümunə dəyəri',totalRules:'Ümumi qaydalar'},{});

write('ka-GE',{rule:'წესები',ruleName:'წესის სახელი',ruleCode:'წესის კოდი',variable:'წესის ცვლადი',decisionTable:'გადაწყვეტითა მაგიდა',hitPolicy:'მოხვედრა პოლიტიკა',cepPattern:'CEP ნიმუში',dslContent:'DSL შინაარსი',dslVersion:'DSL ვერსია',cepName:'CEP სახელი',cepWindow:'CEP ფანჯარა',breakpointName:'წყვეტის წერტილის სახელი',breakpointCondition:'წყვეტის წერტილის პირობა',auditTime:'დრო',auditUser:'მომხმარებელი',auditAction:'მოქმედება',auditResult:'შედეგი',category:'კატეგორია',description:'აღწერა',createdAt:'შექმნილი',sampleValue:'ნიმუში მნიშვნელობა',totalRules:'სულ წესები'},{});

write('kk-KZ',{rule:'Ережелер',ruleName:'Ереже атауы',ruleCode:'Ереже коды',variable:'Ереже айнымалысы',decisionTable:'Шешім кестесі',hitPolicy:'Соғыс саясаты',cepPattern:'CEP үлгісі',dslContent:'DSL мазмұны',dslVersion:'DSL нұсқасы',cepName:'CEP атауы',cepWindow:'CEP терезесі',breakpointName:'Үзіліс нүктесінің атауы',breakpointCondition:'Үзіліс нүктесінің шарты',auditTime:'Уақыт',auditUser:'Пайдаланушы',auditAction:'Әрекет',auditResult:'Нәтиже',category:'Санат',description:'Сипаттама',createdAt:'Құрылды',sampleValue:'Үлгі мәні',totalRules:'Барлығы режелер'},{});

write('mn-MN',{rule:'Дүрмүүд',ruleName:'Дүрмийн нэр',ruleCode:'Дүрмийн код',variable:'Дүрмийн хувьсагч',decisionTable:'Шийдвэрлэх хүснэгт',hitPolicy:'Ойролцооны бодлого',cepPattern:'CEP загвар',dslContent:'DSL агуулга',dslVersion:'DSL хувилбар',cepName:'CEP нэр',cepWindow:'CEP цонх',breakpointName:'Таслах цэгийн нэр',breakpointCondition:'Таслах цэгийн нөхцөл',auditTime:'Цаг',auditUser:'Хэрэглэгч',auditAction:'Үйлдэл',auditResult:'Үр дүн',category:'Ангилал',description:'Тайлбар',createdAt:'Үүсгэсэн',sampleValue:'Жишээ утга',totalRules:'Нийт дүрмүүд'},{});

write('uz-UZ',{rule:'Qoidalar',ruleName:'Qoida nomi',ruleCode:'Qoida kodi',variable:'Qoida o\'zgaruvchisi',decisionTable:'Qararlar jadvali',hitPolicy:'Urish siyosati',cepPattern:'CEP namunasi',dslContent:'DSL mazmuni',dslVersion:'DSP versiyasi',cepName:'CEP nomi',cepWindow:'CEP oynasi',breakpointName:'To\'xtash nuqtasi nomi',breakpointCondition:'To\'xtash nuqtasi sharti',auditTime:'Vaqt',auditUser:'Foydalanuvchi',auditAction:'Harakat',auditResult:'Natija',category:'Turkum',description:'Tavsif',createdAt:'Yaratilgan',sampleValue:'Namuna qiymati',totalRules:'Jami qoidalar'},{});

write('ar-EG',{rule:'إدارة القواعد',ruleName:'اسم القاعدة',ruleCode:'رمز القاعدة',variable:'متغير القاعدة',decisionTable:'جدول القرار',hitPolicy:'سياسة الإصابة',cepPattern:'نمط CEP',dslContent:'محتوى DSL',dslVersion:'إصدار DSL',cepName:'اسم CEP',cepWindow:'نافذة CEP',breakpointName:'اسم نقطة التوقف',breakpointCondition:'شرط نقطة التوقف',auditTime:'الوقت',auditUser:'المستخدم',auditAction:'الإجراء',auditResult:'النتيجة',category:'الفئة',description:'الوصف',createdAt:'تم الإنشاء',sampleValue:'قيمة العينة',totalRules:'إجمالي القواعد'},{});

write('ar-SA',{rule:'إدارة القواعد',ruleName:'اسم القاعدة',ruleCode:'رمز القاعدة',variable:'متغير القاعدة',decisionTable:'جدول القرار',hitPolicy:'سياسة الإصابة',cepPattern:'نمط CEP',dslContent:'محتوى DSL',dslVersion:'إصدار DSL',cepName:'اسم CEP',cepWindow:'نافذة CEP',breakpointName:'اسم نقطة التوقف',breakpointCondition:'شرط نقطة التوقف',auditTime:'الوقت',auditUser:'المستخدم',auditAction:'الإجراء',auditResult:'النتيجة',category:'الفئة',description:'الوصف',createdAt:'تم الإنشاء',sampleValue:'قيمة العينة',totalRules:'إجمالي القواعد'},{});

write('fa-IR',{rule:'مدیریت قوانین',ruleName:'نام قانون',ruleCode:'کد قانون',variable:'متغیر قانون',decisionTable:'جدول تصمیم',hitPolicy:'سیاست ضربه',cepPattern:'الگوی CEP',dslContent:'محتوای DSL',dslVersion:'نسخه DSL',cepName:'نام CEP',cepWindow:'پنجره CEP',breakpointName:'نام نقطه شکست',breakpointCondition:'شرط نقطه شکست',auditTime:'زمان',auditUser:'کاربر',auditAction:'اقدام',auditResult:'نتیجه',category:'دسته',description:'توضیحات',createdAt:'ایجاد شده',sampleValue:'مقدار نمونه',totalRules:'مجموع قوانین'},{});

write('ur-PK',{rule:'قواعد کا انتظام',ruleName:'قاعدے کا نام',ruleCode:'قاعدے کا کوڈ',variable:'قاعدے کا متغیر',decisionTable:'فیصلے کی جدول',hitPolicy:'ہٹ پالیسی',cepPattern:'CEP پیٹرن',dslContent:'DSL مواد',dslVersion:'DSL ورژن',cepName:'CEP نام',cepWindow:'CEP ونڈو',breakpointName:'بریک پوائنٹ کا نام',breakpointCondition:'بریک پوائنٹ کی شرط',auditTime:'وقت',auditUser:'صارف',auditAction:'ایکشن',auditResult:'نتیجہ',category:'زمرہ',description:'تفصیل',createdAt:'بنایا گیا',sampleValue:'نمونہ قدر',totalRules:'کل قواعد'},{});

write('tr-TR',{rule:'Kural Yönetimi',ruleName:'Kural Adı',ruleCode:'Kural Kodu',variable:'Kural Değişkeni',decisionTable:'Karar Tablosu',hitPolicy:'İsabet Politikası',cepPattern:'CEP Kalıbı',dslContent:'DSL İçeriği',dslVersion:'DSL Sürümü',cepName:'CEP Adı',cepWindow:'CEP Penceresi',breakpointName:'Kesme Noktası Adı',breakpointCondition:'Kesme Noktası Koşulu',auditTime:'Zaman',auditUser:'Kullanıcı',auditAction:'Aksiyon',auditResult:'Sonuç',category:'Kategori',description:'Açıklama',createdAt:'Oluşturuldu',sampleValue:'Örnek Değer',totalRules:'Toplam Kural'},{});

write('pl-PL',{rule:'Zarządzanie regułami',ruleName:'Nazwa reguły',ruleCode:'Kod reguły',variable:'Zmienna reguły',decisionTable:'Tabela decyzyjna',hitPolicy:'Polityka trafień',cepPattern:'Wzorzec CEP',dslContent:'Treść DSL',dslVersion:'Wersja DSL',cepName:'Nazwa CEP',cepWindow:'Okno CEP',breakpointName:'Nazwa punktu przerwania',breakpointCondition:'Warunek punktu przerwania',auditTime:'Czas',auditUser:'Użytkownik',auditAction:'Akcja',auditResult:'Wynik',category:'Kategoria',description:'Opis',createdAt:'Utworzono',sampleValue:'Wartość próbki',totalRules:'Wszystkie reguły'},{});

write('pt-BR',{rule:'Gestão de regras',ruleName:'Nome da regra',ruleCode:'Código da regra',variable:'Variável de regra',decisionTable:'Tabela de decisão',hitPolicy:'Política de acerto',cepPattern:'Padrão CEP',dslContent:'Conteúdo DSL',dslVersion:'Versão DSL',cepName:'Nome CEP',cepWindow:'Janela CEP',breakpointName:'Nome do ponto de interrupção',breakpointCondition:'Condição do ponto de interrupção',auditTime:'Tempo',auditUser:'Usuário',auditAction:'Ação',auditResult:'Resultado',category:'Categoria',description:'Descrição',createdAt:'Criado',sampleValue:'Valor de amostra',totalRules:'Total de regras'},{});

write('ru-RU',{rule:'Управление правилами',ruleName:'Имя правила',ruleCode:'Код правила',variable:'Переменная правила',decisionTable:'Таблица решений',hitPolicy:'Политика совпадения',cepPattern:'Шаблон CEP',dslContent:'Содержимое DSL',dslVersion:'Версия DSL',cepName:'Имя CEP',cepWindow:'Окно CEP',breakpointName:'Имя точки останова',breakpointCondition:'Условие точки останова',auditTime:'Время',auditUser:'Пользователь',auditAction:'Действие',auditResult:'Результат',category:'Категория',description:'Описание',createdAt:'Создано',sampleValue:'Значение образца',totalRules:'Всего правил'},{});

write('th-TH',{rule:'กฎ',ruleName:'ชื่อกฎ',ruleCode:'รหัสกฎ',variable:'ตัวแปร',decisionTable:'ตารางตัดสินใจ',hitPolicy:'นโยบายฮิต',cepPattern:'รูปแบบ CEP',dslContent:'เนื้อหา DSL',dslVersion:'เวอร์ชัน DSL',cepName:'ชื่อ CEP',cepWindow:'หน้าต่าง CEP',breakpointName:'ชื่อจุดหยุด',breakpointCondition:'เงื่อนไขจุดหยุด',auditTime:'เวลา',auditUser:'ผู้ใช้',auditAction:'การดำเนินการ',auditResult:'ผลลัพธ์',category:'หมวดหมู่',description:'คำอธิบาย',createdAt:'สร้างเมื่อ',sampleValue:'ค่าตัวอย่าง',totalRules:'กฎทั้งหมด'},{});

write('gu-IN',{rule:'નિયમો',ruleName:'નિયમ નામ',ruleCode:'નિયમ કોડ',variable:'નિયમ ચલ',decisionTable:'નિર્ણય કોષ્ટક',hitPolicy:'હિટ નીતિ',cepPattern:'CEP પેટર્ન',dslContent:'DSL સામગ્રી',dslVersion:'DSL વર્ઝન',cepName:'CEP નામ',cepWindow:'CEP વિન્ડો',breakpointName:'બ્રેકપોઇન્ટ નામ',breakpointCondition:'બ્રેકપોઇન્ટ શરત',auditTime:'સમય',auditUser:'વપરાશકર્તા',auditAction:'ક્રિયા',auditResult:'પરિણામ',category:'વર્ગ',description:'વર્ણન',createdAt:'બનાવ્યું',sampleValue:'નમૂનો મૂલ્ય',totalRules:'કુલ નિયમો'},{});

write('kn-IN',{rule:'ನಿಯಮಗಳು',ruleName:'ನಿಯಮದ ಹೆಸರು',ruleCode:'ನಿಯಮದ ಕೋಡ್',variable:'ನಿಯಮದ ವೇರಿಯಬಲ್',decisionTable:'ನಿರ್ಣಯ ಕೋಷ್ಟಕ',hitPolicy:'ಹಿಟ್ ನೀತಿ',cepPattern:'CEP ಪ್ಯಾಟರ್ನ್',dslContent:'DSL ವಿಷಯ',dslVersion:'DSL ಆವೃತ್ತಿ',cepName:'CEP ಹೆಸರು',cepWindow:'CEP ವಿಂಡೋ',breakpointName:'ಬ್ರೇಕ್ಪಾಯಿಂಟ್ ಹೆಸರು',breakpointCondition:'ಬ್ರೇಕ್ಪಾಯಿಂಟ್ ಷರತ್ತು',auditTime:'ಸಮಯ',auditUser:'ಬಳಕೆದಾರ',auditAction:'ಕ್ರಿಯೆ',auditResult:'ಫಲಿತಾಂಶ',category:'ವರ್ಗ',description:'ವಿವರಣೆ',createdAt:'ರಚಿಸಲಾಗಿದೆ',sampleValue:'ಮಾದರಿ ಮೌಲ್ಯ',totalRules:'ಒಟ್ಟು ನಿಯಮಗಳು'},{});

write('ml-IN',{rule:'ഭരണങ്ങൾ',ruleName:'നിയമത്തിന്റെ പേര്',ruleCode:'നിയമകോഡ്',variable:'നിയമ ചരം',decisionTable:'തീരുമാന പട്ടിക',hitPolicy:'ഹിറ്റ് നയം',cepPattern:'CEP പാറ്റേൺ',dslContent:'DSL ഉള്ളടക്കം',dslVersion:'DSL പതിപ്പ്',cepName:'CEP പേര്',cepWindow:'CEP ജാലകം',breakpointName:'ബ്രേക്പോയിന്റ് പേര്',breakpointCondition:'ബ്രേക്പോയിന്റ് വ്യവസ്ഥ',auditTime:'സമയം',auditUser:'ഉപയോക്താവ്',auditAction:'പ്രവർത്തനം',auditResult:'ഫലം',category:'വിഭാഗം',description:'വിവരണം',createdAt:'സൃഷ്ടിച്ചു',sampleValue:'സാമ്പിൾ മൂല്യം',totalRules:'ആകെ നിയമങ്ങൾ'},{});

write('mr-IN',{rule:'नियम',ruleName:'नियमाचे नाव',ruleCode:'नियम कोड',variable:'नियम व्हेरिएबल',decisionTable:'णय सारणी',hitPolicy:'हिट धोरण',cepPattern:'CEP पॅटर्न',dslContent:'DSL मजकूर',dslVersion:'DSL आवृत्ती',cepName:'CEP नाव',cepWindow:'CEP पटल',breakpointName:'ब्रेकपॉइंट नाव',breakpointCondition:'ब्रेकपॉइंट अट',auditTime:'वेळ',auditUser:'वापरकर्ता',auditAction:'कृती',auditResult:'परिणाम',category:'श्रेणी',description:'वर्णन',createdAt:'तयार केले',sampleValue:'नमुना मूल्य',totalRules:'एकूण नियम'},{});

write('ta-IN',{rule:'விதிகள்',ruleName:'விதி பெயர்',ruleCode:'விதி குறியீடு',variable:'விதி மாறி',decisionTable:'முடிவு அட்டவணை',hitPolicy:'ஹிட் கொள்கை',cepPattern:'CEP வடிவம்',dslContent:'DSL உள்ளடக்கம்',dslVersion:'DSL பதிப்பு',cepName:'CEP பெயர்',cepWindow:'CEP சாளரம்',breakpointName:'பிரேக்பாயிண்ட் பெயர்',breakpointCondition:'பிரேக்பாயிண்ட் நிபந்தனை',auditTime:'நேரம்',auditUser:'பயனர்',auditAction:'செயல்',auditResult:'முடிவு',category:'வகை',description:'விளக்கம்',createdAt:'உருவாக்கப்பட்டது',sampleValue:'மாதிரி மதிப்பு',totalRules:'மொத்த விதிகள்'},{});

write('te-IN',{rule:'నియమాలు',ruleName:'నియమం పేరు',ruleCode:'నియమం కోడ్',variable:'నియమం వేరియబుల్',decisionTable:'నిర్ణయ పట్టిక',hitPolicy:'హిట్ విధానం',cepPattern:'CEP నమూనా',dslContent:'DSL కంటెంట్',dslVersion:'DSL వెర్షన్',cepName:'CEP పేరు',cepWindow:'CEP విండో',breakpointName:'బ్రేక్‌పాయింట్ పేరు',breakpointCondition:'బ్రేక్‌పాయింట్ షరతు',auditTime:'సమయం',auditUser:'వాడుకరి',auditAction:'చర్య',auditResult:'ఫలితం',category:'కేటగిరి',description:'వివరణ',createdAt:'సృష్టించబడింది',sampleValue:'నమూనా విలువ',totalRules:'మొత్తం నియమాలు'},{});

write('si-LK',{rule:'නීති',ruleName:'නීතියේ නම',ruleCode:'නීති කේතය',variable:'නීති විචල්‍යය',decisionTable:'තීරණ වගුව',hitPolicy:'හිට් ප්‍රතිපත්තිය',cepPattern:'CEP රටාව',dslContent:'DSL අන්තර්ගතය',dslVersion:'DSL අනුවාදය',cepName:'CEP නම',cepWindow:'CEP කවුළුව',breakpointName:'විරාම ස්ථානයේ නම',breakpointCondition:'විරාම ස්ථානයේ කොන්දේසිය',auditTime:'වේලාව',auditUser:'පරිශීලකයා',auditAction:'ක්‍රියාව',auditResult:'ප්‍රතිඵලය',category:'ප්‍රවර්ගය',description:'විස්තරය',createdAt:'සාදන ලදි',sampleValue:'සාම්පල අගය',totalRules:'මුළු නීති'},{});

write('ne-NP',{rule:'नियमहरू',ruleName:'नियमको नाम',ruleCode:'नियम कोड',variable:'नियम भेरिएबल',decisionTable:'निर्णय तालिका',hitPolicy:'हिट नीति',cepPattern:'CEP पैटर्न',dslContent:'DSL सामग्री',dslVersion:'DSL संस्करण',cepName:'CEP नाम',cepWindow:'CEP विन्डो',breakpointName:'ब्रेकपोइन्ट नाम',breakpointCondition:'ब्रेकपोइन्ट शर्त',auditTime:'समय',auditUser:'प्रयोगकर्ता',auditAction:'कार्य',auditResult:'परिणाम',category:'श्रेणी',description:'विवरण',createdAt:'सिर्जना गरियो',sampleValue:'नमूना मान',totalRules:'कुल नियमहरू'},{});

write('my-MM',{rule:'စည်းမျဉ်း',ruleName:'စည်းမျဉ်းအမည်',ruleCode:'စည်းမျဉ်းကုဒ်',variable:'စည်းမျဉ်းပြောင်းလဲနိုင်',decisionTable:'ဆုံးဖြတ်ချက်ဇယား',hitPolicy:'ရိုက်နှိပ်မူဝါဒ',cepPattern:'CEP ပုံစံ',dslContent:'DSL အကြောင်းအရာ',dslVersion:'DSL ဗားရှင်း',cepName:'CEP အမည်',cepWindow:'CEP ဝင်းဒိုး',breakpointName:'ဘရက်ပွိုင့်အမည်',breakpointCondition:'ဘရက်ပွိုင့်အခြေအနေ',auditTime:'အချိန်',auditUser:'အသုံးပြုသူ',auditAction:'လုပ်ဆောင်ချက်',auditResult:'ရလဒ်',category:'အမျိုးအစား',description:'ဖော်ပြချက်',createdAt:'ဖန်တီးထားသည်',sampleValue:'နမူနာတန်ဖိုး',totalRules:'စုစုပေါင်းစည်းမျဉ်း'},{});

write('km-KH',{rule:'ក្រិត្យ',ruleName:'ឈ្មោះក្រិត្យ',ruleCode:'លេខកូដក្រិត្យ',variable:'អថេរក្រិត្យ',decisionTable:'តារាងសម្រេចចិត្ត',hitPolicy:'គោលការណ៍វាយ',cepPattern:'គំរូ CEP',dslContent:'មាតិកា DSL',dslVersion:'ជំនាន់ DSL',cepName:'ឈ្មោះ CEP',cepWindow:'បង្អួច CEP',breakpointName:'ឈ្មោះចំណុចឈប់',breakpointCondition:'លក្ខណៈចំណុចឈប់',auditTime:'ពេលវេលា',auditUser:'អ្នកប្រើប្រាស់',auditAction:'សកម្មភាព',auditResult:'លទ្ធផល',category:'ប្រភេទ',description:'ការពិពណ៌នា',createdអ្នក:'បានបង្កើត',sampleValue:'តម្លៃគំរូ',totalRules:'សរុបក្រិត្យ'},{});

write('lo-LA',{rule:'ກົດລະບຽບ',ruleName:'ຊື່ກົດລະບຽບ',ruleCode:'ລະຫັດກົດລະບຽບ',variable:'ຕົວແປກົດລະບຽບ',decisionTable:'ຕາຕະລາງຕັດສິນໃຈ',hitPolicy:'ນະໂຍບາຍຕີ',cepPattern:'ແບບມົດລູກ',dslContent:'ເນື້ອຫາ DSL',dslVersion:'ເວີຊັນ DSL',cepName:'ຊື່ CEP',cepWindow:'ປ່ອງຢ້ຽມ CEP',breakpointName:'ຊື່ຈຸດຢຸດ',breakpointCondition:'ເງື່ອນໄຂຈຸດຢຸດ',auditTime:'ເວລາ',auditUser:'ຜູ້ໃຊ້',auditAction:'ການກະທຳ',auditResult:'ຜົນໄດ້ຮັບ',category:'ໝວດໝູ່',description:'ລາຍລະອຽດ',createdAt:'ສ້າງ',sampleValue:'ຄ່າຕົວຢ່າງ',totalRules:'ທັງໝົດກົດລະບຽບ'},{});

write('en-GB',{rule:'Rule Management',ruleName:'Rule name',ruleCode:'Rule code',variable:'Rule variable',decisionTable:'Decision table',hitPolicy:'Hit policy',cepPattern:'CEP pattern',dslContent:'DSL content',dslVersion:'DSL version',cepName:'CEP name',cepWindow:'CEP window',breakpointName:'Breakpoint name',breakpointCondition:'Breakpoint condition',auditTime:'Time',auditUser:'User',auditAction:'Action',auditResult:'Result',category:'Category',description:'Description',createdAt:'Created',sampleValue:'Sample value',totalRules:'Total rules'},{});

write('zh-HK',{rule:'規則管理',ruleName:'規則名稱',ruleCode:'規則編碼',variable:'規則變量',decisionTable:'決策表',hitPolicy:'匹配策略',cepPattern:'CEP 模式',dslContent:'DSL 內容',dslVersion:'DSL 版本',cepName:'CEP 名稱',cepWindow:'CEP 窗口',breakpointName:'斷點名稱',breakpointCondition:'斷點條件',auditTime:'時間',auditUser:'用戶',auditAction:'操作',auditResult:'結果',category:'分類',description:'描述',createdAt:'創建時間',sampleValue:'示例值',totalRules:'總規則數'},{});

write('zh-TW',{rule:'規則管理',ruleName:'規則名稱',ruleCode:'規則編碼',variable:'規則變數',decisionTable:'決策表',hitPolicy:'匹配策略',cepPattern:'CEP 模式',dslContent:'DSL 內容',dslVersion:'DSL 版本',cepName:'CEP 名稱',cepWindow:'CEP 視窗',breakpointName:'中斷點名稱',breakpointCondition:'中斷點條件',auditTime:'時間',auditUser:'使用者',auditAction:'操作',auditResult:'結果',category:'分類',description:'描述',createdAt:'建立時間',sampleValue:'範例值',totalRules:'總規則數'},{});

write('hi-IN',{rule:'नियम प्रबंधन',ruleName:'नियम का नाम',ruleCode:'नियम कोड',variable:'नियम चर',decisionTable:'निर्णय तालिका',hitPolicy:'हिट नीति',cepPattern:'CEP पैटर्न',dslContent:'DSL सामग्री',dslVersion:'DSL संस्करण',cepName:'CEP नाम',cepWindow:'CEP विंडो',breakpointName:'ब्रेकपॉइंट नाम',breakpointCondition:'ब्रेकपॉइंट शर्त',auditTime:'समय',auditUser:'उपयोगकर्ता',auditAction:'कार्य',auditResult:'परिणाम',category:'श्रेणी',description:'विवरण',createdAt:'बनाया',sampleValue:'नमूना मान',totalRules:'कुल नियम'},{});

write('am-ET',{rule:'ደንብ አስተዳደር',ruleName:'የደንብ ስም',ruleCode:'የደንብ ኮድ',variable:'የደንብ ተለዋጭ',decisionTable:'የውሳኔ ሰንጠረዥ',hitPolicy:'የመመስረት ፖሊሲ',cepPattern:'የ CEP ንጥረ ነገር',dslContent:'የ DSL ይዘት',dslVersion:'የ DSL ስሪት',cepName:'የ CEP ስም',cepWindow:'የ CEP መስኮት',breakpointName:'የብሬክፖንት ስም',breakpointCondition:'የብሬክፖንት ሁኔታ',auditTime:'ሰዓት',auditUser:'ተጠቃሚ',auditAction:'ድርጊት',auditResult:'ውጤት',category:'ምድብ',description:'መግለጫ',createdAt:'ተፈጠረ',sampleValue:'የናሙና ዋጋ',totalRules:'ጠቅላላ ደንቦች'},{});

write('sw-KE',{rule:'Kanuni',ruleName:'Jina la kanuni',ruleCode:'Msimbo wa kanuni',variable:'Kigezo cha kanuni',decisionTable:'Jedwali la maamuzi',hitPolicy:'Sera ya kugonga',cepPattern:'Kioleo cha CEP',dslContent:'Maudhui ya DSL',dslVersion:'Toleo la DSL',cepName:'Jina la CEP',cepWindow:'Dirisha la CEP',breakpointName:'Jina la kijalizo',breakpointCondition:'Hali ya kijalizo',auditTime:'Wakati',auditUser:'Mtumiaji',auditAction:'Hatua',auditResult:'Matokeo',category:'Kategoria',description:'Maelezo',createdAt:'Imetengenezwa',sampleValue:'Thamani ya sampuli',totalRules:'Jumla ya kanuni'},{});

write('zu-ZA',{rule:'Imithetho',ruleName:'Igama lomthetho',ruleCode:'Ikhodi yomthetho',variable:'I-variable yomthetho',decisionTable:'Ithebula yezinqumo',hitPolicy:'Inqubo yokushaya',cepPattern:'Isifanekiso se-CEP',dslContent:'Okuqukethwe kwe-DSL',dslVersion:'Inguqulo ye-DSL',cepName:'Igama le-CEP',cepWindow:'Iwindi le-CEP',breakpointName:'Igama lendawo yokuhluka',breakpointCondition:'Isimo sendawo yokuhluka',auditTime:'Isikhathi',auditUser:'Umsebenzisi',auditAction:'Isenzo',auditResult:'Umphumela',category:'Isigaba',description:'Incazelo',createdAt:'Kwakhiwe',sampleValue:'Inani lesampula',totalRules:'Isamba semithetho'},{});

write('af-ZA',{rule:'Reëlbestuur',ruleName:'Reëlnaam',ruleCode:'Reëlkode',variable:'Reëlveranderlike',decisionTable:'Besluitingstabel',hitPolicy:'Trefbeleid',cepPattern:'CEP-patroon',dslContent:'DSL-inhoud',dslVersion:'DSL-weergawe',cepName:'CEP-naam',cepWindow:'CEP-venster',breakpointName:'Breekpuntnaam',breakpointCondition:'Breekpuntvoorwaarde',auditTime:'Tyd',auditUser:'Gebruiker',auditAction:'Aksie',auditResult:'Uitslag',category:'Kategorie',description:'Beskrywing',createdAt:'Geskep',sampleValue:'Monsternaam',totalRules:'Totale reëls'},{});

console.log('\nDONE');
