const fs=require('fs'),path=require('path');
const TD=__dirname+'/_translations';
fs.mkdirSync(TD,{recursive:true});
const LOC=__dirname+'/langs';
const EN=JSON.parse(fs.readFileSync(path.join(LOC,'en-US','business.json'),'utf8'));
function makeBiz(overrides){const out={...EN};for(const k in overrides){out[k]=overrides[k];}return out;}
function write(loc,bizOverrides){
  const data={business:makeBiz(bizOverrides),page:{}};
  fs.writeFileSync(path.join(TD,loc+'.json'),JSON.stringify(data,null,2));
  process.stdout.write('.');
}

// ============ BATCH 2: Remaining 26 locales ============
write('bs-BA',{rule:'Pravila',ruleName:'Naziv pravila',ruleCode:'Kod pravila',variable:'Varijabla',decisionTable:'Tablica odluka',hitPolicy:'Pravila pogotka',cepPattern:'CEP obrazac',dslContent:'DSL sadržaj',dslVersion:'DSL verzija',cepName:'CEP naziv',cepWindow:'CEP prozor',breakpointName:'Naziv prekidača',breakpointCondition:'Uslov prekidača',auditTime:'Vrijeme',auditUser:'Korisnik',auditAction:'Akcija',auditResult:'Rezultat',category:'Kategorija',description:'Opis',createdAt:'Kreirano',sampleValue:'Uzorak vrijednosti',totalRules:'Ukupno pravila'});

write('ca-ES',{rule:'Regles',ruleName:'Nom de la regla',ruleCode:'Codi de la regla',variable:'Variable',decisionTable:'Taula de decisions',hitPolicy:"Política d'encert",cepPattern:'Patró CEP',dslContent:'Contingut DSL',dslVersion:'Versió DSL',cepName:'Nom CEP',cepWindow:'Finestra CEP',breakpointName:'Nom del punt de ruptura',breakpointCondition:'Condició del punt de ruptura',auditTime:'Temps',auditUser:'Usuari',auditAction:'Acció',auditResult:'Resultat',category:'Categoria',description:'Descripció',createdAt:'Creat',sampleValue:'Valor de mostra',totalRules:'Total regles'});

write('cs-CZ',{rule:'Pravidla',ruleName:'Název pravidla',ruleCode:'Kód pravidla',variable:'Proměnná',decisionTable:'Rozhodovací tabulka',hitPolicy:'Politika zásahu',cepPattern:'CEP vzor',dslContent:'DSL obsah',dslVersion:'DSL verze',cepName:'CEP název',cepWindow:'CEP okno',breakpointName:'Název zarážky',breakpointCondition:'Podmínka zarážky',auditTime:'Čas',auditUser:'Uživatel',auditAction:'Akce',auditResult:'Výsledek',category:'Kategorie',description:'Popis',createdAt:'Vytvořeno',sampleValue:'Ukázková hodnota',totalRules:'Celkem pravidel'});

write('cy-GB',{rule:'Rheolau',ruleName:'Enw rheol',ruleCode:'Cod rheol',variable:'Newidyn',decisionTable:'Benderfyniad Tabl',hitPolicy:'Polisi trawiad',cepPattern:'Patrwm CEP',dslContent:'Cynnwys DSL',dslVersion:'Fersiwn DSL',cepName:'Enw CEP',cepWindow:'Ffenestr CEP',breakpointName:'Enw pwynt torri',breakpointCondition:'Amod pwynt torri',auditTime:'Amser',auditUser:'Defnyddiwr',auditAction:'Gweithred',auditResult:'Canlyniad',category:'Categori',description:'Disgrifiad',createdAt:'Crëwyd',sampleValue:'Gwerth sampl',totalRules:'Cyfanswm rheolau'});

write('da-DK',{rule:'Regler',ruleName:'Regelnavn',ruleCode:'Regelkode',variable:'Regelvariabel',decisionTable:'Beslutningstabel',hitPolicy:'Hit-politik',cepPattern:'CEP-mønster',dslContent:'DSL-indhold',dslVersion:'DSL-version',cepName:'CEP-navn',cepWindow:'CEP-vindue',breakpointName:'Breakpunktnavn',breakpointCondition:'Breakpunktbetingelse',auditTime:'Tid',auditUser:'Bruger',auditAction:'Handling',auditResult:'Resultat',category:'Kategori',description:'Beskrivelse',createdAt:'Oprettet',sampleValue:'Prøveværdi',totalRules:'Total regler'});

write('de-AT',{rule:'Regelverwaltung',ruleName:'Regelname',ruleCode:'Regelcode',variable:'Regelvariable',decisionTable:'Entscheidungstabelle',hitPolicy:'Trefferpolitik',cepPattern:'CEP-Muster',dslContent:'DSL-Inhalt',dslVersion:'DSL-Version',cepName:'CEP-Name',cepWindow:'CEP-Fenster',breakpointName:'Haltepunktname',breakpointCondition:'Haltepunktbedingung',auditTime:'Zeit',auditUser:'Benutzer',auditAction:'Aktion',auditResult:'Ergebnis',category:'Kategorie',description:'Beschreibung',createdAt:'Erstellt',sampleValue:'Musterwert',totalRules:'Gesamtregeln'});

write('de-CH',{rule:'Regelverwaltung',ruleName:'Regelname',ruleCode:'Regelcode',variable:'Regelvariable',decisionTable:'Entscheidungstabelle',hitPolicy:'Trefferpolitik',cepPattern:'CEP-Muster',dslContent:'DSL-Inhalt',dslVersion:'DSL-Version',cepName:'CEP-Name',cepWindow:'CEP-Fenster',breakpointName:'Haltepunktname',breakpointCondition:'Haltepunktbedingung',auditTime:'Zeit',auditUser:'Benutzer',auditAction:'Aktion',auditResult:'Ergebnis',category:'Kategorie',description:'Beschreibung',createdAt:'Erstellt',sampleValue:'Musterwert',totalRules:'Gesamtregeln'});

write('el-GR',{rule:'Κανόνες',ruleName:'Όνομα κανόνα',ruleCode:'Κωδικός κανόνα',variable:'Μεταβλητή',decisionTable:'Πίνακας αποφάσεων',hitPolicy:'Πολιτική επιτυχίας',cepPattern:'Πρότυπο CEP',dslContent:'Περιεχόμενο DSL',dslVersion:'Έκδοση DSL',cepName:'Όνομα CEP',cepWindow:'Παράθυρο CEP',breakpointName:'Όνομα σημείου διακοπής',breakpointCondition:'Συνθήκη σημείου διακοπής',auditTime:'Ώρα',auditUser:'Χρήστης',auditAction:'Ενέργεια',auditResult:'Αποτέλεσμα',category:'Κατηγορία',description:'Περιγραφή',createdAt:'Δημιουργήθηκε',sampleValue:'Δείγμα τιμής',totalRules:'Σύνολο κανόνων'});

write('es-AR',{rule:'Reglas',ruleName:'Nombre de regla',ruleCode:'Código de regla',variable:'Variable',decisionTable:'Tabla de decisiones',hitPolicy:'Política de acierto',cepPattern:'Patrón CEP',dslContent:'Contenido DSL',dslVersion:'Versión DSL',cepName:'Nombre CEP',cepWindow:'Ventana CEP',breakpointName:'Nombre de punto de interrupción',breakpointCondition:'Condición de punto de interrupción',auditTime:'Tiempo',auditUser:'Usuario',auditAction:'Acción',auditResult:'Resultado',category:'Categoría',description:'Descripción',createdAt:'Creado',sampleValue:'Valor de muestra',totalRules:'Total reglas'});

write('es-MX',{rule:'Reglas',ruleName:'Nombre de regla',ruleCode:'Código de regla',variable:'Variable',decisionTable:'Tabla de decisiones',hitPolicy:'Política de acierto',cepPattern:'Patrón CEP',dslContent:'Contenido DSL',dslVersion:'Versión DSL',cepName:'Nombre CEP',cepWindow:'Ventana CEP',breakpointName:'Nombre de punto de interrupción',breakpointCondition:'Condición de punto de interrupción',auditTime:'Tiempo',auditUser:'Usuario',auditAction:'Acción',auditResult:'Resultado',category:'Categoría',description:'Descripción',createdAt:'Creado',sampleValue:'Valor de muestra',totalRules:'Total reglas'});

write('et-EE',{rule:'Reeglid',ruleName:'Reegli nimi',ruleCode:'Reegli kood',variable:'Muutuja',decisionTable:'Otsustabel',hitPolicy:'Tabamuse poliitika',cepPattern:'CEP muster',dslContent:'DSL sisu',dslVersion:'DSL versioon',cepName:'CEP nimi',cepWindow:'CEP aken',breakpointName:'Katkestuse nimi',breakpointCondition:'Katkestuse tingimus',auditTime:'Aeg',auditUser:'Kasutaja',auditAction:'Tegevus',auditResult:'Tulemus',category:'Kategooria',description:'Kirjeldus',createdAt:'Loodud',sampleValue:'Näidisväärtus',totalRules:'Kokku reegleid'});

write('eu-ES',{rule:'Arauak',ruleName:'Araua izena',ruleCode:'Arau kodea',variable:'Aldagaia',decisionTable:'Erabaki taula',hitPolicy:'Asistentzi politika',cepPattern:'CEP eredua',dslContent:'DSL edukia',dslVersion:'DSL bertsioa',cepName:'CEPa izena',cepWindow:'CEPa leihoa',breakpointName:'Etengarri izenburua',breakpointCondition:'Etengarri baldintza',auditTime:'Ordu',auditUser:'Erabiltzaile',auditAction:'Ekintza',auditResult:'Emaitza',category:'Kategoria',description:'Deskribapena',createdAt:'Sortu',sampleValue:'Adibide balioa',totalRules:'Guztira arauak'});

write('fi-FI',{rule:'Säännöt',ruleName:'Säännön nimi',ruleCode:'Säännön koodi',variable:'Muuttuja',decisionTable:'Päätöskaukalo',hitPolicy:'Osumapolitiikka',cepPattern:'CEP-malli',dslContent:'DSL-sisältö',dslVersion:'DSL-versio',cepName:'CEP-nimi',cepWindow:'CEP-ikkuna',breakpointName:'Keskeytyspisteen nimi',breakpointCondition:'Keskeytyspisteen ehto',auditTime:'Aika',auditUser:'Käyttäjä',auditAction:'Toiminto',auditResult:'Tulos',category:'Luokka',description:'Kuvaus',createdAt:'Luotu',sampleValue:'Arvo',totalRules:'Yhteensääntöjä'});

write('fil-PH',{rule:'Mga Tuntunin',ruleName:'Pangalan ng tuntunin',ruleCode:'Code ng tuntunin',variable:'Variable',decisionTable:'Desisyon Table',hitPolicy:'Patakaran sa-hit',cepPattern:'CEP pattern',dslContent:'DSL nilalaman',dslVersion:'DSL bersyon',cepName:'CEP pangalan',cepWindow:'CEP window',breakpointName:'Breakpoint pangalan',breakpointCondition:'Breakpoint kondisyon',auditTime:'Oras',auditUser:'Gumagamit',auditAction:'Aksyon',auditResult:'Resulta',category:'Kategorya',description:'Deskripsyon',createdAt:'Nilikha',sampleValue:'Sample value',totalRules:'Kabuuang tuntunin'});

write('fr-CA',{rule:'Règles',ruleName:'Nom de règle',ruleCode:'Code de règle',variable:'Variable',decisionTable:'Table de décision',hitPolicy:'Politique de correspondance',cepPattern:'Motif CEP',dslContent:'Contenu DSL',dslVersion:'Version DSL',cepName:'Nom CEP',cepWindow:'Fenêtre CEP',breakpointName:"Nom du point d'arrêt",breakpointCondition:"Condition du point d'arrêt",auditTime:'Temps',auditUser:'Utilisateur',auditAction:'Action',auditResult:'Résultat',category:'Catégorie',description:'Description',createdAt:'Créé',sampleValue:'Échantillon',totalRules:'Total règles'});

write('gl-ES',{rule:'Regras',ruleName:'Nome da regra',ruleCode:'Código da regra',variable:'Variable',decisionTable:'Táboa de decisións',hitPolicy:'Política de acertos',cepPattern:'Patrón CEP',dslContent:'Contido DSL',dslVersion:'Versión DSL',cepName:'Nome CEP',cepWindow:'Xanela CEP',breakpointName:'Nome do punto de interrupción',breakpointCondition:'Condición do punto de interrupción',auditTime:'Tempo',auditUser:'Usuario',auditAction:'Acción',auditResult:'Resultado',category:'Categoría',description:'Descrición',createdAt:'Creado',sampleValue:'Mostra',totalRules:'Total regras'});

write('he-IL',{rule:'ניהול כללים',ruleName:'שם הכלל',ruleCode:'קוד הכלל',variable:'משתנה',decisionTable:'טבלת החלטות',hitPolicy:'מדיניות פגיעה',cepPattern:'תבנית CEP',dslContent:'תוכן DSL',dslVersion:'גרסת DSL',cepName:'שם CEP',cepWindow:'חלון CEP',breakpointName:'שם נקודת עצירה',breakpointCondition:'תנאי נקודת עצירה',auditTime:'זמן',auditUser:'משתמש',auditAction:'פעולה',auditResult:'תוצאה',category:'קטגוריה',description:'תיאור',createdAt:'נוצר',sampleValue:'ערך לדוגמה',totalRules:'סהכ כללים'});

write('hr-HR',{rule:'Pravila',ruleName:'Naziv pravila',ruleCode:'Kod pravila',variable:'Varijabla',decisionTable:'Tablica odluka',hitPolicy:'Pravila pogotka',cepPattern:'CEP obrazac',dslContent:'DSL sadržaj',dslVersion:'DSL verzija',cepName:'CEP naziv',cepWindow:'CEP prozor',breakpointName:'Naziv prekidača',breakpointCondition:'Uslov prekidača',auditTime:'Vrijeme',auditUser:'Korisnik',auditAction:'Akcija',auditResult:'Rezultat',category:'Kategorija',description:'Opis',createdAt:'Kreirano',sampleValue:'Uzorak vrijednosti',totalRules:'Ukupno pravila'});

write('hu-HU',{rule:'Szabályok',ruleName:'Szabály neve',ruleCode:'Szabály kódja',variable:'Változó',decisionTable:'Döntéstáblázat',hitPolicy:'Találat politika',cepPattern:'CEP minta',dslContent:'DSL tartalom',dslVersion:'DSL verzió',cepName:'CEP név',cepWindow:'CEP ablak',breakpointName:'Töréspont neve',breakpointCondition:'Töréspont feltétel',auditTime:'Idő',auditUser:'Felhasználó',auditAction:'Művelet',auditResult:'Eredmény',category:'Kategória',description:'Leírás',createdAt:'Létrehozva',sampleValue:'Mintaérték',totalRules:'Összes szabály'});

write('hy-AM',{rule:'Կանոններ',ruleName:'Կանոնի անուն',ruleCode:'Կանոնի կոդ',variable:'Փոփոխական',decisionTable:'Որոշումների աղյուսակ',hitPolicy:'Արդյունավետության քաղաքականություն',cepPattern:'CEP ձևանմուշ',dslContent:'DSL բովանդակություն',dslVersion:'DSL տարբերակ',cepName:'CEP անուն',cepWindow:'CEP պատուհան',breakpointName:'Կետի անուն',breakpointCondition:'Կետի պայման',auditTime:'Ժամանակ',auditUser:'Օգտվող',auditAction:'Գործողություն',auditResult:'Արդյունք',category:'Կատեգորիա',description:'Նկարագրություն',createdAt:'Ստեղծվել է',sampleValue:'Նմանակ արժեք',totalRules:'Ընդամենը կանոններ'});

write('id-ID',{rule:'Aturan',ruleName:'Nama aturan',ruleCode:'Kode aturan',variable:'Variabel',decisionTable:'Tabel keputusan',hitPolicy:'Kebijakan hit',cepPattern:'Pola CEP',dslContent:'Konten DSL',dslVersion:'Versi DSL',cepName:'Nama CEP',cepWindow:'Jendela CEP',breakpointName:'Nama breakpoint',breakpointCondition:'Kondisi breakpoint',auditTime:'Waktu',auditUser:'Pengguna',auditAction:'Aksi',auditResult:'Hasil',category:'Kategori',description:'Deskripsi',createdAt:'Dibuat',sampleValue:'Nilai sampel',totalRules:'Total aturan'});

write('is-IS',{rule:'Reglur',ruleName:'Regluheiti',ruleCode:'Reglukóði',variable:'Breyta',decisionTable:'Ákvörðuntafla',hitPolicy:'Samsvörunarstefna',cepPattern:'CEP mynster',dslContent:'DSL innihald',dslVersion:'DSL útgáfa',cepName:'CEP heiti',cepWindow:'CEP gluggi',breakpointName:'Rospunkti heiti',breakpointCondition:'Rospunkti skilyrði',auditTime:'Tími',auditUser:'Notandi',auditAction:'Aðgerð',auditResult:'Niðurstaða',category:'Flokkur',description:'Lýsing',createdAt:'Búið til',sampleValue:'Sýni gildi',totalRules:'Samtals reglur'});

write('lt-LT',{rule:'Taisyklės',ruleName:'Taisyklės pavadinimas',ruleCode:'Taisyklės kodas',variable:'Kintamasis',decisionTable:'Sprendimo lentelė',hitPolicy:'Sėkmės politika',cepPattern:'CEP šablonas',dslContent:'DSL turinys',dslVersion:'DSL versija',cepName:'CEP pavadinimas',cepWindow:'CEP langas',breakpointName:'Nutraukimo taško pavadinimas',breakpointCondition:'Nutraukimo taško sąlyga',auditTime:'Laikas',auditUser:'Vartotojas',auditAction:'Veiksmas',auditResult:'Rezultatas',category:'Kategorija',description:'Aprašymas',createdAt:'Sukurta',sampleValue:'Pavyzdžio vertė',totalRules:'Iš viso taisyklių'});

write('lv-LV',{rule:'Noteikumi',ruleName:'Noteikuma nosaukums',ruleCode:'Noteikuma kods',variable:'Mainīgais',decisionTable:'Lēmuma tabula',hitPolicy:'Trāpīšanas politika',cepPattern:'CEP veidne',dslContent:'DSL saturs',dslVersion:'DSL versija',cepName:'CEP nosaukums',cepWindow:'CEP logs',breakpointName:'Pārtrauktspunkta nosaukums',breakpointCondition:'Pārtrauktspunkta nosacījums',auditTime:'Laiks',auditUser:'Lietotājs',auditAction:'Darbība',auditResult:'Rezultāts',category:'Kategorija',description:'Apraksts',createdAt:'Izveidots',sampleValue:'Parauga vērtība',totalRules:'Kopā noteikumi'});

write('mk-MK',{rule:'Правила',ruleName:'Назив на правилото',ruleCode:'Код на правилото',variable:'Променлива',decisionTable:'Табела на одлуки',hitPolicy:'Политика за совпаѓање',cepPattern:'CEP шема',dslContent:'DSL содржина',dslVersion:'DSL верзија',cepName:'CEP назив',cepWindow:'CEP прозорец',breakpointName:'Назив на прекин',breakpointCondition:'Услов за прекин',auditTime:'Време',auditUser:'Корисник',auditAction:'Акција',auditResult:'Резултат',category:'Категорија',description:'Опис',createdAt:'Крирано',sampleValue:'Примерка',totalRules:'Вкупно правила'});

write('ms-MY',{rule:'Peraturan',ruleName:'Nama peraturan',ruleCode:'Kod peraturan',variable:'Pembolehubah',decisionTable:'Jadual keputusan',hitPolicy:'Dasar hit',cepPattern:'Pola CEP',dslContent:'Kandungan DSL',dslVersion:'Versi DSL',cepName:'Nama CEP',cepWindow:'Tetingkap CEP',breakpointName:'Nama titik putus',breakpointCondition:'Keadaan titik putus',auditTime:'Masa',auditUser:'Pengguna',auditAction:'Tindakan',auditResult:'Keputusan',category:'Kategori',description:'Penerangan',createdAt:'Dicipta',sampleValue:'Nilai sampel',totalRules:'Jumlah peraturan'});

console.log('\nDONE');
