const fs=require('fs'),path=require('path');
const LOC=__dirname+'/langs';
const EN=JSON.parse(fs.readFileSync(path.join(LOC,'en-US','business.json'),'utf8'));
const ENP=JSON.parse(fs.readFileSync(path.join(LOC,'en-US','page.json'),'utf8'));
const ZHP=JSON.parse(fs.readFileSync(path.join(LOC,'zh-CN','page.json'),'utf8'));

// Helper: clone EN business values, then override with translations
function biz(translations){
  const out={...EN};
  for(const k of Object.keys(translations)) out[k]=translations[k];
  return out;
}
function pag(translations){
  const out={...ENP};
  for(const k of Object.keys(translations)) out[k]=translations[k];
  return out;
}
function BP(translations){return {business:biz(translations),page:pag({})};}
function BP2(b,p){return {business:biz(b),page:pag(p)};} 
function BO(b){return {business:biz(b),page:pag({})};}

const T={};

// ============ BATCH 1: Major Latin-script European ============
Object.assign(T,{
  'af-ZA': BP({rule:'Reëlbestuur',ruleName:'Reëlnaam',ruleCode:'Reëlkode',variable:'Reëlveranderlike',decisionTable:'Besluitingstabel',hitPolicy:'Trefbeleid',cepPatroon:'CEP-patroon',dslContent:'DSL-inhoud',dslVersion:'DSL-weergawe',cepName:'CEP-naam',cepWindow:'CEP-venster',breakpointName:'Breekpuntnaam',breakpointCondition:'Breekpuntvoorwaarde',auditTime:'Tyd',auditUser:'Gebruiker',auditAction:'Aksie',auditResult:'Uitslag',category:'Kategorie',description:'Beskrywing',createdAt:'Geskep',sampleValue:'Monsternaam',totalRules:'Totale reëls'}),

  'bs-BA': BP({rule:'Pravila',ruleName:'Naziv pravila',ruleCode:'Kod pravila',variable:'Varijabla pravila',decisionTable:'Tablica odluka',hitPolicy:'Pravila pogotka',cepPattern:'CEP obrazac',dslContent:'DSL sadržaj',dslVersion:'DSL verzija',cepName:'CEP naziv',cepWindow:'CEP prozor',breakpointName:'Naziv prekidača',breakpointCondition:'Uslov prekidača',auditTime:'Vrijeme',auditUser:'Korisnik',auditAction:'Akcija',auditResult:'Rezultat',category:'Kategorija',description:'Opis',createdAt:'Kreirano',sampleValue:'Uzorak vrijednost',totalRules:'Ukupno pravila'}),

  'ca-ES': BP({rule:'Regles',ruleName:'Nom de la regla',ruleCode:'Codi de la regla',variable:'Variable de regla',decisionTable:'Taula de decisions',hitPolicy:'Política d\'encert',cepPattern:'Patró CEP',dslContent:'Contingut DSL',dslVersion:'Versió DSL',cepName:'Nom CEP',cepWindow:'Finestra CEP',breakpointName:'Nom del punt de ruptura',breakpointCondition:'Condició del punt de ruptura',auditTime:'Temps',auditUser:'Usuari',auditAction:'Acció',auditResult:'Resultat',category:'Categoria',description:'Descripció',createdAt:'Creat',sampleValue:'Valor de mostra',totalRules:'Total regles'}),

  'cs-CZ': BP({rule:'Pravidla',ruleName:'Název pravidla',ruleCode:'Kód pravidla',variable:'Proměnná pravidla',decisionTable:'Rozhodovací tabulka',hitPolicy:'Politika zásahu',cepPattern:'CEP vzor',dslContent:'DSL obsah',dslVersion:'DSL verze',cepName:'CEP název',cepWindow:'CEP okno',breakpointName:'Název zarážky',breakpointCondition:'Podmínka zarážky',auditTime:'Čas',auditUser:'Uživatel',auditAction:'Akce',auditResult:'Výsledek',category:'Kategorie',description:'Popis',createdAt:'Vytvořeno',sampleValue:'Ukázková hodnota',totalRules:'Celkem pravidel'}),

  'cy-GB': BP({rule:'Rheolau',ruleName:'Enw rheol',ruleCode:'Cod rheol',variable=':'Newidyn rheol',decisionTable:'Benderfyniad Tabl',hitPolicy:'Polisi trawiad',cepPattern:'Patrwm CEP',dslContent:'Cynnwys DSL',dslVersion:'Fersiwn DSL',cepName:'Enw CEP',cepWindow:'Ffenestr CEP',breakpointName:'Enw pwynt torri',breakpointCondition:'Amod pwynt torri',auditTime:'Amser',auditUser:'Defnyddiwr',auditAction:'Gweithred',auditResult:'Canlyniad',category:'Categori',description:'Disgrifiad',createdAt:'Crëwyd',sampleValue:'Gwerth sampl',totalRules:'Cyfanswm rheolau'}),

  'da-DK': BP({rule:'Regler',ruleName:'Regelnavn',ruleCode:'Regelkode',variable:'Regelvariabel',decisionTable:'Beslutningstabel',hitPolicy:'Hit-politik',cepPattern:'CEP-mønster',dslContent:'DSL-indhold',dslVersion:'DSL-version',cepName:'CEP-navn',cepWindow:'CEP-vindue',breakpointName:'Breakpunktnavn',breakpointCondition:'Breakpunktbetingelse',auditTime:'Tid',auditUser:'Bruger',auditAction:'Handling',auditResult:'Resultat',category:'Kategori',description:'Beskrivelse',createdAt:'Oprettet',sampleValue:'Prøveværdi',totalRules:'Total regler'}),

  'de-AT': BP({rule:'Regelverwaltung',ruleName:'Regelname',ruleCode:'Regelcode',variable:'Regelvariable',decisionTable:'Entscheidungstabelle',hitPolicy:'Trefferpolitik',cepPattern:'CEP-Muster',dslContent:'DSL-Inhalt',dslVersion:'DSL-Version',cepName:'CEP-Name',cepWindow:'CEP-Fenster',breakpointName:'Haltepunktname',breakpointCondition:'Haltepunktbedingung',auditTime:'Zeit',auditUser:'Benutzer',auditAction:'Aktion',auditResult:'Ergebnis',category:'Kategorie',description:'Beschreibung',createdAt:'Erstellt',sampleValue:'Musterwert',totalRules:'Gesamtregeln'}),

  'de-CH': BP({rule:'Regelverwaltung',ruleName:'Regelname',ruleCode:'Regelcode',variable:'Regelvariable',decisionTable:'Entscheidungstabelle',hitPolicy:'Trefferpolitik',cepPattern:'CEP-Muster',dslContent:'DSL-Inhalt',dslVersion:'DSL-Version',cepName:'CEP-Name',cepWindow:'CEP-Fenster',breakpointName:'Haltepunktname',breakpointCondition:'Haltepunktbedingung',auditTime:'Zeit',auditUser:'Benutzer',auditAction:'Aktion',auditResult:'Ergebnis',category:'Kategorie',description:'Beschreibung',createdAt:'Erstellt',sampleValue:'Musterwert',totalRules:'Gesamtregels'}),

  'el-GR': BP({rule:'Κανόνες',ruleName:'Όνομα κανόνα',ruleCode:'Κωδικός κανόνα',variable:'Μεταβλητή κανόνα',decisionTable:'Πίνακας αποφάσεων',hitPolicy:'Πολιτική επιτυχίας',cepPattern:'Πρότυπο CEP',dslContent:'Περιεχόμενο DSL',dslVersion:'Έκδοση DSL',cepName:'Όνομα CEP',cepWindow:'Παράθυρο CEP',breakpointName:'Όνομα σημείου διακοπής',breakpointCondition:'Συνθήκη σημείου διακοπής',auditTime:'Ώρα',auditUser:'Χρήστης',auditAction:'Ενέργεια',auditResult:'Αποτέλεσμα',category:'Κατηγορία',description:'Περιγραφή',createdAt:'Δημιουργήθηκε',sampleValue:'Δείγμα τιμής',totalRules:'Σύνολο κανόνων'}),

  'es-AR': BP({rule:'Reglas',ruleName:'Nombre de regla',ruleCode:'Código de regla',variable:'Variable de regla',decisionTable:'Tabla de decisiones',hitPolicy:'Política de acierto',cepPattern:'Patrón CEP',dslContent:'Contenido DSL',dslVersion:'Versión DSL',cepName:'Nombre CEP',cepWindow:'Ventana CEP',breakpointName:'Nombre de punto de interrupción',breakpointCondition:'Condición de punto de interrupción',auditTime:'Tiempo',auditUser:'Usuario',auditAction:'Acción',auditResult:'Resultado',category:'Categoría',description:'Descripción',createdAt:'Creado',sampleValue:'Valor de muestra',totalRules:'Total reglas'}),

  'es-MX': BP({rule:'Reglas',ruleName:'Nombre de regla',ruleCode:'Código de regla',variable:'Variable de regla',decisionTable:'Tabla de decisiones',hitPolicy:'Política de acierto',cepPattern:'Patrón CEP',dslContent:'Contenido DSL',dslVersion:'Versión DSL',cepName:'Nombre CEP',cepWindow:'Ventana CEP',breakpointName:'Nombre de punto de interrupción',breakpointCondition:'Condición de punto de interrupción',auditTime:'Tiempo',auditUser:'Usuario',auditAction:'Acción',auditResult:'Resultado',category:'Categoría',description:'Descripción',createdAt:'Creado',sampleValue:'Valor de muestra',totalRules:'Total reglas'}),

  'et-EE': BP({rule:'Reeglid',ruleName:'Reegli nimi',ruleCode:'Reegli kood',variable:'Reegli muutuja',decisionTable:'Otsustabel',hitPolicy:'Tabamuse poliitika',cepPattern:'CEP muster',dslContent:'DSL sisu',dslVersion:'DSL versioon',cepName:'CEP nimi',cepWindow:'CEP aken',breakpointName:'Katkestuse nimi',breakpointCondition:'Katkestuse tingimus',auditTime:'Aeg',auditUser:'Kasutaja',auditAction:'Tegevus',auditResult:'Tulemus',category:'Kategooria',description:'Kirjeldus',createdAt:'Loodud',sampleValue:'Näidisväärtus',totalRules:'Kokku reegleid'}),

  'eu-ES': BP({rule:'Arauak',ruleName:'Araua izena',ruleCode:'Arau kodea',variable:'Arau aldagaia',decisionTable:'Erabaki taula',hitPolicy:'Asistentzi politika',cepPattern:'CEP eredua',dslContent:'DSL edukia',dslVersion:'DSL bertsioa',cepName:'CEPa izena',cepWindow:'CEPa leihoa',breakpointName:'Etengarri izenburua',breakpointCondition:'Etengarri baldintza',auditTime:'Ordu',auditUser:'Erabiltzaile',auditAction:'Ekintza',auditResult:'Emaitza',category:'Kategoria',description:'Deskribapena',createdAt:'Sortu',sampleValue:'Adibide balioa',totalRules:'Guztira arauak'}),

  'fi-FI': BP({rule:'Säännöt',ruleName:'Säännön nimi',ruleCode:'Säännön koodi',variable:'Säännön muuttuja',decisionTable:'Päätöskaukalo',hitPolicy:'Osumapolitiikka',cepPattern:'CEP-malli',dslContent:'DSL-sisältö',dslVersion:'DSL-versio',cepName:'CEP-nimi',cepWindow:'CEP-ikkuna',breakpointName:'Keskeytyspisteen nimi',breakpointCondition:'Keskeytyspisteen ehto',auditTime:'Aika',auditUser:'Käyttäjä',auditAction:'Toiminto',auditResult:'Tulos',category:'Luokka',description:'Kuvaus',createdAt:'Luotu',sampleValue:'Arvo',totalRules:'Yhteensääntöjä'}),

  'fil-PH': BP({rule:'Mga Tuntunin',ruleName:'Pangalan ng tuntunin',ruleCode:'Code ng tuntunin',variable:'Variable ng tuntunin',decisionTable:'Desisyon Table',hitPolicy:'Patakaran sa-hit',cepPattern:'CEP pattern',dslContent:'DSL nilalaman',dslVersion:'DSL bersyon',cepName:'CEP pangalan',cepWindow:'CEP window',breakpointName:'Breakpoint pangalan',breakpointCondition:'Breakpoint kundisyon',auditTime:'Oras',auditUser:'Gumagamit',auditAction:'Aksyon',auditResult:'Resulta',category:'Kategorya',description:'Deskripsyon',createdAt:'Nilikha',sampleValue:'Sample value',totalRules:'Kabuuang tuntunin'}),

  'fr-CA': BP({rule:'Règles',ruleName:'Nom de règle',ruleCode:'Code de règle',variable:'Variable de règle',decisionTable:'Table de décision',hitPolicy:'Politique de correspondance',cepPattern:'Motif CEP',dslContent:'Contenu DSL',dslVersion:'Version DSL',cepName:'Nom CEP',cepWindow:'Fenêtre CEP',breakpointName:'Nom du point d\'arrêt',breakpointCondition:'Condition du point d\'arrêt',auditTime:'Temps',auditUser:'Utilisateur',auditAction:'Action',auditResult:'Résultat',category:'Catégorie',description:'Description',createdAt:'Créé',sampleValue:'Échantillon',totalRules:'Total règles'}),

  'gl-ES': BP({rule:'Regras',ruleName:'Nome da regra',ruleCode:'Código da regra',variable:'Variable de regra',decisionTable:'Táboa de decisións',hitPolicy:'Política de acertos',cepPattern:'Patrón CEP',dslContent:'Contido DSL',dslVersion:'Versión DSL',cepName:'Nome CEP',cepWindow:'Xanela CEP',breakpointName:'Nome do punto de interrupción',breakpointCondition:'Condición do punto de interrupción',auditTime:'Tempo',auditUser:'Usuario',auditAction:'Acción',auditResult:'Resultado',category:'Categoría',description:'Descrición',createdAt:'Creado',sampleValue:'Mostra',totalRules:'Total regras'}),

  'he-IL': BP({rule:'ניהול כללים',ruleName:'שם הכלל',ruleCode:'קוד הכלל',variable:'משתנה כלל',decisionTable:'טבלת החלטות',hitPolicy:'מדיניות פגיעה',cepPattern:'תבנית CEP',dslContent:'תוכן DSL',dslVersion:'גרסת DSL',cepName:'שם CEP',cepWindow:'חלון CEP',breakpointName:'שם נקודת עצירה',breakpointCondition:'תנאי נקודת עצירה',auditTime:'זמן',auditUser:'משתמש',auditAction:'פעולה',auditResult:'תוצאה',category:'קטגוריה',description:'תיאור',createdAt:'נוצר',sampleValue:'ערך לדוגמה',totalRules:'סהכ כללים'}),

  'hi-IN': BP({rule:'नियम प्रबंधन',ruleName:'नियम का नाम',ruleCode:'नियम कोड',variable:'नियम चर',decisionTable:'निर्णय तालिका',hitPolicy:'हिट नीति',cepPattern:'CEP पैटर्न',dslContent:'DSL सामग्री',dslVersion:'DSL संस्करण',cepName:'CEP नाम',cepWindow:'CEP विंडो',breakpointName:'ब्रेकपॉइंट नाम',breakpointCondition:'ब्रेकपॉइंट शर्त',auditTime:'समय',auditUser:'उपयोगकर्ता',auditAction:'कार्य',auditResult:'परिणाम',category:'श्रेणी',description:'विवरण',createdAt:'बनाया',sampleValue:'नमूना मान',totalRules:'कुल नियम'}),

  'hr-HR': BP({rule:'Pravila',ruleName:'Naziv pravila',ruleCode:'Kod pravila',variable:'Varijabla pravila',decisionTable:'Tablica odluka',hitPolicy:'Pravila pogotka',cepPattern:'CEP obrazac',dslContent:'DSL sadržaj',dslVersion:'DSL verzija',cepName:'CEP naziv',cepWindow:'CEP prozor',breakpointName:'Naziv prekidača',breakpointCondition:'Uslov prekidača',auditTime:'Vrijeme',auditUser:'Korisnik',auditAction:'Akcija',auditResult:'Rezultat',category:'Kategorija',description:'Opis',createdAt:'Kreirano',sampleValue:'Uzorak vrijednosti',totalRules:'Ukupno pravila'}),

  'hu-HU': BP({rule:'Szabályok',ruleName:'Szabály neve',ruleCode:'Szabály kódja',variable:'Szabály változó',decisionTable:'Döntéstáblázat',hitPolicy:'Találat politika',cepPattern:'CEP minta',dslContent:'DSL tartalom',dslVersion:'DSL verzió',cepName:'CEP név',cepWindow:'CEP ablak',breakpointName:'Töréspont neve',breakpointCondition:'Töréspont feltétel',auditTime:'Idő',auditUser:'Felhasználó',auditAction:'Művelet',auditResult:'Eredmény',category:'Kategória',description:'Leírás',createdAt:'Létrehozva',sampleValue:'Mintaérték',totalRules:'Összes szabály'}),

  'hy-AM': BP({rule:'Կանոններ',ruleName:'Կանոնի անուն',ruleCode:'Կանոնի կոդ',variable:'Կանոնի փոփոխական',decisionTable:'Որոշումների աղյուսակ',hitPolicy:'Արդյունավետության քաղաքականություն',cepPattern:'CEP ձևանմուշ',dslContent:'DSL բովանդակություն',dslVersion:'DSL տարբերակ',cepName:'CEP անուն',cepWindow:'CEP պատուհան',breakpointName:'Կետի անուն',breakpointCondition:'Կետի պայման',auditTime:'Ժամանակ',auditUser:'Օգտվող',auditAction:'Գործողություն',auditResult:'Արդյունք',category:'Կատեգորիա',description:'Նկարագրություն',createdAt:'Ստեղծվել է',sampleValue:'Նմանակ արժեք',totalRules:'Ընդամենը կանոններ'}),

  'id-ID': BP({rule:'Aturan',ruleName:'Nama aturan',ruleCode:'Kode aturan',variable:'Variabel aturan',decisionTable:'Tabel keputusan',hitPolicy:'Kebijakan hit',cepPattern:'Pola CEP',dslContent:'Konten DSL',dslVersion:'Versi DSL',cepName:'Nama CEP',cepWindow:'Jendela CEP',breakpointName:'Nama breakpoint',breakpointCondition:'Kondisi breakpoint',auditTime:'Waktu',auditUser:'Pengguna',auditAction:'Aksi',auditResult:'Hasil',category:'Kategori',description:'Deskripsi',createdAt:'Dibuat',sampleValue:'Nilai sampel',totalRules:'Total aturan'}),

  'is-IS': BP({rule:'Reglur',ruleName:'Regluheiti',ruleCode:'Reglukóði',variable:'Reglubreytir',decisionTable:'Ákvörðuntafla',hitPolicy:'Samsvörunarstefna',cepPattern:'CEP mynster',dslContent:'DSL innihald',dslVersion:'DSL útgáfa',cepName:'CEP heiti',cepWindow:'CEP gluggi',breakpointName:'Rospunkti heiti',breakpointCondition:'Rospunkti skilyrði',auditTime:'Tími',auditUser:'Notandi',auditAction:'Aðgerð',auditResult:'Niðurstaða',category:'Flokkur',description:'Lýsing',createdAt:'Búið til',sampleValue:'Sýni gildi',totalRules:'Samtals reglur'}),

  'lo-LA': BP({rule:'ກົດລະບຽບ',ruleName:'ຊື່ກົດລະບຽບ',ruleCode:'ລະຫັດກົດລະບຽບ',variable=':'ຕົວແປກົດລະບຽບ',decisionTable:'ຕາຕະລາງຕັດສິນໃຈ',hitPolicy:'ນະໂຍບາຍຕີ',cepPattern:'ແບບມົດລູກ',dslContent:'ເນື້ອຫາ DSL',dslVersion:'ເວີຊັນ DSL',cepName:'ຊື່ CEP',cepWindow:'ປ່ອງຢ້ຽມ CEP',breakpointName:'ຊື່ຈຸດຢຸດ',breakpointCondition:'ເງື່ອນໄຂຈຸດຢຸດ',auditTime:'ເວລາ',auditUser:'ຜູ້ໃຊ້',auditAction:'ການກະທຳ',auditResult:'ຜົນໄດ້ຮັບ',category:'ໝວດໝູ່',description:'ລາຍລະອຽດ',createdAt:'ສ້າງ',sampleValue:'ຄ່າຕົວຢ່າງ',totalRules:'ທັງໝົດກົດລະບຽບ'}),

  'lt-LT': BP({rule:'Taisyklės',ruleName:'Taisyklės pavadinimas',ruleCode:'Taisyklės kodas',variable:'Taisyklės kintamasis',decisionTable:'Sprendimo lentelė',hitPolicy:'Sėkmės politika',cepPattern:'CEP šablonas',dslContent:'DSL turinys',dslVersion:'DSL versija',cepName:'CEP pavadinimas',cepWindow:'CEP langas',breakpointName:'Nutraukimo taško pavadinimas',breakpointCondition:'Nutraukimo taško sąlyga',auditTime:'Laikas',auditUser:'Vartotojas',auditAction:'Veiksmas',auditResult:'Rezultatas',category:'Kategorija',description:'Aprašymas',createdAt:'Sukurta',sampleValue:'Pavyzdžio vertė',totalRules:'Iš viso taisyklių'}),

  'lv-LV': BP({rule:'Noteikumi',ruleName:'Noteikuma nosaukums',ruleCode:'Noteikuma kods',variable:'Noteikuma mainīgais',decisionTable:'Lēmuma tabula',hitPolicy:'Trāpīšanas politika',cepPattern:'CEP veidne',dslContent:'DSL saturs',dslVersion:'DSL versija',cepName:'CEP nosaukums',cepWindow:'CEP logs',breakpointName:'Pārtrauktspunkta nosaukums',breakpointCondition:'Pārtrauktspunkta nosacījums',auditTime:'Laiks',auditUser:'Lietotājs',auditAction:'Darbība',auditResult:'Rezultāts',category:'Kategorija',description:'Apraksts',createdAt:'Izveidots',sampleValue:'Parauga vērtība',totalRules:'Kopā noteikumi'})
});
