/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * CEPController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code CEPController}，共 7 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @path apps\literule-web\src\api\cep.ts
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { CEPHitVO, CEPPattern, CEPPatternVO } from './models';

/**
 * listPatterns: GET /api/v1/literule/cep/patterns
 */
export function listPatterns(): Promise<CEPPatternVO[]> {
  return requestClient.get<CEPPatternVO[]>(`/api/v1/literule/cep/patterns`);
}

/**
 * registerPattern: POST /api/v1/literule/cep/patterns
 */
export function registerPattern(data: CEPPattern): Promise<void> {
  return requestClient.post<void>(`/api/v1/literule/cep/patterns`, data);
}

/**
 * unregisterPattern: DELETE /api/v1/literule/cep/patterns/{pattern-id}
 */
export function unregisterPattern({ patternId }: {
    patternId: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/literule/cep/patterns/${patternId}`);
}

/**
 * feedEvent: POST /api/v1/literule/cep/events
 */
export function feedEvent(data: Record<string, Record<string, unknown>>): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.post<Record<string, Record<string, unknown>>>(`/api/v1/literule/cep/events`, data);
}

/**
 * feedEvents: POST /api/v1/literule/cep/events/batch
 */
export function feedEvents(data: Record<string, Record<string, unknown>>[]): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.post<Record<string, Record<string, unknown>>>(`/api/v1/literule/cep/events/batch`, data);
}

/**
 * recentHits: GET /api/v1/literule/cep/hits
 */
export function recentHits(): Promise<CEPHitVO[]> {
  return requestClient.get<CEPHitVO[]>(`/api/v1/literule/cep/hits`);
}

/**
 * stats: GET /api/v1/literule/cep/stats
 */
export function stats(): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/api/v1/literule/cep/stats`);
}
