/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * RuleDslImportExportController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RuleDslImportExportController}，共 3 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';

/**
 * importDsl: POST /api/v1/literule/dsl/import
 */
export function importDsl(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/dsl/import`, data);
}

/**
 * exportAll: GET /api/v1/literule/dsl/export
 */
export function exportAll(params: { category?: string }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/dsl/export`, { params });
}

/**
 * exportSingle: GET /api/v1/literule/dsl/export/{ruleCode}
 */
export function exportSingle({ ruleCode }: { ruleCode: string }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/dsl/export/${ruleCode}`);
}
