/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * RuleDebugController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RuleDebugController}，共 8 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';


/**
 * listBreakpoints: GET /api/v1/literule/debug/breakpoints
 */
export function listBreakpoints(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/debug/breakpoints`);
}

/**
 * addBreakpoint: POST /api/v1/literule/debug/breakpoints
 */
export function addBreakpoint(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/debug/breakpoints`, data);
}

/**
 * removeBreakpoint: DELETE /api/v1/literule/debug/breakpoints/{breakpointId}
 */
export function removeBreakpoint({ breakpointId }: {
    breakpointId: string;
  }): Promise<unknown> {
  return requestClient.delete<unknown>(`/api/v1/literule/debug/breakpoints/${breakpointId}`);
}

/**
 * createSession: POST /api/v1/literule/debug/sessions
 */
export function createSession(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/debug/sessions`, data);
}

/**
 * getSession: GET /api/v1/literule/debug/sessions/{sessionId}
 */
export function getSession({ sessionId }: {
    sessionId: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/debug/sessions/${sessionId}`);
}

/**
 * submitCommand: POST /api/v1/literule/debug/sessions/{sessionId}/command
 */
export function submitCommand({ sessionId }: {
    sessionId: string;
  }, data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/debug/sessions/${sessionId}/command`, data);
}

/**
 * terminateSession: DELETE /api/v1/literule/debug/sessions/{sessionId}
 */
export function terminateSession({ sessionId }: {
    sessionId: string;
  }): Promise<unknown> {
  return requestClient.delete<unknown>(`/api/v1/literule/debug/sessions/${sessionId}`);
}

/**
 * listSessions: GET /api/v1/literule/debug/sessions
 */
export function listSessions(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/debug/sessions`);
}
