/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * RulePackController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RulePackController}，共 15 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @path apps\literule-web\src\api\rulePack.ts
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { InstallResultVO, PackDiffVO, PackUpdateInfoVO, RulePackVO } from './models';

/**
 * listPacks: GET /api/v1/literule/rules/packs
 */
export function listPacks(): Promise<RulePackVO[]> {
  return requestClient.get<RulePackVO[]>(`/api/v1/literule/rules/packs`);
}

/**
 * searchPacks: GET /api/v1/literule/rules/packs/search
 */
export function searchPacks(params: {
    keyword?: string;
  }): Promise<RulePackVO[]> {
  return requestClient.get<RulePackVO[]>(`/api/v1/literule/rules/packs/search`, { params });
}

/**
 * getLatestPack: GET /api/v1/literule/rules/packs/{packCode}/latest
 */
export function getLatestPack({ packCode }: {
    packCode: string;
  }): Promise<RulePackVO> {
  return requestClient.get<RulePackVO>(`/api/v1/literule/rules/packs/${packCode}/latest`);
}

/**
 * listPackVersions: GET /api/v1/literule/rules/packs/{packCode}/versions
 */
export function listPackVersions({ packCode }: {
    packCode: string;
  }): Promise<RulePackVO[]> {
  return requestClient.get<RulePackVO[]>(`/api/v1/literule/rules/packs/${packCode}/versions`);
}

/**
 * getPackVersion: GET /api/v1/literule/rules/packs/{packCode}/versions/{version}
 */
export function getPackVersion({ packCode, version }: {
    packCode: string;
    version: string;
  }): Promise<RulePackVO> {
  return requestClient.get<RulePackVO>(`/api/v1/literule/rules/packs/${packCode}/versions/${version}`);
}

/**
 * rollbackPack: POST /api/v1/literule/rules/packs/{packCode}/rollback
 */
export function rollbackPack({ packCode }: {
    packCode: string;
  }, params: {
    version?: string;
  }): Promise<InstallResultVO> {
  return requestClient.post<InstallResultVO>(`/api/v1/literule/rules/packs/${packCode}/rollback`, { params });
}

/**
 * diffPack: GET /api/v1/literule/rules/packs/{packCode}/diff
 */
export function diffPack({ packCode }: {
    packCode: string;
  }, params: {
    fromVersion?: string;
    toVersion?: string;
  }): Promise<PackDiffVO> {
  return requestClient.get<PackDiffVO>(`/api/v1/literule/rules/packs/${packCode}/diff`, { params });
}

/**
 * publishPack: POST /api/v1/literule/rules/packs
 */
export function publishPack(data: RulePackVO): Promise<RulePackVO> {
  return requestClient.post<RulePackVO>(`/api/v1/literule/rules/packs`, data);
}

/**
 * installPack: POST /api/v1/literule/rules/packs/{packCode}/install
 */
export function installPack({ packCode }: {
    packCode: string;
  }, params: {
    version?: string;
  }): Promise<InstallResultVO> {
  return requestClient.post<InstallResultVO>(`/api/v1/literule/rules/packs/${packCode}/install`, { params });
}

/**
 * deletePack: DELETE /api/v1/literule/rules/packs/{id}
 */
export function deletePack({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/literule/rules/packs/${id}`);
}

/**
 * markOfficialPack: PUT /api/v1/literule/rules/packs/{id}/official
 */
export function markOfficialPack({ id }: {
    id: string;
  }, params: {
    official?: boolean;
  }): Promise<void> {
  return requestClient.put<void>(`/api/v1/literule/rules/packs/${id}/official`, { params });
}

/**
 * ratePack: PUT /api/v1/literule/rules/packs/{id}/rate
 */
export function ratePack({ id }: {
    id: string;
  }, params: {
    rating?: number;
  }): Promise<void> {
  return requestClient.put<void>(`/api/v1/literule/rules/packs/${id}/rate`, { params });
}

/**
 * stressTest: POST /api/v1/literule/rules/stress-test
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function stressTest(data: Record<string, Record<string, unknown>>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/rules/stress-test`, data);
}

/**
 * checkPackUpdates: GET /api/v1/literule/rules/packs/update-check
 */
export function checkPackUpdates(): Promise<PackUpdateInfoVO[]> {
  return requestClient.get<PackUpdateInfoVO[]>(`/api/v1/literule/rules/packs/update-check`);
}

/**
 * batchUpdatePacks: POST /api/v1/literule/rules/packs/batch-update
 */
export function batchUpdatePacks(data: string[]): Promise<InstallResultVO[]> {
  return requestClient.post<InstallResultVO[]>(`/api/v1/literule/rules/packs/batch-update`, data);
}
