/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * RuleABPolicyController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RuleABPolicyController}，共 5 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { RuleABPolicyPutDTO, RuleABPolicyVO, RuleABRollbackVO } from './models';

/**
 * getABPolicy: GET /api/v1/literule/rules/{ruleCode}/ab-policy
 */
export function getABPolicy(path: {
    ruleCode: string;
  }): Promise<RuleABPolicyVO> {
  return requestClient.get<RuleABPolicyVO>(`/api/v1/literule/rules/${ruleCode}/ab-policy`);
}

/**
 * updateABPolicy: PUT /api/v1/literule/rules/{ruleCode}/ab-policy
 */
export function updateABPolicy(path: {
    ruleCode: string;
  }, data: RuleABPolicyPutDTO): Promise<void> {
  return requestClient.put<void>(`/api/v1/literule/rules/${ruleCode}/ab-policy`, data);
}

/**
 * listRollbackHistory: GET /api/v1/literule/rules/{ruleCode}/ab-rollbacks
 */
export function listRollbackHistory(path: {
    ruleCode: string;
  }): Promise<RuleABRollbackVO[]> {
  return requestClient.get<RuleABRollbackVO[]>(`/api/v1/literule/rules/${ruleCode}/ab-rollbacks`);
}

/**
 * evaluateAB: POST /api/v1/literule/rules/{ruleCode}/ab-evaluate
 */
export function evaluateAB(path: {
    ruleCode: string;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/api/v1/literule/rules/${ruleCode}/ab-evaluate`);
}

/**
 * manualRollback: POST /api/v1/literule/rules/{ruleCode}/ab-rollback
 */
export function manualRollback(path: {
    ruleCode: string;
  }, params: {
    reason?: string;
  }): Promise<RuleABRollbackVO> {
  return requestClient.post<RuleABRollbackVO>(`/api/v1/literule/rules/${ruleCode}/ab-rollback`, { params });
}
