/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * RuleDecisionTableController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RuleDecisionTableController}，共 8 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { DecisionTableDefinitionVO, DecisionTablePostDTO, DecisionTableVO } from './models';

/**
 * listDecisionTables: GET /api/v1/literule/rules/decision-tables
 */
export function listDecisionTables(): Promise<DecisionTableVO[]> {
  return requestClient.get<DecisionTableVO[]>(`/api/v1/literule/rules/decision-tables`);
}

/**
 * getDecisionTable: GET /api/v1/literule/rules/decision-tables/{tableCode}
 */
export function getDecisionTable(path: {
    tableCode: string;
  }): Promise<DecisionTableVO> {
  return requestClient.get<DecisionTableVO>(`/api/v1/literule/rules/decision-tables/${tableCode}`);
}

/**
 * saveDecisionTable: POST /api/v1/literule/rules/decision-tables
 */
export function saveDecisionTable(data: DecisionTablePostDTO): Promise<DecisionTableVO> {
  return requestClient.post<DecisionTableVO>(`/api/v1/literule/rules/decision-tables`, data);
}

/**
 * deleteDecisionTable: DELETE /api/v1/literule/rules/decision-tables/{id}
 */
export function deleteDecisionTable(path: {
    id: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/literule/rules/decision-tables/${id}`);
}

/**
 * evaluateDecisionTable: POST /api/v1/literule/rules/decision-tables/{tableCode}/evaluate
 */
export function evaluateDecisionTable(path: {
    tableCode: string;
  }, data: Record<string, unknown>): Promise<Record<string, unknown>[]> {
  return requestClient.post<Record<string, unknown>[]>(`/api/v1/literule/rules/decision-tables/${tableCode}/evaluate`, data);
}

/**
 * exportDecisionTableExcel: GET /api/v1/literule/rules/decision-tables/{tableCode}/export-excel
 */
export function exportDecisionTableExcel(path: {
    tableCode: string;
  }, params: {
    response?: Record<string, unknown>;
  }): Promise<void> {
  return requestClient.get<void>(`/api/v1/literule/rules/decision-tables/${tableCode}/export-excel`, { params });
}

/**
 * importDecisionTableExcel: POST /api/v1/literule/rules/decision-tables/import-excel
 */
export function importDecisionTableExcel(params: {
    file?: Record<string, unknown>;
  }): Promise<DecisionTableDefinitionVO> {
  return requestClient.post<DecisionTableDefinitionVO>(`/api/v1/literule/rules/decision-tables/import-excel`, { params });
}

/**
 * downloadDecisionTableExcelTemplate: GET /api/v1/literule/rules/decision-tables/excel-template
 */
export function downloadDecisionTableExcelTemplate(params: {
    response?: Record<string, unknown>;
  }): Promise<void> {
  return requestClient.get<void>(`/api/v1/literule/rules/decision-tables/excel-template`, { params });
}
