/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * RuleDslController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RuleDslController}，共 3 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { RuleDslVO } from './models';

/**
 * validate: POST /api/v1/literule/dsl/validate
 */
export function validate(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/dsl/validate`, data);
}

/**
 * parse: POST /api/v1/literule/dsl/parse
 */
export function parse(data: Record<string, unknown>): Promise<RuleDslVO> {
  return requestClient.post<RuleDslVO>(`/api/v1/literule/dsl/parse`, data);
}

/**
 * preview: POST /api/v1/literule/dsl/preview
 */
export function preview(data: Record<string, unknown>): Promise<Record<string, unknown>[]> {
  return requestClient.post<Record<string, unknown>[]>(`/api/v1/literule/dsl/preview`, data);
}
