/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * RuleDebugController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code RuleDebugController}，共 8 个端点。
 * <p>路径规范: /api/v1/literule/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @path apps\literule-web\src\api\ruleDebug.ts
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py literule} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';


/**
 * listBreakpoints: GET /api/v1/literule/debug/breakpoints
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function listBreakpoints(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/debug/breakpoints`);
}

/**
 * addBreakpoint: POST /api/v1/literule/debug/breakpoints
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function addBreakpoint(data: Record<string, string>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/debug/breakpoints`, data);
}

/**
 * removeBreakpoint: DELETE /api/v1/literule/debug/breakpoints/{breakpointId}
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function removeBreakpoint({ breakpointId }: {
    breakpointId: string;
  }): Promise<unknown> {
  return requestClient.delete<unknown>(`/api/v1/literule/debug/breakpoints/${breakpointId}`);
}

/**
 * createSession: POST /api/v1/literule/debug/sessions
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function createSession(data: Record<string, string>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/debug/sessions`, data);
}

/**
 * getSession: GET /api/v1/literule/debug/sessions/{sessionId}
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function getSession({ sessionId }: {
    sessionId: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/debug/sessions/${sessionId}`);
}

/**
 * submitCommand: POST /api/v1/literule/debug/sessions/{sessionId}/command
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function submitCommand({ sessionId }: {
    sessionId: string;
  }, data: Record<string, string>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/literule/debug/sessions/${sessionId}/command`, data);
}

/**
 * terminateSession: DELETE /api/v1/literule/debug/sessions/{sessionId}
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function terminateSession({ sessionId }: {
    sessionId: string;
  }): Promise<unknown> {
  return requestClient.delete<unknown>(`/api/v1/literule/debug/sessions/${sessionId}`);
}

/**
 * listSessions: GET /api/v1/literule/debug/sessions
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function listSessions(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/literule/debug/sessions`);
}
