<!--
 * 菜单管理页面 — 树形表格展示菜单层级，支持新增（顶级/子级）/编辑/删除菜单项
 *
 * @path apps\userinfo-web\src\views\system\menu\index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 菜单（列表页）
 * <p>菜单（{@code ydsz_menu}）的列表页，消费后端契约 MenuController
 * （src/api/menu.ts，auto-generated by bash/gen-contract.py）：
 * 以 tree() 获取带 children 的菜单树直接渲染树形表格，支持新增顶级/子级菜单、
 * 编辑与删除，删除成功后刷新树。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import { Page, useYDSZModal } from '@ydsz/common-ui';

import {
  ElButton,
  ElMessage,
  ElMessageBox,
  ElTable,
  ElTableColumn,
  ElTag,
} from 'element-plus';
import type { TagProps } from 'element-plus';
import { onMounted, ref } from 'vue';

import { remove, tree } from '#/api/menu';
import type { MenuTreeVO } from '#/api/models';

import MenuForm from './menu-form.vue';

defineOptions({ name: 'MenuManagement' });

/** 菜单类型映射（契约 menuType 为字符串，兼容 'DIRECTORY'/'MENU'/'BUTTON' 与 '0'/'1'/'2'） */
const MENU_TYPE_MAP: Record<string, { label: string; type: TagProps['type'] }> = {
  DIRECTORY: { label: '目录', type: 'primary' },
  MENU: { label: '菜单', type: 'success' },
  BUTTON: { label: '按钮', type: 'warning' },
  '0': { label: '目录', type: 'primary' },
  '1': { label: '菜单', type: 'success' },
  '2': { label: '按钮', type: 'warning' },
};

/** 判断菜单状态是否启用（契约 status 为字符串 '1'/'0'） */
function isEnabled(status?: string): boolean {
  return status === '1';
}

/** 判断菜单是否可见（契约 visible 为数字，1 显示 / 0 隐藏） */
function isVisible(visible?: number): boolean {
  return visible === 1;
}

const loading = ref(false);
const tableData = ref<MenuTreeVO[]>([]);

async function loadData() {
  loading.value = true;
  try {
    tableData.value = (await tree()) ?? [];
  } finally {
    loading.value = false;
  }
}

onMounted(loadData);

// ========== 表单弹窗 ==========
const [MenuFormModal, menuFormApi] = useYDSZModal({ connectedComponent: MenuForm });

function handleAdd(parentId?: string) {
  menuFormApi.setData({ parentId, treeData: tableData.value });
  menuFormApi.open();
}

function handleEdit(row: MenuTreeVO) {
  menuFormApi.setData({ record: row, treeData: tableData.value });
  menuFormApi.open();
}

// ========== 删除 ==========
async function handleDelete(row: MenuTreeVO) {
  if (!row.id) return;
  try {
    await ElMessageBox.confirm(
      `确定删除菜单「${row.menuName ?? ''}」吗？`,
      '删除确认',
      { type: 'warning' },
    );
    await remove({ id: row.id });
    ElMessage.success('删除成功');
    loadData();
  } catch {
    // 用户取消或请求失败
  }
}
</script>

<template>
  <Page auto-content-height>
    <div class="p-4">
      <div class="mb-4 flex items-center justify-between">
        <h3 class="text-lg font-semibold">菜单管理</h3>
        <div class="flex gap-2">
          <ElButton @click="loadData">刷新</ElButton>
          <ElButton type="primary" @click="handleAdd()">新增顶级菜单</ElButton>
        </div>
      </div>
      <ElTable
        v-loading="loading"
        :data="tableData"
        row-key="id"
        border
        default-expand-all
        :tree-props="{ children: 'children' }"
      >
        <ElTableColumn prop="menuName" label="菜单名称" min-width="180" />
        <ElTableColumn label="类型" width="80" align="center">
          <template #default="{ row }">
            <ElTag
              :type="MENU_TYPE_MAP[row.menuType]?.type || 'info'"
              size="small"
            >
              {{ MENU_TYPE_MAP[row.menuType]?.label || '未知' }}
            </ElTag>
          </template>
        </ElTableColumn>
        <ElTableColumn prop="menuCode" label="菜单编码" width="120" />
        <ElTableColumn prop="path" label="路由路径" width="160" />
        <ElTableColumn prop="component" label="组件路径" width="200" />
        <ElTableColumn prop="permissionCode" label="权限标识" width="160" />
        <ElTableColumn prop="icon" label="图标" width="80" align="center" />
        <ElTableColumn prop="sortOrder" label="排序" width="80" align="center" />
        <ElTableColumn label="可见" width="80" align="center">
          <template #default="{ row }">
            <ElTag :type="isVisible(row.visible) ? 'success' : 'info'" size="small">
              {{ isVisible(row.visible) ? '显示' : '隐藏' }}
            </ElTag>
          </template>
        </ElTableColumn>
        <ElTableColumn label="状态" width="80" align="center">
          <template #default="{ row }">
            <ElTag :type="isEnabled(row.status) ? 'success' : 'danger'" size="small">
              {{ isEnabled(row.status) ? '启用' : '禁用' }}
            </ElTag>
          </template>
        </ElTableColumn>
        <ElTableColumn label="操作" width="220" fixed="right">
          <template #default="{ row }">
            <ElButton size="small" link type="primary" @click="handleAdd(row.id)">
              新增子菜单
            </ElButton>
            <ElButton size="small" link type="primary" @click="handleEdit(row)">
              编辑
            </ElButton>
            <ElButton size="small" link type="danger" @click="handleDelete(row)">
              删除
            </ElButton>
          </template>
        </ElTableColumn>
      </ElTable>
    </div>
    <MenuFormModal @success="loadData" />
  </Page>
</template>