/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * AdminSessionController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code AdminSessionController}，共 7 个端点。
 * <p>路径规范: /api/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { BanInfoVO, UserBanRequestDTO, UserSessionStatistics, UserSessionVO } from './models';

/**
 * banUser: POST /api/admin/users/{userId}/ban
 */
export function banUser(path: {
    userId: string;
  }, data: UserBanRequestDTO): Promise<boolean> {
  return requestClient.post<boolean>(`/api/admin/users/${userId}/ban`, data);
}

/**
 * unbanUser: POST /api/admin/users/{userId}/unban
 */
export function unbanUser(path: {
    userId: string;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/api/admin/users/${userId}/unban`);
}

/**
 * getBanInfo: GET /api/admin/users/{userId}/ban-info
 */
export function getBanInfo(path: {
    userId: string;
  }): Promise<BanInfoVO> {
  return requestClient.get<BanInfoVO>(`/api/admin/users/${userId}/ban-info`);
}

/**
 * getUserSessions: GET /api/admin/users/{userId}/sessions
 */
export function getUserSessions(path: {
    userId: string;
  }): Promise<UserSessionVO[]> {
  return requestClient.get<UserSessionVO[]>(`/api/admin/users/${userId}/sessions`);
}

/**
 * forceLogout: DELETE /api/admin/users/{userId}/sessions/{accessToken}
 */
export function forceLogout(path: {
    userId: string;
    accessToken: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/admin/users/${userId}/sessions/${accessToken}`);
}

/**
 * getAllActiveSessions: GET /api/admin/sessions
 */
export function getAllActiveSessions(params: {
    page?: number;
    size?: number;
  }): Promise<UserSessionVO[]> {
  return requestClient.get<UserSessionVO[]>(`/api/admin/sessions`, { params });
}

/**
 * getSessionStatistics: GET /api/admin/sessions/statistics
 */
export function getSessionStatistics(): Promise<UserSessionStatistics> {
  return requestClient.get<UserSessionStatistics>(`/api/admin/sessions/statistics`);
}
