/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * SocialClientConfigController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code SocialClientConfigController}，共 5 个端点。
 * <p>路径规范: /api/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { PageResponse, SocialClientDTO, SocialClientPageQuery, SocialClientVO } from './models';

/**
 * page: GET /api/social-client-config/page
 */
export function page(params: {
    query?: SocialClientPageQuery;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/social-client-config/page`, { params });
}

/**
 * listEnabled: GET /api/social-client-config/enabled
 */
export function listEnabled(): Promise<SocialClientVO[]> {
  return requestClient.get<SocialClientVO[]>(`/api/social-client-config/enabled`);
}

/**
 * create: POST /api/social-client-config
 */
export function create(data: SocialClientDTO): Promise<void> {
  return requestClient.post<void>(`/api/social-client-config`, data);
}

/**
 * update: PUT /api/social-client-config/{platform}
 */
export function update(path: {
    platform: string;
  }, data: SocialClientDTO): Promise<void> {
  return requestClient.put<void>(`/api/social-client-config/${platform}`, data);
}

/**
 * delete: DELETE /api/social-client-config/{platform}
 */
export function delete(path: {
    platform: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/social-client-config/${platform}`);
}
