<!--
 * Agent RAG 知识库（调试台）
 *
 * @path apps/agent-web/src/views/rag/index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * Agent RAG 知识库（调试台）
 * <p>消费后端 RagController 契约（auto-generated by bash/gen-contract.py）：
 * 展示知识库统计（stats()，返回结构不确定，逐字段判空兼容展示）、
 * 支持文档导入（ingest，经 rag-form 弹窗）、语义检索（search()）与文档删除（deleteDocument({ documentId })）。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import { Page, useYDSZModal } from '@ydsz/common-ui';
import {
  ElButton, ElDescriptions, ElDescriptionsItem, ElInput, ElInputNumber,
  ElMessage, ElMessageBox, ElStatistic, ElTable, ElTableColumn,
} from 'element-plus';
import { computed, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { deleteDocument, search, stats } from '#/api/rag';
import type { RagQueryDTO } from '#/api/models';
import RagForm from './rag-form.vue';

defineOptions({ name: 'RagManagement' });

const { t } = useI18n();

/** 知识库统计（后端返回结构不确定） */
const statsData = ref<Record<string, unknown>>({});
const statsLoading = ref(false);
/** 检索条件与结果 */
const queryForm = ref<RagQueryDTO>({ query: '', topK: 10, minScore: 0 });
const searchRows = ref<Record<string, unknown>[]>([]);
const searchLoading = ref(false);

const [RagFormModal, ragFormApi] = useYDSZModal({ connectedComponent: RagForm });

/** 统计条目（v-for 渲染用） */
const statsEntries = computed<[string, unknown][]>(() => Object.entries(statsData.value));
/** 统计卡片（取前 4 项） */
const statCards = computed(() =>
  statsEntries.value.slice(0, 4).map(([key, value]) => ({ key, label: key, value: displayValue(value) })),
);

/**
 * 将未知取值安全转为展示字符串，空值统一显示为 '-'。
 *
 * @param value - 待展示的未知取值
 * @returns 展示字符串
 */
function displayValue(value: unknown): string {
  if (value === null || value === undefined) { return '-'; }
  if (typeof value === 'object') {
    try { return JSON.stringify(value); } catch { return String(value); }
  }
  return String(value);
}

/** 加载知识库统计 */
async function handleLoadStats() {
  statsLoading.value = true;
  try {
    const res = await stats();
    statsData.value = res && typeof res === 'object' ? (res as Record<string, unknown>) : {};
  } finally { statsLoading.value = false; }
}

/** 打开文档导入弹窗 */
function handleOpenIngest() { ragFormApi.open(); }

/** 语义检索（search()），结果结构不确定，兼容数组与常见列表字段 */
async function handleSearch() {
  const query = queryForm.value.query?.trim() ?? '';
  if (!query) { ElMessage.warning('请输入检索内容'); return; }
  searchLoading.value = true;
  try {
    const res = await search({ ...queryForm.value, query });
    searchRows.value = normalizeRows(res);
  } finally { searchLoading.value = false; }
}

/**
 * 归一化检索结果：数组直接使用，对象兼容 hits/results/documents/items/list/data 字段，其余作为单条。
 *
 * @param res - search() 返回的未知结构
 * @returns 行数据数组
 */
function normalizeRows(res: unknown): Record<string, unknown>[] {
  if (Array.isArray(res)) { return res as Record<string, unknown>[]; }
  if (res && typeof res === 'object') {
    const obj = res as Record<string, unknown>;
    const listField = ['hits', 'results', 'documents', 'items', 'list', 'data'].find((key) => Array.isArray(obj[key]));
    if (listField) { return obj[listField] as Record<string, unknown>[]; }
    return [obj];
  }
  return [];
}

/** 删除文档（deleteDocument({ documentId })） */
async function handleDelete(row: Record<string, unknown>) {
  const documentId = typeof row?.documentId === 'string' ? row.documentId : '';
  try {
    await ElMessageBox.confirm(`确定删除文档「${displayValue(row?.documentTitle ?? row?.title)}」吗？`, '删除确认', { type: 'warning' });
    await deleteDocument({ documentId });
    ElMessage.success('删除成功');
    handleLoadStats();
  } catch { /* 用户取消或请求失败，保持现状 */ }
}

onMounted(() => { handleLoadStats(); });
</script>
<template>
  <Page>
    <div class="mb-3 flex flex-wrap gap-3">
      <div v-for="card in statCards" :key="card.key" class="w-40 rounded-md border p-3">
        <div class="mb-1 truncate text-sm text-gray-500">{{ card.label }}</div>
        <ElStatistic :value="Number(card.value) || 0" />
      </div>
    </div>
    <ElDescriptions v-if="statsEntries.length > statCards.length" :column="2" border class="mb-3">
      <ElDescriptionsItem v-for="[key, value] in statsEntries.slice(statCards.length)" :key="key" :label="key">
        {{ displayValue(value) }}
      </ElDescriptionsItem>
    </ElDescriptions>
    <div class="mb-3 flex items-center gap-2">
      <ElButton type="primary" :loading="statsLoading" @click="handleLoadStats">刷新统计</ElButton>
      <ElButton type="success" @click="handleOpenIngest">导入文档</ElButton>
    </div>
    <div class="mb-3 flex flex-wrap items-center gap-2 rounded-md border p-3">
      <ElInput v-model="queryForm.query" placeholder="输入检索内容" clearable class="w-72" @keyup.enter="handleSearch" />
      <span class="text-sm text-gray-500">TopK</span>
      <ElInputNumber v-model="queryForm.topK" :min="1" :max="100" class="w-24" />
      <span class="text-sm text-gray-500">最小得分</span>
      <ElInputNumber v-model="queryForm.minScore" :min="0" :max="1" :step="0.1" class="w-24" />
      <ElButton type="primary" :loading="searchLoading" @click="handleSearch">检索</ElButton>
    </div>
    <ElTable :data="searchRows" border stripe height="360">
      <ElTableColumn prop="id" label="ID" min-width="180" show-overflow-tooltip />
      <ElTableColumn prop="documentId" label="文档ID" min-width="180" show-overflow-tooltip />
      <ElTableColumn prop="documentTitle" label="标题" min-width="180" show-overflow-tooltip />
      <ElTableColumn prop="title" label="标题(兼容)" min-width="160" show-overflow-tooltip />
      <ElTableColumn prop="content" label="内容" min-width="320" show-overflow-tooltip />
      <ElTableColumn prop="score" label="得分" width="100" />
      <ElTableColumn prop="source" label="来源" min-width="140" show-overflow-tooltip />
      <ElTableColumn :label="t('common.actions')" width="100" fixed="right">
        <template #default="{ row }">
          <ElButton size="small" link type="danger" @click="handleDelete(row)">{{ t('common.delete') }}</ElButton>
        </template>
      </ElTableColumn>
    </ElTable>
    <RagFormModal @success="handleLoadStats" />
  </Page>
</template>