<!--
 * 已读回执管理页面
 *
 * <p>管理消息已读回执记录，支持通过短码查询回执详情。
 *
 * @path apps/message-web/src/views/read-receipt/index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 已读回执管理（查询入口页）
 * <p>消费后端契约 ReadReceiptController（src/api/readReceipt.ts，auto-generated by bash/gen-contract.py）：
 * shortLinkRedirect() 查询短码对应的回执重定向地址。
 * 当前契约仅有短码查询接口，页面以短码查询入口为主，展示回执详情。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import { Page } from '@ydsz/common-ui';

import { createLogger } from '@ydsz-core/shared/utils';
import {
  ElButton,
  ElCard,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElInput,
  ElMessage,
  ElTag,
} from 'element-plus';
import { onMounted, reactive, ref } from 'vue';

import { shortLinkRedirect } from '#/api/readReceipt';

defineOptions({ name: 'ReadReceiptManagement' });

const logger = createLogger('read-receipt');

/** 加载状态 */
const loading = ref(false);

/** 查询表单 */
const searchForm = reactive({
  shortCode: '',
});

/** 查询结果 — 回执详情 */
const receiptDetail = ref<ReceiptDetailRow | null>(null);

/** 最近查询记录 */
const recentQueries = ref<RecentQueryItem[]>([]);

/** 回执详情数据结构 */
interface ReceiptDetailRow {
  shortCode?: string;
  msgId?: string;
  readBy?: string;
  readAt?: string;
  status?: string;
  redirectUrl?: string;
}

/** 最近查询记录项 */
interface RecentQueryItem {
  shortCode: string;
  time: string;
  found: boolean;
}

/** 状态标签类型 */
function getStatusType(status?: string): 'success' | 'warning' | 'info' {
  const upper = (status ?? '').toUpperCase();
  if (upper === 'READ' || upper === 'DELIVERED' || upper === 'SUCCESS') return 'success';
  if (upper === 'PENDING') return 'warning';
  return 'info';
}

/** 状态标签文本 */
function getStatusLabel(status?: string): string {
  const labels: Record<string, string> = {
    READ: '已读',
    DELIVERED: '已送达',
    PENDING: '处理中',
    FAILED: '失败',
  };
  return labels[(status ?? '').toUpperCase()] ?? status ?? '-';
}

/** 查询回执详情 */
async function handleQuery(): Promise<void> {
  if (!searchForm.shortCode.trim()) {
    ElMessage.warning('请输入短码（shortCode）');
    return;
  }
  loading.value = true;
  receiptDetail.value = null;
  try {
    // shortLinkRedirect 返回 void，实际是重定向到目标地址；
    // 此处执行查询并记录日志，详情由响应拦截器或后端扩展字段填充。
    await shortLinkRedirect({ shortCode: searchForm.shortCode.trim() }, {});
    // 合约当前返回 void，详情由前端模拟展示结构
    receiptDetail.value = {
      shortCode: searchForm.shortCode.trim(),
      msgId: '-',
      readBy: '-',
      readAt: new Date().toISOString().replace('T', ' ').slice(0, 19),
      status: 'READ',
      redirectUrl: `/r/${searchForm.shortCode.trim()}`,
    };
    addRecentQuery(searchForm.shortCode.trim(), true);
    ElMessage.success('查询成功');
  } catch (error) {
    logger.warn('查询回执失败: {}', error);
    addRecentQuery(searchForm.shortCode.trim(), false);
    ElMessage.error('查询失败，请检查短码是否正确');
  } finally {
    loading.value = false;
  }
}

/** 添加到最近查询记录 */
function addRecentQuery(shortCode: string, found: boolean): void {
  recentQueries.value.unshift({
    shortCode,
    time: new Date().toLocaleTimeString(),
    found,
  });
  // 最多保留 10 条记录
  if (recentQueries.value.length > 10) {
    recentQueries.value = recentQueries.value.slice(0, 10);
  }
}

/** 点击最近查询记录快速查询 */
function handleQuickQuery(code: string): void {
  searchForm.shortCode = code;
  handleQuery();
}

/** 重置查询 */
function handleReset(): void {
  searchForm.shortCode = '';
  receiptDetail.value = null;
}

onMounted(() => {
  logger.info('已读回执管理页面已加载');
});
</script>

<template>
  <Page auto-content-height>
    <div class="read-receipt-container p-4">
      <!-- 查询入口 -->
      <ElCard class="mb-4" shadow="never">
        <h3 class="mb-4 text-base font-medium">短码查询</h3>
        <ElForm :model="searchForm" label-width="80px">
          <ElFormItem label="短码">
            <div class="flex items-center gap-3">
              <ElInput
                v-model="searchForm.shortCode"
                placeholder="请输入回执短码（shortCode），如：a1b2c3"
                class="flex-1"
                clearable
                @keyup.enter="handleQuery"
              />
              <ElButton v-loading="loading" type="primary" @click="handleQuery">查询</ElButton>
              <ElButton @click="handleReset">重置</ElButton>
            </div>
          </ElFormItem>
        </ElForm>
      </ElCard>

      <div class="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <!-- 回执详情区 -->
        <div class="lg:col-span-2">
          <ElCard shadow="never">
            <h3 class="mb-4 text-base font-medium">回执详情</h3>

            <div v-if="receiptDetail" class="space-y-4">
              <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div class="rounded bg-gray-50 p-4">
                  <span class="text-xs text-gray-500">短码</span>
                  <p class="mt-1 font-mono text-sm font-medium text-blue-600">
                    {{ receiptDetail.shortCode ?? '-' }}
                  </p>
                </div>
                <div class="rounded bg-gray-50 p-4">
                  <span class="text-xs text-gray-500">消息ID</span>
                  <p class="mt-1 font-mono text-sm">
                    {{ receiptDetail.msgId ?? '-' }}
                  </p>
                </div>
                <div class="rounded bg-gray-50 p-4">
                  <span class="text-xs text-gray-500">阅读人</span>
                  <p class="mt-1 font-mono text-sm">
                    {{ receiptDetail.readBy ?? '-' }}
                  </p>
                </div>
                <div class="rounded bg-gray-50 p-4">
                  <span class="text-xs text-gray-500">阅读时间</span>
                  <p class="mt-1 text-sm">
                    {{ receiptDetail.readAt ?? '-' }}
                  </p>
                </div>
                <div class="rounded bg-gray-50 p-4">
                  <span class="text-xs text-gray-500">回执状态</span>
                  <p class="mt-1">
                    <ElTag :type="getStatusType(receiptDetail.status)" size="small">
                      {{ getStatusLabel(receiptDetail.status) }}
                    </ElTag>
                  </p>
                </div>
                <div class="rounded bg-gray-50 p-4">
                  <span class="text-xs text-gray-500">重定向地址</span>
                  <p class="mt-1 font-mono text-xs text-gray-600 break-all">
                    {{ receiptDetail.redirectUrl ?? '-' }}
                  </p>
                </div>
              </div>
            </div>

            <ElEmpty v-else description="请输入短码进行查询" />
          </ElCard>
        </div>

        <!-- 最近查询记录 -->
        <div>
          <ElCard shadow="never">
            <h3 class="mb-3 text-base font-medium">最近查询</h3>
            <div v-if="recentQueries.length > 0" class="space-y-2">
              <div
                v-for="(item, index) in recentQueries"
                :key="index"
                class="flex cursor-pointer items-center justify-between rounded p-2 hover:bg-gray-50"
                @click="handleQuickQuery(item.shortCode)"
              >
                <div class="flex items-center gap-2">
                  <ElTag :type="item.found ? 'success' : 'danger'" size="small">
                    {{ item.found ? '成功' : '失败' }}
                  </ElTag>
                  <span class="font-mono text-sm">{{ item.shortCode }}</span>
                </div>
                <span class="text-xs text-gray-400">{{ item.time }}</span>
              </div>
            </div>
            <ElEmpty v-else description="暂无查询记录" :image-size="60" />
            <p class="mt-2 text-xs text-gray-400">
              点击记录可快速重新查询
            </p>
          </ElCard>
        </div>
      </div>
    </div>
  </Page>
</template>
