<!--
 * 公司管理页面 — 展示公司列表（左侧组织树导航 + 右侧列表），支持新增/编辑/删除公司信息
 *
 * @path apps\userinfo-web\src\views\system\company\index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 公司（列表页）
 * <p>公司（{@code ydsz_company}）的列表页，消费后端契约 CompanyController
 * （src/api/company.ts，auto-generated by bash/gen-contract.py）：
 * 左侧以 tree() 展示公司层级树用于按父公司筛选，右侧以 list() 展示公司列表
 * （非分页，query 返回 { items, total: items.length }），支持新增/编辑/删除。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import type { VxeTableGridOptions } from '@ydsz/plugins/vxe-table';

import { Page, useYDSZModal } from '@ydsz/common-ui';

import { ElButton, ElMessage, ElMessageBox, ElTag, ElTree } from 'element-plus';
import { h, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { createLogger } from '@YDSZ-core/shared/utils';

import { useYDSZVxeGrid } from '#/adapter/vxe-table';
import { list, remove, tree } from '#/api/company';
import type { CompanyTreeVO, CompanyVO } from '#/api/models';

import CompanyForm from './company-form.vue';

defineOptions({ name: 'CompanyManagement' });

const logger = createLogger('userinfo-company');
const { t } = useI18n();

/** 判断公司状态是否启用（兼容字符串 '1'/'ENABLED' 等取值） */
function isEnabled(status?: string): boolean {
  return status === '1' || status === 'ENABLED' || status === 'true';
}

/** 公司层级树（来自 tree()），用于左侧导航与表单上级公司选择 */
const companyTree = ref<CompanyTreeVO[]>([]);

/** 当前选中的父公司 ID（空串表示不过滤） */
const filterParentId = ref('');

async function loadTree() {
  try {
    companyTree.value = (await tree()) ?? [];
  } catch (error) {
    logger.warn('加载组织树失败: {}', error);
  }
}

onMounted(loadTree);

const gridOptions: VxeTableGridOptions<CompanyVO> = {
  columns: [
    { type: 'seq', width: 50, title: t('page.rowIndex') },
    { field: 'companyName', title: t('page.companyName'), minWidth: 180 },
    { field: 'companyCode', title: t('page.companyCode'), width: 140 },
    { field: 'contactPerson', title: t('company.contactPerson'), width: 100 },
    { field: 'contactPhone', title: t('company.contactPhone'), width: 130 },
    { field: 'address', title: t('company.address'), minWidth: 200 },
    {
      field: 'status',
      title: t('page.status'),
      width: 80,
      slots: {
        default: ({ row }) => {
          const enable = isEnabled(row.status);
          return h(
            ElTag,
            { type: enable ? 'success' : 'danger', size: 'small' },
            () => (enable ? t('page.enabled') : t('page.disabled')),
          );
        },
      },
    },
    {
      field: 'action',
      title: t('page.operation'),
      width: 160,
      fixed: 'right',
      slots: {
        default: ({ row }) => {
          return h('div', { class: 'flex gap-1' }, [
            h(
              ElButton,
              { size: 'small', link: true, type: 'primary', onClick: () => handleEdit(row) },
              () => t('page.edit'),
            ),
            h(
              ElButton,
              { size: 'small', link: true, type: 'danger', onClick: () => handleDelete(row) },
              () => t('page.delete'),
            ),
          ]);
        },
      },
    },
  ],
  height: 'auto',
  proxyConfig: {
    ajax: {
      query: async () => {
        const items = (await list()) ?? [];
        const filtered = filterParentId.value
          ? items.filter((item) => item.parentId === filterParentId.value)
          : items;
        return { items: filtered, total: filtered.length };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, zoom: true },
};

const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });

// ========== 组织树导航 ==========
function handleTreeClick(node: CompanyTreeVO) {
  filterParentId.value = node.id ?? '';
  gridApi.query();
}

function handleTreeClear() {
  filterParentId.value = '';
  gridApi.query();
}

// ========== 表单弹窗 ==========
const [CompanyFormModal, companyFormApi] = useYDSZModal({ connectedComponent: CompanyForm });

function handleAdd() {
  companyFormApi.setData({ treeData: companyTree.value });
  companyFormApi.open();
}

function handleEdit(row: CompanyVO) {
  companyFormApi.setData({ record: row, treeData: companyTree.value });
  companyFormApi.open();
}

// ========== 删除 ==========
async function handleDelete(row: CompanyVO) {
  if (!row.id) return;
  // 步骤1：确认弹窗（用户取消直接返回）
  try {
    await ElMessageBox.confirm(
      t('company.deleteCompanyConfirm', { companyName: row.companyName ?? '' }),
      t('page.confirmDelete'),
      { type: 'warning' },
    );
  } catch {
    return; // 用户主动取消删除操作
  }
  // 步骤2：执行删除 API（失败提示由 errorMessageResponseInterceptor 统一处理）
  try {
    await remove({ id: row.id });
    ElMessage.success(t('page.deleteSuccess'));
    gridApi.query();
    loadTree();
  } catch (error) {
    logger.warn('删除公司失败: {}', error);
  }
}
</script>

<template>
  <Page auto-content-height>
    <div class="flex gap-4 p-4">
      <div class="w-60 shrink-0">
        <div class="mb-2 flex items-center justify-between">
          <span class="text-sm font-semibold">{{ t('company.orgStructure') }}</span>
          <ElButton link type="primary" size="small" @click="handleTreeClear">{{ t('company.all') }}</ElButton>
        </div>
        <ElTree
          :data="companyTree"
          :props="{ label: 'companyName', children: 'children' }"
          node-key="id"
          default-expand-all
          highlight-current
          @node-click="handleTreeClick"
        />
      </div>
      <div class="min-w-0 flex-1">
        <Grid :table-title="t('company.companyManagement')">
          <template #toolbar-tools>
            <ElButton type="primary" @click="handleAdd">{{ t('company.createCompany') }}</ElButton>
          </template>
        </Grid>
      </div>
    </div>
    <CompanyFormModal @success="gridApi.query()" />
  </Page>
</template>