<!--
 * 抄送中心独立页面
 *
 * 展示当前用户的抄送列表（分页），支持查看原流程实例、标记已读、全部已读。
 * 消费后端 FlowCcController 契约（auto-generated by bash/gen-contract.py）。
 *
 * @path apps/workflow-web/src/views/cc/index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 抄送中心（列表页）
 * <p>消费后端契约 FlowCcController（src/api/flowCc.ts，auto-generated by bash/gen-contract.py）：
 * pageCc() 分页查询抄送列表，ccMarkRead() 标记单条已读，ccMarkAllRead() 全部已读，
 * ccUnreadCount() 获取未读数。
 *
 * @author ydsz-team
 * @since 1.0.0
*/
import type { VxeTableGridOptions } from '@ydsz/plugins/vxe-table';

import { Page } from '@ydsz/common-ui';

import { YdBadge, YdButton, YdConfirm } from '@ydsz-core/ydsz-ui';
import { h, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';

import { useYDSZVxeGrid } from '#/adapter/vxe-table';
import { ccMarkAllRead, ccMarkRead, ccUnreadCount, pageCc } from '#/api/flowCc';
import type { FlowCcQuery, FlowCcVO } from '#/api/models';
import { $t } from '#/locales';

import { createLogger } from '@ydsz-core/shared/utils';

const logger = createLogger('workflow-cc');

defineOptions({ name: 'FlowCcCenter' });

const router = useRouter();

/** 未读抄送数量 */
const unreadCount = ref<number>(0);

/** 行类型 */
type CcRow = FlowCcVO & { id?: string };

/**
 * 加载未读数量
 */
async function loadUnreadCount(): Promise<void> {
  try {
    const count = await ccUnreadCount();
    unreadCount.value = count ?? 0;
  } catch (e) {
    logger.warn('加载未读数量失败', e);
  }
}

/**
 * 已读状态标签
 */
function getReadStatusVariant(readStatus?: string): 'default' | 'destructive' | 'outline' | 'secondary' {
  const s = (readStatus ?? '').toUpperCase();
  if (s === 'READ') return 'default';
  if (s === 'UNREAD') return 'destructive';
  return 'secondary';
}

/**
 * 已读状态中文
 */
function getReadStatusLabel(readStatus?: string): string {
  const s = (readStatus ?? '').toUpperCase();
  if (s === 'READ') return '已读';
  if (s === 'UNREAD') return '未读';
  return readStatus ?? '-';
}

const gridOptions: VxeTableGridOptions<CcRow> = {
  columns: [
    { type: 'seq', width: 50, title: $t('wf.seq') },
    { field: 'flowName', title: $t('wf.flowName'), width: 160, showOverflow: 'tooltip' },
    { field: 'businessKey', title: $t('wf.businessNo'), width: 140, showOverflow: 'tooltip' },
    { field: 'nodeName', title: '抄送节点', width: 140, showOverflow: 'tooltip' },
    { field: 'ccType', width: 120, title: '抄送类型', showOverflow: 'tooltip' },
    { field: 'title', width: 160, title: t('wf.title'), showOverflow: 'tooltip' },
    {
      field: 'readStatus',
      title: $t('status'),
      width: 90,
      slots: {
        default: ({ row }) =>
          h(YdBadge, { variant: getReadStatusVariant(row.readStatus) }, () => getReadStatusLabel(row.readStatus)),
      },
    },
    { field: 'triggerUserName', title: '发起人', width: 120 },
    { field: 'createdAt', title: $t('common.createTime'), width: 170 },
    {
      field: 'action',
      title: $t('cc.action') || $t('common.actions'),
      width: 220,
      fixed: 'right',
      slots: {
        default: ({ row }) => {
          const r = row as CcRow;
          return h('div', { class: 'flex gap-1' }, [
            h(
              YdButton,
              {
                size: 'sm',
                variant: 'link',
                'aria-label': $t('cc.viewInstance'),
                onClick: () => handleViewInstance(r),
              },
              () => $t('cc.viewInstance'),
            ),
            h(
              YdButton,
              {
                size: 'sm',
                variant: 'link',
                disabled: (r.readStatus ?? '').toUpperCase() === 'READ',
                'aria-label': $t('cc.markRead'),
                onClick: () => handleMarkRead(r),
              },
              () => $t('cc.markRead'),
            ),
          ]);
        },
      },
    },
  ],
  height: 'auto',
  pagerConfig: { pageSize: 20, pageSizes: [10, 20, 50, 100] },
  proxyConfig: {
    ajax: {
      query: async (_params, formValues) => {
        const query: FlowCcQuery = {
          readStatus: formValues?.readStatus ?? undefined,
          flowCode: formValues?.flowCode ?? undefined,
        };
        const data = await pageCc(query);
        return { items: (data ?? []) as CcRow[], total: (data ?? []).length };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, search: true, zoom: true },
  formConfig: {
    enabled: true,
    items: [
      {
        field: 'flowCode',
        title: t('wf.flowCode'),
        itemRender: { name: 'YdInput', props: { placeholder: t('wf.inputFlowCode') || '请输入流程编码' } },
      },
      {
        field: 'readStatus',
        title: '已读状态',
        itemRender: {
          name: 'YdSelectBase',
          props: {
            clearable: true,
            options: [
              { label: '全部', value: '' },
              { label: '未读', value: 'UNREAD' },
              { label: '已读', value: 'READ' },
            ],
          },
        },
      },
    ],
  },
};

const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });

/**
 * 查看原流程实例
 */
function handleViewInstance(row: CcRow): void {
  if (row.instanceId) {
    router.push({ path: '/flow/instance', query: { instanceId: row.instanceId } });
  }
}

/**
 * 标记单条已读
 */
async function handleMarkRead(row: CcRow): Promise<void> {
  if (!row.id) return;
  try {
    await ccMarkRead({ id: row.id });
    showToast.success($t('cc.markRead') + $t('common.operationSuccess'));
    gridApi.query();
    await loadUnreadCount();
  } catch (e) {
    logger.warn('标记已读失败', e);
  }
}

/**
 * 全部已读
 */
async function handleMarkAllRead(): Promise<void> {
  try {
    await YdConfirm(
      $t('cc.confirmReadAll'),
      $t('cc.markRead'),
      { type: 'warning' },
    );
  } catch {
    logger.debug('用户取消全部已读');
    return;
  }
  try {
    const count = await ccMarkAllRead();
    showToast.success(`${$t('cc.markRead')}${$t('common.operationSuccess')} (${count ?? 0})`);
    gridApi.query();
    await loadUnreadCount();
  } catch (e) {
    logger.warn('全部已读失败', e);
  }
}

// 初始加载未读数量
onMounted(() => {
  void loadUnreadCount();
});
</script>

<template>
  <Page auto-content-height>
    <div class="space-y-4">
      <!-- 头部 -->
      <div class="flex items-center justify-between">
        <h2 class="text-lg font-semibold text-text-primary">
          {{ $t('cc.title') || '抄送中心' }}
          <YdBadge
            v-if="unreadCount > 0"
            variant="destructive"
            class="ml-2"
          >
            {{ unreadCount }} {{ $t('cc.unread') || '未读' }}
          </YdBadge>
        </h2>
        <YdButton
          variant="outline"
          :disabled="unreadCount === 0"
          @click="handleMarkAllRead"
        >
          {{ $t('cc.readAll') || '全部已读' }}
        </YdButton>
      </div>

      <!-- 数据表格 -->
      <Grid :table-title="$t('cc.title') || '抄送列表'">
        <template #toolbar-tools>
          <YdButton variant="outline" @click="loadUnreadCount">
            {{ $t('common.refresh') || '刷新' }}
          </YdButton>
        </template>
      </Grid>
    </div>
  </Page>
</template>
