<!--
 * 消息批量发送列表页组件
 *
 * 视图模式：卡片视图（默认）/ 表格视图 可切换。
 *  - 卡片视图：YdCardGrid + YdEntityCard，承载批次可视化展示；
 *  - 表格视图：VxeTable，保持原有兼容视图。
 *
 * @path apps/message-web/src/views/batch/index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 消息批量发送（列表页）
 * <p>消费后端契约 BatchController（src/api/batch.ts，auto-generated by bash/gen-contract.py）：
 * 本地维护已提交的批次列表（工具栏「新建批量」提交后把 batchId 存入列表），
 * 每行通过「进度」按钮打开抽屉，先取 getProgress({batchId}) 快照，再订阅
 * SSE（{@code /api/message/batch/progress/{batchId}/sse}）实时刷新 progressPercent 等指标。
 * 契约无批次列表查询接口，故列表为本地快照，刷新页面后仅保留本次会话内提交的批次。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import type { VxeTableGridOptions } from '@ydsz/plugins/vxe-table';
import { YdCardGrid, YdEmptyState, YdEntityCard, YdStatusBadge } from '@ydsz-core/shadcn-ui';
import { Page, useYdModal } from '@ydsz/common-ui';
import { Badge, Button } from '@ydsz-core/ui-kit/shadcn-ui';
// SKIP: ElDrawer/ElDescriptions/ElDescriptionsItem/ElProgress 不在 shadcn 映射表，保留 EP
import {
  ElDescriptions,
  ElDescriptionsItem,
  ElDrawer,
  ElProgress,
} from 'element-plus';
import { h, onBeforeUnmount, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { useYDSZVxeGrid } from '#/adapter/vxe-table';
import { getProgress } from '#/api/batch';
import type { BatchProgressDTO as BatchProgressVO, MsgBatchVO } from '#/api/models';
import { openSseStream } from '#/utils/sse-client';
import type { SseEventHandlers } from '#/utils/sse-client';

import BatchForm from './batch-form.vue';

defineOptions({ name: 'BatchManagement' });

const { t } = useI18n();

type ViewMode = 'card' | 'table';
const viewMode = ref<ViewMode>('card');

/** Badge variant 映射（EP type → shadcn variant） */
function mapTagVariant(type: 'success' | 'danger' | 'warning' | 'info'): 'default' | 'destructive' | 'outline' | 'secondary' {
  if (type === 'danger') return 'destructive';
  if (type === 'warning') return 'outline';
  if (type === 'info') return 'secondary';
  return 'default';
}

/** 状态列 Tag 类型映射（未知值按 info 展示） */
function getStatusType(status?: string): 'success' | 'danger' | 'warning' | 'info' {
  const upper = (status ?? '').toUpperCase();
  if (['SUCCESS', 'COMPLETED', 'DONE'].includes(upper)) return 'success';
  if (['FAILED', 'ERROR', 'PARTIAL'].includes(upper)) return 'danger';
  if (['RUNNING', 'PROCESSING', 'PENDING', 'QUEUED'].includes(upper)) return 'warning';
  return 'info';
}

/** 批次状态 → YdStatusBadge 语义值 */
function resolveBatchStatus(status?: string): 'running' | 'success' | 'failed' | 'draft' {
  const upper = (status ?? '').toUpperCase();
  if (['SUCCESS', 'COMPLETED', 'DONE'].includes(upper)) return 'success';
  if (['FAILED', 'ERROR', 'PARTIAL'].includes(upper)) return 'failed';
  if (['RUNNING', 'PROCESSING', 'PENDING', 'QUEUED'].includes(upper)) return 'running';
  return 'draft';
}

/** 是否已进入终态（用于进度条判定） */
function statusDone(status?: string): boolean {
  return getStatusType(status) === 'success';
}

/** 本地已提交批次快照 */
const batchRows = ref<MsgBatchVO[]>([]);

const gridOptions: VxeTableGridOptions<MsgBatchVO> = {
  columns: [
    { type: 'seq', width: 50, title: t('common.seq') },
    { field: 'batchId', title: '批次ID', width: 220 },
    { field: 'batchName', title: '批次名称', width: 160 },
    { field: 'channel', title: '通道', width: 100 },
    { field: 'templateCode', title: t('templateCode'), width: 140 },
    { field: 'bizType', title: '业务类型', width: 110 },
    {
      field: 'status',
      title: t('common.status'),
      width: 100,
      slots: {
        default: ({ row }) =>
          h(Badge, { variant: mapTagVariant(getStatusType(row.status)) }, () => row.status ?? '-'),
      },
    },
    {
      field: 'action',
      title: t('common.actions'),
      width: 100,
      fixed: 'right',
      slots: {
        default: ({ row }) =>
          h(Button, { size: 'sm', variant: 'link', onClick: () => handleProgress(row) }, () => '进度'),
      },
    },
  ],
  height: 'auto',
  proxyConfig: {
    ajax: {
      query: async (_page, formValues) => {
        const keyword = String((formValues as Record<string, unknown>)?.batchName ?? '').trim();
        const items = keyword
          ? batchRows.value.filter((row) => (row.batchName ?? '').includes(keyword))
          : batchRows.value;
        return { items, total: items.length };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, search: true, zoom: true },
  formConfig: {
    enabled: true,
    items: [
      { field: 'batchName', title: '批次名称', itemRender: { name: 'Input', props: { placeholder: '批次名称' } } },
    ],
  },
};

const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });
const [BatchFormModal, batchFormApi] = useYdModal({ connectedComponent: BatchForm });

/** 视图切换 */
function handleViewModeChange(mode: ViewMode): void {
  viewMode.value = mode;
}

/** 刷新列表（兼容两视图） */
function handleRefresh(): void {
  gridApi.query();
}

function handleAdd(): void {
  batchFormApi.open();
}

/** 提交成功后把批次写入本地列表（按 batchId 去重） */
function handleBatchCreated(batch: MsgBatchVO): void {
  if (!batch.batchId) return;
  if (!batchRows.value.some((row) => row.batchId === batch.batchId)) {
    batchRows.value.unshift(batch);
  }
  handleRefresh();
}

/** 进度抽屉状态 */
const progressVisible = ref(false);
const progressLoading = ref(false);
const progressData = ref<BatchProgressVO | null>(null);
/** SSE 连接状态（idle/connecting/live/closed/error） */
const sseState = ref<'idle' | 'connecting' | 'live' | 'closed' | 'error'>('idle');
/** 当前订阅的批次 ID（用于抽屉关闭时清理与重复打开去重） */
let subscribedBatchId = '';
let closeSse = (() => undefined) as () => void;

/** SSE 连接状态文案映射 */
const sseStateText: Record<string, string> = {
  closed: '已结束',
  connecting: '连接中…',
  error: '连接异常',
  idle: '未连接',
  live: '实时推送中',
};

/** 关闭当前 SSE 流并复位连接状态（已结束/异常时保持终态文案） */
function stopSseStream(): void {
  closeSse();
  closeSse = () => undefined;
  if (subscribedBatchId) subscribedBatchId = '';
  if (sseState.value === 'connecting' || sseState.value === 'live') {
    sseState.value = 'closed';
  }
}

/** 合并 SSE 推送的进度增量（服务端按快照或字段级增量推送均可兼容） */
function applyProgressPatch(patch: Record<string, unknown>): void {
  if (!progressData.value) return;
  progressData.value = { ...progressData.value, ...(patch as Partial<BatchProgressVO>) };
}

/** 订阅批次 SSE 实时进度 */
function subscribeSseProgress(batchId: string): void {
  const controller = new AbortController();
  const handlers: SseEventHandlers & { signal?: AbortSignal } = {
    signal: controller.signal,
    onOpen: () => {
      sseState.value = 'live';
    },
    onEvent: (eventName: string, data: Record<string, unknown> | null) => {
      if (!data) return;
      if (eventName === 'progress') {
        applyProgressPatch(data);
      } else if (eventName === 'complete') {
        applyProgressPatch(data);
        sseState.value = 'closed';
        controller.abort();
      }
    },
    onError: () => {
      sseState.value = 'error';
    },
    onClose: () => {
      if (sseState.value === 'live' || sseState.value === 'connecting') {
        sseState.value = 'closed';
      }
    },
  };
  closeSse = openSseStream(`/api/message/batch/progress/${batchId}/sse`, handlers);
}

/** 手动刷新进度快照（SSE 异常时兜底） */
async function refreshProgressSnapshot(): Promise<void> {
  if (!subscribedBatchId) return;
  try {
    const res = await getProgress({ batchId: subscribedBatchId });
    progressData.value = res;
  } catch {
    // 错误提示由请求拦截器统一处理
  }
}

async function handleProgress(row: MsgBatchVO): Promise<void> {
  if (!row.batchId) return;
  stopSseStream();
  progressLoading.value = true;
  try {
    const res = await getProgress({ batchId: row.batchId });
    progressData.value = res;
    subscribedBatchId = row.batchId;
    progressVisible.value = true;
    sseState.value = 'connecting';
    subscribeSseProgress(row.batchId);
  } catch {
    // 错误提示由请求拦截器统一处理
  } finally {
    progressLoading.value = false;
  }
}

/** 关闭抽屉时断开 SSE，避免后台残留长连接 */
watch(progressVisible, (visible) => {
  if (!visible) stopSseStream();
});

onBeforeUnmount(() => {
  stopSseStream();
});
</script>

<template>
  <Page auto-content-height>
    <!-- 视图切换 + 工具栏 -->
    <div class="mb-4 flex items-center justify-between">
      <div class="flex items-center gap-1 rounded-lg border border-border-subtle bg-accent/50 p-1">
        <button
          class="rounded-md px-2.5 py-1 text-xs transition-colors"
          :class="viewMode === 'card' ? 'bg-surface-2 text-text-primary shadow-sm' : 'text-text-secondary hover:text-text-primary'"
          type="button"
          @click="handleViewModeChange('card')"
        >
          <svg
            class="mb-0.5 me-1 inline"
            fill="none"
            height="14"
            stroke="currentColor"
            viewBox="0 0 24 24"
            width="14"
          >
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="2.5"
              y="2.5"
            />
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="12.5"
              y="2.5"
            />
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="2.5"
              y="12.5"
            />
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="12.5"
              y="12.5"
            />
          </svg>
          卡片
        </button>
        <button
          class="rounded-md px-2.5 py-1 text-xs transition-colors"
          :class="viewMode === 'table' ? 'bg-surface-2 text-text-primary shadow-sm' : 'text-text-secondary hover:text-text-primary'"
          type="button"
          @click="handleViewModeChange('table')"
        >
          <svg
            class="mb-0.5 me-1 inline"
            fill="none"
            height="14"
            stroke="currentColor"
            stroke-width="1.8"
            viewBox="0 0 24 24"
            width="14"
          >
            <line
              x1="3"
              x2="21"
              y1="6.5"
              y2="6.5"
            />
            <line
              x1="3"
              x2="21"
              y1="12"
              y2="12"
            />
            <line
              x1="3"
              x2="21"
              y1="17.5"
              y2="17.5"
            />
          </svg>
          表格
        </button>
      </div>
      <Button @click="handleAdd">{{ t('common.create') }}</Button>
    </div>

    <!-- 表格视图 -->
    <Grid
      v-if="viewMode === 'table'"
      table-title="批量发送"
    />

    <!-- 卡片视图 -->
    <div
      v-else
      class="min-h-[400px]"
    >
      <YdCardGrid
        :is-empty="batchRows.length === 0"
        :is-loading="false"
      >
        <template #empty>
          <YdEmptyState
            description="创建批量发送任务后可查看发送进度和统计"
            preset="created"
            :action-text="t('common.create')"
            title="暂无批量任务"
            @action="handleAdd"
          />
        </template>
        <YdEntityCard
          v-for="item in batchRows"
          :key="item.batchId"
          :avatar-text="item.batchName"
          :avatar-variant="resolveBatchStatus(item.status) === 'running' ? 'blue' : (resolveBatchStatus(item.status) === 'success' ? 'primary' : 'neutral')"
          :code="item.batchId ?? undefined"
          :description="`${item.channel ?? ''} · ${item.templateCode ?? ''}`"
          class="transition-transform hover:-translate-y-0.5"
          @click="handleProgress(item)"
        >
          <template #status-badge>
            <YdStatusBadge
              :status="resolveBatchStatus(item.status)"
              :label="item.status ?? '待处理'"
              class="shrink-0"
            />
          </template>

          <template #meta>
            <div class="mt-3 text-xs text-text-tertiary">
              <div class="flex items-center justify-between">
                <span>业务类型: {{ item.bizType ?? '-' }}</span>
                <span>{{ item.createdAt ?? '' }}</span>
              </div>
            </div>
          </template>

          <template #actions>
            <Button
              size="sm"
              variant="link"
              @click.stop="handleProgress(item)"
            >
              查看进度
            </Button>
          </template>
        </YdEntityCard>
      </YdCardGrid>
    </div>

    <BatchFormModal @success="handleBatchCreated" />
    <ElDrawer v-model="progressVisible" title="批次进度" :size="440" v-loading="progressLoading">
      <template #header>
        <div class="flex w-full items-center justify-between pe-2">
          <span>{{ t('page.batchSend') }}</span>
          <span class="flex items-center gap-2">
            <Badge :variant="sseState === 'live' ? 'default' : sseState === 'error' ? 'destructive' : 'secondary'">
              {{ sseStateText[sseState] }}
            </Badge>
            <Button size="sm" variant="link" :disabled="!subscribedBatchId" @click="refreshProgressSnapshot">
              {{ t('common.refresh') }}
            </Button>
          </span>
        </div>
      </template>
      <ElDescriptions v-if="progressData" :column="1" border size="small">
        <ElDescriptionsItem label="批次ID">{{ progressData.batchId ?? '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="批次名称">{{ progressData.batchName ?? '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="通道">{{ progressData.channel ?? '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem :label="t('templateCode')">{{ progressData.templateCode ?? '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem :label="t('common.status')">{{ progressData.status ?? '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="进度">
          <ElProgress
            :percentage="Math.min(100, Number(progressData.progressPercent ?? 0))"
            :status="Number(progressData.progressPercent ?? 0) >= 100 || statusDone(progressData.status) ? 'success' : undefined"
            :stroke-width="12"
            class="w-56"
          />
        </ElDescriptionsItem>
        <ElDescriptionsItem label="总数">{{ progressData.total ?? 0 }}</ElDescriptionsItem>
        <ElDescriptionsItem label="已处理">{{ progressData.processed ?? 0 }}</ElDescriptionsItem>
        <ElDescriptionsItem label="成功">{{ progressData.success ?? 0 }}</ElDescriptionsItem>
        <ElDescriptionsItem label="失败">{{ progressData.failed ?? 0 }}</ElDescriptionsItem>
        <ElDescriptionsItem label="跳过">{{ progressData.skipped ?? 0 }}</ElDescriptionsItem>
        <ElDescriptionsItem label="错误信息">{{ progressData.errorMessage ?? '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="开始时间">{{ progressData.startedAt ?? '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="完成时间">{{ progressData.completedAt ?? '-' }}</ElDescriptionsItem>
      </ElDescriptions>
    </ElDrawer>
  </Page>
</template>
