/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * AiController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code AiController}，共 2 个端点。
 * <p>路径规范: /api/v1/nextwiki/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py nextwiki} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { Record<string, never> } from './models';

/**
 * generateSummary: POST /api/v1/nextwiki/ai/summary
 */
export function generateSummary(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/nextwiki/ai/summary`, data);
}

/**
 * getStatus: GET /api/v1/nextwiki/ai/status
 */
export function getStatus(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/nextwiki/ai/status`);
}
