/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * SpaceTemplateController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code SpaceTemplateController}，共 6 个端点。
 * <p>路径规范: /api/v1/nextwiki/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py nextwiki} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { SpaceTemplateDTO, SpaceVO } from './models';

/**
 * listTemplates: GET /api/v1/nextwiki/templates
 */
export function listTemplates(params: {
    category?: string;
  }): Promise<SpaceTemplateDTO[]> {
  return requestClient.get<SpaceTemplateDTO[]>(`/api/v1/nextwiki/templates`, { params });
}

/**
 * getTemplate: GET /api/v1/nextwiki/templates/{templateId}
 */
export function getTemplate(path: {
    templateId: string;
  }): Promise<SpaceTemplateDTO> {
  return requestClient.get<SpaceTemplateDTO>(`/api/v1/nextwiki/templates/${templateId}`);
}

/**
 * createTemplate: POST /api/v1/nextwiki/templates
 */
export function createTemplate(data: Record<string, unknown>): Promise<SpaceTemplateDTO> {
  return requestClient.post<SpaceTemplateDTO>(`/api/v1/nextwiki/templates`, data);
}

/**
 * updateTemplate: PUT /api/v1/nextwiki/templates/{templateId}
 */
export function updateTemplate(path: {
    templateId: string;
  }, data: Record<string, unknown>): Promise<SpaceTemplateDTO> {
  return requestClient.put<SpaceTemplateDTO>(`/api/v1/nextwiki/templates/${templateId}`, data);
}

/**
 * deleteTemplate: DELETE /api/v1/nextwiki/templates/{templateId}
 */
export function deleteTemplate(path: {
    templateId: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/v1/nextwiki/templates/${templateId}`);
}

/**
 * useTemplate: POST /api/v1/nextwiki/templates/{templateId}/use
 */
export function useTemplate(path: {
    templateId: string;
  }, data: Record<string, unknown>): Promise<SpaceVO> {
  return requestClient.post<SpaceVO>(`/api/v1/nextwiki/templates/${templateId}/use`, data);
}
