/* eslint-disable */
/* auto-generated by pnpm gen:api — DO NOT EDIT */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/v1/app/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queryByTimeRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit/operator/{operatorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queryByOperator"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit/action/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queryByAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit/trace/{traceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queryByTraceId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pageByCursor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["batchSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/key/{configKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/group/{configGroup}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigsByGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importConfigs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/version/{resourceKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listByResourceKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/version/{resourceKey}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/type/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/type/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/type/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item/type/{typeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listByType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item/children/{parentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item/tree/{typeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["buildTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/item/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["batchSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/version/{typeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listByTypeCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/version/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pageByTypeCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dict/version/{typeCode}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["init"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/init/dicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["initWithDicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/config/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/dict/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getDictItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/dict/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listDictItems"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/app/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant-plan/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant-plan/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant-plan/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant-plan/{planId}/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMenus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant-plan/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateMenus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variable/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variable/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variable/key/{variableKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variable/version/{resourceKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listByResourceKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variable/version/{resourceKey}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /**
         * @description 统一API返回结果封装类
         *
         *     用于前后端交互的标准返回格式，封装了响应码、消息、数据和时间戳。
         *
         *     响应结构：
         *
         *
         *     code: 响应码，A00000表示成功，其他表示失败
         *     msg: 响应消息
         *     data: 响应数据
         *     timestamp: 响应时间戳
         *
         *
         *     使用示例：
         *
         *     <pre>{@code
         *     // 返回成功
         *     return YdszResponse.success(user);
         *
         *     // 返回失败（走 i18n）
         *     return YdszResponse.error(YdszResultCode.NOT_FOUND);
         *     }</pre>
         *
         *     @param <T> 数据泛型
         */
        YdszResponse: {
            /** Format: int64 */
            serialVersionUID?: number;
            /** @description 返回编码 */
            code?: string;
            /** @description 返回信息 */
            msg?: string;
            /**
             * @description 返回数据
             *
             *     泛型类型 T 无法限定为 Serializable（API 响应可携带任意类型数据）， Java 序列化非主要序列化方式（项目使用 Jackson JSON），此处抑制编译器警告。
             */
            data?: Record<string, never>;
            /**
             * @description 链路追踪 ID。
             *
             *     首次调用 #getTraceId() 时从 RequestContext/MDC 懒解析， 避免批量/流式场景下每次构造响应对象都产生 MDC 读取开销。
             */
            traceId?: Record<string, never>;
            /**
             * @description 请求 ID（用于客户端/前端精准排障，单个请求唯一）。
             *
             *     volatile + 懒加载：为 `null` 时首次访问从 RequestContext#getRequestId() 解析并缓存。
             */
            requestId?: Record<string, never>;
            /**
             * @description 当前服务调用的 Span ID（W3C Trace Context span ID）。
             *
             *     volatile + 懒加载：traceId 被解析后若 spanId 为空， 自动调用 {@link
             *     com.njydsz.common.core.trace.TraceIdGenerator#generateSpanId()} 生成。
             */
            spanId?: Record<string, never>;
            /**
             * Format: int64
             * @description 时间戳
             */
            timestamp?: number;
            /**
             * @description 扩展字段（可选）。
             *
             *     用于携带额外的上下文信息，如 debugInfo、cost 等。 为 `null` 时不序列化（通过 `@JsonInclude(NON_NULL)` 控制）。
             */
            extensions?: {
                [key: string]: Record<string, never>;
            };
            /**
             * @description 国际化消息解析器实例（AtomicReference 保证线程安全和一次性设置）。
             *
             *     采用一次性设置语义：启动时由 `CoreAutoConfiguration` 注入， 后续不可修改，消除全局可变状态的线程安全隐患。
             */
            RESOLVER?: Record<string, never>;
        };
        /**
         * @description 应用信息分页查询参数
         *
         *     对应 `ydsz_sys_app_info` 表的分页查询条件。继承自 PageQuery，自带 `pageNum` /
         *     `pageSize` / `orderBy` / `sort` 等通用分页参数。
         *
         *     字段语义：
         *
         *
         *     `appName` — 应用名称模糊匹配（可选）
         *     `status` — 启用状态精确匹配（可选）
         */
        AppInfoPageQuery: {
            /** Format: int64 */
            serialVersionUID?: number;
            appName?: string;
            status?: string;
        };
        /**
         * @description 应用注册创建/更新 DTO
         *
         *     对应 `ydsz_sys_app_info` 表的写入参数，对标 OAuth 2.0 客户端注册模型。 创建时 `id` 为空（由雪花算法自动生成），更新时 {@code
         *     id} 必填。
         *
         *     字段约束：
         *
         *
         *     `appCode` — 应用编码，租户内唯一，最长 64 字符
         *     `appName` — 应用名称，最长 128 字符
         *     `appKey` — 客户端 ID（`client_id`），最长 128 字符
         *     `appSecret` — 客户端密钥（`client_secret`），BCrypt 加密存储，最长 256 字符
         *     `redirectUrl` — 授权回调地址，最长 512 字符，需 URL 合法
         *     `scopes` — OAuth2 授权范围（CSV），如 `"user.read,order.write"`
         *     `boundIps` — IP 绑定白名单（CSV），如 `"192.168.1.0/24,10.0.0.1"`，为空表示不限制
         *     `status` — 启用状态：`ENABLED / DISABLED`
         *
         *
         *     安全约束：
         *
         *
         *     `appSecret` 在 Service 层 BCrypt 加密后存储，明文不落库
         *     接口权限校验：`ydsz:app:create / ydsz:app:update`
         */
        AppInfoDTO: {
            id?: string;
            appCode?: string;
            appName?: string;
            appKey?: string;
            appSecret?: string;
            redirectUrl?: string;
            scopes?: string;
            boundIps?: string;
            description?: string;
            status?: string;
        };
        /**
         * @description 系统配置分页查询参数
         *
         *     对应 `ydsz_sys_config` 表的分页查询条件，由 Controller 接收并透传给 `ConfigService.page()`。继承自 {@link
         *     PageQuery}，自带 `pageNum` / `pageSize` / `orderBy` / `sort` 等通用分页参数。
         *
         *     字段语义：
         *
         *
         *     `configGroup` — 配置分组精确匹配（`=`），如 `ydsz.workflow`
         *     `configKey` — 配置键模糊匹配（`LIKE %xxx%`）
         *     `status` — 启用状态精确匹配（`=`），可空
         *
         *
         *     多租户：租户过滤由 MyBatis 拦截器自动注入。
         *
         *     索引利用：`(configGroup, configKey)` 命中 `uk_tenant_group_key` 唯一索引的前缀；典型查询模式
         *     「按分组列出」走该索引范围扫描，性能可控。
         */
        ConfigPageQuery: {
            /** Format: int64 */
            serialVersionUID?: number;
            configGroup?: string;
            configKey?: string;
            status?: string;
        };
        /**
         * @description 系统配置创建/更新 DTO
         *
         *     对应 `ydsz_sys_config` 表的写入参数，是「系统配置中心」创建 / 更新接口的入参载体。 创建时 `id` 为空（由雪花算法自动生成），更新时
         *     `id` 必填。
         *
         *     P1-5 字段重叠处理：本类与 ConfigVO 字段完全一致，遵循《云顶编码规范》"VO 兼 DTO"模式（字段无差异时不作三分离）。 作为
         *     Repository 层的写入契约存在，避免 infra 层直接依赖 ConfigVO（保持分层边界清晰）。
         *
         *     维护约定：新增字段时需同步 ConfigVO，确保两者结构一致。
         *
         *     字段语义：
         *
         *
         *     `configGroup` — 配置分组，按业务域分类管理
         *     `configKey` — 配置键，同组内唯一标识
         *     `configValue` — 配置值
         *     `valueType` — 值类型: STRING/NUMBER/BOOLEAN/JSON
         *     `defaultValue` — 默认值（配置未设置时使用）
         *     `isPublic` — 是否对前端公开: 1 公开 / 0 仅后端
         *     `sortOrder` — 排序序号
         *     `status` — 启用状态: ENABLED/DISABLED
         */
        ConfigDTO: {
            id?: string;
            configGroup?: string;
            configKey?: string;
            configValue?: string;
            valueType?: string;
            defaultValue?: string;
            description?: string;
            /** Format: int32 */
            isPublic?: number;
            /** Format: int32 */
            sortOrder?: number;
            status?: string;
        };
        /**
         * @description 系统配置批量操作 DTO
         *
         *     用于批量创建配置项（运营初始化场景），单次最多 500 条。
         */
        ConfigBatchDTO: {
            items?: components["schemas"]["ConfigVO"][];
        };
        /**
         * @description 系统配置 VO（视图对象）
         *
         *     对应 `ydsz_sys_config` 表的展示视图，是「系统配置中心」列表 / 详情接口的响应载体。
         *     由 com.njydsz.system.infra.converter.SystemConverter 从 {@link
         *     com.njydsz.system.infra.entity.Config} 实体转换而来。
         *
         *     字段语义：
         *
         *
         *     `configValue` — 配置值，序列化时按 `valueType` 转换： `STRING` 原样输出；{@code NUMBER /
         *     BOOLEAN / JSON} 解析为对应类型
         *     `defaultValue` — 默认值（`configValue` 为空时回退）
         *     `isPublic` — 是否对前端公开：`1` 公开 / `0` 仅后端； 前端「公开配置」接口仅返回 `isPublic=1`
         *     的项
         *
         *
         *     使用场景：
         *
         *
         *     配置中心列表 / 详情 / 编辑回显
         *     业务参数动态下发（`ydsz.workflow.sla-default-hours` 等）
         *     前端「公开配置」接口返回值（开关、限流阈值、特性开关等）
         *
         *
         *     缓存策略：读取通过 ydsz-common-cache 进程内本地缓存（键 `value:{tenantId`:{configKey}}）；
         *     写入时 `@CacheEvict` 精准失效；TTL 通过 `ydsz.cache.caches.system:config` 配置（默认 5 分钟）。
         *
         *     注意：本类为视图对象，不包含输入校验逻辑。输入校验由 {@link
         *     com.njydsz.system.domain.dto.ConfigDTO} 负责。
         */
        ConfigVO: {
            id?: string;
            configGroup?: string;
            configKey?: string;
            configValue?: string;
            valueType?: string;
            defaultValue?: string;
            description?: string;
            /** Format: int32 */
            isPublic?: number;
            /** Format: int32 */
            sortOrder?: number;
            status?: string;
        };
        /**
         * @description 字典类型分页查询参数
         *
         *     对应 `ydsz_sys_dict_type` 表的分页查询条件，由 Controller 接收并透传给 `DictTypeService.page()`。继承自
         *     PageQuery，自带 `pageNum` / `pageSize` / `orderBy` / `sort` 等通用分页参数。
         *
         *     字段语义：
         *
         *
         *     `typeCode` — 类型编码精确匹配（`=`），用于「按编码快速定位」
         *     `typeName` — 类型名称模糊匹配（`LIKE %xxx%`），用于「按名称搜索」
         *     `status` — 启用状态精确匹配（`=`），可空（`null` 表示全部）
         *
         *
         *     多租户：租户过滤由 MyBatis 拦截器（`ydsz-common-jdbc`）自动注入， 本类无需显式声明 `tenantId`。
         *
         *     索引利用：`typeCode` 命中 `uk_tenant_type_code` 唯一索引； `typeName`
         *     模糊匹配走全表扫描（数据量可控，小于 1000 条无影响）。
         */
        DictPageQuery: {
            /** Format: int64 */
            serialVersionUID?: number;
            typeCode?: string;
            typeName?: string;
            status?: string;
        };
        /**
         * @description 字典类型 DTO
         *
         *     用于字典类型的创建和更新操作，作为 Repository 接口 CUD 方法的入参。
         *
         *     字段语义：
         *
         *
         *     `id` — 主键 ID（更新时必填）
         *     `typeCode` — 字典类型编码，租户内唯一
         *     `typeName` — 字典类型名称
         *     `description` — 字典类型业务说明
         *     `status` — 启用状态: ENABLED/DISABLED
         */
        DictTypeDTO: {
            id?: string;
            typeCode?: string;
            typeName?: string;
            description?: string;
            status?: string;
        };
        /**
         * @description 字典项分页查询参数
         *
         *     对应 `ydsz_sys_dict_item` 表的分页查询条件。继承自 PageQuery，自带 `pageNum` /
         *     `pageSize` / `orderBy` / `sort` 等通用分页参数。
         *
         *     字段语义：
         *
         *
         *     `typeCode` — 字典类型编码精确匹配（可选）
         *     `itemCode` — 字典项编码模糊匹配（可选）
         *     `status` — 启用状态精确匹配（可选）
         */
        DictItemPageQuery: {
            /** Format: int64 */
            serialVersionUID?: number;
            typeCode?: string;
            itemCode?: string;
            status?: string;
        };
        /**
         * @description 字典项 DTO
         *
         *     用于字典项的创建和更新操作，作为 Repository 接口 CUD 方法的入参。
         *
         *     字段语义：
         *
         *
         *     `id` — 主键 ID（更新时必填）
         *     `typeCode` — 所属字典类型编码
         *     `itemCode` — 字典项编码
         *     `itemValue` — 字典项展示值
         *     `parentId` — 父级 ID
         *     `sortOrder` — 排序号
         *     `description` — 字典项业务说明
         *     `extJson` — 扩展属性 JSON
         *     `status` — 启用状态: ENABLED/DISABLED
         */
        DictItemDTO: {
            id?: string;
            parentId?: string;
            typeCode?: string;
            itemCode?: string;
            itemValue?: string;
            /** Format: int32 */
            sortOrder?: number;
            description?: string;
            extJson?: string;
            status?: string;
        };
        /**
         * @description 字典项批量操作 DTO
         *
         *     用于批量新增字典项（运营初始化场景），单次最多 500 条。
         */
        DictItemBatchDTO: {
            items?: components["schemas"]["DictItemVO"][];
        };
        /**
         * @description 字典项 VO（视图对象）
         *
         *     对应 `ydsz_sys_dict_item` 表的展示视图，是「字典中心」列表 / 详情接口的响应载体，
         *     也是前端下拉框、单选框、级联选择器、Tag 组件的核心数据载体。
         *
         *     使用 com.njydsz.common.domain.tree.TreeBuilder#buildSimple 构建树形结构，无需继承 `TreeNode` 基类，
         *     保持 VO 类的纯粹性（无框架耦合），同时通过 `level`/`path` 回调自动填充层级元数据。
         *
         *     字段语义：
         *
         *
         *     `typeCode` — 所属字典类型编码，与 DictTypeVO#typeCode 关联
         *     `itemCode` — 字典项编码（业务存储值，`<el-option :value="...">`）
         *     `itemValue` — 字典项展示值（前端展示文本）
         *     `parentId` — 父级 ID（`0` = 根），支持「省 / 市 / 区县」三级级联
         *     `sortOrder` — 同类型内排序号（升序），直接作为 TreeBuilder 排序字段
         *     `extJson` — 扩展属性 JSON（如地区码、颜色值、图标等），前端按需解析
         *
         *
         *     使用场景：
         *
         *
         *     字典中心列表 / 详情
         *     前端通用下拉框 / 单选框 / 多选框 / 级联选择 / 树形字典渲染
         *     业务表单中的「枚举字段」数据源
         *
         *
         *     缓存策略：读取时按 `ydsz:dict:item:{typeCode`} 整体缓存至 Redis； 列表查询支持本地缓存（Caffeine），TTL 5min。
         *
         *     注意：本类为视图对象，不包含输入校验逻辑。输入校验由 {@link
         *     com.njydsz.system.domain.dto.DictItemDTO} 负责。
         *
         *     构建树形结构，消除业务 VO 与框架基类的耦合
         */
        DictItemVO: {
            /** @description 字典项唯一标识 */
            id?: string;
            /** @description 父级 ID（`0` = 根），支持「省 / 市 / 区县」三级级联 */
            parentId?: string;
            /** @description 子节点列表（树形构建时由 TreeBuilder 自动填充） */
            children?: components["schemas"]["DictItemVO"][];
            /**
             * Format: int32
             * @description 层级深度（根节点=1，由 TreeBuilder 自动填充）
             */
            level?: number;
            /** @description 节点路径（如 "/1/2/5/"，由 TreeBuilder 自动填充） */
            path?: string;
            typeCode?: string;
            itemCode?: string;
            itemValue?: string;
            /**
             * Format: int32
             * @description 排序号（同类型内升序），直接作为 TreeBuilder 排序字段
             */
            sortOrder?: number;
            description?: string;
            extJson?: string;
            status?: string;
        };
        /**
         * @description 实体版本分页查询条件（P2-3 分页优化）。
         *
         *     用于 EntityVersion 的分页查询，统一管理 Config/Dict/Variable 版本的翻页参数。
         *
         *     设计要点：
         *
         *
         *     继承 BaseQuery 获取标准分页参数（pageNum / pageSize）
         *     资源类型 + 资源键为必填条件（版本按资源隔离）
         */
        EntityVersionPageQuery: {
            /** @description 资源类型（CONFIG/DICT/VARIABLE） */
            resourceType?: string;
            /** @description 资源唯一标识（如配置键、字典类型编码、变量键） */
            resourceKey?: string;
            /**
             * Format: int32
             * @description 页码（1-based，默认 1）
             */
            pageNum?: number;
            /**
             * Format: int32
             * @description 默认每页条数
             */
            DEFAULT_PAGE_SIZE?: number;
            /**
             * Format: int32
             * @description 每页条数（默认 20，最大 500）
             */
            pageSize?: number;
        };
        /** @description 配置查询请求 DTO。 */
        ConfigGetRequest: {
            /** @description 配置键 */
            key?: string;
        };
        /** @description 字典项查询请求 DTO。 */
        DictItemGetRequest: {
            /** @description 字典类型编码 */
            typeCode?: string;
            /** @description 字典项编码 */
            itemCode?: string;
        };
        /**
         * @description 字典项列表查询请求 DTO。
         *
         *     用于 InternalApiController 内部 API 的字典项列表查询，通过 POST body 传输参数，
         *     与同模块其他请求 DTO 保持风格一致（DictItemGetRequest、ConfigGetRequest、
         *     AppValidateRequest）。
         */
        DictListRequest: {
            /** @description 字典类型编码 */
            typeCode?: string;
        };
        /** @description 应用密钥校验请求 DTO。 */
        AppValidateRequest: {
            /** @description 应用 Key（client_id） */
            appKey?: string;
            /** @description 应用密钥（client_secret） */
            appSecret?: string;
        };
        /**
         * @description 租户分页查询参数
         *
         *     对应 `ydsz_sys_tenant` 表的分页查询条件。继承自 PageQuery，自带 `pageNum` /
         *     `pageSize` / `orderBy` / `sort` 等通用分页参数。
         *
         *     字段语义：
         *
         *
         *     `tenantName` — 租户名称模糊匹配（可选）
         *     `status` — 启用状态精确匹配（可选）
         *
         *
         *     多租户：租户过滤由 MyBatis 拦截器（`ydsz-common-jdbc`）自动注入， 本类无需显式声明 `tenantId`。
         */
        TenantPageQuery: {
            /** Format: int64 */
            serialVersionUID?: number;
            tenantName?: string;
            tenantCode?: string;
            status?: string;
        };
        /**
         * @description 租户创建/更新 DTO
         *
         *     对应 `ydsz_sys_tenant` 表的写入参数。 创建时 `id` 为空（由雪花算法自动生成），更新时 `id` 必填。
         *
         *     字段约束：
         *
         *
         *     `tenantCode` — 租户编码，全局唯一，最长 64 字符
         *     `tenantName` — 租户名称，最长 128 字符
         */
        TenantDTO: {
            id?: string;
            tenantCode?: string;
            tenantName?: string;
            contactName?: string;
            contactPhone?: string;
            contactEmail?: string;
            planId?: string;
            /** Format: date-time */
            expireAt?: string;
            datasourceKey?: string;
            status?: string;
            remark?: string;
        };
        /**
         * @description 租户套餐分页查询参数
         *
         *     对应 `ydsz_sys_tenant_plan` 表的分页查询条件。继承自 PageQuery，自带 `pageNum` /
         *     `pageSize` / `orderBy` / `sort` 等通用分页参数。
         *
         *     字段语义：
         *
         *
         *     `planName` — 套餐名称模糊匹配（可选）
         *     `status` — 启用状态精确匹配（可选）
         */
        TenantPlanPageQuery: {
            /** Format: int64 */
            serialVersionUID?: number;
            planName?: string;
            status?: string;
        };
        /**
         * @description 租户套餐创建/更新 DTO
         *
         *     对应 `ydsz_sys_tenant_plan` 表的写入参数，是「套餐管理」创建 / 更新接口的入参载体。
         *     创建时 `id` 为空（由雪花算法自动生成），更新时 `id` 必填。
         *
         *     字段语义：
         *
         *
         *     `planCode` — 套餐编码，全局唯一标识
         *     `sortOrder` — 排序号（升序，影响前端套餐选择器顺序）
         */
        TenantPlanDTO: {
            id?: string;
            planCode?: string;
            planName?: string;
            description?: string;
            /** Format: int32 */
            sortOrder?: number;
            quotaJson?: string;
            featureJson?: string;
            status?: string;
        };
        /**
         * @description 租户套餐-菜单关联 DTO
         *
         *     用于为套餐批量配置可访问菜单列表。 通过套餐 ID + 菜单 ID 列表一次性设置套餐的菜单权限。
         */
        TenantPlanMenuDTO: {
            planId?: string;
            menuIds?: string[];
        };
        /**
         * @description 系统变量分页查询参数
         *
         *     对应 `ydsz_sys_variable` 表的分页查询条件。继承自 PageQuery，自带 `pageNum` /
         *     `pageSize` / `orderBy` / `sort` 等通用分页参数。
         *
         *     字段语义：
         *
         *
         *     `variableKey` — 变量键模糊匹配（可选）
         *     `status` — 启用状态精确匹配（可选）
         */
        VariablePageQuery: {
            /** Format: int64 */
            serialVersionUID?: number;
            variableKey?: string;
            status?: string;
        };
        /**
         * @description 系统变量创建/更新 DTO
         *
         *     对应 `ydsz_sys_variable` 表的写入参数，是「系统变量中心」创建 / 更新接口的入参载体。
         *     创建时 `id` 为空（由雪花算法自动生成），更新时 `id` 必填。
         *
         *     字段语义：
         *
         *
         *     `variableKey` — 变量键，租户内唯一
         *     `variableValue` — 变量值
         *     `valueType` — 值类型: STRING/NUMBER/BOOLEAN/JSON
         *     `status` — 启用状态: ENABLED/DISABLED
         */
        VariableDTO: {
            id?: string;
            variableKey?: string;
            variableValue?: string;
            valueType?: string;
            description?: string;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    page: {
        parameters: {
            query?: {
                query?: components["schemas"]["AppInfoPageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppInfoDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppInfoDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    queryByTimeRange: {
        parameters: {
            query?: {
                startTime?: string;
                endTime?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    queryByOperator: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                operatorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    queryByAction: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                action: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    queryByTraceId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    page: {
        parameters: {
            query?: {
                query?: components["schemas"]["ConfigPageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    pageByCursor: {
        parameters: {
            query?: {
                configGroup?: string;
                configKey?: string;
                pageSize?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    batchSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigBatchDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getByKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getConfigsByGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configGroup: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listPublicConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    exportConfigs: {
        parameters: {
            query?: {
                configGroup?: string;
                response?: Record<string, never>;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never> | null;
                };
            };
        };
    };
    importConfigs: {
        parameters: {
            query?: {
                file?: Record<string, never>;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listByResourceKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    rollback: {
        parameters: {
            query?: {
                targetVersion?: string;
            };
            header?: {
                operatorId?: string;
            };
            path: {
                resourceKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    page: {
        parameters: {
            query?: {
                query?: components["schemas"]["DictPageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictTypeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictTypeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    page: {
        parameters: {
            query?: {
                query?: components["schemas"]["DictItemPageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    lookup: {
        parameters: {
            query?: {
                typeCode?: string;
                itemCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listByType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listChildren: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    buildTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictItemDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictItemDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    batchSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictItemBatchDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listByTypeCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    pageByTypeCode: {
        parameters: {
            query?: {
                query?: components["schemas"]["EntityVersionPageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    rollback: {
        parameters: {
            query?: {
                targetVersion?: string;
            };
            header?: {
                operatorId?: string;
            };
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    init: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    initWithDicts: {
        parameters: {
            query?: {
                dictTypes?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigGetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getDictItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictItemGetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listDictItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictListRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    validateClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppValidateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    page: {
        parameters: {
            query?: {
                query?: components["schemas"]["TenantPageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                userId?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: {
                userId?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    page: {
        parameters: {
            query?: {
                query?: components["schemas"]["TenantPlanPageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                userId?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantPlanDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: {
                userId?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantPlanDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listMenus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    updateMenus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantPlanMenuDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    page: {
        parameters: {
            query?: {
                query?: components["schemas"]["VariablePageQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    getByKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variableKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariableDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariableDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    listByResourceKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
    rollback: {
        parameters: {
            query?: {
                targetVersion?: string;
            };
            header?: {
                operatorId?: string;
            };
            path: {
                resourceKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YdszResponse"];
                };
            };
        };
    };
}
