/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * MessageController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code MessageController}，共 4 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { MessageLogQueryDTO, MessageResult, MessageSendDTO, MsgLogVO } from './models';

/**
 * send: POST /api/v1/message/send
 *
 * <p>返回 unknown 的理由（云顶编码规范 §3.1 特殊场景豁免）：
 * 后端方法声明为 {@code YdszResponse}，响应结构未固定为具名 VO，
 * 无法在生成期推导出稳定字段，故不使用 any，退守为 unknown。
 * 调用方应在使用前做类型收窄（参见规范 §3.1 的 isUserInfo 参考实现）。
 */
export function send(data: MessageSendDTO): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/message/send`, data);
}

/**
 * pageLog: GET /api/v1/message/log/page
 */
export function pageLog(params: {
    query?: MessageLogQueryDTO;
  }): Promise<PageResponse<MsgLogVO[]>> {
  return requestClient.get<PageResponse<MsgLogVO[]>>(`/api/v1/message/log/page`, { params });
}

/**
 * cancelScheduled: POST /api/v1/message/cancelScheduled
 */
export function cancelScheduled(params: {
    msgId?: string;
  }): Promise<MessageResult> {
  return requestClient.post<MessageResult>(`/api/v1/message/cancelScheduled`, { params });
}

/**
 * batchProgress: GET /api/v1/message/batch/{batchId}/progress
 */
export function batchProgress({ batchId }: {
    batchId: string;
  }, params: {
    page?: number;
    size?: number;
  }): Promise<PageResponse<MsgLogVO[]>> {
  return requestClient.get<PageResponse<MsgLogVO[]>>(`/api/v1/message/batch/${batchId}/progress`, { params });
}
