/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * MessageController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code MessageController}，共 8 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { BatchSendResult, MessageLogQueryDTO, MessageRequest, MessageResult, MessageSendDTO, PageResponse } from './models';

/**
 * send: POST /api/v1/message/send
 */
export function send(data: MessageSendDTO): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/message/send`, data);
}

/**
 * sendDirect: POST /api/v1/message/sendDirect
 */
export function sendDirect(data: MessageSendDTO): Promise<MessageResult> {
  return requestClient.post<MessageResult>(`/api/v1/message/sendDirect`, data);
}

/**
 * sendAsync: POST /api/v1/message/sendAsync
 */
export function sendAsync(data: MessageRequest): Promise<MessageResult> {
  return requestClient.post<MessageResult>(`/api/v1/message/sendAsync`, data);
}

/**
 * pageLog: GET /api/v1/message/log/page
 */
export function pageLog(params: {
    query?: MessageLogQueryDTO;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/v1/message/log/page`, { params });
}

/**
 * cancelScheduled: POST /api/v1/message/cancelScheduled
 */
export function cancelScheduled(params: {
    msgId?: string;
  }): Promise<MessageResult> {
  return requestClient.post<MessageResult>(`/api/v1/message/cancelScheduled`, { params });
}

/**
 * sendTransactionally: POST /api/v1/message/sendTransactional
 */
export function sendTransactionally(data: MessageRequest): Promise<MessageResult> {
  return requestClient.post<MessageResult>(`/api/v1/message/sendTransactional`, data);
}

/**
 * batchSend: POST /api/v1/message/batchSend
 */
export function batchSend(params: {
    batchId?: string;
  }, data: MessageRequest[]): Promise<BatchSendResult> {
  return requestClient.post<BatchSendResult>(`/api/v1/message/batchSend`, data, { params });
}

/**
 * batchProgress: GET /api/v1/message/batch/{batchId}/progress
 */
export function batchProgress({ batchId }: {
    batchId: string;
  }, params: {
    page?: number;
    size?: number;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/v1/message/batch/${batchId}/progress`, { params });
}
