/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * MessageStatsController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code MessageStatsController}，共 5 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type {
  ChannelStatsVO,
  CostStatsVO,
  FunnelStatsVO,
  MessageStatsVO,
  ReceiptStatsVO,
} from './models';

/**
 * overview: GET /api/v1/message/stats/overview
 */
export function overview(params: { start?: string; end?: string }): Promise<MessageStatsVO> {
  return requestClient.get<MessageStatsVO>(`/api/v1/message/stats/overview`, { params });
}

/**
 * channelStats: GET /api/v1/message/stats/channel
 */
export function channelStats(params: { start?: string; end?: string }): Promise<ChannelStatsVO[]> {
  return requestClient.get<ChannelStatsVO[]>(`/api/v1/message/stats/channel`, { params });
}

/**
 * receiptStats: GET /api/v1/message/stats/receipt
 */
export function receiptStats(params: { start?: string; end?: string }): Promise<ReceiptStatsVO> {
  return requestClient.get<ReceiptStatsVO>(`/api/v1/message/stats/receipt`, { params });
}

/**
 * funnel: GET /api/v1/message/stats/funnel
 */
export function funnel(params: {
  start?: string;
  end?: string;
  channel?: string;
  templateCode?: string;
}): Promise<FunnelStatsVO> {
  return requestClient.get<FunnelStatsVO>(`/api/v1/message/stats/funnel`, { params });
}

/**
 * cost: GET /api/v1/message/stats/cost
 */
export function cost(params: { start?: string; end?: string }): Promise<CostStatsVO> {
  return requestClient.get<CostStatsVO>(`/api/v1/message/stats/cost`, { params });
}
