/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * MessageFeedbackController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code MessageFeedbackController}，共 4 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { MessageFeedbackDTO, MsgFeedbackVO } from './models';

/**
 * submitFeedback: POST /api/v1/message/feedback
 */
export function submitFeedback(data: MessageFeedbackDTO): Promise<string> {
  return requestClient.post<string>(`/api/v1/message/feedback`, data);
}

/**
 * getAverageRating: GET /api/v1/message/feedback/rating
 */
export function getAverageRating(params: {
    userId?: string;
    channel?: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/message/feedback/rating`, { params });
}

/**
 * pageFeedback: GET /api/v1/message/feedback/page
 */
export function pageFeedback(params: {
    page?: number;
    size?: number;
    channel?: string;
    userId?: string;
  }): Promise<PageResponse<MsgFeedbackVO[]>> {
  return requestClient.get<PageResponse<MsgFeedbackVO[]>>(`/api/v1/message/feedback/page`, { params });
}

/**
 * shouldReduceFrequency: GET /api/v1/message/feedback/shouldReduceFreq
 */
export function shouldReduceFrequency(params: {
    userId?: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/message/feedback/shouldReduceFreq`, { params });
}
