/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * MessageTraceController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code MessageTraceController}，共 3 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';

/**
 * getByMsgId: GET /api/v1/message/trace/msg/{msgId}
 */
export function getByMsgId({
  msgId,
}: {
  msgId: string;
}): Promise<
  | 'RECEIVED'
  | 'CHANNEL_CHECK'
  | 'ROUTE_MATCHED'
  | 'CANARY_HIT'
  | 'SUBSCRIPTION_CHECK'
  | 'PREFERENCE_CHECK'
  | 'DEDUP_CHECK'
  | 'RATE_LIMIT_CHECK'
  | 'TEMPLATE_LOADED'
  | 'TEMPLATE_RENDERED'
  | 'SENSITIVE_FILTERED'
  | 'PERSISTED'
  | 'SCHEDULED'
  | 'AGGREGATED'
  | 'DISPATCH_START'
  | 'DISPATCH_SUCCESS'
  | 'FALLBACK'
  | 'RETRY'
  | 'SEND_FAILED'
  | 'RECEIPT_RECEIVED'
  | 'RECALLED'
  | 'CASCADE_SENT'[]
> {
  return requestClient.get<
    | 'RECEIVED'
    | 'CHANNEL_CHECK'
    | 'ROUTE_MATCHED'
    | 'CANARY_HIT'
    | 'SUBSCRIPTION_CHECK'
    | 'PREFERENCE_CHECK'
    | 'DEDUP_CHECK'
    | 'RATE_LIMIT_CHECK'
    | 'TEMPLATE_LOADED'
    | 'TEMPLATE_RENDERED'
    | 'SENSITIVE_FILTERED'
    | 'PERSISTED'
    | 'SCHEDULED'
    | 'AGGREGATED'
    | 'DISPATCH_START'
    | 'DISPATCH_SUCCESS'
    | 'FALLBACK'
    | 'RETRY'
    | 'SEND_FAILED'
    | 'RECEIPT_RECEIVED'
    | 'RECALLED'
    | 'CASCADE_SENT'[]
  >(`/api/v1/message/trace/msg/${msgId}`);
}

/**
 * getByTraceId: GET /api/v1/message/trace/trace/{traceId}
 */
export function getByTraceId({
  traceId,
}: {
  traceId: string;
}): Promise<
  | 'RECEIVED'
  | 'CHANNEL_CHECK'
  | 'ROUTE_MATCHED'
  | 'CANARY_HIT'
  | 'SUBSCRIPTION_CHECK'
  | 'PREFERENCE_CHECK'
  | 'DEDUP_CHECK'
  | 'RATE_LIMIT_CHECK'
  | 'TEMPLATE_LOADED'
  | 'TEMPLATE_RENDERED'
  | 'SENSITIVE_FILTERED'
  | 'PERSISTED'
  | 'SCHEDULED'
  | 'AGGREGATED'
  | 'DISPATCH_START'
  | 'DISPATCH_SUCCESS'
  | 'FALLBACK'
  | 'RETRY'
  | 'SEND_FAILED'
  | 'RECEIPT_RECEIVED'
  | 'RECALLED'
  | 'CASCADE_SENT'[]
> {
  return requestClient.get<
    | 'RECEIVED'
    | 'CHANNEL_CHECK'
    | 'ROUTE_MATCHED'
    | 'CANARY_HIT'
    | 'SUBSCRIPTION_CHECK'
    | 'PREFERENCE_CHECK'
    | 'DEDUP_CHECK'
    | 'RATE_LIMIT_CHECK'
    | 'TEMPLATE_LOADED'
    | 'TEMPLATE_RENDERED'
    | 'SENSITIVE_FILTERED'
    | 'PERSISTED'
    | 'SCHEDULED'
    | 'AGGREGATED'
    | 'DISPATCH_START'
    | 'DISPATCH_SUCCESS'
    | 'FALLBACK'
    | 'RETRY'
    | 'SEND_FAILED'
    | 'RECEIPT_RECEIVED'
    | 'RECALLED'
    | 'CASCADE_SENT'[]
  >(`/api/v1/message/trace/trace/${traceId}`);
}

/**
 * getByBiz: GET /api/v1/message/trace/biz
 */
export function getByBiz(params: {
  bizType?: string;
  bizId?: string;
}): Promise<
  | 'RECEIVED'
  | 'CHANNEL_CHECK'
  | 'ROUTE_MATCHED'
  | 'CANARY_HIT'
  | 'SUBSCRIPTION_CHECK'
  | 'PREFERENCE_CHECK'
  | 'DEDUP_CHECK'
  | 'RATE_LIMIT_CHECK'
  | 'TEMPLATE_LOADED'
  | 'TEMPLATE_RENDERED'
  | 'SENSITIVE_FILTERED'
  | 'PERSISTED'
  | 'SCHEDULED'
  | 'AGGREGATED'
  | 'DISPATCH_START'
  | 'DISPATCH_SUCCESS'
  | 'FALLBACK'
  | 'RETRY'
  | 'SEND_FAILED'
  | 'RECEIPT_RECEIVED'
  | 'RECALLED'
  | 'CASCADE_SENT'[]
> {
  return requestClient.get<
    | 'RECEIVED'
    | 'CHANNEL_CHECK'
    | 'ROUTE_MATCHED'
    | 'CANARY_HIT'
    | 'SUBSCRIPTION_CHECK'
    | 'PREFERENCE_CHECK'
    | 'DEDUP_CHECK'
    | 'RATE_LIMIT_CHECK'
    | 'TEMPLATE_LOADED'
    | 'TEMPLATE_RENDERED'
    | 'SENSITIVE_FILTERED'
    | 'PERSISTED'
    | 'SCHEDULED'
    | 'AGGREGATED'
    | 'DISPATCH_START'
    | 'DISPATCH_SUCCESS'
    | 'FALLBACK'
    | 'RETRY'
    | 'SEND_FAILED'
    | 'RECEIPT_RECEIVED'
    | 'RECALLED'
    | 'CASCADE_SENT'[]
  >(`/api/v1/message/trace/biz`, { params });
}
