/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * PreferenceController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code PreferenceController}，共 4 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { MsgPreferenceVO, PreferenceUpsertDTO } from './models';

/**
 * upsert: POST /message/preference
 */
export function upsert(data: PreferenceUpsertDTO): Promise<MsgPreferenceVO> {
  return requestClient.post<MsgPreferenceVO>(`/message/preference`, data);
}

/**
 * listByUser: GET /message/preference/{userId}
 */
export function listByUser({ userId }: {
    userId: string;
  }): Promise<MsgPreferenceVO[]> {
  return requestClient.get<MsgPreferenceVO[]>(`/message/preference/${userId}`);
}

/**
 * getByUser: GET /message/preference/{userId}/{channel}/{bizType}
 */
export function getByUser({ userId, channel, bizType }: {
    userId: string;
    channel: string;
    bizType: string;
  }): Promise<MsgPreferenceVO> {
  return requestClient.get<MsgPreferenceVO>(`/message/preference/${userId}/${channel}/${bizType}`);
}

/**
 * delete: DELETE /message/preference/{id}
 */
export function deleteApi({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/message/preference/${id}`);
}
