/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * TemplatePreviewController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code TemplatePreviewController}，共 2 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';


/**
 * previewByCode: POST /api/v1/message/template/preview/by-code
 */
export function previewByCode(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/message/template/preview/by-code`, data);
}

/**
 * previewRaw: POST /api/v1/message/template/preview/raw
 */
export function previewRaw(data: Record<string, unknown>): Promise<string> {
  return requestClient.post<string>(`/api/v1/message/template/preview/raw`, data);
}
