/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * UnsubscribeController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code UnsubscribeController}，共 4 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { MsgSubscriptionVO, UnsubscribeQueryDTO, UnsubscribeTokenPayload } from './models';

/**
 * oneClick: POST /api/v1/message/unsubscribe/oneClick
 */
export function oneClick(params: { token?: string }): Promise<MsgSubscriptionVO> {
  return requestClient.post<MsgSubscriptionVO>(`/api/v1/message/unsubscribe/oneClick`, { params });
}

/**
 * preview: GET /api/v1/message/unsubscribe/preview
 */
export function preview(params: { token?: string }): Promise<UnsubscribeTokenPayload> {
  return requestClient.get<UnsubscribeTokenPayload>(`/api/v1/message/unsubscribe/preview`, {
    params,
  });
}

/**
 * page: GET /api/v1/message/unsubscribe/page
 */
export function page(params: {
  query?: UnsubscribeQueryDTO;
}): Promise<PageResponse<MsgSubscriptionVO[]>> {
  return requestClient.get<PageResponse<MsgSubscriptionVO[]>>(`/api/v1/message/unsubscribe/page`, {
    params,
  });
}

/**
 * resubscribe: POST /api/v1/message/unsubscribe/resubscribe
 */
export function resubscribe(params: {
  userId?: string;
  topicCode?: string;
  channel?: string;
}): Promise<void> {
  return requestClient.post<void>(`/api/v1/message/unsubscribe/resubscribe`, { params });
}
