/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * UserChannelBindingController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code UserChannelBindingController}，共 4 个端点。
 * <p>路径规范: /api/v1/message/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py message} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { MsgUserChannelVO, UserChannelBindingDTO } from './models';

/**
 * upsert: POST /api/v1/message/user-channels
 */
export function upsert(data: UserChannelBindingDTO): Promise<MsgUserChannelVO> {
  return requestClient.post<MsgUserChannelVO>(`/api/v1/message/user-channels`, data);
}

/**
 * listMine: GET /api/v1/message/user-channels/mine
 */
export function listMine(): Promise<MsgUserChannelVO[]> {
  return requestClient.get<MsgUserChannelVO[]>(`/api/v1/message/user-channels/mine`);
}

/**
 * listByUser: GET /api/v1/message/user-channels/user/{userId}
 */
export function listByUser({ userId }: {
    userId: string;
  }): Promise<MsgUserChannelVO[]> {
  return requestClient.get<MsgUserChannelVO[]>(`/api/v1/message/user-channels/user/${userId}`);
}

/**
 * delete: DELETE /api/v1/message/user-channels/{id}
 */
export function deleteApi({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/message/user-channels/${id}`);
}
