/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * GlueCodeController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code GlueCodeController}，共 7 个端点。
 * <p>路径规范: /api/v1/cronjob/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py cronjob} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { GlueCodeVO } from './models';

/**
 * save: POST /api/v1/cronjob/glue/save
 */
export function save(data: Record<string, unknown>): Promise<GlueCodeVO> {
  return requestClient.post<GlueCodeVO>(`/api/v1/cronjob/glue/save`, data);
}

/**
 * latest: GET /api/v1/cronjob/glue/latest
 */
export function latest(params: {
    jobId?: string;
  }): Promise<GlueCodeVO> {
  return requestClient.get<GlueCodeVO>(`/api/v1/cronjob/glue/latest`, { params });
}

/**
 * versions: GET /api/v1/cronjob/glue/versions
 */
export function versions(params: {
    jobId?: string;
  }): Promise<GlueCodeVO[]> {
  return requestClient.get<GlueCodeVO[]>(`/api/v1/cronjob/glue/versions`, { params });
}

/**
 * rollback: POST /api/v1/cronjob/glue/rollback
 */
export function rollback(data: Record<string, unknown>): Promise<GlueCodeVO> {
  return requestClient.post<GlueCodeVO>(`/api/v1/cronjob/glue/rollback`, data);
}

/**
 * test: POST /api/v1/cronjob/glue/test
 */
export function test(data: Record<string, unknown>): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/cronjob/glue/test`, data);
}

/**
 * template: GET /api/v1/cronjob/glue/template
 */
export function template(params: {
    language?: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/cronjob/glue/template`, { params });
}

/**
 * diff: GET /api/v1/cronjob/glue/diff
 */
export function diff(params: {
    jobId?: string;
    versionA?: number;
    versionB?: number;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/cronjob/glue/diff`, { params });
}
