/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * JobStatsController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code JobStatsController}，共 5 个端点。
 * <p>路径规范: /api/v1/cronjob/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py cronjob} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { JobDailyStatsVO, JobLogVO } from './models';

/**
 * daily: GET /api/v1/cronjob/stats/daily
 */
export function daily(params: {
    jobId?: string;
    startDate?: string;
    endDate?: string;
  }): Promise<JobDailyStatsVO[]> {
  return requestClient.get<JobDailyStatsVO[]>(`/api/v1/cronjob/stats/daily`, { params });
}

/**
 * summary: GET /api/v1/cronjob/stats/summary
 */
export function summary(params: {
    jobId?: string;
    startDate?: string;
    endDate?: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/cronjob/stats/summary`, { params });
}

/**
 * dashboard: GET /api/v1/cronjob/stats/dashboard
 */
export function dashboard(): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/cronjob/stats/dashboard`);
}

/**
 * recentFailures: GET /api/v1/cronjob/stats/recent-failures
 */
export function recentFailures(params: {
    limit?: number;
  }): Promise<JobLogVO[]> {
  return requestClient.get<JobLogVO[]>(`/api/v1/cronjob/stats/recent-failures`, { params });
}

/**
 * heatmap: GET /api/v1/cronjob/stats/heatmap
 */
export function heatmap(params: {
    date?: string;
  }): Promise<Record<string, unknown>[]> {
  return requestClient.get<Record<string, unknown>[]>(`/api/v1/cronjob/stats/heatmap`, { params });
}
