/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
export interface YdszResponse {

  serialVersionUID?: number;

  code?: string;

  msg?: string;

  data?: Record<string, unknown>;

  traceId?: Record<string, unknown>;

  requestId?: Record<string, unknown>;

  spanId?: Record<string, unknown>;

  timestamp?: number;

  extensions?: Record<string, unknown>;

  RESOLVER?: Record<string, unknown>;
}

export interface AlertRulePostDTO {

  serialVersionUID?: number;

  ruleName?: string;

  jobId?: string;

  jobKey?: string;

  alertType?: string;

  alertLevel?: string;

  threshold?: number;

  timeWindowMinutes?: number;

  channels?: string;

  receivers?: string;

  cooldownMinutes?: number;

  enabled?: number;
}

export interface AlertRulePutDTO {

  serialVersionUID?: number;

  id?: string;

  ruleName?: string;

  jobId?: string;

  jobKey?: string;

  alertType?: string;

  alertLevel?: string;

  threshold?: number;

  timeWindowMinutes?: number;

  channels?: string;

  receivers?: string;

  cooldownMinutes?: number;

  enabled?: number;
}

export interface ConnectorConfigPostDTO {

  serialVersionUID?: number;

  endpoint?: string;

  authType?: string;

  username?: string;

  password?: string;

  accessKey?: string;

  secretKey?: string;

  extraProps?: Record<string, unknown>;

  connectTimeoutSeconds?: number;

  readTimeoutSeconds?: number;
}

export interface JobDagPostDTO {

  serialVersionUID?: number;

  dagKey?: string;

  dagName?: string;

  dagDefinition?: string;

  status?: string;

  triggerType?: string;

  cronExpression?: string;

  maxConcurrentInstances?: number;

  failStrategy?: string;

  description?: string;
}

export interface JobDagPutDTO {

  serialVersionUID?: number;

  dagKey?: string;

  dagName?: string;

  dagDefinition?: string;

  status?: string;

  triggerType?: string;

  cronExpression?: string;

  maxConcurrentInstances?: number;

  failStrategy?: string;

  description?: string;
}

export interface JobDagTriggerDTO {

  serialVersionUID?: number;

  dagKey?: string;

  triggerBy?: string;
}

export interface RemoteTaskRequest {

  serialVersionUID?: number;

  job?: JobVO;

  triggerType?: string;

  shardIndex?: number;

  shardTotal?: number;

  traceId?: string;
}

export interface JobVO {

  serialVersionUID?: number;

  id?: string;

  jobName?: string;

  jobGroup?: string;

  jobKey?: string;

  handler?: string;

  cronExpression?: string;

  scheduleType?: string;

  fixedRateMs?: number;

  fixedDelayMs?: number;

  paramsJson?: string;

  jobRemark?: string;

  nextFireTime?: string;

  lastFireTime?: string;

  fireCount?: number;

  successCount?: number;

  failCount?: number;

  lockTtlMs?: number;

  timeoutMs?: number;

  slowThresholdMs?: number;

  misfirePolicy?: string;

  shardTotal?: number;

  jobType?: string;

  maxRetries?: number;

  retryIntervalMs?: number;

  retryBackoff?: string;

  blockStrategy?: string;

  consecutiveFailCount?: number;

  maxConsecutiveFails?: number;

  autoResumeAfterMinutes?: number;

  priority?: number;

  version?: number;

  timezone?: string;

  cluster?: string;

  canaryRatio?: number;

  canaryHandler?: string;

  createdBy?: string;

  createdAt?: string;

  updatedBy?: string;

  updatedAt?: string;
}

export interface RemoteSubTaskRequest {

  serialVersionUID?: number;

  jobId?: string;

  logId?: string;

  jobKey?: string;

  handler?: string;

  taskName?: string;

  taskParams?: string;

  traceId?: string;
}

export interface JobPostDTO {

  serialVersionUID?: number;

  jobName?: string;

  jobGroup?: string;

  jobKey?: string;

  handler?: string;

  cronExpression?: string;

  scheduleType?: string;

  fixedRateMs?: number;

  fixedDelayMs?: number;

  paramsJson?: string;

  status?: string;

  remark?: string;

  lockTtlMs?: number;

  timeoutMs?: number;

  slowThresholdMs?: number;

  misfirePolicy?: string;

  shardTotal?: number;

  timezone?: string;

  cluster?: string;
}

export interface JobPutDTO {

  serialVersionUID?: number;

  id?: string;

  jobName?: string;

  jobGroup?: string;

  jobKey?: string;

  handler?: string;

  cronExpression?: string;

  scheduleType?: string;

  fixedRateMs?: number;

  fixedDelayMs?: number;

  paramsJson?: string;

  status?: string;

  remark?: string;

  lockTtlMs?: number;

  timeoutMs?: number;

  slowThresholdMs?: number;

  misfirePolicy?: string;

  shardTotal?: number;

  timezone?: string;

  cluster?: string;
}

export interface JobBatchDTO {

  serialVersionUID?: number;

  jobIds?: string[];
}

export interface JobWebhookPostDTO {

  serialVersionUID?: number;

  name?: string;

  eventType?: string;

  jobKey?: string;

  jobGroup?: string;

  callbackUrl?: string;

  httpMethod?: string;

  headers?: string;

  secret?: string;

  webhookStatus?: string;
}

export interface JobWebhookPutDTO {

  serialVersionUID?: number;

  id?: string;

  name?: string;

  eventType?: string;

  jobKey?: string;

  jobGroup?: string;

  callbackUrl?: string;

  httpMethod?: string;

  headers?: string;

  secret?: string;

  webhookStatus?: string;
}