/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * AppInfoController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code AppInfoController}，共 5 个端点。
 * <p>路径规范: /api/system/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py system} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { AppInfoDTO, AppInfoPageQuery, AppInfoVO, PageResponse } from './models';

/**
 * page: GET /api/app/page
 */
export function page(params: {
    query?: AppInfoPageQuery;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/app/page`, { params });
}

/**
 * getById: GET /api/app/{id}
 */
export function getById(path: {
    id: string;
  }): Promise<AppInfoVO> {
  return requestClient.get<AppInfoVO>(`/api/app/${id}`);
}

/**
 * save: POST /api/app
 */
export function save(data: AppInfoDTO): Promise<string> {
  return requestClient.post<string>(`/api/app`, data);
}

/**
 * update: PUT /api/app
 */
export function update(data: AppInfoDTO): Promise<boolean> {
  return requestClient.put<boolean>(`/api/app`, data);
}

/**
 * remove: DELETE /api/app/{id}
 */
export function remove(path: {
    id: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/app/${id}`);
}
