/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * AuditAdminController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code AuditAdminController}，共 5 个端点。
 * <p>路径规范: /api/v1/system/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py system} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { AuditLog } from './models';

/**
 * queryByTimeRange: GET /api/v1/admin/audit/logs
 */
export function queryByTimeRange(params: {
    startTime?: string;
    endTime?: string;
    page?: number;
    size?: number;
  }): Promise<AuditLog[]> {
  return requestClient.get<AuditLog[]>(`/api/v1/admin/audit/logs`, { params });
}

/**
 * queryByOperator: GET /api/v1/admin/audit/operator/{operatorId}
 */
export function queryByOperator(path: {
    operatorId: string;
  }, params: {
    page?: number;
    size?: number;
  }): Promise<AuditLog[]> {
  return requestClient.get<AuditLog[]>(`/api/v1/admin/audit/operator/${operatorId}`, { params });
}

/**
 * queryByAction: GET /api/v1/admin/audit/action/{action}
 */
export function queryByAction(path: {
    action: number;
  }, params: {
    page?: number;
    size?: number;
  }): Promise<AuditLog[]> {
  return requestClient.get<AuditLog[]>(`/api/v1/admin/audit/action/${action}`, { params });
}

/**
 * queryByTraceId: GET /api/v1/admin/audit/trace/{traceId}
 */
export function queryByTraceId(path: {
    traceId: string;
  }): Promise<AuditLog[]> {
  return requestClient.get<AuditLog[]>(`/api/v1/admin/audit/trace/${traceId}`);
}

/**
 * getById: GET /api/v1/admin/audit/{id}
 */
export function getById(path: {
    id: string;
  }): Promise<AuditLog> {
  return requestClient.get<AuditLog>(`/api/v1/admin/audit/${id}`);
}
