/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
export interface YdszResponse {

  serialVersionUID?: number;

  code?: string;

  msg?: string;

  data?: Record<string, unknown>;

  traceId?: Record<string, unknown>;

  requestId?: Record<string, unknown>;

  spanId?: Record<string, unknown>;

  timestamp?: number;

  extensions?: Record<string, unknown>;

  RESOLVER?: Record<string, unknown>;
}

export interface AppInfoPageQuery {

  serialVersionUID?: number;

  appName?: string;

  status?: string;
}

export interface AppInfoDTO {

  id?: string;

  appCode?: string;

  appName?: string;

  appKey?: string;

  appSecret?: string;

  redirectUrl?: string;

  scopes?: string;

  boundIps?: string;

  description?: string;

  status?: string;
}

export interface ConfigPageQuery {

  serialVersionUID?: number;

  configGroup?: string;

  configKey?: string;

  status?: string;
}

export interface ConfigDTO {

  id?: string;

  configGroup?: string;

  configKey?: string;

  configValue?: string;

  valueType?: string;

  defaultValue?: string;

  description?: string;

  isPublic?: number;

  sortOrder?: number;

  status?: string;
}

export interface ConfigBatchDTO {

  items?: ConfigVO[];
}

export interface ConfigVO {

  id?: string;

  configGroup?: string;

  configKey?: string;

  configValue?: string;

  valueType?: string;

  defaultValue?: string;

  description?: string;

  isPublic?: number;

  sortOrder?: number;

  status?: string;
}

export interface DictPageQuery {

  serialVersionUID?: number;

  typeCode?: string;

  typeName?: string;

  status?: string;
}

export interface DictTypeDTO {

  id?: string;

  typeCode?: string;

  typeName?: string;

  description?: string;

  status?: string;
}

export interface DictItemPageQuery {

  serialVersionUID?: number;

  typeCode?: string;

  itemCode?: string;

  status?: string;
}

export interface DictItemDTO {

  id?: string;

  parentId?: string;

  typeCode?: string;

  itemCode?: string;

  itemValue?: string;

  sortOrder?: number;

  description?: string;

  extJson?: string;

  status?: string;
}

export interface DictItemBatchDTO {

  items?: DictItemVO[];
}

export interface DictItemVO {

  id?: string;

  parentId?: string;

  children?: DictItemVO[];

  level?: number;

  path?: string;

  typeCode?: string;

  itemCode?: string;

  itemValue?: string;

  sortOrder?: number;

  description?: string;

  extJson?: string;

  status?: string;
}

export interface EntityVersionPageQuery {

  resourceType?: string;

  resourceKey?: string;

  pageNum?: number;

  DEFAULT_PAGE_SIZE?: number;

  pageSize?: number;
}

export interface ConfigGetRequest {

  key?: string;
}

export interface DictItemGetRequest {

  typeCode?: string;

  itemCode?: string;
}

export interface DictListRequest {

  typeCode?: string;
}

export interface AppValidateRequest {

  appKey?: string;

  appSecret?: string;
}

export interface TenantPageQuery {

  serialVersionUID?: number;

  tenantName?: string;

  tenantCode?: string;

  status?: string;
}

export interface TenantDTO {

  id?: string;

  tenantCode?: string;

  tenantName?: string;

  contactName?: string;

  contactPhone?: string;

  contactEmail?: string;

  planId?: string;

  expireAt?: string;

  datasourceKey?: string;

  status?: string;

  remark?: string;
}

export interface TenantPlanPageQuery {

  serialVersionUID?: number;

  planName?: string;

  status?: string;
}

export interface TenantPlanDTO {

  id?: string;

  planCode?: string;

  planName?: string;

  description?: string;

  sortOrder?: number;

  quotaJson?: string;

  featureJson?: string;

  status?: string;
}

export interface TenantPlanMenuDTO {

  planId?: string;

  menuIds?: string[];
}

export interface VariablePageQuery {

  serialVersionUID?: number;

  variableKey?: string;

  status?: string;
}

export interface VariableDTO {

  id?: string;

  variableKey?: string;

  variableValue?: string;

  valueType?: string;

  description?: string;

  status?: string;
}