/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * TenantPlanController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code TenantPlanController}，共 8 个端点。
 * <p>路径规范: /api/v1/system/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py system} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './base';
import type { PageResponse, TenantPlanDTO, TenantPlanMenuDTO, TenantPlanMenuVO, TenantPlanPageQuery, TenantPlanVO } from './models';

/**
 * page: GET /api/v1/tenant-plan/page
 */
export function page(params: {
    query?: TenantPlanPageQuery;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/v1/tenant-plan/page`, { params });
}

/**
 * listAll: GET /api/v1/tenant-plan/list
 */
export function listAll(): Promise<TenantPlanVO[]> {
  return requestClient.get<TenantPlanVO[]>(`/api/v1/tenant-plan/list`);
}

/**
 * getById: GET /api/v1/tenant-plan/{id}
 */
export function getById(path: {
    id: string;
  }): Promise<TenantPlanVO> {
  return requestClient.get<TenantPlanVO>(`/api/v1/tenant-plan/${id}`);
}

/**
 * save: POST /api/v1/tenant-plan
 */
export function save(data: TenantPlanDTO): Promise<string> {
  return requestClient.post<string>(`/api/v1/tenant-plan`, data);
}

/**
 * update: PUT /api/v1/tenant-plan
 */
export function update(data: TenantPlanDTO): Promise<boolean> {
  return requestClient.put<boolean>(`/api/v1/tenant-plan`, data);
}

/**
 * remove: DELETE /api/v1/tenant-plan/{id}
 */
export function remove(path: {
    id: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/v1/tenant-plan/${id}`);
}

/**
 * listMenus: GET /api/v1/tenant-plan/{planId}/menus
 */
export function listMenus(path: {
    planId: string;
  }): Promise<TenantPlanMenuVO[]> {
  return requestClient.get<TenantPlanMenuVO[]>(`/api/v1/tenant-plan/${planId}/menus`);
}

/**
 * updateMenus: POST /api/v1/tenant-plan/menus
 */
export function updateMenus(data: TenantPlanMenuDTO): Promise<void> {
  return requestClient.post<void>(`/api/v1/tenant-plan/menus`, data);
}
