 
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * AuthEventSseController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code AuthEventSseController}，共 1 个端点。
 * <p>路径规范: /api/v1/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';


/**
 * streamEvents: GET /api/v1/auth/events/stream
 */
export function streamEvents(params: {
    request?: Record<string, unknown>;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/auth/events/stream`, { params });
}
