/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * CompanyController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code CompanyController}，共 6 个端点。
 * <p>路径规范: /api/v1/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { CompanyDTO, CompanyTreeVO, CompanyVO } from './models';

/**
 * list: GET /company/list
 */
export function list(): Promise<CompanyVO[]> {
  return requestClient.get<CompanyVO[]>(`/company/list`);
}

/**
 * tree: GET /company/tree
 */
export function tree(): Promise<CompanyTreeVO[]> {
  return requestClient.get<CompanyTreeVO[]>(`/company/tree`);
}

/**
 * getById: GET /company/{id}
 */
export function getById({ id }: {
    id: string;
  }): Promise<CompanyVO> {
  return requestClient.get<CompanyVO>(`/company/${id}`);
}

/**
 * create: POST /company
 */
export function create(data: CompanyDTO): Promise<string> {
  return requestClient.post<string>(`/company`, data);
}

/**
 * update: PUT /company
 */
export function update(data: CompanyDTO): Promise<boolean> {
  return requestClient.put<boolean>(`/company`, data);
}

/**
 * remove: DELETE /company/{id}
 */
export function remove({ id }: {
    id: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/company/${id}`);
}
