/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * InternalApiController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code InternalApiController}，共 16 个端点。
 * <p>路径规范: /api/v1/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { DepartmentTreeVO, DepartmentVO, UserAccountVO } from './models';

/**
 * getUserInfo: GET /internal/user/info
 */
export function getUserInfo(params: {
    userId?: string;
  }): Promise<UserAccountVO> {
  return requestClient.get<UserAccountVO>(`/internal/user/info`, { params });
}

/**
 * getDeptTree: GET /internal/dept/tree
 */
export function getDeptTree(): Promise<DepartmentTreeVO[]> {
  return requestClient.get<DepartmentTreeVO[]>(`/internal/dept/tree`);
}

/**
 * getDeptList: GET /internal/dept/list
 */
export function getDeptList(): Promise<DepartmentVO[]> {
  return requestClient.get<DepartmentVO[]>(`/internal/dept/list`);
}

/**
 * listUserIdsByRole: GET /internal/user/list-by-role
 */
export function listUserIdsByRole(params: {
    roleCode?: string;
  }): Promise<string[]> {
  return requestClient.get<string[]>(`/internal/user/list-by-role`, { params });
}

/**
 * listRoleCodesByUserId: GET /internal/user/role-codes
 */
export function listRoleCodesByUserId(params: {
    userId?: string;
  }): Promise<string[]> {
  return requestClient.get<string[]>(`/internal/user/role-codes`, { params });
}

/**
 * listDeptIdsByUserId: GET /internal/user/dept-ids
 */
export function listDeptIdsByUserId(params: {
    userId?: string;
  }): Promise<string[]> {
  return requestClient.get<string[]>(`/internal/user/dept-ids`, { params });
}

/**
 * getLeaderByUserId: GET /internal/user/leader
 */
export function getLeaderByUserId(params: {
    userId?: string;
  }): Promise<string> {
  return requestClient.get<string>(`/internal/user/leader`, { params });
}

/**
 * listUserIdsByPosition: GET /internal/user/list-by-position
 */
export function listUserIdsByPosition(params: {
    positionCode?: string;
  }): Promise<string[]> {
  return requestClient.get<string[]>(`/internal/user/list-by-position`, { params });
}

/**
 * getDeptLeaderByDeptId: GET /internal/dept/leader-by-id
 */
export function getDeptLeaderByDeptId(params: {
    deptId?: string;
  }): Promise<string> {
  return requestClient.get<string>(`/internal/dept/leader-by-id`, { params });
}

/**
 * getDeptLeaderByDeptCode: GET /internal/dept/leader-by-code
 */
export function getDeptLeaderByDeptCode(params: {
    deptCode?: string;
  }): Promise<string> {
  return requestClient.get<string>(`/internal/dept/leader-by-code`, { params });
}

/**
 * batchUserNames: POST /internal/user/batch-names
 */
export function batchUserNames(data: string[]): Promise<Record<string, string>> {
  return requestClient.post<Record<string, string>>(`/internal/user/batch-names`, data);
}

/**
 * batchDeptNames: POST /internal/dept/batch-names
 */
export function batchDeptNames(data: string[]): Promise<Record<string, string>> {
  return requestClient.post<Record<string, string>>(`/internal/dept/batch-names`, data);
}

/**
 * batchRoleNames: POST /internal/role/batch-names
 */
export function batchRoleNames(data: string[]): Promise<Record<string, string>> {
  return requestClient.post<Record<string, string>>(`/internal/role/batch-names`, data);
}

/**
 * batchPostNames: POST /internal/post/batch-names
 */
export function batchPostNames(data: string[]): Promise<Record<string, string>> {
  return requestClient.post<Record<string, string>>(`/internal/post/batch-names`, data);
}

/**
 * batchCompanyNames: POST /internal/company/batch-names
 */
export function batchCompanyNames(data: string[]): Promise<Record<string, string>> {
  return requestClient.post<Record<string, string>>(`/internal/company/batch-names`, data);
}

/**
 * verifyPassword: GET /internal/user/verify-password
 */
export function verifyPassword(params: {
    userId?: string;
    password?: string;
  }): Promise<boolean> {
  return requestClient.get<boolean>(`/internal/user/verify-password`, { params });
}
