/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * PostController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code PostController}，共 5 个端点。
 * <p>路径规范: /api/v1/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { PostDTO, PostVO } from './models';

/**
 * list: GET /api/v1/post/list
 */
export function list(): Promise<PostVO[]> {
  return requestClient.get<PostVO[]>(`/api/v1/post/list`);
}

/**
 * getById: GET /api/v1/post/{id}
 */
export function getById(path: {
    id: string;
  }): Promise<PostVO> {
  return requestClient.get<PostVO>(`/api/v1/post/${id}`);
}

/**
 * create: POST /api/v1/post
 */
export function create(data: PostDTO): Promise<string> {
  return requestClient.post<string>(`/api/v1/post`, data);
}

/**
 * update: PUT /api/v1/post
 */
export function update(data: PostDTO): Promise<boolean> {
  return requestClient.put<boolean>(`/api/v1/post`, data);
}

/**
 * remove: DELETE /api/v1/post/{id}
 */
export function remove(path: {
    id: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/v1/post/${id}`);
}
