/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * SamlIdpConfigController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code SamlIdpConfigController}，共 5 个端点。
 * <p>路径规范: /api/v1/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { SamlIdpConfigVO, SamlIdpDTO, SamlIdpPageQuery } from './models';

/**
 * page: GET /api/saml-idp-config/page
 */
export function page(params: {
    query?: SamlIdpPageQuery;
  }): Promise<PageResponse<SamlIdpConfigVO[]>> {
  return requestClient.get<PageResponse<SamlIdpConfigVO[]>>(`/api/saml-idp-config/page`, { params });
}

/**
 * listEnabled: GET /api/saml-idp-config/enabled
 */
export function listEnabled(): Promise<SamlIdpConfigVO[]> {
  return requestClient.get<SamlIdpConfigVO[]>(`/api/saml-idp-config/enabled`);
}

/**
 * create: POST /api/saml-idp-config
 */
export function create(data: SamlIdpDTO): Promise<void> {
  return requestClient.post<void>(`/api/saml-idp-config`, data);
}

/**
 * update: PUT /api/saml-idp-config/{entityId}
 */
export function update({ entityId }: {
    entityId: string;
  }, data: SamlIdpDTO): Promise<void> {
  return requestClient.put<void>(`/api/saml-idp-config/${entityId}`, data);
}

/**
 * delete: DELETE /api/saml-idp-config/{entityId}
 */
export function deleteApi({ entityId }: {
    entityId: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/saml-idp-config/${entityId}`);
}
