/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * UserAccountController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code UserAccountController}，共 23 个端点。
 * <p>路径规范: /api/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { AssignRolesDTO, BatchUserStatusDTO, ChangePasswordDTO, ResetPasswordDTO, SensitiveVerifyDTO, UserAccountDTO, UserAccountPageQuery, UserAccountVO, UserImportResultDTO, UserLoginHistoryVO } from './models';

/**
 * page: GET /api/user/page
 */
export function page(params: {
    query?: UserAccountPageQuery;
  }): Promise<PageResponse<UserAccountVO[]>> {
  return requestClient.get<PageResponse<UserAccountVO[]>>(`/api/user/page`, { params });
}

/**
 * list: GET /api/user/list
 */
export function list(): Promise<UserAccountVO[]> {
  return requestClient.get<UserAccountVO[]>(`/api/user/list`);
}

/**
 * getById: GET /api/user/{id}
 */
export function getById({ id }: {
    id: string;
  }): Promise<UserAccountVO> {
  return requestClient.get<UserAccountVO>(`/api/user/${id}`);
}

/**
 * create: POST /api/user
 */
export function create(data: UserAccountDTO): Promise<string> {
  return requestClient.post<string>(`/api/user`, data);
}

/**
 * update: PUT /api/user
 */
export function update(data: UserAccountDTO): Promise<string> {
  return requestClient.put<string>(`/api/user`, data);
}

/**
 * remove: DELETE /api/user/{id}
 */
export function remove({ id }: {
    id: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/user/${id}`);
}

/**
 * changePassword: POST /api/user/change-password
 */
export function changePassword(data: ChangePasswordDTO): Promise<boolean> {
  return requestClient.post<boolean>(`/api/user/change-password`, data);
}

/**
 * resetPassword: POST /api/user/reset-password
 */
export function resetPassword(data: ResetPasswordDTO): Promise<boolean> {
  return requestClient.post<boolean>(`/api/user/reset-password`, data);
}

/**
 * assignRoles: POST /api/user/{userId}/roles
 */
export function assignRoles({ userId }: {
    userId: string;
  }, data: AssignRolesDTO): Promise<boolean> {
  return requestClient.post<boolean>(`/api/user/${userId}/roles`, data);
}

/**
 * getUserRoles: GET /api/user/{userId}/roles
 */
export function getUserRoles({ userId }: {
    userId: string;
  }): Promise<string[]> {
  return requestClient.get<string[]>(`/api/user/${userId}/roles`);
}

/**
 * importUsers: POST /api/user/import
 */
export function importUsers(params: {
    file?: Record<string, unknown>;
  }): Promise<UserImportResultDTO> {
  return requestClient.post<UserImportResultDTO>(`/api/user/import`, { params });
}

/**
 * downloadImportTemplate: GET /api/user/import-template
 */
export function downloadImportTemplate(params: {
    response?: Record<string, unknown>;
  }): Promise<void> {
  return requestClient.get<void>(`/api/user/import-template`, { params });
}

/**
 * exportUsers: GET /api/user/export
 */
export function exportUsers(params: {
    response?: Record<string, unknown>;
  }): Promise<void> {
  return requestClient.get<void>(`/api/user/export`, { params });
}

/**
 * getLoginHistory: GET /api/user/{userId}/login-history
 */
export function getLoginHistory({ userId }: {
    userId: string;
  }, params: {
    limit?: number;
  }): Promise<UserLoginHistoryVO[]> {
  return requestClient.get<UserLoginHistoryVO[]>(`/api/user/${userId}/login-history`, { params });
}

/**
 * batchRemove: POST /api/user/batch-remove
 */
export function batchRemove(data: BatchUserStatusDTO): Promise<number> {
  return requestClient.post<number>(`/api/user/batch-remove`, data);
}

/**
 * batchEnable: POST /api/user/batch-enable
 */
export function batchEnable(data: BatchUserStatusDTO): Promise<number> {
  return requestClient.post<number>(`/api/user/batch-enable`, data);
}

/**
 * batchDisable: POST /api/user/batch-disable
 */
export function batchDisable(data: BatchUserStatusDTO): Promise<number> {
  return requestClient.post<number>(`/api/user/batch-disable`, data);
}

/**
 * suspend: PUT /api/user/{userId}/lifecycle/suspend
 */
export function suspend({ userId }: {
    userId: string;
  }): Promise<string> {
  return requestClient.put<string>(`/api/user/${userId}/lifecycle/suspend`);
}

/**
 * resume: PUT /api/user/{userId}/lifecycle/resume
 */
export function resume({ userId }: {
    userId: string;
  }): Promise<string> {
  return requestClient.put<string>(`/api/user/${userId}/lifecycle/resume`);
}

/**
 * disable: PUT /api/user/{userId}/lifecycle/disable
 */
export function disable({ userId }: {
    userId: string;
  }): Promise<string> {
  return requestClient.put<string>(`/api/user/${userId}/lifecycle/disable`);
}

/**
 * enable: PUT /api/user/{userId}/lifecycle/enable
 */
export function enable({ userId }: {
    userId: string;
  }): Promise<string> {
  return requestClient.put<string>(`/api/user/${userId}/lifecycle/enable`);
}

/**
 * resign: PUT /api/user/{userId}/lifecycle/resign
 */
export function resign({ userId }: {
    userId: string;
  }): Promise<string> {
  return requestClient.put<string>(`/api/user/${userId}/lifecycle/resign`);
}

/**
 * sensitiveVerify: POST /api/user/sensitive-verify
 */
export function sensitiveVerify(data: SensitiveVerifyDTO): Promise<boolean> {
  return requestClient.post<boolean>(`/api/user/sensitive-verify`, data);
}
