/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * WebAuthnController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code WebAuthnController}，共 9 个端点。
 * <p>路径规范: /api/userinfo/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py userinfo} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { LoginVO, WebAuthnCredentialVO } from './models';

/**
 * getPasskeyRegistrationOptions: GET /api/webauthn/passkey/registration/options
 */
export function getPasskeyRegistrationOptions(params: {
    username?: string;
    displayName?: string;
  }): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/api/webauthn/passkey/registration/options`, { params });
}

/**
 * getPasskeyAuthenticationOptions: GET /api/webauthn/passkey/options
 */
export function getPasskeyAuthenticationOptions(): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/api/webauthn/passkey/options`);
}

/**
 * verifyPasskeyAuthentication: POST /api/webauthn/passkey/verify
 */
export function verifyPasskeyAuthentication(data: Record<string, Record<string, unknown>>): Promise<LoginVO> {
  return requestClient.post<LoginVO>(`/api/webauthn/passkey/verify`, data);
}

/**
 * getRegistrationOptions: GET /api/webauthn/registration/options
 */
export function getRegistrationOptions(params: {
    username?: string;
    displayName?: string;
  }): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/api/webauthn/registration/options`, { params });
}

/**
 * verifyRegistration: POST /api/webauthn/registration/verify
 */
export function verifyRegistration(data: Record<string, Record<string, unknown>>): Promise<void> {
  return requestClient.post<void>(`/api/webauthn/registration/verify`, data);
}

/**
 * getAuthenticationOptions: GET /api/webauthn/authentication/options
 */
export function getAuthenticationOptions(params: {
    userId?: string;
  }): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/api/webauthn/authentication/options`, { params });
}

/**
 * verifyAuthentication: POST /api/webauthn/authentication/verify
 */
export function verifyAuthentication(data: Record<string, Record<string, unknown>>): Promise<LoginVO> {
  return requestClient.post<LoginVO>(`/api/webauthn/authentication/verify`, data);
}

/**
 * listCredentials: GET /api/webauthn/credentials
 */
export function listCredentials(): Promise<WebAuthnCredentialVO[]> {
  return requestClient.get<WebAuthnCredentialVO[]>(`/api/webauthn/credentials`);
}

/**
 * deleteCredential: DELETE /api/webauthn/credentials/{credentialId}
 */
export function deleteCredential({ credentialId }: {
    credentialId: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/webauthn/credentials/${credentialId}`);
}
