<!--
 * 技能引擎管理（列表页）
 *
 * <p>提供 Agent 技能的管理能力，包括查看技能详情、执行技能、清除沙箱缓存。
 * 消费 SkillController 4 个端点（auto-generated by bash/gen-contract.py）。
 *
 * @path apps/agent-web/src/views/skill/index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 技能引擎管理（列表页）
 * <p>管理 Agent 可调用的技能，支持查看、执行、清除沙箱缓存。
 *
 * @author ydsz-team
 * @since 1.0.0
*/
import type { VxeTableGridOptions } from '@ydsz/plugins/vxe-table';
import { Page, useYdModal } from '@ydsz/common-ui';
import { createLogger } from '@ydsz/utils';
import { YdBadge, YdButton, YdInput } from '@ydsz-core/ydsz-ui';
import { executeSkill, invalidateSandbox, listSkills } from '#/api/skill';
import type { SkillExecutionRequestDTO } from '#/api/models';
import { h, reactive, ref } from 'vue';
import { useYDSZVxeGrid } from '#/adapter/vxe-table';
import { useI18n } from 'vue-i18n';
import SkillDetailDrawer from './skill-detail-drawer.vue';

const logger = createLogger('agent-skill');

defineOptions({ name: 'SkillManagement' });

const { t } = useI18n();

/** 技能列表数据 */
const skillList = ref<Record<string, unknown>[]>([]);

/** 抽屉控制 */
const drawerVisible = ref<boolean>(false);
const selectedSkillCode = ref<string>('');

/** 执行弹窗表单数据 */
const executeFormData = reactive<SkillExecutionRequestDTO>({
  skillCode: '',
  inputParams: undefined,
  timeoutMs: 0,
  envVariables: undefined,
});

/** 执行弹窗结果 */
const executeResult = ref<string>('');
const executeLoading = ref<boolean>(false);

/**
 * 类型守卫：安全获取字符串字段
 */
function safeStringField(record: Record<string, unknown>, field: string): string {
  const val = record[field];
  return val != null ? String(val) : '';
}

/**
 * 获取技能类型标签样式
 */
function getSkillTypeTagType(
  type?: string,
): 'success' | 'warning' | 'info' | 'danger' | 'primary' {
  switch ((type ?? '').toUpperCase()) {
    case 'SANDBOX':
      return 'primary';
    case 'FUNCTION':
      return 'success';
    case 'SCRIPT':
      return 'warning';
    case 'HTTP':
      return 'info';
    default:
      return 'danger';
  }
}

/** VxeTable 配置 */
const gridOptions: VxeTableGridOptions = {
  columns: [
    { type: 'seq', width: 50, title: t('common.seq') },
    {
      field: 'skillCode',
      title: t('business.skill.skillCode') || '技能编码',
      width: 160,
    },
    {
      field: 'skillName',
      title: t('business.skill.skillName') || '技能名称',
      width: 160,
    },
    {
      field: 'skillType',
      title: t('business.skill.skillType') || '类型',
      width: 100,
      slots: {
        default: ({ row }) =>
          h(
            YdBadge,
            { variant: getSkillTypeTagType(safeStringField(row, 'skillType')) as any },
            () => safeStringField(row, 'skillType') || '-',
          ),
      },
    },
    {
      field: 'description',
      title: t('business.skill.description') || '描述',
      minWidth: 180,
      showOverflow: true,
    },
    {
      field: 'version',
      title: t('business.skill.version') || '版本',
      width: 80,
    },
    {
      field: 'status',
      title: t('business.skill.status') || '状态',
      width: 100,
      slots: {
        default: ({ row }) =>
          h(
            YdBadge,
            {
              variant: safeStringField(row, 'status') === 'ACTIVE' ? 'default' : 'outline',
            },
            () => safeStringField(row, 'status') || '-',
          ),
      },
    },
    {
      field: 'updatedAt',
      title: t('business.skill.updatedAt') || '更新时间',
      width: 160,
    },
    {
      field: 'action',
      title: t('business.skill.actions') || '操作',
      width: 220,
      fixed: 'right',
      slots: {
        default: ({ row }) =>
          h('div', { class: 'flex gap-1' }, [
            h(
              YdButton,
              {
                size: 'sm',
                variant: 'link',
                onClick: () => handleView(row),
              },
              () => t('business.skill.view') || '查看',
            ),
            h(
              YdButton,
              {
                size: 'sm',
                variant: 'link',
                onClick: () => handleExecute(row),
              },
              () => t('business.skill.execute') || '执行',
            ),
            h(
              YdButton,
              {
                size: 'sm',
                variant: 'link',
                onClick: () => handleInvalidateCache(row),
              },
              () => t('business.skill.clearCache') || '清除缓存',
            ),
          ]),
      },
    },
  ],
  height: 'auto',
  pagerConfig: { pageSize: 20, pageSizes: [10, 20, 50, 100] },
  proxyConfig: {
    ajax: {
      query: async () => {
        const items = await fetchSkillList();
        return { items, total: items.length };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, search: true, zoom: true },
  formConfig: {
    enabled: true,
    items: [
      {
        field: 'skillCode',
        title: t('business.skill.skillCode') || '技能编码',
        itemRender: {
          name: 'YdInput',
          props: {
            placeholder: t('business.skill.searchPlaceholder') || '按技能编码/名称搜索',
          },
        },
      },
      {
        field: 'skillName',
        title: t('business.skill.skillName') || '技能名称',
        itemRender: {
          name: 'YdInput',
          props: {
            placeholder: t('business.skill.searchPlaceholder') || '按技能编码/名称搜索',
          },
        },
      },
    ],
  },
};

const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });

/** 执行弹窗 */
const [ExecuteModal, executeModalApi] = useYdModal({
  connectedComponent: undefined,
});

/**
 * 获取技能列表
 */
async function fetchSkillList(): Promise<Record<string, unknown>[]> {
  try {
    const data = await listSkills();
    skillList.value = data ?? [];
    return skillList.value;
  } catch {
    skillList.value = [];
    return [];
  }
}

/**
 * 查看技能详情
 */
function handleView(row: Record<string, unknown>): void {
  const code = safeStringField(row, 'skillCode');
  selectedSkillCode.value = code;
  drawerVisible.value = true;
}

/**
 * 执行技能弹窗
 */
function handleExecute(row: Record<string, unknown>): void {
  executeFormData.skillCode = safeStringField(row, 'skillCode');
  executeFormData.inputParams = undefined;
  executeFormData.timeoutMs = 0;
  executeFormData.envVariables = undefined;
  executeResult.value = '';
  executeModalApi.open();
}

/**
 * 提交执行技能
 */
async function handleSubmitExecute(): Promise<void> {
  executeLoading.value = true;
  executeResult.value = '';
  try {
    const result = await executeSkill(executeFormData);
    executeResult.value = JSON.stringify(result, null, 2);
    showToast.success(t('business.skill.executeSuccess') || '技能执行成功');
  } catch {
    executeResult.value = t('business.skill.executeFailed') || '技能执行失败';
  } finally {
    executeLoading.value = false;
  }
}

/**
 * 清除沙箱缓存
 */
async function handleInvalidateCache(row: Record<string, unknown>): Promise<void> {
  try {
    await YdConfirm(
      t('business.skill.invalidateConfirmContent') || '确定要使当前沙箱缓存失效吗？',
      {
        title: t('business.skill.invalidateConfirmTitle') || '清除缓存确认',
        type: 'warning',
      },
    );
  } catch {
    logger.debug('用户取消清除沙箱缓存操作');
    return;
  }

  try {
    await invalidateSandbox();
    showToast.success(t('business.skill.invalidateSuccess') || '沙箱缓存已清除');
  } catch {
    showToast.error(t('business.skill.invalidateFailed') || '清除缓存失败');
  }
}

/** 初始加载 */
void fetchSkillList();
</script>

<template>
  <Page auto-content-height>
    <Grid :table-title="t('business.skill.title') || '技能引擎'" />

    <!-- 详情抽屉 -->
    <SkillDetailDrawer
      v-model="drawerVisible"
      :skill-code="selectedSkillCode"
    />

    <!-- 执行弹窗 -->
    <ExecuteModal
      :title="t('business.skill.executeTitle') || '执行技能'"
      width="600px"
    >
      <div class="space-y-4 pt-2">
        <!-- 技能编码（只读） -->
        <div>
          <label class="mb-1 block text-sm font-medium text-text-secondary">
            {{ t('business.skill.skillCode') || '技能编码' }}
          </label>
          <YdInput
            :model-value="executeFormData.skillCode"
            disabled
          />
        </div>

        <!-- 输入参数 JSON -->
        <div>
          <label class="mb-1 block text-sm font-medium text-text-secondary">
            {{ t('business.skill.inputParams') || '输入参数' }}
          </label>
          <YdInput
            :model-value="executeFormData.inputParams ? JSON.stringify(executeFormData.inputParams) : ''"
            type="textarea"
            :rows="6"
            :placeholder="t('business.skill.executeParamsPlaceholder') || '请输入参数 JSON'"
            @update:model-value="
              (val: string) => {
                try {
                  executeFormData.inputParams = val ? JSON.parse(val) : undefined;
                } catch {
                  executeFormData.inputParams = undefined;
                }
              }
            "
          />
        </div>

        <!-- 超时时间 -->
        <div>
          <label class="mb-1 block text-sm font-medium text-text-secondary">
            {{ t('business.skill.timeoutMs') || '超时时间(ms)' }}
          </label>
          <YdInput
            :model-value="String(executeFormData.timeoutMs ?? 0)"
            @update:model-value="
              (val: string) => {
                executeFormData.timeoutMs = Number(val) || 0;
              }
            "
          />
        </div>

        <!-- 环境变量 -->
        <div>
          <label class="mb-1 block text-sm font-medium text-text-secondary">
            {{ t('business.skill.envVariables') || '环境变量' }}
          </label>
          <YdInput
            :model-value="executeFormData.envVariables ? JSON.stringify(executeFormData.envVariables) : ''"
            type="textarea"
            :rows="3"
            :placeholder="'{\"KEY\": \"value\"}'"
            @update:model-value="
              (val: string) => {
                try {
                  executeFormData.envVariables = val
                    ? (JSON.parse(val) as Record<string, string>)
                    : undefined;
                } catch {
                  executeFormData.envVariables = undefined;
                }
              }
            "
          />
        </div>

        <!-- 执行结果 -->
        <div v-if="executeResult">
          <label class="mb-1 block text-sm font-medium text-text-secondary">
            {{ t('business.skill.executeResult') || '执行结果' }}
          </label>
          <pre class="max-h-60 overflow-auto rounded-md bg-accent/60 p-3 text-xs text-text-primary">{{ executeResult }}</pre>
        </div>
      </div>

      <template #footer>
        <YdButton
          variant="outline"
          @click="executeModalApi.close()"
        >
          {{ t('common.cancel') || '取消' }}
        </YdButton>
        <YdButton
          :loading="executeLoading"
          @click="handleSubmitExecute"
        >
          {{ t('business.skill.execute') || '执行' }}
        </YdButton>
      </template>
    </ExecuteModal>
  </Page>
</template>
