/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * DictController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code DictController}，共 6 个端点。
 * <p>路径规范: /api/v1/system/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py system} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { DictPageQuery, DictTypeDTO, DictTypeVO } from './models';

/**
 * page: GET /api/dict/type/page
 */
export function page(params: {
    query?: DictPageQuery;
  }): Promise<PageResponse<DictTypeVO[]>> {
  return requestClient.get<PageResponse<DictTypeVO[]>>(`/api/dict/type/page`, { params });
}

/**
 * getById: GET /api/dict/type/{id}
 */
export function getById({ id }: {
    id: string;
  }): Promise<DictTypeVO> {
  return requestClient.get<DictTypeVO>(`/api/dict/type/${id}`);
}

/**
 * save: POST /api/dict/type
 */
export function save(data: DictTypeDTO): Promise<string> {
  return requestClient.post<string>(`/api/dict/type`, data);
}

/**
 * update: PUT /api/dict/type
 */
export function update(data: DictTypeDTO): Promise<boolean> {
  return requestClient.put<boolean>(`/api/dict/type`, data);
}

/**
 * remove: DELETE /api/dict/type/{id}
 */
export function remove({ id }: {
    id: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/api/dict/type/${id}`);
}

/**
 * listAll: GET /api/dict/type/all
 */
export function listAll(): Promise<DictTypeVO[]> {
  return requestClient.get<DictTypeVO[]>(`/api/dict/type/all`);
}
