/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * DictVersionController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code DictVersionController}，共 3 个端点。
 * <p>路径规范: /api/v1/system/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py system} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { EntityVersionPageQuery, EntityVersionVO } from './models';

/**
 * listByTypeCode: GET /api/v1/dict/version/{typeCode}
 */
export function listByTypeCode({ typeCode }: {
    typeCode: string;
  }): Promise<EntityVersionVO[]> {
  return requestClient.get<EntityVersionVO[]>(`/api/v1/dict/version/${typeCode}`);
}

/**
 * pageByTypeCode: GET /api/v1/dict/version/page
 */
export function pageByTypeCode(params: {
    query?: EntityVersionPageQuery;
  }): Promise<PageResponse<EntityVersionVO[]>> {
  return requestClient.get<PageResponse<EntityVersionVO[]>>(`/api/v1/dict/version/page`, { params });
}

/**
 * rollback: POST /api/v1/dict/version/{typeCode}/rollback
 */
export function rollback({ typeCode }: {
    typeCode: string;
  }, params: {
    targetVersion?: string;
  }): Promise<string> {
  return requestClient.post<string>(`/api/v1/dict/version/${typeCode}/rollback`, { params });
}
