/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * InternalApiController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code InternalApiController}，共 4 个端点。
 * <p>路径规范: /api/v1/system/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py system} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { AppValidateRequest, ConfigGetRequest, DictItemGetRequest, DictListRequest } from './models';

/**
 * getConfig: POST /api/internal/config/get
 */
export function getConfig(data: ConfigGetRequest): Promise<string> {
  return requestClient.post<string>(`/api/internal/config/get`, data);
}

/**
 * getDictItem: POST /api/internal/dict/item
 */
export function getDictItem(data: DictItemGetRequest): Promise<string> {
  return requestClient.post<string>(`/api/internal/dict/item`, data);
}

/**
 * listDictItems: POST /api/internal/dict/list
 */
export function listDictItems(data: DictListRequest): Promise<string[]> {
  return requestClient.post<string[]>(`/api/internal/dict/list`, data);
}

/**
 * validateClient: POST /api/internal/app/validate
 */
export function validateClient(data: AppValidateRequest): Promise<boolean> {
  return requestClient.post<boolean>(`/api/internal/app/validate`, data);
}
