/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * 后端统一响应结构（对齐 {@code YdszResponse<T>}）
 * <p>注意: requestClient 拦截器已按 successCode='A00000' 解包 data，
 * 业务调用处泛型直接写 data 类型；此处类型仅供契约说明使用。
 */
export interface YdszResponse<T = unknown> {
  /** 业务成功码（A00000 表示成功） */
  code: string;
  /** 提示信息 */
  msg: string;
  /** 业务数据 */
  data: T;
  /** 链路追踪 ID */
  traceId?: string;
  requestId?: string;
  spanId?: string;
  timestamp?: number;
  extensions?: Record<string, unknown>;
}

/** 分页响应（对齐后端 {@code PageResponse<T>}：total/pageNum/pageSize 平铺 + data 分页数据） */
export interface PageResponse<T = unknown> {
  /** 总记录数 */
  total?: number;
  /** 当前页码（从 1 开始） */
  pageNum?: number;
  /** 每页记录数 */
  pageSize?: number;
  /** 分页数据（由后端工厂方法填充） */
  data: T;
}

/** 分页查询参数（前端通用约定） */
export interface PageQuery {
  pageNum?: number;
  pageSize?: number;
}

export interface AppInfoPageQuery {

  serialVersionUID?: number;

  appName?: string;

  status?: string;
}

export interface AppInfoDTO {

  id?: string;

  appCode?: string;

  appName?: string;

  appKey?: string;

  appSecret?: string;

  redirectUrl?: string;

  scopes?: string;

  boundIps?: string;

  description?: string;

  status?: string;
}

export interface ConfigPageQuery {

  serialVersionUID?: number;

  configGroup?: string;

  configKey?: string;

  status?: string;
}

export interface ConfigDTO {

  id?: string;

  configGroup?: string;

  configKey?: string;

  configValue?: string;

  valueType?: string;

  defaultValue?: string;

  description?: string;

  isPublic?: number;

  sortOrder?: number;

  status?: string;
}

export interface ConfigBatchDTO {

  items?: ConfigVO[];
}

export interface ConfigVO {

  id?: string;

  configGroup?: string;

  configKey?: string;

  configValue?: string;

  valueType?: string;

  defaultValue?: string;

  description?: string;

  isPublic?: number;

  sortOrder?: number;

  status?: string;
}

export interface DictPageQuery {

  serialVersionUID?: number;

  typeCode?: string;

  typeName?: string;

  status?: string;
}

export interface DictTypeDTO {

  id?: string;

  typeCode?: string;

  typeName?: string;

  description?: string;

  status?: string;
}

export interface DictItemPageQuery {

  serialVersionUID?: number;

  typeCode?: string;

  itemCode?: string;

  status?: string;
}

export interface DictItemDTO {

  id?: string;

  parentId?: string;

  typeCode?: string;

  itemCode?: string;

  itemValue?: string;

  sortOrder?: number;

  description?: string;

  extJson?: string;

  status?: string;
}

export interface DictItemBatchDTO {

  items?: DictItemVO[];
}

export interface DictItemVO {

  id?: string;

  parentId?: string;

  children?: DictItemVO[];

  level?: number;

  path?: string;

  typeCode?: string;

  itemCode?: string;

  itemValue?: string;

  sortOrder?: number;

  description?: string;

  extJson?: string;

  status?: string;
}

export interface EntityVersionPageQuery {

  resourceType?: string;

  resourceKey?: string;

  pageNum?: number;

  DEFAULT_PAGE_SIZE?: number;

  pageSize?: number;
}

export interface ConfigGetRequest {

  key?: string;
}

export interface DictItemGetRequest {

  typeCode?: string;

  itemCode?: string;
}

export interface DictListRequest {

  typeCode?: string;
}

export interface AppValidateRequest {

  appKey?: string;

  appSecret?: string;
}

export interface TenantPageQuery {

  serialVersionUID?: number;

  tenantName?: string;

  tenantCode?: string;

  status?: string;
}

export interface TenantDTO {

  id?: string;

  tenantCode?: string;

  tenantName?: string;

  contactName?: string;

  contactPhone?: string;

  contactEmail?: string;

  planId?: string;

  expireAt?: string;

  datasourceKey?: string;

  status?: string;

  remark?: string;
}

export interface TenantPlanPageQuery {

  serialVersionUID?: number;

  planName?: string;

  status?: string;
}

export interface TenantPlanDTO {

  id?: string;

  planCode?: string;

  planName?: string;

  description?: string;

  sortOrder?: number;

  quotaJson?: string;

  featureJson?: string;

  status?: string;
}

export interface TenantPlanMenuDTO {

  planId?: string;

  menuIds?: string[];
}

export interface VariablePageQuery {

  serialVersionUID?: number;

  variableKey?: string;

  status?: string;
}

export interface VariableDTO {

  id?: string;

  variableKey?: string;

  variableValue?: string;

  valueType?: string;

  description?: string;

  status?: string;
}

export interface AppInfoVO {

  id?: string;

  appCode?: string;

  appName?: string;

  appKey?: string;

  appSecret?: string;

  redirectUrl?: string;

  scopes?: string;

  boundIps?: string;

  description?: string;

  status?: string;
}

export interface AuditLog {

  serialVersionUID?: number;

  id?: string;

  auditType?: number;

  action?: number;

  status?: number;

  module?: string;

  content?: string;

  businessNo?: string;

  operatorId?: string;

  operatorName?: string;

  operationTime?: string;

  ipAddress?: string;

  requestParams?: string;

  responseResult?: string;

  errorMessage?: string;

  costTime?: number;

  appKey?: string;

  tenantId?: string;

  traceId?: string;

  createdAt?: string;
}

export interface CursorPageResponse {

  records?: Record<string, unknown>[];

  nextCursor?: string;

  hasMore?: boolean;

  size?: number;
}

export interface ImportResult {

  totalCount?: number;

  successCount?: number;

  failCount?: number;

  skipCount?: number;

  errors?: string[];

  message?: string;
}

export interface EntityVersionVO {

  id?: string;

  resourceType?: string;

  resourceKey?: string;

  resourceGroup?: string;

  version?: string;

  changeLog?: string;

  effectiveDate?: string;

  snapshotJson?: string;
}

export interface DictTypeVO {

  id?: string;

  typeCode?: string;

  typeName?: string;

  description?: string;

  status?: string;
}

export interface FrontendInitVO {

  publicConfigs?: Record<string, unknown>;

  dictMap?: Record<string, unknown>;

  systemVersion?: string;

  tenantId?: string;

  userId?: string;
}

export interface TenantVO {

  id?: string;

  tenantCode?: string;

  tenantName?: string;

  contactName?: string;

  contactPhone?: string;

  contactEmail?: string;

  planId?: string;

  expireAt?: string;

  datasourceKey?: string;

  status?: string;

  remark?: string;

  createdAt?: string;

  updatedAt?: string;
}

export interface TenantPlanVO {

  id?: string;

  planCode?: string;

  planName?: string;

  description?: string;

  sortOrder?: number;

  quotaJson?: string;

  featureJson?: string;
}

export interface TenantPlanMenuVO {

  id?: string;

  planId?: string;

  menuId?: string;
}

export interface VariableVO {

  id?: string;

  variableKey?: string;

  variableValue?: string;

  valueType?: string;

  description?: string;

  status?: string;
}