/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * TenantController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code TenantController}，共 6 个端点。
 * <p>路径规范: /api/v1/system/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py system} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { TenantDTO, TenantPageQuery, TenantVO } from './models';

/**
 * listAccessible: GET /tenant/accessible
 */
export function listAccessible(): Promise<TenantVO[]> {
  return requestClient.get<TenantVO[]>(`/tenant/accessible`);
}

/**
 * page: GET /tenant/page
 */
export function page(params: {
    query?: TenantPageQuery;
  }): Promise<PageResponse<TenantVO[]>> {
  return requestClient.get<PageResponse<TenantVO[]>>(`/tenant/page`, { params });
}

/**
 * getById: GET /tenant/{id}
 */
export function getById({ id }: {
    id: string;
  }): Promise<TenantVO> {
  return requestClient.get<TenantVO>(`/tenant/${id}`);
}

/**
 * save: POST /tenant
 */
export function save(data: TenantDTO): Promise<string> {
  return requestClient.post<string>(`/tenant`, data);
}

/**
 * update: PUT /tenant
 */
export function update(data: TenantDTO): Promise<boolean> {
  return requestClient.put<boolean>(`/tenant`, data);
}

/**
 * remove: DELETE /tenant/{id}
 */
export function remove({ id }: {
    id: string;
  }): Promise<boolean> {
  return requestClient.delete<boolean>(`/tenant/${id}`);
}
