<!--
 * 系统配置管理页面 — 参数配置的分页列表、搜索、新增、编辑、删除
 *
 * @path apps\system-web\src\views\config\index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 系统配置（列表页）
 * <p>消费后端契约 ConfigController（src/api/config.ts，auto-generated by bash/gen-contract.py）的系统配置列表页：
 * 分页查询 page、编辑/删除（remove）。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import type { VxeTableGridOptions } from '@ydsz/plugins/vxe-table';

import { Page, useYDSZModal } from '@ydsz/common-ui';

import { ElButton, ElMessage, ElMessageBox, ElTag } from 'element-plus';
import { h } from 'vue';
import { useI18n } from 'vue-i18n';

import { useYDSZVxeGrid } from '#/adapter/vxe-table';
import { page, remove } from '#/api/config';
import type { ConfigPageQuery, ConfigVO, PageQuery } from '#/api/models';

import ConfigForm from './config-form.vue';

defineOptions({ name: 'ConfigManagement' });

const { t } = useI18n();

/** 行类型：真实契约 ConfigVO（字段以 models.ts 为准） */
type ConfigRow = ConfigVO;

/** 分页查询参数：契约 ConfigPageQuery + 通用分页字段（models.ts PageQuery） */
type ConfigPageQueryParams = ConfigPageQuery & PageQuery;

/** 状态是否启用（后端 status 为字符串，兼容 '1' / 'ENABLED' 两种取值） */
function isEnabled(status?: string): boolean {
  return status === '1' || status === 'ENABLED';
}

const gridOptions: VxeTableGridOptions<ConfigRow> = {
  columns: [
    { type: 'seq', width: 50, title: '序号' },
    { field: 'configKey', title: t('configKey'), width: 180 },
    { field: 'configValue', title: t('configValue'), width: 200 },
    { field: 'configGroup', title: t('configGroup'), width: 130 },
    { field: 'valueType', title: '值类型', width: 100 },
    { field: 'isPublic', title: '公开', width: 70 },
    {
      field: 'status',
      title: t('status'),
      width: 80,
      slots: {
        default: ({ row }) => {
          const config = row as ConfigRow;
          return h(
            ElTag,
            { type: isEnabled(config.status) ? 'success' : 'info' },
            () => (isEnabled(config.status) ? '启用' : '禁用'),
          );
        },
      },
    },
    { field: 'description', title: t('description'), width: 180 },
    {
      field: 'action',
      title: t('action'),
      width: 140,
      fixed: 'right',
      slots: {
        default: ({ row }) => {
          const config = row as ConfigRow;
          return h('div', { class: 'flex gap-1' }, [
            h(ElButton, { size: 'small', link: true, type: 'primary', onClick: () => handleEdit(config) }, () => t('edit')),
            h(ElButton, { size: 'small', link: true, type: 'danger', onClick: () => handleDelete(config) }, () => t('delete')),
          ]);
        },
      },
    },
  ],
  height: 'auto',
  pagerConfig: { pageSize: 20, pageSizes: [10, 20, 50, 100] },
  proxyConfig: {
    ajax: {
      query: async ({ page: pageInfo }, formValues) => {
        const query: ConfigPageQueryParams = {
          pageNum: pageInfo.currentPage,
          pageSize: pageInfo.pageSize,
          ...formValues,
        };
        const res = await page({ query });
        return { items: res.data ?? [], total: res.total ?? 0 };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, search: true, zoom: true },
  formConfig: {
    enabled: true,
    items: [
      { field: 'configKey', title: t('configKey'), itemRender: { name: 'Input', props: { placeholder: t('configKey') } } },
      { field: 'configGroup', title: t('configGroup'), itemRender: { name: 'Input', props: { placeholder: t('configGroup') } } },
    ],
  },
};

const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });

const [ConfigFormModal, configFormApi] = useYDSZModal({ connectedComponent: ConfigForm });

function handleAdd() {
  configFormApi.open();
}

function handleEdit(row: ConfigRow) {
  configFormApi.setData({ record: row });
  configFormApi.open();
}

async function handleDelete(row: ConfigRow) {
  try {
    await ElMessageBox.confirm(`确定删除「${row.configKey ?? ''}」吗？`, '删除确认', { type: 'warning' });
    if (row.id) await remove({ id: row.id });
    ElMessage.success(t('operationSuccess'));
    gridApi.query();
  } catch {
    // 用户取消或请求失败
  }
}
</script>

<template>
  <Page auto-content-height>
    <Grid table-title="系统配置">
      <template #toolbar-tools>
        <ElButton type="primary" @click="handleAdd">{{ t('create') }}</ElButton>
      </template>
    </Grid>
    <ConfigFormModal @success="gridApi.query()" />
  </Page>
</template>