# Batch 1: af-ZA through da-DK
T["af-ZA"] = {
    "messageTitle": "Boodskapbestuur", "messageId": "Boodskap-ID",
    "messageChannel": "Kanaal", "messageRecipient": "Ontvanger",
    "messageSubject": "Onderwerp", "messageSendTime": "Gestuur om",
    "messageConfirmDelete": 'Is jy seker jy wil "{id}" uitvee?',
    "operationSuccess": "Sukses",
    "templateName": "Sjabloonnaam", "templateContent": "Sjablooninhoud",
    "templateType": "Sjabloontipe", "routeName": "Roetenaam",
    "routePriority": "Prioriteit", "routeCondition": "Roete-voorwaarde",
    "preferenceName": "Voorkeur-naam", "dndEnabled": "Moenie-Storen",
    "dndStart": "Moenie-Storen Begin", "dndEnd": "Moenie-Storen Einde",
    "confirmDelete": 'Is jy seker jy wil "{id}" uitvee?',
    "create": "Skep", "edit": "Wysig", "delete": "Verwyder",
    "msg_message": "Boodskap", "msg_messageList": "Boodskaplys",
    "msg_batchSend": "Bondelstuur", "msg_deadLetter": "Dead Letter",
    "msg_template": "Sjabloon", "msg_templateList": "Sjabloonlys",
    "msg_notification": "Kennisgewing", "msg_notificationList": "Kennisgewinglys",
    "msg_route": "Roete", "msg_routeRule": "Roete-reel",
    "msg_preference": "Voorkeur", "msg_messagePreference": "Boodskapvoorkeur",
}
T["am-ET"] = {
    "messageTitle": "የመልእክት አስተዳደር", "messageId": "የመልእክት መታወቂያ",
    "messageChannel": "ቻናል", "messageRecipient": "ተቀባይ",
    "messageSubject": "ርዕስ", "messageSendTime": "የተላከበት ጊዜ",
    "messageConfirmDelete": 'እርግጠኛ ነዎት "{id}" ማስወገድ ይፈልጋሉ?',
    "operationSuccess": "ተሳክቷል",
    "templateName": "የአብነት ስም", "templateContent": "የአብነት ይዘት",
    "templateType": "የአብነት አይነት", "routeName": "የመንገድ ስም",
    "routePriority": "ቅድሚያ", "routeCondition": "የመንገድ ሁኔታ",
    "preferenceName": "የምርጫ ስም", "dndEnabled": "አትረታታ",
    "dndStart": "አትረታታ ጀምር", "dndEnd": "አትረታታ ጨርስ",
    "confirmDelete": 'እርግጠኛ ነዎት "{id}" ማስወገድ ይፈልጋሉ?',
    "create": "ፍጠር", "edit": "አርትዕ", "delete": "ሰርዝ",
    "msg_message": "መልእክት", "msg_messageList": "የመልእክት ዝርዝር",
    "msg_batchSend": "የቡድን መላኪያ", "msg_deadLetter": "የሞተ ደብዳቤ",
    "msg_template": "አብነት", "msg_templateList": "የአብነት ዝርዝር",
    "msg_notification": "ማሳወቂያ", "msg_notificationList": "የማሳወቂያ ዝርዝር",
    "msg_route": "መንገድ", "msg_routeRule": "የመንገድ ደንብ",
    "msg_preference": "ምርጫ", "msg_messagePreference": "የመልእክት ምርጫ",
}
T["ar-EG"] = {
    "messageTitle": "إدارة الرسائل", "messageId": "معرف الرسالة",
    "messageChannel": "القناة", "messageRecipient": "المستلم",
    "messageSubject": "الموضوع", "messageSendTime": "وقت الإرسال",
    "messageConfirmDelete": 'هل أنت متأكد من حذف "{id}"؟',
    "operationSuccess": "تمت العملية بنجاح",
    "templateName": "اسم القالب", "templateContent": "محتوى القالب",
    "templateType": "نوع القالب", "routeName": "اسم المسار",
    "routePriority": "الأولوية", "routeCondition": "شرط المسار",
    "preferenceName": "اسم التفضيل", "dndEnabled": "عدم الإزعاج",
    "dndStart": "بدء عدم الإزعاج", "dndEnd": "إنهاء عدم الإزعاج",
    "confirmDelete": 'هل أنت متأكد من حذف "{id}"؟',
    "create": "إضافة", "edit": "تعديل", "delete": "حذف",
    "msg_message": "رسالة", "msg_messageList": "قائمة الرسائل",
    "msg_batchSend": "إرسال مجمّع", "msg_deadLetter": "الرسائل الميتة",
    "msg_template": "قالب", "msg_templateList": "قائمة القوالب",
    "msg_notification": "إشعار", "msg_notificationList": "قائمة الإشعارات",
    "msg_route": "مسار", "msg_routeRule": "قاعدة المسار",
    "msg_preference": "تفضيل", "msg_messagePreference": "تفضيل الرسائل",
}
T["ar-SA"] = {
    "messageTitle": "إدارة الرسائل", "messageId": "معرّف الرسالة",
    "messageChannel": "القناة", "messageRecipient": "المستلم",
    "messageSubject": "الموضوع", "messageSendTime": "وقت الإرسال",
    "messageConfirmDelete": 'هل أنت متأكد من حذف "{id}"؟',
    "operationSuccess": "تمت العملية بنجاح",
    "templateName": "اسم القالب", "templateContent": "محتوى القالب",
    "templateType": "نوع القالب", "routeName": "اسم المسار",
    "routePriority": "الأولوية", "routeCondition": "شرط المسار",
    "preferenceName": "اسم التفضيل", "dndEnabled": "عدم الإزعاج",
    "dndStart": "بدء عدم الإزعاج", "dndEnd": "إنهاء عدم الإزعاج",
    "confirmDelete": 'هل أنت متأكد من حذف "{id}"؟',
    "create": "إضافة", "edit": "تعديل", "delete": "حذف",
    "msg_message": "رسالة", "msg_messageList": "قائمة الرسائل",
    "msg_batchSend": "إرسال مجمّع", "msg_deadLetter": "الرسائل الميتة",
    "msg_template": "قالب", "msg_templateList": "قائمة القوالب",
    "msg_notification": "إشعار", "msg_notificationList": "قائمة الإشعارات",
    "msg_route": "مسار", "msg_routeRule": "قاعدة المسار",
    "msg_preference": "تفضيل", "msg_messagePreference": "تفضيل الرسائل",
}
T["az-AZ"] = {
    "messageTitle": "Mesaj İdarəetməsi", "messageId": "Mesaj ID",
    "messageChannel": "Kanal", "messageRecipient": "Alıcı",
    "messageSubject": "Mövzu", "messageSendTime": "Göndərmə vaxtı",
    "messageConfirmDelete": '"{id}" silmək istədiyinizə əminsiniz?',
    "operationSuccess": "Uğurlu oldu",
    "templateName": "Şablon adı", "templateContent": "Şablon məzmunu",
    "templateType": "Şablon növü", "routeName": "Marşrut adı",
    "routePriority": "Prioritet", "routeCondition": "Marşrut şərti",
    "preferenceName": "Tərcih adı", "dndEnabled": "Narahat etməyin",
    "dndStart": "Narahat etməyin Başlanğıc", "dndEnd": "Narahat etməyin Son",
    "confirmDelete": '"{id}" silmək istədiyinizə əminsiniz?',
    "create": "Əlavə et", "edit": "Redaktə et", "delete": "Sil",
    "msg_message": "Mesaj", "msg_messageList": "Mesaj siyahısı",
    "msg_batchSend": "Toplu göndərmə", "msg_deadLetter": "Dead Letter",
    "msg_template": "Şablon", "msg_templateList": "Şablon siyahısı",
    "msg_notification": "Bildiriş", "msg_notificationList": "Bildiriş siyahısı",
    "msg_route": "Marşrut", "msg_routeRule": "Marşrut qaydası",
    "msg_preference": "Tərcih", "msg_messagePreference": "Mesaj tərcihi",
}
T["bg-BG"] = {
    "messageTitle": "Управление на съобщения", "messageId": "ID на съобщение",
    "messageChannel": "Канал", "messageRecipient": "Получател",
    "messageSubject": "Тема", "messageSendTime": "Време на изпращане",
    "messageConfirmDelete": 'Сигурни ли сте, че искате да изтриете "{id}"?',
    "operationSuccess": "Успешно",
    "templateName": "Име на шаблон", "templateContent": "Съдържание на шаблон",
    "templateType": "Тип на шаблон", "routeName": "Име на маршрут",
    "routePriority": "Приоритет", "routeCondition": "Условие за маршрут",
    "preferenceName": "Име на предпочитание", "dndEnabled": "Не безпокойте",
    "dndStart": "Начало на Не безпокойте", "dndEnd": "Край на Не безпокойте",
    "confirmDelete": 'Сигурни ли сте, че искате да изтриете "{id}"?',
    "create": "Добавяне", "edit": "Редактиране", "delete": "Изтриване",
    "msg_message": "Съобщение", "msg_messageList": "Списък със съобщения",
    "msg_batchSend": "Групово изпращане", "msg_deadLetter": "Мъртва поща",
    "msg_template": "Шаблон", "msg_templateList": "Списък с шаблони",
    "msg_notification": "Известие", "msg_notificationList": "Списък с известия",
    "msg_route": "Маршрут", "msg_routeRule": "Правило за маршрут",
    "msg_preference": "Предпочитание", "msg_messagePreference": "Предпочитание за съобщения",
}
T["bn-BD"] = {
    "messageTitle": "বার্তা ব্যবস্থাপনা", "messageId": "বার্তা আইডি",
    "messageChannel": "চ্যানেল", "messageRecipient": "প্রাপক",
    "messageSubject": "বিষয়", "messageSendTime": "পাঠানোর সময়",
    "messageConfirmDelete": 'আপনি কি নিশ্চিত "{id}" মুছে ফেলতে চান?',
    "operationSuccess": "সফল",
    "templateName": "টেমপ্লেটের নাম", "templateContent": "টেমপ্লেট বিষয়বস্তু",
    "templateType": "টেমপ্লেটের ধরন", "routeName": "রুটের নাম",
    "routePriority": "অগ্রাধিকার", "routeCondition": "রুটের শর্ত",
    "preferenceName": "পছন্দের নাম", "dndEnabled": "বিঘ্নিত করবেন না",
    "dndStart": "DND শুরু", "dndEnd": "DND শেষ",
    "confirmDelete": 'আপনি কি নিশ্চিত "{id}" মুছে ফেলতে চান?',
    "create": "যোগ করুন", "edit": "সম্পাদনা", "delete": "মুছে ফেলুন",
    "msg_message": "বার্তা", "msg_messageList": "বার্তার তালিকা",
    "msg_batchSend": "ব্যাচ পাঠান", "msg_deadLetter": "মৃত চিঠি",
    "msg_template": "টেমপ্লেট", "msg_templateList": "টেমপ্লেট তালিকা",
    "msg_notification": "বিজ্ঞপ্তি", "msg_notificationList": "বিজ্ঞপ্তি তালিকা",
    "msg_route": "রুট", "msg_routeRule": "রুট নিয়ম",
    "msg_preference": "পছন্দ", "msg_messagePreference": "বার্তা পছন্দ",
}
T["bs-BA"] = {
    "messageTitle": "Upravljanje porukama", "messageId": "ID poruke",
    "messageChannel": "Kanal", "messageRecipient": "Primalac",
    "messageSubject": "Tema", "messageSendTime": "Vrijeme slanja",
    "messageConfirmDelete": 'Da li ste sigurni da želite obrisati "{id}"?',
    "operationSuccess": "Uspješno",
    "templateName": "Naziv predloška", "templateContent": "Sadržaj predloška",
    "templateType": "Vrsta predloška", "routeName": "Naziv rute",
    "routePriority": "Prioritet", "routeCondition": "Uslov rute",
    "preferenceName": "Naziv postavke", "dndEnabled": "Ne uznemiravaj",
    "dndStart": "Ne uznemiravaj Početak", "dndEnd": "Ne uznemiravaj Kraj",
    "confirmDelete": 'Da li ste sigurni da želite obrisati "{id}"?',
    "create": "Dodaj", "edit": "Uredi", "delete": "Obriši",
    "msg_message": "Poruka", "msg_messageList": "Lista poruka",
    "msg_batchSend": "Grupno slanje", "msg_deadLetter": "Mrtvo pismo",
    "msg_template": "Predložak", "msg_templateList": "Lista predložaka",
    "msg_notification": "Obavijest", "msg_notificationList": "Lista obavijesti",
    "msg_route": "Ruta", "msg_routeRule": "Pravilo rute",
    "msg_preference": "Postavka", "msg_messagePreference": "Postavka poruka",
}
T["ca-ES"] = {
    "messageTitle": "Gestió de missatges", "messageId": "ID de missatge",
    "messageChannel": "Canal", "messageRecipient": "Destinatari",
    "messageSubject": "Assumpte", "messageSendTime": "Hora d'enviament",
    "messageConfirmDelete": 'Esteu segur que voleu eliminar "{id}"?',
    "operationSuccess": "Èxit",
    "templateName": "Nom de la plantilla", "templateContent": "Contingut de la plantilla",
    "templateType": "Tipus de plantilla", "routeName": "Nom de la ruta",
    "routePriority": "Prioritat", "routeCondition": "Condició de ruta",
    "preferenceName": "Nom de la preferència", "dndEnabled": "No molestar",
    "dndStart": "No molestar Inici", "dndEnd": "No molestar Fi",
    "confirmDelete": 'Esteu segur que voleu eliminar "{id}"?',
    "create": "Crear", "edit": "Editar", "delete": "Eliminar",
    "msg_message": "Missatge", "msg_messageList": "Llista de missatges",
    "msg_batchSend": "Enviat per lots", "msg_deadLetter": "Carta morta",
    "msg_template": "Plantilla", "msg_templateList": "Llista de plantilles",
    "msg_notification": "Notificació", "msg_notificationList": "Llista de notificacions",
    "msg_route": "Ruta", "msg_routeRule": "Regla de ruta",
    "msg_preference": "Preferència", "msg_messagePreference": "Preferència de missatges",
}
T["cs-CZ"] = {
    "messageTitle": "Správa zpráv", "messageId": "ID zprávy",
    "messageChannel": "Kanál", "messageRecipient": "Příjemce",
    "messageSubject": "Předmět", "messageSendTime": "Čas odeslání",
    "messageConfirmDelete": 'Opravdu chcete smazat "{id}"?',
    "operationSuccess": "Úspěch",
    "templateName": "Název šablony", "templateContent": "Obsah šablony",
    "templateType": "Typ šablony", "routeName": "Název trasy",
    "routePriority": "Priorita", "routeCondition": "Podmínka trasy",
    "preferenceName": "Název předvolby", "dndEnabled": "Nerušit",
    "dndStart": "Nerušit Začátek", "dndEnd": "Nerušit Konec",
    "confirmDelete": 'Opravdu chcete smazat "{id}"?',
    "create": "Přidat", "edit": "Upravit", "delete": "Smazat",
    "msg_message": "Zpráva", "msg_messageList": "Seznam zpráv",
    "msg_batchSend": "Hromadné odeslání", "msg_deadLetter": "Mrtvá pošta",
    "msg_template": "Šablona", "msg_templateList": "Seznam šablon",
    "msg_notification": "Oznámení", "msg_notificationList": "Seznam oznámení",
    "msg_route": "Trasa", "msg_routeRule": "Pravidlo trasy",
    "msg_preference": "Předvolba", "msg_messagePreference": "Předvolba zpráv",
}
T["cy-GB"] = {
    "messageTitle": "Rheolaeth Negeseuon", "messageId": "ID Neges",
    "messageChannel": "Sianel", "messageRecipient": "Derbynnydd",
    "messageSubject": "Pwnc", "messageSendTime": "Afonfonwyd am",
    "messageConfirmDelete": 'Ydych chi\'n siŵr eich bod eisiau dileu "{id}"?',
    "operationSuccess": "Llwyddiant",
    "templateName": "Enw'r Templed", "templateContent": "Cynnwys y Templed",
    "templateType": "Math o Dempled", "routeName": "Enw'r Llwybr",
    "routePriority": "Blaenoriaeth", "routeCondition": "Amod Llwybr",
    "preferenceName": "Enw'r Dewisiad", "dndEnabled": "Peidiwch â Tharfu",
    "dndStart": "Peidiwch â Tharfu Dechrau", "dndEnd": "Peidiwch â Tharfu Diwedd",
    "confirmDelete": 'Ydych chi\'n siŵr eich bod eisiau dileu "{id}"?',
    "create": "Creu", "edit": "Golygu", "delete": "Dileu",
    "msg_message": "Neges", "msg_messageList": "Rhestr Negeseuon",
    "msg_batchSend": "Anfon Swp", "msg_deadLetter": "Llythyr Marw",
    "msg_template": "Templed", "msg_templateList": "Rhestr Templets",
    "msg_notification": "Hysbysiad", "msg_notificationList": "Rhestr Hysbysiadau",
    "msg_route": "Llwybr", "msg_routeRule": "Rheol Llwybr",
    "msg_preference": "Dewisiad", "msg_messagePreference": "Dewisiad Neges",
}
T["da-DK"] = {
    "messageTitle": "Beskedsadministration", "messageId": "Besked-ID",
    "messageChannel": "Kanal", "messageRecipient": "Modtager",
    "messageSubject": "Emne", "messageSendTime": "Sendt kl.",
    "messageConfirmDelete": 'Er du sikker på, at du vil slette "{id}"?',
    "operationSuccess": "Lykkedes",
    "templateName": "Skabelonnavn", "templateContent": "Skabelonindhold",
    "templateType": "Skabelontype", "routeName": "Rutenavn",
    "routePriority": "Prioritet", "routeCondition": "Rutebetingelse",
    "preferenceName": "Præferencenavn", "dndEnabled": "Forstyr ikke",
    "dndStart": "Forstyr ikke Start", "dndEnd": "Forstyr ikke Slut",
    "confirmDelete": 'Er du sikker på, at du vil slette "{id}"?',
    "create": "Tilføj", "edit": "Rediger", "delete": "Slet",
    "msg_message": "Besked", "msg_messageList": "Beskedliste",
    "msg_batchSend": "Batchafsendelse", "msg_deadLetter": "Dødt brev",
    "msg_template": "Skabelon", "msg_templateList": "Skabelonliste",
    "msg_notification": "Notifikation", "msg_notificationList": "Notifikationsliste",
    "msg_route": "Rute", "msg_routeRule": "Ruteregul",
    "msg_preference": "Præference", "msg_messagePreference": "Beskedpræference",
}
