<!--
 * 流程分类（列表页）
 *
 * @path apps\workflow-web\src\views\category\index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 流程分类（列表页）
 * <p>消费后端契约 FlowCategoryController（src/api/flowCategory.ts，auto-generated by bash/gen-contract.py）：
 * 列表 list() 展示全部分类（非分页，query 直接返回 { items, total: items.length }），
 * 支持新增、编辑、删除。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import type { VxeGridProps } from '@ydsz/plugins/vxe-table';
import { Page, useYDSZModal } from '@ydsz/common-ui';
import { ElButton, ElMessage, ElMessageBox } from 'element-plus';
import { h } from 'vue';
import { useYDSZVxeGrid } from '#/adapter/vxe-table';
import { deleteApi, list } from '#/api/flowCategory';
import type { FlowCategoryVO } from '#/api/models';
import CategoryForm from './category-form.vue';
defineOptions({ name: 'CategoryManagement' });
const gridOptions: VxeGridProps<FlowCategoryVO> = {
  columns: [
    { type: 'seq', width: 50, title: '序号' },
    { field: 'categoryCode', title: '编码', width: 160 },
    { field: 'categoryName', title: '名称', width: 200 },
    { field: 'parentId', title: '父分类ID', width: 160 },
    { field: 'sortNum', title: '排序', width: 80 },
    { field: 'updatedAt', title: '更新时间', width: 170 },
    {
      field: 'action',
      title: '操作',
      width: 160,
      fixed: 'right',
      slots: {
        default: ({ row }) =>
          h('div', { class: 'flex gap-1' }, [
            h(
              ElButton,
              { size: 'small', link: true, type: 'primary', onClick: () => handleEdit(row) },
              () => '编辑',
            ),
            h(
              ElButton,
              { size: 'small', link: true, type: 'danger', onClick: () => handleDelete(row) },
              () => '删除',
            ),
          ]),
      },
    },
  ],
  height: 'auto',
  pagerConfig: { pageSize: 20, pageSizes: [10, 20, 50, 100] },
  proxyConfig: {
    ajax: {
      // list() 为全量非分页接口：直接返回全部条目，total 取条目数
      query: async () => {
        const items = (await list()) ?? [];
        return { items, total: items.length };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, zoom: true },
};
const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });
const [CategoryFormModal, categoryFormApi] = useYDSZModal({ connectedComponent: CategoryForm });
function handleAdd() {
  categoryFormApi.open();
}
function handleEdit(row: FlowCategoryVO) {
  categoryFormApi.setData({ record: row });
  categoryFormApi.open();
}
async function handleDelete(row: FlowCategoryVO) {
  if (!row.id) return;
  // 步骤1：确认弹窗（用户取消直接返回）
  try {
    await ElMessageBox.confirm(
      `确定删除「${row.categoryName ?? row.categoryCode}」吗？`,
      '删除确认',
      { type: 'warning' },
    );
  } catch {
    return; // 用户主动取消删除操作
  }
  // 步骤2：执行删除 API（失败提示由 errorMessageResponseInterceptor 统一处理）
  try {
    await deleteApi({ id: row.id });
    ElMessage.success('删除成功');
    gridApi.query();
  } catch {
    // 错误已由请求拦截器展示，无需重复处理
  }
}
</script>
<template>
  <Page auto-content-height>
    <Grid table-title="流程分类">
      <template #toolbar-tools
        ><ElButton type="primary" @click="handleAdd">新增</ElButton></template
      >
    </Grid>
    <CategoryFormModal @success="gridApi.query()" />
  </Page>
</template>
