<!--
 * 流程模板（列表页）
 *
 * 视图模式：卡片视图（默认）/ 表格视图 可切换。
 *  - 卡片视图：YdCardGrid + YdEntityCard，承载模板可视化展示；
 *  - 表格视图：VxeTable，保持原有兼容视图。
 *
 * @path apps\workflow-web\src\views\template\index.vue
 * @author ydsz-team
 * @since 1.0.0
-->
<script lang="ts" setup>
/**
 * 流程模板（列表页）
 * <p>消费后端契约 FlowTemplateController（src/api/flowTemplate.ts，auto-generated by bash/gen-contract.py）：
 * 列表 listTemplates()（非分页，query 直接返回 { items, total: items.length }），
 * 支持导入 importTemplate、克隆 cloneTemplate、新建版本 createNewVersion、
 * 版本历史 listTemplateVersions 抽屉（getTemplateVersion 查看详情）。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
import type { VxeGridProps } from '@ydsz/plugins/vxe-table';
import { YdCardGrid, YdEmptyState, YdEntityCard, YdStatusBadge } from '@ydsz-core/shadcn-ui';
import { Page, useYdModal } from '@ydsz/common-ui';
// TODO: ElTable / ElTableColumn 暂不迁移，保留 element-plus 导入
import { ElTable, ElTableColumn } from 'element-plus';
import {
  Button,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  Sheet,
  SheetContent,
} from '@ydsz-core/ui-kit/shadcn-ui';
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { createLogger } from '@ydsz-core/shared/utils';
import { useYDSZVxeGrid } from '#/adapter/vxe-table';

const logger = createLogger('workflow-template');
import {
  cloneTemplate,
  createNewVersion,
  getTemplateVersion,
  importTemplate,
  listTemplates,
  listTemplateVersions,
} from '#/api/flowTemplate';
import TemplateForm from './template-form.vue';

defineOptions({ name: 'TemplateManagement' });

const { t } = useI18n();

/** 行类型：后端契约未声明模板 VO，使用 Record<string, unknown> 兼容（可选链收窄取值） */
type TemplateRow = Record<string, unknown>;

/** 视图模式类型 */
type ViewMode = 'card' | 'table';
const viewMode = ref<ViewMode>('card');

/** 卡片视图数据源 */
const templateList = ref<TemplateRow[]>([]);
const cardLoading = ref<boolean>(false);

/** 安全读取字符串字段 */
function str(row: TemplateRow, key: string): string {
  const value = row[key];
  return typeof value === 'string' ? value : '';
}

/** 安全读取数字字段 */
function num(row: TemplateRow, key: string): number {
  const value = row[key];
  return typeof value === 'number' ? value : 0;
}

/** 模板状态 → YdStatusBadge 语义值 */
function resolveTemplateStatus(row: TemplateRow): 'draft' | 'published' | 'offline' {
  const status = (str(row, 'status') || '').toUpperCase();
  if (status === 'PUBLISHED' || status === 'ACTIVE' || status === 'RELEASED') {
    return 'published';
  }
  if (status === 'OFFLINE' || status === 'ARCHIVED' || status === 'DISABLED') {
    return 'offline';
  }
  return 'draft';
}

/** 状态原始文本 */
function resolveStatusLabel(row: TemplateRow): string {
  return str(row, 'status') || '草稿';
}

const gridOptions: VxeGridProps<TemplateRow> = {
  columns: [
    { type: 'seq', width: 50, title: t('common.seq') },
    { field: 'templateCode', title: t('wf.templateCode'), width: 150 },
    { field: 'templateName', title: t('wf.templateName'), width: 200 },
    { field: 'category', title: t('wf.categoryName'), width: 100 },
    { field: 'version', title: t('wf.version'), width: 80 },
    { field: 'status', title: t('wf.status'), width: 80 },
    { field: 'updatedAt', title: t('wf.updateTime'), width: 170 },
    {
      field: 'action',
      title: t('wf.action'),
      width: 220,
      fixed: 'right',
    },
  ],
  height: 'auto',
  pagerConfig: { pageSize: 20, pageSizes: [10, 20, 50, 100] },
  proxyConfig: {
    ajax: {
      query: async (_params, formValues) => {
        const values = (formValues ?? {}) as TemplateRow;
        const items =
          (await listTemplates({ category: str(values, 'category') || undefined })) ?? [];
        return { items, total: items.length };
      },
    },
  },
  toolbarConfig: { custom: true, refresh: { code: 'query' }, zoom: true },
  formConfig: {
    enabled: true,
    items: [
      {
        field: 'category',
        title: t('wf.categoryName'),
        itemRender: { name: 'Input', props: { placeholder: t('wf.categoryName') } },
      },
    ],
  },
};

const [Grid, gridApi] = useYDSZVxeGrid({ gridOptions });
const [TemplateFormModal, templateFormApi] = useYdModal({ connectedComponent: TemplateForm });

/** 加载卡片视图数据 */
async function loadCardData(): Promise<void> {
  cardLoading.value = true;
  try {
    templateList.value = (await listTemplates({})) ?? [];
  } catch (error) {
    logger.warn('加载模板列表失败: {}', error);
    templateList.value = [];
  } finally {
    cardLoading.value = false;
  }
}

/** 视图切换 */
function handleViewModeChange(mode: ViewMode): void {
  if (mode === 'card' && templateList.value.length === 0 && !cardLoading.value) {
    void loadCardData();
  }
  viewMode.value = mode;
}

/** 刷新列表（兼容两视图） */
async function handleRefresh(): Promise<void> {
  if (viewMode.value === 'table') {
    gridApi.query();
  } else {
    await loadCardData();
  }
}

/** 模板编码获取失败时的统一提示 */
function getTemplateCode(row: TemplateRow): string | undefined {
  const code = str(row, 'templateCode');
  if (!code) {
    showToast.warning(t('wf.missingTemplateCode'));
    return undefined;
  }
  return code;
}

/** 导入模板（可填写流程名称） */
async function handleImport(row: TemplateRow): Promise<void> {
  const templateCode = getTemplateCode(row);
  if (!templateCode) return;
  let flowName: string;
  // 步骤1：输入弹窗（用户取消直接返回）
  try {
    const { value } = await ElMessageBox.prompt(
      t('wf.importFlowNamePlaceholder'),
      t('wf.templateImport'),
      {
        inputPlaceholder: 'flowName',
        inputValidator: (inputValue) => (inputValue ? true : t('wf.importValidator')),
      },
    );
    flowName = value;
  } catch (error) {
    logger.warn('用户取消模板导入操作', error);
    return; // 用户主动取消导入操作
  }
  // 步骤2：执行导入 API（失败提示由 errorMessageResponseInterceptor 统一处理）
  try {
    await importTemplate({ templateCode }, { flowName });
    showToast.success(t('wf.importSuccess'));
    await handleRefresh();
  } catch (error) {
    logger.warn('模板导入失败，详见拦截器提示', error);
    // 用户提示由 errorMessageResponseInterceptor 统一处理
  }
}

/** 克隆模板 */
async function handleClone(row: TemplateRow): Promise<void> {
  const templateCode = getTemplateCode(row);
  if (!templateCode) return;
  let newTemplateName: string;
  // 步骤1：输入弹窗（用户取消直接返回）
  try {
    const { value } = await ElMessageBox.prompt(t('wf.confirmClone'), t('wf.cloneTemplate'), {
      inputPlaceholder: 'newTemplateName',
      inputValidator: (inputValue) => (inputValue ? true : t('wf.cloneValidator')),
    });
    newTemplateName = value;
  } catch (error) {
    logger.warn('用户取消模板克隆操作', error);
    return; // 用户主动取消克隆操作
  }
  // 步骤2：执行克隆 API（失败提示由 errorMessageResponseInterceptor 统一处理）
  try {
    await cloneTemplate({ templateCode }, { newTemplateName });
    showToast.success(t('wf.cloneSuccess'));
    await handleRefresh();
  } catch (error) {
    logger.warn('模板克隆失败，详见拦截器提示', error);
    // 用户提示由 errorMessageResponseInterceptor 统一处理
  }
}

/** 基于现有模板创建新版本 */
async function handleNewVersion(row: TemplateRow): Promise<void> {
  const templateCode = getTemplateCode(row);
  if (!templateCode) return;
  let versionLabel: string | undefined;
  // 步骤1：输入弹窗（用户取消直接返回）
  try {
    const { value } = await ElMessageBox.prompt(
      t('wf.confirmNewVersion'),
      t('wf.newVersionTitle'),
      {
        inputPlaceholder: 'versionLabel',
      },
    );
    versionLabel = value || undefined;
  } catch (error) {
    logger.warn('用户取消创建模板新版本操作', error);
    return; // 用户主动取消创建版本操作
  }
  // 步骤2：执行创建版本 API（失败提示由 errorMessageResponseInterceptor 统一处理）
  try {
    await createNewVersion({ templateCode }, { versionLabel });
    showToast.success(t('wf.newVersionSuccess'));
    await handleRefresh();
  } catch (error) {
    logger.warn('创建模板新版本失败，详见拦截器提示', error);
    // 用户提示由 errorMessageResponseInterceptor 统一处理
  }
}

/** 版本历史抽屉状态 */
const versionsVisible = ref(false);
const versionsLoading = ref(false);
const versionRows = ref<TemplateRow[]>([]);
const currentTemplateCode = ref('');

/** 打开版本历史抽屉 */
async function openVersions(row: TemplateRow): Promise<void> {
  const templateCode = getTemplateCode(row);
  if (!templateCode) return;
  currentTemplateCode.value = templateCode;
  versionsVisible.value = true;
  await loadVersions();
}

/** 加载当前模板的版本列表 */
async function loadVersions(): Promise<void> {
  if (!currentTemplateCode.value) return;
  versionsLoading.value = true;
  try {
    versionRows.value =
      (await listTemplateVersions({ templateCode: currentTemplateCode.value })) ?? [];
  } finally {
    versionsLoading.value = false;
  }
}

/** 查看版本详情（以 JSON 格式展示） */
async function handleVersionDetail(versionItem: TemplateRow): Promise<void> {
  if (!currentTemplateCode.value) return;
  const version = num(versionItem, 'version') || Number(str(versionItem, 'version'));
  if (!version && !str(versionItem, 'version')) {
    showToast.warning(t('wf.missingVersion'));
    return;
  }
  try {
    const detail = await getTemplateVersion({ templateCode: currentTemplateCode.value, version });
    ElMessageBox.alert(
      `<pre class="max-h-64 overflow-auto text-left text-xs">${JSON.stringify(detail, null, 2)}</pre>`,
      `${t('wf.versionDetail')} ${version}`,
      {
        dangerouslyUseHTMLString: true,
      },
    );
  } catch (error) {
    logger.warn('获取模板版本详情失败，详见拦截器提示', error);
    // 用户提示由 errorMessageResponseInterceptor 统一处理
  }
}

/** 操作命令处理器 */
type CardCommand = 'import' | 'clone' | 'version' | 'newVersion';
function handleCardAction(command: CardCommand, row: TemplateRow): void {
  const handlerMap: Record<CardCommand, (r: TemplateRow) => Promise<void> | void> = {
    clone: handleClone,
    import: handleImport,
    newVersion: handleNewVersion,
    version: openVersions,
  };
  const handler = handlerMap[command];
  if (handler) {
    const result = handler(row);
    if (result instanceof Promise) {
      result.catch((error) => logger.warn('卡片操作执行失败: {}', error));
    }
  }
}

/** 默认加载卡片数据 */
void loadCardData();
</script>

<template>
  <Page auto-content-height>
    <!-- 视图切换 + 工具栏 -->
    <div class="mb-4 flex items-center justify-between">
      <div class="flex items-center gap-1 rounded-lg border border-border-subtle bg-accent/50 p-1">
        <button
          class="rounded-md px-2.5 py-1 text-xs transition-colors"
          :class="viewMode === 'card' ? 'bg-surface-2 text-text-primary shadow-sm' : 'text-text-secondary hover:text-text-primary'"
          type="button"
          @click="handleViewModeChange('card')"
        >
          <svg
            class="mb-0.5 me-1 inline"
            fill="none"
            height="14"
            stroke="currentColor"
            viewBox="0 0 24 24"
            width="14"
          >
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="2.5"
              y="2.5"
            />
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="12.5"
              y="2.5"
            />
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="2.5"
              y="12.5"
            />
            <rect
              height="9"
              rx="1.5"
              width="9"
              x="12.5"
              y="12.5"
            />
          </svg>
          卡片
        </button>
        <button
          class="rounded-md px-2.5 py-1 text-xs transition-colors"
          :class="viewMode === 'table' ? 'bg-surface-2 text-text-primary shadow-sm' : 'text-text-secondary hover:text-text-primary'"
          type="button"
          @click="handleViewModeChange('table')"
        >
          <svg
            class="mb-0.5 me-1 inline"
            fill="none"
            height="14"
            stroke="currentColor"
            stroke-width="1.8"
            viewBox="0 0 24 24"
            width="14"
          >
            <line
              x1="3"
              x2="21"
              y1="6.5"
              y2="6.5"
            />
            <line
              x1="3"
              x2="21"
              y1="12"
              y2="12"
            />
            <line
              x1="3"
              x2="21"
              y1="17.5"
              y2="17.5"
            />
            <line
              x1="8.5"
              x2="8.5"
              y1="3"
              y2="21"
            />
          </svg>
          表格
        </button>
      </div>
      <Button @click="templateFormApi.open()">{{ t('wf.import') }}</Button>
    </div>

    <!-- 表格视图 -->
    <Grid
      v-if="viewMode === 'table'"
      :table-title="t('template')"
    >
      <template #col-action="{ row }">
        <div class="flex gap-1">
          <Button size="sm" variant="link" @click="handleImport(row as TemplateRow)">{{
            t('wf.import')
          }}</Button>
          <Button size="sm" variant="link" @click="handleClone(row as TemplateRow)">{{
            t('wf.clone')
          }}</Button>
          <Button size="sm" variant="link" @click="handleNewVersion(row as TemplateRow)">{{
            t('wf.newVersion')
          }}</Button>
          <Button size="sm" variant="link" @click="openVersions(row as TemplateRow)">{{
            t('wf.version')
          }}</Button>
        </div>
      </template>
    </Grid>

    <!-- 卡片视图 -->
    <div
      v-else
      class="min-h-[400px]"
    >
      <YdCardGrid
        :is-empty="templateList.length === 0 && !cardLoading"
        :is-loading="cardLoading"
      >
        <template #empty>
          <YdEmptyState
            description="导入流程模板后可在多个业务场景中复用"
            preset="created"
            :action-text="t('wf.import')"
            :title="t('wf.templateName')"
            @action="templateFormApi.open()"
          />
        </template>
        <YdEntityCard
          v-for="item in templateList"
          :key="String(item.templateCode ?? item.templateName)"
          :avatar-text="String(item.templateName || item.templateCode || '')"
          :avatar-variant="resolveTemplateStatus(item) === 'published' ? 'primary' : 'neutral'"
          :code="item.templateCode ? String(item.templateCode) : undefined"
          :description="`${t('wf.categoryName')}: ${item.category || '-'} · ${t('wf.version')}: ${item.version ?? '-'}`"
          class="transition-transform hover:-translate-y-0.5"
          clickable
          @click="handleImport(item)"
        >
          <template #status-badge>
            <YdStatusBadge
              :status="resolveTemplateStatus(item)"
              :label="resolveStatusLabel(item)"
              class="shrink-0"
            />
          </template>

          <template #meta>
            <div class="mt-3 flex items-center justify-between text-xs text-text-tertiary">
              <span>{{ t('wf.version') }} {{ item.version ?? '-' }}</span>
              <span>{{ item.updatedAt || '-' }}</span>
            </div>
          </template>

          <template #actions>
            <DropdownMenu>
              <DropdownMenuTrigger as-child>
                <Button
                  size="sm"
                  variant="link"
                  @click.stop
                >
                  <svg
                    class="mb-0.5 me-1 inline"
                    fill="none"
                    height="14"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    width="14"
                  >
                    <circle
                      cx="12"
                      cy="5"
                      r="1"
                    />
                    <circle
                      cx="12"
                      cy="12"
                      r="1"
                    />
                    <circle
                      cx="12"
                      cy="19"
                      r="1"
                    />
                  </svg>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem @click="handleCardAction('import', item)">
                  {{ t('wf.import') }}
                </DropdownMenuItem>
                <DropdownMenuItem @click="handleCardAction('clone', item)">
                  {{ t('wf.clone') }}
                </DropdownMenuItem>
                <DropdownMenuItem @click="handleCardAction('newVersion', item)">
                  {{ t('wf.newVersion') }}
                </DropdownMenuItem>
                <DropdownMenuItem @click="handleCardAction('version', item)">
                  {{ t('wf.version') }}
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </template>
        </YdEntityCard>
      </YdCardGrid>
    </div>

    <TemplateFormModal @success="handleRefresh()" />
    <Sheet :open="versionsVisible" @update:open="versionsVisible = $event">
      <SheetContent class="!max-w-[540px]">
        <div class="mb-2 flex justify-end">
        <Button size="sm" variant="secondary" @click="loadVersions">{{ t('common.refresh') }}</Button>
      </div>
      <ElTable
        :data="versionRows"
        border
        size="small"
        v-loading="versionsLoading"
      >
        <ElTableColumn
          prop="version"
          :label="t('wf.version')"
          width="90"
        />
        <ElTableColumn
          prop="versionLabel"
          :label="t('wf.versionLabel')"
          width="120"
        />
        <ElTableColumn
          prop="templateName"
          :label="t('wf.templateName')"
          min-width="120"
          show-overflow-tooltip
        />
        <ElTableColumn
          prop="status"
          :label="t('wf.status')"
          width="90"
        />
        <ElTableColumn
          prop="updatedAt"
          :label="t('wf.updateTime')"
          width="170"
        />
        <ElTableColumn
          :label="t('wf.action')"
          width="90"
          fixed="right"
        >
          <template #default="{ row }">
            <Button
              variant="link"
              size="sm"
              @click="handleVersionDetail(row as TemplateRow)"
            >{{ t('wf.detail') }}</Button>
          </template>
        </ElTableColumn>
      </ElTable>
      </SheetContent>
    </Sheet>
  </Page>
</template>
