/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * FlowTemplateController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code FlowTemplateController}，共 13 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';

/**
 * listTemplates: GET /api/v1/workflow/template/list
 */
export function listTemplates(params: { category?: string }): Promise<Record<string, unknown>[]> {
  return requestClient.get<Record<string, unknown>[]>(`/api/v1/workflow/template/list`, { params });
}

/**
 * getTemplate: GET /api/v1/workflow/template/{templateCode}
 */
export function getTemplate({ templateCode }: { templateCode: string }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/workflow/template/${templateCode}`);
}

/**
 * importTemplate: POST /api/v1/workflow/template/{templateCode}/import
 */
export function importTemplate(
  {
    templateCode,
  }: {
    templateCode: string;
  },
  params: {
    flowName?: string;
  },
): Promise<string> {
  return requestClient.post<string>(`/api/v1/workflow/template/${templateCode}/import`, { params });
}

/**
 * exportAsTemplate: POST /api/v1/workflow/template/export/{definitionId}
 */
export function exportAsTemplate(
  {
    definitionId,
  }: {
    definitionId: string;
  },
  params: {
    templateName?: string;
    category?: string;
  },
): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/template/export/${definitionId}`, { params });
}

/**
 * listTemplateVersions: GET /api/v1/workflow/template/{templateCode}/versions
 */
export function listTemplateVersions({
  templateCode,
}: {
  templateCode: string;
}): Promise<Record<string, unknown>[]> {
  return requestClient.get<Record<string, unknown>[]>(
    `/api/v1/workflow/template/${templateCode}/versions`,
  );
}

/**
 * getTemplateVersion: GET /api/v1/workflow/template/{templateCode}/versions/{version}
 */
export function getTemplateVersion({
  templateCode,
  version,
}: {
  templateCode: string;
  version: number;
}): Promise<unknown> {
  return requestClient.get<unknown>(
    `/api/v1/workflow/template/${templateCode}/versions/${version}`,
  );
}

/**
 * createNewVersion: POST /api/v1/workflow/template/{templateCode}/newVersion
 */
export function createNewVersion(
  {
    templateCode,
  }: {
    templateCode: string;
  },
  params: {
    versionLabel?: string;
  },
): Promise<number> {
  return requestClient.post<number>(`/api/v1/workflow/template/${templateCode}/newVersion`, {
    params,
  });
}

/**
 * cloneTemplate: POST /api/v1/workflow/template/{templateCode}/clone
 */
export function cloneTemplate(
  {
    templateCode,
  }: {
    templateCode: string;
  },
  params: {
    newTemplateCode?: string;
    newTemplateName?: string;
    newCategory?: string;
  },
): Promise<string> {
  return requestClient.post<string>(`/api/v1/workflow/template/${templateCode}/clone`, { params });
}

/**
 * inheritFromParent: POST /api/v1/workflow/template/{parentTemplateCode}/inherit
 */
export function inheritFromParent(
  {
    parentTemplateCode,
  }: {
    parentTemplateCode: string;
  },
  params: {
    newTemplateCode?: string;
    newTemplateName?: string;
    newCategory?: string;
  },
): Promise<string> {
  return requestClient.post<string>(`/api/v1/workflow/template/${parentTemplateCode}/inherit`, {
    params,
  });
}

/**
 * listInheritedTemplates: GET /api/v1/workflow/template/{parentTemplateCode}/inherited
 */
export function listInheritedTemplates({
  parentTemplateCode,
}: {
  parentTemplateCode: string;
}): Promise<Record<string, unknown>[]> {
  return requestClient.get<Record<string, unknown>[]>(
    `/api/v1/workflow/template/${parentTemplateCode}/inherited`,
  );
}

/**
 * syncFromParent: POST /api/v1/workflow/template/{childTemplateCode}/sync
 */
export function syncFromParent({
  childTemplateCode,
}: {
  childTemplateCode: string;
}): Promise<number> {
  return requestClient.post<number>(`/api/v1/workflow/template/${childTemplateCode}/sync`);
}

/**
 * recommend: GET /api/v1/workflow/template/recommend
 */
export function recommend(params: { topN?: number }): Promise<Record<string, unknown>[]> {
  return requestClient.get<Record<string, unknown>[]>(`/api/v1/workflow/template/recommend`, {
    params,
  });
}

/**
 * recommendByBusinessType: GET /api/v1/workflow/template/recommend/byBusinessType
 */
export function recommendByBusinessType(params: {
  businessType?: string;
  topN?: number;
}): Promise<Record<string, unknown>[]> {
  return requestClient.get<Record<string, unknown>[]>(
    `/api/v1/workflow/template/recommend/byBusinessType`,
    { params },
  );
}
