/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * FlowInstanceController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code FlowInstanceController}，共 29 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { FlowAuditTrailVO, FlowAutoTriggerCreateDTO, FlowAutoTriggerVO, FlowDefinitionDetailVO, FlowInstanceVariablesDTO, FlowInstanceViewDTO, FlowRecallableNodeVO, FlowReplayStepVO, FlowStartProcessDTO, FlowTimelineVO, InstanceMigrationDTO, InstanceMigrationResultDTO, PageResponse } from './models';

/**
 * startProcess: POST /api/v1/workflow/engine/instance/start
 */
export function startProcess(data: FlowStartProcessDTO): Promise<string> {
  return requestClient.post<string>(`/api/v1/workflow/engine/instance/start`, data);
}

/**
 * batchStartInstances: POST /api/v1/workflow/engine/instance/batchStart
 */
export function batchStartInstances(data: FlowStartProcessDTO[]): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/workflow/engine/instance/batchStart`, data);
}

/**
 * getByBusiness: GET /api/v1/workflow/engine/instance/byBusiness
 */
export function getByBusiness(params: {
    businessType?: string;
    businessId?: string;
  }): Promise<FlowInstanceViewDTO> {
  return requestClient.get<FlowInstanceViewDTO>(`/api/v1/workflow/engine/instance/byBusiness`, { params });
}

/**
 * terminate: POST /api/v1/workflow/engine/instance/{id}/terminate
 */
export function terminate({ id }: {
    id: string;
  }, params: {
    reason?: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/engine/instance/${id}/terminate`, { params });
}

/**
 * suspend: POST /api/v1/workflow/engine/instance/{id}/suspend
 */
export function suspend({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/engine/instance/${id}/suspend`);
}

/**
 * activate: POST /api/v1/workflow/engine/instance/{id}/activate
 */
export function activate({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/engine/instance/${id}/activate`);
}

/**
 * recall: POST /api/v1/workflow/engine/instance/{id}/recall
 */
export function recall({ id }: {
    id: string;
  }, params: {
    targetNodeCode?: string;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/api/v1/workflow/engine/instance/${id}/recall`, { params });
}

/**
 * listRecallableNodes: GET /api/v1/workflow/engine/instance/{id}/recallableNodes
 */
export function listRecallableNodes({ id }: {
    id: string;
  }): Promise<FlowRecallableNodeVO[]> {
  return requestClient.get<FlowRecallableNodeVO[]>(`/api/v1/workflow/engine/instance/${id}/recallableNodes`);
}

/**
 * rollback: POST /api/v1/workflow/engine/instance/{id}/rollback
 */
export function rollback({ id }: {
    id: string;
  }, params: {
    reason?: string;
    maxRollbackDays?: number;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/api/v1/workflow/engine/instance/${id}/rollback`, { params });
}

/**
 * resubmit: POST /api/v1/workflow/engine/instance/{id}/resubmit
 */
export function resubmit({ id }: {
    id: string;
  }, params: {
    comment?: string;
    redoMode?: string;
  }, data: Record<string, unknown>): Promise<string> {
  return requestClient.post<string>(`/api/v1/workflow/engine/instance/${id}/resubmit`, data, { params });
}

/**
 * auditTrail: GET /api/v1/workflow/engine/instance/{id}/auditTrail
 */
export function auditTrail({ id }: {
    id: string;
  }): Promise<FlowAuditTrailVO[]> {
  return requestClient.get<FlowAuditTrailVO[]>(`/api/v1/workflow/engine/instance/${id}/auditTrail`);
}

/**
 * timeline: GET /api/v1/workflow/engine/instance/{id}/timeline
 */
export function timeline({ id }: {
    id: string;
  }): Promise<FlowTimelineVO[]> {
  return requestClient.get<FlowTimelineVO[]>(`/api/v1/workflow/engine/instance/${id}/timeline`);
}

/**
 * diagram: GET /api/v1/workflow/engine/instance/{id}/diagram
 */
export function diagram({ id }: {
    id: string;
  }): Promise<FlowDefinitionDetailVO> {
  return requestClient.get<FlowDefinitionDetailVO>(`/api/v1/workflow/engine/instance/${id}/diagram`);
}

/**
 * replay: GET /api/v1/workflow/engine/instance/{id}/replay
 */
export function replay({ id }: {
    id: string;
  }): Promise<FlowReplayStepVO[]> {
  return requestClient.get<FlowReplayStepVO[]>(`/api/v1/workflow/engine/instance/${id}/replay`);
}

/**
 * instancePage: GET /api/v1/workflow/engine/instance/page
 */
export function instancePage(params: {
    pageNo?: number;
    pageSize?: number;
    businessType?: string;
    initiatorId?: string;
    flowStatus?: string;
    startTime?: string;
    endTime?: string;
    tenantId?: string;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/v1/workflow/engine/instance/page`, { params });
}

/**
 * instanceMy: GET /api/v1/workflow/engine/instance/my
 */
export function instanceMy(params: {
    flowCode?: string;
    flowName?: string;
    status?: string;
    startTime?: string;
    endTime?: string;
    pageNum?: number;
    pageSize?: number;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/v1/workflow/engine/instance/my`, { params });
}

/**
 * instanceAll: GET /api/v1/workflow/engine/instance/all
 */
export function instanceAll(params: {
    page?: number;
    size?: number;
    businessType?: string;
    flowStatus?: string;
    startTime?: string;
    endTime?: string;
  }): Promise<PageResponse> {
  return requestClient.get<PageResponse>(`/api/v1/workflow/engine/instance/all`, { params });
}

/**
 * getVariables: GET /api/v1/workflow/engine/instance/{id}/variables
 */
export function getVariables({ id }: {
    id: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/workflow/engine/instance/${id}/variables`);
}

/**
 * setVariables: POST /api/v1/workflow/engine/instance/{id}/variables
 */
export function setVariables({ id }: {
    id: string;
  }, data: FlowInstanceVariablesDTO): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/engine/instance/${id}/variables`, data);
}

/**
 * urge: POST /api/v1/workflow/engine/instance/{id}/urge
 */
export function urge({ id }: {
    id: string;
  }, params: {
    comment?: string;
  }): Promise<string[]> {
  return requestClient.post<string[]>(`/api/v1/workflow/engine/instance/${id}/urge`, { params });
}

/**
 * urgeByNode: POST /api/v1/workflow/engine/instance/{id}/urge/node
 */
export function urgeByNode({ id }: {
    id: string;
  }, params: {
    nodeCode?: string;
    comment?: string;
  }): Promise<string[]> {
  return requestClient.post<string[]>(`/api/v1/workflow/engine/instance/${id}/urge/node`, { params });
}

/**
 * getFormRenderData: GET /api/v1/workflow/engine/instance/{id}/formRender
 */
export function getFormRenderData({ id }: {
    id: string;
  }, params: {
    taskId?: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/workflow/engine/instance/${id}/formRender`, { params });
}

/**
 * migrateInstances: POST /api/v1/workflow/engine/instance/migrate
 */
export function migrateInstances(data: InstanceMigrationDTO): Promise<InstanceMigrationResultDTO> {
  return requestClient.post<InstanceMigrationResultDTO>(`/api/v1/workflow/engine/instance/migrate`, data);
}

/**
 * previewMigration: POST /api/v1/workflow/engine/instance/migrate/preview
 */
export function previewMigration(data: InstanceMigrationDTO): Promise<InstanceMigrationResultDTO> {
  return requestClient.post<InstanceMigrationResultDTO>(`/api/v1/workflow/engine/instance/migrate/preview`, data);
}

/**
 * autoMapNodes: GET /api/v1/workflow/engine/instance/migrate/autoMap
 */
export function autoMapNodes(params: {
    sourceDefinitionId?: number;
    targetDefinitionId?: number;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/workflow/engine/instance/migrate/autoMap`, { params });
}

/**
 * listTriggers: GET /api/v1/workflow/engine/instance/trigger/list
 */
export function listTriggers(): Promise<FlowAutoTriggerVO[]> {
  return requestClient.get<FlowAutoTriggerVO[]>(`/api/v1/workflow/engine/instance/trigger/list`);
}

/**
 * createTrigger: POST /api/v1/workflow/engine/instance/trigger
 */
export function createTrigger(data: FlowAutoTriggerCreateDTO): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/engine/instance/trigger`, data);
}

/**
 * deleteTrigger: DELETE /api/v1/workflow/engine/instance/trigger/{id}
 */
export function deleteTrigger({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/workflow/engine/instance/trigger/${id}`);
}

/**
 * toggleTrigger: PUT /api/v1/workflow/engine/instance/trigger/{id}/toggle
 */
export function toggleTrigger({ id }: {
    id: string;
  }): Promise<unknown> {
  return requestClient.put<unknown>(`/api/v1/workflow/engine/instance/trigger/${id}/toggle`);
}
