/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * FlowDefinitionController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code FlowDefinitionController}，共 36 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { FlowBatchDeployResultVO, FlowDefinitionDetailVO, FlowDefinitionDiffVO, FlowDefinitionVO, FlowDefinitionVersionVO, FlowDeployProcessDTO, FlowEventSubscriptionVO, FlowMigrationImpactVO, FlowRollbackResultVO, RollbackRequestDTO } from './models';

/**
 * deploy: POST /workflow/engine/definition/deploy
 */
export function deploy(data: FlowDeployProcessDTO): Promise<string> {
  return requestClient.post<string>(`/workflow/engine/definition/deploy`, data);
}

/**
 * batchDeployFromZip: POST /workflow/engine/definition/batchDeployZip
 */
export function batchDeployFromZip(params: {
    file?: Record<string, unknown>;
  }): Promise<FlowBatchDeployResultVO> {
  return requestClient.post<FlowBatchDeployResultVO>(`/workflow/engine/definition/batchDeployZip`, { params });
}

/**
 * publish: POST /workflow/engine/definition/{id}/publish
 */
export function publish({ id }: {
    id: string;
  }, params: {
    force?: boolean;
  }): Promise<void> {
  return requestClient.post<void>(`/workflow/engine/definition/${id}/publish`, { params });
}

/**
 * deprecate: POST /workflow/engine/definition/{id}/deprecate
 */
export function deprecate({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/workflow/engine/definition/${id}/deprecate`);
}

/**
 * getByCode: GET /workflow/engine/definition/code/{code}
 */
export function getByCode({ code }: {
    code: string;
  }, params: {
    version?: string;
    tenantId?: string;
  }): Promise<FlowDefinitionVO> {
  return requestClient.get<FlowDefinitionVO>(`/workflow/engine/definition/code/${code}`, { params });
}

/**
 * page: GET /workflow/engine/definition/page
 */
export function page(params: {
    pageNo?: number;
    pageSize?: number;
    category?: string;
    flowCode?: string;
  }): Promise<PageResponse<FlowDefinitionVO[]>> {
  return requestClient.get<PageResponse<FlowDefinitionVO[]>>(`/workflow/engine/definition/page`, { params });
}

/**
 * getDefinitionDetail: GET /workflow/engine/definition/{id}
 */
export function getDefinitionDetail({ id }: {
    id: string;
  }): Promise<FlowDefinitionDetailVO> {
  return requestClient.get<FlowDefinitionDetailVO>(`/workflow/engine/definition/${id}`);
}

/**
 * getDefinitionPreview: GET /workflow/engine/definition/{id}/preview
 */
export function getDefinitionPreview({ id }: {
    id: string;
  }): Promise<FlowDefinitionDetailVO> {
  return requestClient.get<FlowDefinitionDetailVO>(`/workflow/engine/definition/${id}/preview`);
}

/**
 * switchVersion: POST /workflow/engine/definition/{code}/switchVersion
 */
export function switchVersion({ code }: {
    code: string;
  }, params: {
    definitionId?: string;
    tenantId?: string;
  }): Promise<void> {
  return requestClient.post<void>(`/workflow/engine/definition/${code}/switchVersion`, { params });
}

/**
 * enable: POST /workflow/engine/definition/{id}/enable
 */
export function enable({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/workflow/engine/definition/${id}/enable`);
}

/**
 * disable: POST /workflow/engine/definition/{id}/disable
 */
export function disable({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/workflow/engine/definition/${id}/disable`);
}

/**
 * listVersions: GET /workflow/engine/definition/{id}/versions
 */
export function listVersions({ id }: {
    id: string;
  }): Promise<FlowDefinitionVersionVO[]> {
  return requestClient.get<FlowDefinitionVersionVO[]>(`/workflow/engine/definition/${id}/versions`);
}

/**
 * diffVersions: GET /workflow/engine/definition/{id}/diff
 */
export function diffVersions({ id }: {
    id: string;
  }, params: {
    v1?: number;
    v2?: number;
  }): Promise<FlowDefinitionDiffVO> {
  return requestClient.get<FlowDefinitionDiffVO>(`/workflow/engine/definition/${id}/diff`, { params });
}

/**
 * rollbackDefinition: POST /workflow/engine/definition/rollback
 */
export function rollbackDefinition(data: RollbackRequestDTO): Promise<FlowRollbackResultVO> {
  return requestClient.post<FlowRollbackResultVO>(`/workflow/engine/definition/rollback`, data);
}

/**
 * updateNodeCoordinate: POST /workflow/engine/definition/{id}/node/{nodeCode}/coordinate
 */
export function updateNodeCoordinate({ id, nodeCode }: {
    id: string;
    nodeCode: string;
  }, data: string): Promise<void> {
  return requestClient.post<void>(`/workflow/engine/definition/${id}/node/${nodeCode}/coordinate`, data);
}

/**
 * updateDefinition: PUT /workflow/engine/definition/{id}
 */
export function updateDefinition({ id }: {
    id: string;
  }, data: FlowDeployProcessDTO): Promise<void> {
  return requestClient.put<void>(`/workflow/engine/definition/${id}`, data);
}

/**
 * exportDefinition: GET /workflow/engine/definition/{id}/export
 */
export function exportDefinition({ id }: {
    id: string;
  }): Promise<string> {
  return requestClient.get<string>(`/workflow/engine/definition/${id}/export`);
}

/**
 * importDefinition: POST /workflow/engine/definition/import
 */
export function importDefinition(params: {
    tenantId?: string;
  }, data: string): Promise<string> {
  return requestClient.post<string>(`/workflow/engine/definition/import`, data, { params });
}

/**
 * analyzeMigrationImpact: GET /workflow/engine/definition/migrationImpact
 */
export function analyzeMigrationImpact(params: {
    oldDefinitionId?: string;
    newDefinitionId?: string;
  }): Promise<FlowMigrationImpactVO> {
  return requestClient.get<FlowMigrationImpactVO>(`/workflow/engine/definition/migrationImpact`, { params });
}

/**
 * info: GET /workflow/engine/info
 */
export function info(): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/workflow/engine/info`);
}

/**
 * correlateMessage: POST /workflow/engine/event/correlateMessage
 */
export function correlateMessage(params: {
    messageName?: string;
    correlationKey?: string;
    tenantId?: string;
  }, data: string): Promise<number> {
  return requestClient.post<number>(`/workflow/engine/event/correlateMessage`, data, { params });
}

/**
 * throwError: POST /workflow/engine/event/throwError
 */
export function throwError(params: {
    errorCode?: string;
    instanceId?: string;
    tenantId?: string;
  }, data: string): Promise<number> {
  return requestClient.post<number>(`/workflow/engine/event/throwError`, data, { params });
}

/**
 * listEventSubscriptions: GET /workflow/engine/instance/{instanceId}/eventSubscriptions
 */
export function listEventSubscriptions({ instanceId }: {
    instanceId: string;
  }): Promise<FlowEventSubscriptionVO[]> {
  return requestClient.get<FlowEventSubscriptionVO[]>(`/workflow/engine/instance/${instanceId}/eventSubscriptions`);
}

/**
 * slaScan: POST /workflow/engine/sla/scan
 */
export function slaScan(): Promise<number> {
  return requestClient.post<number>(`/workflow/engine/sla/scan`);
}

/**
 * slaProcess: POST /workflow/engine/sla/process/{taskId}
 */
export function slaProcess({ taskId }: {
    taskId: string;
  }): Promise<boolean> {
  return requestClient.post<boolean>(`/workflow/engine/sla/process/${taskId}`);
}

/**
 * buildExpression: POST /workflow/engine/definition/conditionExpr/build
 */
export function buildExpression(data: Record<string, string>): Promise<string> {
  return requestClient.post<string>(`/workflow/engine/definition/conditionExpr/build`, data);
}

/**
 * parseExpression: POST /workflow/engine/definition/conditionExpr/parse
 */
export function parseExpression(data: Record<string, string>): Promise<string> {
  return requestClient.post<string>(`/workflow/engine/definition/conditionExpr/parse`, data);
}

/**
 * validateExpression: POST /workflow/engine/definition/conditionExpr/validate
 */
export function validateExpression(data: Record<string, string>): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.post<Record<string, Record<string, unknown>>>(`/workflow/engine/definition/conditionExpr/validate`, data);
}

/**
 * operators: GET /workflow/engine/definition/conditionExpr/operators
 */
export function operators(): Promise<Record<string, string>[]> {
  return requestClient.get<Record<string, string>[]>(`/workflow/engine/definition/conditionExpr/operators`);
}

/**
 * valueTypes: GET /workflow/engine/definition/conditionExpr/valueTypes
 */
export function valueTypes(): Promise<Record<string, string>[]> {
  return requestClient.get<Record<string, string>[]>(`/workflow/engine/definition/conditionExpr/valueTypes`);
}

/**
 * variables: GET /workflow/engine/definition/conditionExpr/variables/{id}
 */
export function variables({ id }: {
    id: string;
  }): Promise<Record<string, string>[]> {
  return requestClient.get<Record<string, string>[]>(`/workflow/engine/definition/conditionExpr/variables/${id}`);
}

/**
 * previewExpression: POST /workflow/engine/definition/conditionExpr/preview
 */
export function previewExpression(data: Record<string, Record<string, unknown>>): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.post<Record<string, Record<string, unknown>>>(`/workflow/engine/definition/conditionExpr/preview`, data);
}

/**
 * conditionTemplates: GET /workflow/engine/definition/conditionExpr/templates
 */
export function conditionTemplates(): Promise<Record<string, string>[]> {
  return requestClient.get<Record<string, string>[]>(`/workflow/engine/definition/conditionExpr/templates`);
}

/**
 * listCustomButtons: GET /workflow/engine/definition/customButtons
 */
export function listCustomButtons(params: {
    definitionId?: string;
    nodeCode?: string;
  }): Promise<Record<string, Record<string, unknown>>[]> {
  return requestClient.get<Record<string, Record<string, unknown>>[]>(`/workflow/engine/definition/customButtons`, { params });
}

/**
 * saveCustomButtons: POST /workflow/engine/definition/customButtons
 */
export function saveCustomButtons(params: {
    definitionId?: string;
    nodeCode?: string;
  }, data: Record<string, Record<string, unknown>>[]): Promise<void> {
  return requestClient.post<void>(`/workflow/engine/definition/customButtons`, data, { params });
}

/**
 * executeCustomButton: POST /workflow/engine/definition/customButtons/execute
 */
export function executeCustomButton(params: {
    taskId?: string;
    buttonCode?: string;
    comment?: string;
  }, data: Record<string, Record<string, unknown>>): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.post<Record<string, Record<string, unknown>>>(`/workflow/engine/definition/customButtons/execute`, data, { params });
}
