/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * FlowDelegateAuthController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code FlowDelegateAuthController}，共 5 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { FlowDelegateAuthPostDTO, FlowDelegateAuthVO } from './models';

/**
 * createDelegateAuth: POST /api/v1/workflow/engine/delegateAuth/create
 */
export function createDelegateAuth(data: FlowDelegateAuthPostDTO): Promise<string> {
  return requestClient.post<string>(`/api/v1/workflow/engine/delegateAuth/create`, data);
}

/**
 * revokeDelegateAuth: POST /api/v1/workflow/engine/delegateAuth/{id}/revoke
 */
export function revokeDelegateAuth({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/engine/delegateAuth/${id}/revoke`);
}

/**
 * updateDelegateAuthStatus: POST /api/v1/workflow/engine/delegateAuth/{id}/status
 */
export function updateDelegateAuthStatus({ id }: {
    id: string;
  }, params: {
    status?: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/engine/delegateAuth/${id}/status`, { params });
}

/**
 * listMyDelegateAuths: GET /api/v1/workflow/engine/delegateAuth/mine
 */
export function listMyDelegateAuths(params: {
    status?: string;
  }): Promise<FlowDelegateAuthVO[]> {
  return requestClient.get<FlowDelegateAuthVO[]>(`/api/v1/workflow/engine/delegateAuth/mine`, { params });
}

/**
 * listAsDelegate: GET /api/v1/workflow/engine/delegateAuth/asDelegate
 */
export function listAsDelegate(params: {
    status?: string;
  }): Promise<FlowDelegateAuthVO[]> {
  return requestClient.get<FlowDelegateAuthVO[]>(`/api/v1/workflow/engine/delegateAuth/asDelegate`, { params });
}
