/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * FlowCategoryController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code FlowCategoryController}，共 5 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { FlowCategoryDTO, FlowCategoryTreeVO, FlowCategoryVO } from './models';

/**
 * list: GET /api/v1/workflow/categories
 */
export function list(): Promise<FlowCategoryVO[]> {
  return requestClient.get<FlowCategoryVO[]>(`/api/v1/workflow/categories`);
}

/**
 * tree: GET /api/v1/workflow/categories/tree
 */
export function tree(): Promise<FlowCategoryTreeVO[]> {
  return requestClient.get<FlowCategoryTreeVO[]>(`/api/v1/workflow/categories/tree`);
}

/**
 * create: POST /api/v1/workflow/categories
 */
export function create(data: FlowCategoryDTO): Promise<string> {
  return requestClient.post<string>(`/api/v1/workflow/categories`, data);
}

/**
 * update: PUT /api/v1/workflow/categories
 */
export function update(data: FlowCategoryDTO): Promise<void> {
  return requestClient.put<void>(`/api/v1/workflow/categories`, data);
}

/**
 * delete: DELETE /api/v1/workflow/categories/{id}
 */
export function deleteApi({ id }: { id: string }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/workflow/categories/${id}`);
}
