/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * FlowAdvancedController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code FlowAdvancedController}，共 16 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { FlowInstanceVO, FlowMergeGroupVO, FlowReportVO, FlowUrgeCooldownVO, StringVO } from './models';

/**
 * weeklyReport: GET /api/v1/workflow/advanced/report/weekly
 */
export function weeklyReport(): Promise<FlowReportVO> {
  return requestClient.get<FlowReportVO>(`/api/v1/workflow/advanced/report/weekly`);
}

/**
 * monthlyReport: GET /api/v1/workflow/advanced/report/monthly
 */
export function monthlyReport(): Promise<FlowReportVO> {
  return requestClient.get<FlowReportVO>(`/api/v1/workflow/advanced/report/monthly`);
}

/**
 * sendWeekly: POST /api/v1/workflow/advanced/report/weekly/send
 */
export function sendWeekly(): Promise<boolean> {
  return requestClient.post<boolean>(`/api/v1/workflow/advanced/report/weekly/send`);
}

/**
 * sendMonthly: POST /api/v1/workflow/advanced/report/monthly/send
 */
export function sendMonthly(): Promise<boolean> {
  return requestClient.post<boolean>(`/api/v1/workflow/advanced/report/monthly/send`);
}

/**
 * merge: POST /api/v1/workflow/advanced/merge
 */
export function merge(params: {
    instanceIds?: string[];
  }): Promise<StringVO> {
  return requestClient.post<StringVO>(`/api/v1/workflow/advanced/merge`, { params });
}

/**
 * getMergeGroup: GET /api/v1/workflow/advanced/merge/{mergeGroupId}
 */
export function getMergeGroup({ mergeGroupId }: {
    mergeGroupId: string;
  }): Promise<FlowMergeGroupVO> {
  return requestClient.get<FlowMergeGroupVO>(`/api/v1/workflow/advanced/merge/${mergeGroupId}`);
}

/**
 * mergePass: POST /api/v1/workflow/advanced/merge/{mergeGroupId}/pass
 */
export function mergePass({ mergeGroupId }: {
    mergeGroupId: string;
  }, params: {
    comment?: string;
  }): Promise<number> {
  return requestClient.post<number>(`/api/v1/workflow/advanced/merge/${mergeGroupId}/pass`, { params });
}

/**
 * mergeReject: POST /api/v1/workflow/advanced/merge/{mergeGroupId}/reject
 */
export function mergeReject({ mergeGroupId }: {
    mergeGroupId: string;
  }, params: {
    comment?: string;
  }): Promise<number> {
  return requestClient.post<number>(`/api/v1/workflow/advanced/merge/${mergeGroupId}/reject`, { params });
}

/**
 * mergeable: GET /api/v1/workflow/advanced/mergeable
 */
export function mergeable(): Promise<FlowInstanceVO[]> {
  return requestClient.get<FlowInstanceVO[]>(`/api/v1/workflow/advanced/mergeable`);
}

/**
 * updateVotePassRate: POST /api/v1/workflow/advanced/countersign/{taskId}/votePassRate
 */
export function updateVotePassRate({ taskId }: {
    taskId: string;
  }, params: {
    votePassRate?: number;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/advanced/countersign/${taskId}/votePassRate`, { params });
}

/**
 * updateApproveCount: POST /api/v1/workflow/advanced/countersign/{taskId}/approveCount
 */
export function updateApproveCount({ taskId }: {
    taskId: string;
  }, params: {
    approveCount?: number;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/workflow/advanced/countersign/${taskId}/approveCount`, { params });
}

/**
 * hasApproved: GET /api/v1/workflow/advanced/dedup/{instanceId}/check/{userId}
 */
export function hasApproved({ instanceId, userId }: {
    instanceId: string;
    userId: string;
  }): Promise<boolean> {
  return requestClient.get<boolean>(`/api/v1/workflow/advanced/dedup/${instanceId}/check/${userId}`);
}

/**
 * approvedUsers: GET /api/v1/workflow/advanced/dedup/{instanceId}/approvedUsers
 */
export function approvedUsers({ instanceId }: {
    instanceId: string;
  }): Promise<StringVO[]> {
  return requestClient.get<StringVO[]>(`/api/v1/workflow/advanced/dedup/${instanceId}/approvedUsers`);
}

/**
 * urgeCooldown: GET /api/v1/workflow/advanced/urge/cooldown/{instanceId}
 */
export function urgeCooldown({ instanceId }: {
    instanceId: string;
  }): Promise<FlowUrgeCooldownVO> {
  return requestClient.get<FlowUrgeCooldownVO>(`/api/v1/workflow/advanced/urge/cooldown/${instanceId}`);
}

/**
 * autoForward: POST /api/v1/workflow/advanced/offlineForward/auto
 */
export function autoForward(params: {
    authId?: string;
  }): Promise<number> {
  return requestClient.post<number>(`/api/v1/workflow/advanced/offlineForward/auto`, { params });
}

/**
 * manualForward: POST /api/v1/workflow/advanced/offlineForward/manual
 */
export function manualForward(params: {
    userId?: string;
    delegateUserId?: string;
  }): Promise<number> {
  return requestClient.post<number>(`/api/v1/workflow/advanced/offlineForward/manual`, { params });
}
