/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * InternalWorkflowApiController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code InternalWorkflowApiController}，共 3 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { FlowInstanceViewDTO, FlowStartProcessDTO } from './models';

/**
 * startProcess: POST /api/internal/engine/instance/start
 */
export function startProcess(data: FlowStartProcessDTO): Promise<string> {
  return requestClient.post<string>(`/api/internal/engine/instance/start`, data);
}

/**
 * getByBusiness: GET /api/internal/engine/instance/byBusiness
 */
export function getByBusiness(params: {
    businessType?: string;
    businessId?: string;
  }): Promise<FlowInstanceViewDTO> {
  return requestClient.get<FlowInstanceViewDTO>(`/api/internal/engine/instance/byBusiness`, { params });
}

/**
 * terminate: POST /api/internal/engine/instance/{id}/terminate
 */
export function terminate({ id }: {
    id: string;
  }, params: {
    reason?: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/internal/engine/instance/${id}/terminate`, { params });
}
