/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * MessageEventController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code MessageEventController}，共 1 个端点。
 * <p>路径规范: /api/v1/workflow/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py workflow} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';


/**
 * publish: POST /api/workflow/message-event/publish
 */
export function publish(data: Record<string, unknown>): Promise<string> {
  return requestClient.post<string>(`/api/workflow/message-event/publish`, data);
}

/**
 * publishMessageEvent: POST /api/workflow/message-event/publish
 * <p>{@link publish} 的别名，供视图层使用更语义化的命名。
 */
export function publishMessageEvent(data: Record<string, unknown>): Promise<string> {
  return publish(data);
}
