/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * AlertController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code AlertController}，共 7 个端点。
 * <p>路径规范: /api/v1/cronjob/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py cronjob} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { AlertRulePostDTO, AlertRulePutDTO, JobAlertLogVO, JobAlertRuleVO } from './models';

/**
 * createRule: POST /cronjob/alert/rule
 */
export function createRule(data: AlertRulePostDTO): Promise<string> {
  return requestClient.post<string>(`/cronjob/alert/rule`, data);
}

/**
 * updateRule: PUT /cronjob/alert/rule/{id}
 */
export function updateRule({ id }: {
    id: string;
  }, data: AlertRulePutDTO): Promise<void> {
  return requestClient.put<void>(`/cronjob/alert/rule/${id}`, data);
}

/**
 * deleteRule: DELETE /cronjob/alert/rule/{id}
 */
export function deleteRule({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/cronjob/alert/rule/${id}`);
}

/**
 * getRuleById: GET /cronjob/alert/rule/{id}
 */
export function getRuleById({ id }: {
    id: string;
  }): Promise<JobAlertRuleVO> {
  return requestClient.get<JobAlertRuleVO>(`/cronjob/alert/rule/${id}`);
}

/**
 * listRules: GET /cronjob/alert/rules
 */
export function listRules(): Promise<JobAlertRuleVO[]> {
  return requestClient.get<JobAlertRuleVO[]>(`/cronjob/alert/rules`);
}

/**
 * toggleRule: PUT /cronjob/alert/rule/{id}/toggle
 */
export function toggleRule({ id }: {
    id: string;
  }, params: {
    enabled?: number;
  }): Promise<void> {
  return requestClient.put<void>(`/cronjob/alert/rule/${id}/toggle`, { params });
}

/**
 * queryAlertLogs: GET /cronjob/alert/logs/{jobId}
 */
export function queryAlertLogs({ jobId }: {
    jobId: string;
  }, params: {
    since?: string;
  }): Promise<JobAlertLogVO[]> {
  return requestClient.get<JobAlertLogVO[]>(`/cronjob/alert/logs/${jobId}`, { params });
}
