 
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * JobController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code JobController}，共 17 个端点。
 * <p>路径规范: /api/v1/cronjob/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py cronjob} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { BatchResult, JobBatchDTO, JobBatchUpdateDTO, JobLogVO, JobPostDTO, JobPutDTO, JobVO } from './models';

/**
 * create: POST /api/v1/cronjob
 */
export function create(data: JobPostDTO): Promise<string> {
  return requestClient.post<string>(`/api/v1/cronjob`, data);
}

/**
 * update: PUT /api/v1/cronjob
 */
export function update(data: JobPutDTO): Promise<void> {
  return requestClient.put<void>(`/api/v1/cronjob`, data);
}

/**
 * validateCron: GET /api/v1/cronjob/cron/validate
 */
export function validateCron(params: {
    expr?: string;
    count?: number;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/cronjob/cron/validate`, { params });
}

/**
 * batchDelete: POST /api/v1/cronjob/batch/delete
 */
export function batchDelete(data: JobBatchDTO): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/batch/delete`, data);
}

/**
 * delete: DELETE /api/v1/cronjob/{id}
 */
export function deleteApi({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.delete<void>(`/api/v1/cronjob/${id}`);
}

/**
 * pause: POST /api/v1/cronjob/{id}/pause
 */
export function pause({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/cronjob/${id}/pause`);
}

/**
 * resume: POST /api/v1/cronjob/{id}/resume
 */
export function resume({ id }: {
    id: string;
  }): Promise<void> {
  return requestClient.post<void>(`/api/v1/cronjob/${id}/resume`);
}

/**
 * trigger: POST /api/v1/cronjob/{id}/trigger
 */
export function trigger({ id }: {
    id: string;
  }, params: {
    holdLock?: boolean;
  }): Promise<string> {
  return requestClient.post<string>(`/api/v1/cronjob/${id}/trigger`, { params });
}

/**
 * batchPause: POST /api/v1/cronjob/batch/pause
 */
export function batchPause(data: JobBatchDTO): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/batch/pause`, data);
}

/**
 * batchResume: POST /api/v1/cronjob/batch/resume
 */
export function batchResume(data: JobBatchDTO): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/batch/resume`, data);
}

/**
 * batchTrigger: POST /api/v1/cronjob/batch/trigger
 */
export function batchTrigger(data: JobBatchDTO): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/batch/trigger`, data);
}

/**
 * batchUpdateGroup: POST /api/v1/cronjob/batch/updateGroup
 */
export function batchUpdateGroup(data: JobBatchUpdateDTO): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/batch/updateGroup`, data);
}

/**
 * batchUpdateCron: POST /api/v1/cronjob/batch/updateCron
 */
export function batchUpdateCron(data: JobBatchUpdateDTO): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/batch/updateCron`, data);
}

/**
 * getById: GET /api/v1/cronjob/{id}
 */
export function getById({ id }: {
    id: string;
  }): Promise<JobVO> {
  return requestClient.get<JobVO>(`/api/v1/cronjob/${id}`);
}

/**
 * page: GET /api/v1/cronjob/page
 */
export function page(params: {
    pageNum?: number;
    size?: number;
    keyword?: string;
    status?: string;
    group?: string;
  }): Promise<PageResponse<JobVO[]>> {
  return requestClient.get<PageResponse<JobVO[]>>(`/api/v1/cronjob/page`, { params });
}

/**
 * pageLog: GET /api/v1/cronjob/log/page
 */
export function pageLog(params: {
    pageNum?: number;
    size?: number;
    jobKey?: string;
    status?: string;
  }): Promise<PageResponse<JobLogVO[]>> {
  return requestClient.get<PageResponse<JobLogVO[]>>(`/api/v1/cronjob/log/page`, { params });
}

/**
 * reload: POST /api/v1/cronjob/reload
 */
export function reload(): Promise<unknown> {
  return requestClient.post<unknown>(`/api/v1/cronjob/reload`);
}
