/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * JobGroupController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code JobGroupController}，共 5 个端点。
 * <p>路径规范: /api/v1/cronjob/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py cronjob} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { BatchResult, JobVO } from './models';

/**
 * pageByGroup: GET /api/v1/cronjob/group/{jobGroup}/page
 */
export function pageByGroup({ jobGroup }: {
    jobGroup: string;
  }, params: {
    page?: number;
    size?: number;
  }): Promise<PageResponse<JobVO[]>> {
  return requestClient.get<PageResponse<JobVO[]>>(`/api/v1/cronjob/group/${jobGroup}/page`, { params });
}

/**
 * pauseByGroup: POST /api/v1/cronjob/group/{jobGroup}/pause
 */
export function pauseByGroup({ jobGroup }: {
    jobGroup: string;
  }): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/group/${jobGroup}/pause`);
}

/**
 * resumeByGroup: POST /api/v1/cronjob/group/{jobGroup}/resume
 */
export function resumeByGroup({ jobGroup }: {
    jobGroup: string;
  }): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/group/${jobGroup}/resume`);
}

/**
 * triggerByGroup: POST /api/v1/cronjob/group/{jobGroup}/trigger
 */
export function triggerByGroup({ jobGroup }: {
    jobGroup: string;
  }): Promise<BatchResult> {
  return requestClient.post<BatchResult>(`/api/v1/cronjob/group/${jobGroup}/trigger`);
}

/**
 * groupStats: GET /api/v1/cronjob/group/stats
 */
export function groupStats(): Promise<Record<string, unknown>[]> {
  return requestClient.get<Record<string, unknown>[]>(`/api/v1/cronjob/group/stats`);
}
