/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * JobTaskController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code JobTaskController}，共 3 个端点。
 * <p>路径规范: /api/v1/cronjob/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py cronjob} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { PageResponse } from './models';
import type { JobTaskVO } from './models';

/**
 * list: GET /api/v1/cronjob/task/list
 */
export function list(params: {
    logId?: string;
  }): Promise<JobTaskVO[]> {
  return requestClient.get<JobTaskVO[]>(`/api/v1/cronjob/task/list`, { params });
}

/**
 * page: GET /api/v1/cronjob/task/page
 */
export function page(params: {
    logId?: string;
    page?: number;
    size?: number;
  }): Promise<PageResponse<JobTaskVO[]>> {
  return requestClient.get<PageResponse<JobTaskVO[]>>(`/api/v1/cronjob/task/page`, { params });
}

/**
 * progress: GET /api/v1/cronjob/task/progress
 */
export function progress(params: {
    logId?: string;
  }): Promise<unknown> {
  return requestClient.get<unknown>(`/api/v1/cronjob/task/progress`, { params });
}
