/* eslint-disable */
/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
/**
 * 后端统一响应结构（对齐 {@code YdszResponse<T>}）
 * <p>注意: requestClient 拦截器已按 successCode='A00000' 解包 data，
 * 业务调用处泛型直接写 data 类型；此处类型仅供契约说明使用。
 */
export interface YdszResponse<T = unknown> {
  /** 业务成功码（A00000 表示成功） */
  code: string;
  /** 提示信息 */
  msg: string;
  /** 业务数据 */
  data: T;
  /** 链路追踪 ID */
  traceId?: string;
  requestId?: string;
  spanId?: string;
  timestamp?: number;
  extensions?: Record<string, unknown>;
}

/** 分页响应（对齐后端 {@code PageResponse<T>}：total/pageNum/pageSize 平铺 + data 分页数据） */
export interface PageResponse<T = unknown> {
  /** 总记录数 */
  total?: number;
  /** 当前页码（从 1 开始） */
  pageNum?: number;
  /** 每页记录数 */
  pageSize?: number;
  /** 分页数据（由后端工厂方法填充） */
  data: T;
}

/** 分页查询参数（前端通用约定） */
export interface PageQuery {
  pageNum?: number;
  pageSize?: number;
}

export interface AlertRulePostDTO {

  serialVersionUID?: number;

  ruleName?: string;

  jobId?: string;

  jobKey?: string;

  alertType?: string;

  alertLevel?: string;

  threshold?: number;

  timeWindowMinutes?: number;

  channels?: string;

  receivers?: string;

  cooldownMinutes?: number;

  enabled?: number;
}

export interface AlertRulePutDTO {

  serialVersionUID?: number;

  id?: string;

  ruleName?: string;

  jobId?: string;

  jobKey?: string;

  alertType?: string;

  alertLevel?: string;

  threshold?: number;

  timeWindowMinutes?: number;

  channels?: string;

  receivers?: string;

  cooldownMinutes?: number;

  enabled?: number;
}

export interface ConnectorConfigPostDTO {

  serialVersionUID?: number;

  endpoint?: string;

  authType?: string;

  username?: string;

  password?: string;

  accessKey?: string;

  secretKey?: string;

  extraProps?: Record<string, unknown>;

  connectTimeoutSeconds?: number;

  readTimeoutSeconds?: number;
}

export interface JobDagPostDTO {

  serialVersionUID?: number;

  dagKey?: string;

  dagName?: string;

  dagDefinition?: string;

  status?: string;

  triggerType?: string;

  cronExpression?: string;

  maxConcurrentInstances?: number;

  failStrategy?: string;

  description?: string;
}

export interface JobDagPutDTO {

  serialVersionUID?: number;

  dagKey?: string;

  dagName?: string;

  dagDefinition?: string;

  status?: string;

  triggerType?: string;

  cronExpression?: string;

  maxConcurrentInstances?: number;

  failStrategy?: string;

  description?: string;
}

export interface JobDagTriggerDTO {

  serialVersionUID?: number;

  dagKey?: string;

  triggerBy?: string;
}

export interface RemoteTaskRequest {

  serialVersionUID?: number;

  job?: JobVO;

  triggerType?: string;

  shardIndex?: number;

  shardTotal?: number;

  traceId?: string;
}

export interface JobVO {

  serialVersionUID?: number;

  id?: string;

  jobName?: string;

  jobGroup?: string;

  jobKey?: string;

  handler?: string;

  cronExpression?: string;

  scheduleType?: string;

  fixedRateMs?: number;

  fixedDelayMs?: number;

  paramsJson?: string;

  jobRemark?: string;

  nextFireTime?: string;

  lastFireTime?: string;

  fireCount?: number;

  successCount?: number;

  failCount?: number;

  lockTtlMs?: number;

  timeoutMs?: number;

  slowThresholdMs?: number;

  misfirePolicy?: string;

  shardTotal?: number;

  jobType?: string;

  maxRetries?: number;

  retryIntervalMs?: number;

  retryBackoff?: string;

  blockStrategy?: string;

  consecutiveFailCount?: number;

  maxConsecutiveFails?: number;

  autoResumeAfterMinutes?: number;

  priority?: number;

  version?: number;

  timezone?: string;

  cluster?: string;

  canaryRatio?: number;

  canaryHandler?: string;

  createdBy?: string;

  createdAt?: string;

  updatedBy?: string;

  updatedAt?: string;
}

export interface RemoteSubTaskRequest {

  serialVersionUID?: number;

  jobId?: string;

  logId?: string;

  jobKey?: string;

  handler?: string;

  taskName?: string;

  taskParams?: string;

  traceId?: string;
}

export interface JobPostDTO {

  serialVersionUID?: number;

  jobName?: string;

  jobGroup?: string;

  jobKey?: string;

  handler?: string;

  cronExpression?: string;

  scheduleType?: string;

  fixedRateMs?: number;

  fixedDelayMs?: number;

  paramsJson?: string;

  status?: string;

  remark?: string;

  lockTtlMs?: number;

  timeoutMs?: number;

  slowThresholdMs?: number;

  misfirePolicy?: string;

  shardTotal?: number;

  timezone?: string;

  cluster?: string;
}

export interface JobPutDTO {

  serialVersionUID?: number;

  id?: string;

  jobName?: string;

  jobGroup?: string;

  jobKey?: string;

  handler?: string;

  cronExpression?: string;

  scheduleType?: string;

  fixedRateMs?: number;

  fixedDelayMs?: number;

  paramsJson?: string;

  status?: string;

  remark?: string;

  lockTtlMs?: number;

  timeoutMs?: number;

  slowThresholdMs?: number;

  misfirePolicy?: string;

  shardTotal?: number;

  timezone?: string;

  cluster?: string;
}

export interface JobBatchDTO {

  serialVersionUID?: number;

  jobIds?: string[];
}

export interface JobWebhookPostDTO {

  serialVersionUID?: number;

  name?: string;

  eventType?: string;

  jobKey?: string;

  jobGroup?: string;

  callbackUrl?: string;

  httpMethod?: string;

  headers?: string;

  secret?: string;

  webhookStatus?: string;
}

export interface JobWebhookPutDTO {

  serialVersionUID?: number;

  id?: string;

  name?: string;

  eventType?: string;

  jobKey?: string;

  jobGroup?: string;

  callbackUrl?: string;

  httpMethod?: string;

  headers?: string;

  secret?: string;

  webhookStatus?: string;
}