/** auto-generated by bash/gen-contract.py — DO NOT EDIT */
// @data-file 纯类型 API 封装生成件（不计入行数/复杂度规则）
/**
 * TaskTopologyController API 封装（auto-generated by bash/gen-contract.py）
 *
 * <p>对应后端 {@code TaskTopologyController}，共 3 个端点。
 * <p>路径规范: /api/v1/cronjob/**（kebab-case），成功码统一为 code === 'A00000'。
 *
 * @author ydsz-team
 * @path apps\cronjob-web\src\api\taskTopology.ts
 * @auto-generated 请勿手动修改；后端契约变更后执行 {@code python bash/gen-contract.py cronjob} 重新生成
 * @since 1.0.0
 */
import { requestClient } from '#/api/request';
import type { JobLogVO } from './models';

/**
 * getDagInstanceTopology: GET /api/v1/cronjob/topology/dagInstance/{dagInstanceId}
 */
export function getDagInstanceTopology({ dagInstanceId }: {
    dagInstanceId: string;
  }): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/api/v1/cronjob/topology/dagInstance/${dagInstanceId}`);
}

/**
 * getDagInstanceCytoscape: GET /api/v1/cronjob/topology/dagInstance/{dagInstanceId}/cytoscape
 */
export function getDagInstanceCytoscape({ dagInstanceId }: {
    dagInstanceId: string;
  }): Promise<Record<string, Record<string, unknown>>> {
  return requestClient.get<Record<string, Record<string, unknown>>>(`/api/v1/cronjob/topology/dagInstance/${dagInstanceId}/cytoscape`);
}

/**
 * getJobExecutionHistory: GET /api/v1/cronjob/topology/jobHistory/{jobKey}
 */
export function getJobExecutionHistory({ jobKey }: {
    jobKey: string;
  }): Promise<JobLogVO[]> {
  return requestClient.get<JobLogVO[]>(`/api/v1/cronjob/topology/jobHistory/${jobKey}`);
}
